- validator/sawtooth_validator/execution/scheduler_parallel.py
Here are some slight optimizations to the parallel scheduler, with numbers. In particular, the function `ParallelScheduler._has_predecessors` has gone from taking ~3% of total program time to around ~1%.
The profiling setup is the same as described in https://github.com/hyperledger/sawtooth-core/pull/1299.
- validator-1, master
- validator-1, PR
- validator-2, master
- validator-2, PR
The functions `_txn_result_is_invalid` and `_txn_is_in_valid_batch` remain bottlenecks. Nothing I've tried so far to speed them up has worked, but I'm sure there must be something. It might require some high-level rethinking of the scheduler implementation.
> Parallel scheduler optimizations

- integration/sawtooth_integration/tests/test_peer_list.py
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/server/core.py
In the edge case where a node that joins a new network, where the only
block produced is the genesis block, and the network is larger than the
mimimum peering threashold, the a node can be left in a state where it
has no blocks, until new blocks are published.  This leaves the node in
a precarious state, whereby it cannot publish any blocks for the batches
it receives until its network is ready.
This change modifieds the peer search to include a check for an existing
chain.  If no chain exists, it will query its connected peers until it
receives a block.
Additionally:
- Update doc string with missing params
- separate dynamic peering retry to own function
> Request Chain Head from Peers, if None

- docs/source/sysadmin_guide/configure_sgx.rst
Add a [sawtooth@system] prompt to mark the commands that must be run
as the sawtooth user.
Reorganize content to make this part of the procedure less confusing:
- Move the "skip for multiple validators" note to the right place.
- Make the "sawtooth proposal" details into a note and move after
the command output.
These changes address STL-989.
> Clarify which commands must run as sawtooth

- validator/sawtooth_validator/gossip/permission_verifier.py
- validator/sawtooth_validator/journal/chain.py
- validator/tests/test_journal/mock.py
This will remove the case where a value in the cache could
be replaced by an outdated value while validating an old
block. Instead the value will be checked from state and it
will not be added to the cache.
> Add a from_state option to identity cache

- docs/source/_templates/sdk_TP_tutorial.rst
Fixed the missing space that caused substitution to fail.
Corrected function and file names for each language.
Added links to the correct files on GitHub.
Made minor wording changes for clarity.
Removed reference to 'apply' in the last section.
> Correct game play info in XO Java/JS/Python SDK tutorials

- validator/sawtooth_validator/gossip/signature_verifier.py
- validator/sawtooth_validator/server/core.py
- validator/sawtooth_validator/server/network_handlers.py
This message frequently occurs, and provides little value as a log
message. However, the data is still useful and can be analyzed more
effectively as a metric.
> Replace 'Drop already validated batch/block' log with metric

- .gitignore
- adm/Cargo.toml
- adm/packaging/ubuntu/changelog
- adm/packaging/ubuntu/control
- adm/packaging/ubuntu/postinst
- adm/src/blockstore.rs
- adm/src/commands/blockstore.rs
- adm/src/commands/genesis.rs
- adm/src/commands/keygen.rs
- adm/src/commands/mod.rs
- adm/src/config.rs
- adm/src/database/database.rs
- adm/src/database/lmdb.rs
- adm/src/database/mod.rs
- adm/src/err.rs
- adm/src/main.rs
- adm/src/wrappers.rs
- bin/build_debs
- sdk/rust/Cargo.toml
- sdk/rust/src/lib.rs
- sdk/rust/src/messaging/zmq_stream.rs
- sdk/rust/src/signing/mod.rs
- sdk/rust/src/signing/pem_loader.rs
- sdk/rust/src/signing/secp256k1.rs
This creates a new subcommand for the `sawadm` command called `blockstore` which allows users to directly inspect and modify the blockstore database. The `blockstore` subcommand names and arguments should be treated as unstable as additional work is being done on this command.
The new command was written in rust and so the old command has been removed.
> Create new sawadm blockstore command (in rust)

- validator/sawtooth_validator/state/state_view.py
This fixes an issue where the call to create_view separates the
construciton and a call to set_merkle_root, in the case where no
root is provided.  However, the constructor also calls set_merkle_root,
which does a db put when the INIT_ROOT_KEY is the root. Therefore,
every instance of StateView is incurring the cost of a db write, after
block 0.
> Avoid db write via StateViewFactory.create_view

- validator/sawtooth_validator/journal/chain.py
- validator/tests/test_journal/tests.py
Currently when a block fails validation, the reason it failed is logged separately from the message saying that it failed. This makes it hard to track down what happened. This PR rearranges things in the block validator so that the messages are logged together.
> Centralize block validation logging

- validator/sawtooth_validator/journal/block_sender.py
- validator/sawtooth_validator/journal/publisher.py
- validator/tests/test_journal/mock.py
This PR removes all batches (besides injected batches) from a block before it is broadcasted to the validator network. This will be an improvement for two main reasons:
1. Most nodes are already likely to have these batches in their pending batch queues from previous gossip messages, so sending these batches is likely to repeat work.
2. This will greatly reduce the message size of broadcasted blocks.
Injected batches will still be broadcasted. At the time of broadcast, only the injecting node will have these batches, and if they were omitted from the block all other nodes would request the batches at the same time.
> Remove non injected batches from block before broacasting

- sdk/examples/intkey_cxx/int_key_transaction_processor.cpp
This PR removes typos from intkey transaction processor example
of cxx sdk.
Signed-off-by: ibansalankit <ankiteciitkgp@gmail.com>
> Fixing typos in cxx sdk

- docs/source/_templates/sdk_TP_tutorial.rst
Merge PR #1307 into the 1-0 branch.
Fixed the missing space that caused substitution to fail.
Corrected function and file names for each language.
Added links to the correct files on GitHub.
Made minor wording changes for clarity.
Removed reference to 'apply' in the last section.
> Backport: Correct game play info in XO Java/JS/Python SDK tutorials

- validator/sawtooth_validator/journal/chain.py
This was checking the wrong block to see if it reached genesis. Possibly
a copy-paste error.
> Fix typo in _find_common_height

- adm/src/commands/blockstore.rs
- adm/src/main.rs
This adds subcommands for backing up and restoring the blockstore to and
from a regular file. This is needed because the blockstore is a sparse
file and also contains indexes.
> Implement blockstore backup and restore

- validator/packaging/systemd/sawtooth-validator.service
Systemd was restarting sawtooth services so fast the network was
unaware a node had dropped off. This change should also help the
core dump issue by reducing IO contention while the core gets written
to disk.
> backport: Add 5 min. delay before systemd restarts services

- validator/packaging/systemd/sawtooth-validator.service
Systemd was restarting sawtooth services so fast the network was
unaware a node had dropped off. This change should also help the
core dump issue by reducing IO contention while the core gets written
to disk.
> Add 5 min. delay before systemd restarts services

- docker/compose/sawtooth-debug.yaml
The compose file was creating two settings TPs instead of a settings TP and an intkey TP.
> Fix typo in sawtooth-debug compose file

- bin/generate_cli_output
- cli/sawtooth_cli/main.py
- cli/sawtooth_cli/network_command/peers.py
- cli/sawtooth_cli/peer.py
- cli/sawtooth_cli/rest_client.py
- cli/sawtooth_cli/sawnet.py
- cli/sawtooth_cli/status.py
- docs/source/cli/sawnet.rst
- docs/source/cli/sawtooth.rst
- integration/sawtooth_integration/tests/test_peer_list.py
- protos/client_status.proto
- protos/validator.proto
- rest_api/openapi.yaml
- rest_api/sawtooth_rest_api/rest_api.py
- rest_api/sawtooth_rest_api/route_handlers.py
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/server/component_handlers.py
- validator/sawtooth_validator/state/client_handlers.py
This PR adds `sawtooth status show`, which currently reports a node's public network endpoint and peers, and `sawnet peers {list,graph}`, which display the peering arrangement of a network of nodes.
> Add new peer reporting CLI commands

- validator/sawtooth_validator/journal/completer.py
Setting the requested keep time higher than the cache keep time can
cause the validator to get into a state where it stops processing blocks
all together because it thinks it has already requested the blocks that
it needs to request.
Swapping these keep times should eliminate this bug an allow a validator
to catchup successfully, provided it does not run out of memory (a
different bug).
> Swap completer cache keep times

- consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
- docs/source/architecture/journal.rst
Remove reference in docs to now unsupported minimum_wait_time
and improve the code comment on the now hard-coded value.
See also #1367
> Fix doc and comment for minimum wait time

- validator/sawtooth_validator/journal/completer.py
Setting the requested keep time higher than the cache keep time can
cause the validator to get into a state where it stops processing blocks
all together because it thinks it has already requested the blocks that
it needs to request.
Swapping these keep times should eliminate this bug and allow a
validator to catchup successfully, provided it does not run out of
memory (a different bug).
> 1-0 Backport Swap completer cache keep times

- validator/sawtooth_validator/execution/context_manager.py
- validator/sawtooth_validator/execution/scheduler_parallel.py
- validator/tests/test_scheduler/tests.py
One error is a scheduler - context manager - wildcarded addresses interaction where a transaction is in flight when unscheduling occurs. This would raise a KeyError in the context manager when the transaction processor performed a Get using the context id for the in-flight transaction. This was apparent during manual testing of Smallbank and SupplyChain, and in the unit test in this PR.
The other error is in the parallel-scheduler unscheduling mechanism. This was found by the unit test in this PR. This caused the parallel-scheduler to hang on calling complete with block=True.
> Fix for two errors dealing with unscheduling.

- protos/network.proto
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/gossip/gossip_handlers.py
Add `protocol_version` to `PeerRegisterRequest`, to create a future avenue for dealing with network protocol changes.
> Add protocol_version to  PeerRegisterRequest

- validator/sawtooth_validator/networking/interconnect.py
A recent traceback showed `RuntimeError: dictionary changed size
during iteration` getting raised from this function. This may be
related to occasional bad repeering behavior.
> Add lock around get_connection_id_by_endpoint

- validator/sawtooth_validator/journal/publisher.py
Currently, when the chain is updated and a candidate block is in progress,
it is set to None - i.e. discarded. Its schedule is cancelled when the
garbage collector reclaims the object's memory. This can happen at
unpredictable times, which results blocks being published which should
have been abandoned.
By converting this to an explicit cancel, the candidate block is
abandoned and its schedule cancelled immediately.  This reduces the need
for the network to evaluate blocks that should never have been produced
in the first place.
> Explicitly Cancel Discarded Candidate Blocks

- validator/sawtooth_validator/journal/block_validator.py
- validator/sawtooth_validator/journal/chain.py
- validator/tests/test_journal/tests.py
This PR changes the block validator to log the reason for failed validation. The idea is to ensure that we have the block validation process logged in a clear, ordered way: "Starting block validation...Block validation failed because blah blah blah...Finished block validation". Currently the error message only gets logged by helper functions, and we might end up with the messages out of order.
This PR does not change the helper functions the throw exceptions rather than log, so there will be some duplicate logging. A longer-term goal is to convert everything to exception-throwing style, but the various components (permission validation, block validation, etc) can be changed independently and in separate PRs.
This is basically the same change as …
> Centralize block validator logging (master)

- validator/sawtooth_validator/execution/scheduler_parallel.py
- validator/sawtooth_validator/execution/scheduler_serial.py
- validator/tests/test_scheduler/tests.py
When an transaction has been removed from the schedule, but was being
processed by a transaction processor, the scheduler will ignore any
results provided.
Includes a pair of unit tests for both schedulers to verify this
behavior.
> Ignore unscheduled transaction results

- docs/source/cli/sawset.rst
- families/settings/sawtooth_settings/processor/main.py
Bug fix to change the incorrect command name, "sawtooth-settings", to the right one: "settings-tp". 
This PR has two commits: one to fix the documentation, and one to fix the code comment.
> Correct settings-tp name in doc and command's help text

- .gitignore
- sdk/rust/Cargo.toml
- sdk/rust/src/messaging/stream.rs
- sdk/rust/src/processor/mod.rs
Looking for suggestions on ways to improve this. Currently, I needed to add timeouts to 3 places we were blocking on  (using arbitrary timeouts for now). I originally tried adding unregister directly as the handler for ctl-c but the handler can only be set once but we need to be able to update the sender used in case of reconnection.
> Add shutdown on CTL-C to rust transaction processor

- docker/sawtooth-dev-cxx
When this is not set, the cxx deb packages build without an incremented
.dev version. This is causing problems with package publishing.
> Add VERSION env var to dev-cxx dockerfile

- validator/sawtooth_validator/execution/scheduler_parallel.py
This PR makes two changes to the parallel scheduler.
The first change affects the function `_index_of_txn_in_schedule`. This function was taking around .7% of total CPU time, with most of that being taking up by a list comprehension. It's in the upper left corner of the graph below.
It turns out that the function, which is called frequently, was taking a list of transactions and then building out a new list of transaction ids every time just to get the index of one id. Switching from list comprehension / index to an enumeration causes the function to drop off the graph entirely, indicating that it no longer takes a significant amount of time.
The second change has to do with a function called `_txn_is_in_valid_batch`. This function takes around 5% of total CPU time. About 2/5 of that time …
> More parallel scheduler optimizations

- CONTRIBUTING.md
- docs/source/community/contributing.rst
- docs/source/community/issue_tracking.rst
- docs/source/community/join_the_discussion.rst
In Community chapter:
- Lightly edit to fix titles, reduce wordiness, wrap lines at 80,
and conform to Sawtooth doc standards (first pass)
- Add JIRA links and cross references to helpful info in the
Sawtooth documentation
In CONTRIBUTING.md:
- Change content in CONTRIBUTING.md to point to the Sawtooth documentation.
Plus a second commit with changes to address review comments: 
- Delete "Arcade features" bullet from "Ways to contribute" (outdated info)
- Correct lint test info (lint DOES produce output on success)
- Add new "Commit email address" section (must match GitHub account)
> Edit Community section and CONTRIBUTING.md

- docs/source/_templates/sdk_TP_tutorial.rst
- docs/source/app_developers_guide/aws.rst
- docs/source/app_developers_guide/docker.rst
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/architecture/transactions_and_batches.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/transaction_family_specifications/settings_transaction_family.rst
- Fix wording and capitalization for several titles (and remove ! from "Transactions and Batches")
- Correct a few wording problems, such as capitalization for the Identity and Settings transaction family 
- Change "CLI" to "command" throughout
> Fix titles and content in Sawtooth documentation

- perf/sawtooth_perf/src/workload.rs
- perf/smallbank_workload/Cargo.toml
- perf/smallbank_workload/build.rs
- perf/smallbank_workload/src/main.rs
This PR has three main fixes:
- #1325 took out generating rust files from protogen script and handled it by using a build.rs file. This PR adds it back in for smallbank_workload.
- Removing the wait from the sawtooth_perf long running batch submitter. This is only a short-term fix and will be handled better by work done in STL-1052. 
- ~Adding the Cargo.lock to version control since smallbank_workload is a bin. https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html This cargo documentation explains.~
- Changing the default transactions per batch to 1.
> Add generating proto files to smallbank_workload

- sdk/rust/src/processor/handler.rs
Give the cloneable trait to TransactionContext.
> Make TransactionContext cloneable

- families/block_info/sawtooth_block_info/processor/handler.py
- integration/sawtooth_integration/docker/test_poet_liveness.yaml
- validator/sawtooth_validator/journal/block_validator.py
- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/journal/validation_rule_enforcer.py
- validator/tests/test_journal/mock.py
- validator/tests/test_journal/tests.py
- validator/tests/test_validation_rule_enforcer/test.py
Validate that a batch added to a candidate block does not violate the block validation rules specified in the settings.  Before this change, batches that violated these rules were only verified before the block was committed, but this left open the possibility of rule-violating transactions being processed, which could affect downstream state in a given schedule.
Additionally:
* Adds block-info-tp to PoET Liveness test
> Reject Batches That Will Violate Block Validation Rules

- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
Signed-off-by: Al Hulaton <al.hulaton@gmail.com>
> Update metadata address typo in blockinfo docs

- bin/build_all
- docker/compose/sawtooth-local-poet.yaml
- docker/grafana/dashboards/dashboard.json
- docker/grafana/grafana_entrypoint.sh
- docker/grafana/sawtooth-stats-grafana
- docker/poet-settings.sh
- The influxdb and grafana dockerfiles do not follow the same format as the rest of our Docker stuff. This moves the dockerfiles into the docker directory, and moves the scripts and json files to their own directory.
- This PR adds some new metrics to the grafana dashboard. It also utilizes a different json structure for the dashboard that allows us to use a template variable for the metrics datasource. This means we will not have to create a new dashboard for each LR network that show the same graphs. It will also allow us to create new dashboards for specialized metrics without having to edit the main dashboard.
- The sawtooth-metrics.yaml docker-compose file starts up a network that is connected to influxdb and grafana. This allows us to easily test new metrics or conduct other …
> Relocate metrics dockerfiles and improve dashboard

- validator/sawtooth_validator/execution/executor.py
This commit logs any transaction processor internal errors at the error
level on the validator. It also includes information about the
transaction that was being executed when the error ocurred.
> Log TP internal error on validator

- sdk/java/pom.xml
This cleans up some warnings that are printed during `mvn package`.
> Add logging implementation to Java sdk tests

- adm/src/blockstore.rs
- adm/src/commands/blockstore.rs
- adm/src/database/lmdb.rs
- adm/src/main.rs
This adds a subcommand to compute some basic summary stats for the
blockstore database. More detailed stats can be added later.
> Implement blockstore stats command

- validator/sawtooth_validator/networking/dispatch.py
- validator/sawtooth_validator/server/network_handlers.py
Remove the explicit priority setting from within the dispatcher,
allowing priority be configured as either part of the handler addition
or explicitly for handlers grouped by message type.
> Remove explicit priority from within dispatcher

- docker/grafana/dashboards/dashboard.json
- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/metrics/wrappers.py
This PR adds a new metric to track the transactions that are currently in process for each node. In order to do this, the metrics counter wrapper had to be extended to allow the `dec()` method. This PR also adds the metric to the dashboard.
In order to test this metric, run the `sawtooth-local-poet.yaml` docker-compose file, and set a workload. Since the validators in this compose file use the serial scheduler, we see on the graph that each node has between 0 and 2 transactions in process at a time. Next, edit the validators in `sawtooth-local-poet.yaml` to use the parallel scheduler. We see that many more transactions can be processed in parallel with this scheduler.
> Add transactions in process metric

- adm/src/commands/blockstore.rs
- adm/src/main.rs
Previously, this was including a length delimiter byte, which makes
reading exported blocks more difficult. The length delimiter is only
needed when exporting multiple blocks to one file, such as with the
backup command.
> Export blocks as regular protobuf messages

- consensus/poet/families/stdeb.cfg
- consensus/poet/simulator/stdeb.cfg
Make the poet-families and poet-simulator deb packages depend on our
build or greater of python3-cryptography. This resolves STL-988 where
python3-cryptography is not upgraded to the correct version if the
Ubuntu package was already installed.
> make deb packages depend on cryptography >=1.7.1

- bin/build_rust
- docker/sawtooth-dev-rust
This turns off incremental builds.
This should fix the read issues that have been failing builds.
> Add CARGO_INCREMENTAL=0 to sawtooth_dev_rust

- validator/packaging/validator.toml.example
The subcategory for roles and permissions should come last
in the files. I also commented those categories out as they
are less likely to be used when starting the validator for
the first time.
@dcmiddle This should fix the issues people have been seeing when trying to start the validator up with the full example file.
> Reorganize validator.toml.example so it is valid toml

- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/execution/scheduler.py
- validator/sawtooth_validator/execution/scheduler_parallel.py
- validator/sawtooth_validator/execution/scheduler_serial.py
- validator/tests/test_journal/mock.py
Transaction that return INTERNAL_ERROR on their result will immediately be resent to a transaction processor.  This can trigger a death spiral of transaction executions, over and over again.  We can mitigate this problem by not resending the transaction once its containing batch has been unscheduled.
This requires the addition of a `is_transaction_in_schedule` method to the Scheduler interface.
> Fix issue Unscheduled InternalError Results

- validator/sawtooth_validator/server/component_handlers.py
- validator/sawtooth_validator/server/core.py
Add a separate threadpool for handling client messages.  This removes
contention between components like transaction processors being starved
for thread attention by high-volume client requests.
> Add separate threadpool for client handlers

- validator/sawtooth_validator/server/cli.py
- validator/sawtooth_validator/server/state_verifier.py
This PR adds a feature to the validator where it checks if any state is missing on startup and, if it is, recomputes it before starting normal operation. This can be used in conjuction with the `sawadm blockstore restore` command to restore a validator from a backup.
> Recompute state on startup if missing

- docker/sawtooth-dev-rust
This turns off incremental builds.
> Backport: Add CARGO_INCREMENTAL=0 to sawtooth_dev_rust

- validator/sawtooth_validator/execution/scheduler_parallel.py
- validator/tests/test_scheduler/test_predecessor_tree.py
Separate the predecessor tree's predecessor logic from its data structure and add a `Tree` class with the following methods: `update`, `prune`, and `walk`.
Note that the data structure implemented by `Tree` is not yet a radix tree.
Two of the predecessor test assertions have been dropped, as they test low-level implementation details rather than an interface.
> Split off predecessor tree's tree

- ci/sawtooth-block-info-tp
- ci/sawtooth-validator
This is merged to master in PR #1440 . This was not tested in LR because we don't run docker containers there. This was tested locally.
> Create block-info docker - Backport

- validator/sawtooth_validator/server/component_handlers.py
The messages `CLIENT_BLOCK_GET_BY_TRANSACTION_ID_REQUEST` and `CLIENT_BLOCK_GET_BY_BATCH_ID` are now properly handled by the validator code.
> Adds missing handlers for GetBlock client messages

- docs/source/introduction.rst
In "Real-world Application Examples", change the text so that it doesn't make (or appear to make) 
any claims about about security or completeness.
Also: Make wording consistent for all TF blurbs and change "repo" to "repository".
> Fix Sawtooth doc Introduction: clarify info on example TFs

- validator/sawtooth_validator/execution/scheduler_parallel.py
- validator/tests/test_scheduler/test_predecessor_tree.py
This PR changes the data structure of the parallel scheduler's predecessor tree from a trie to a prefix tree (there's a lot of confusing and overlapping terminology for this family of data structures; these are the names I've settled on). For a nice comparison of these data structures, see https://medium.com/basecs/compressing-radix-trees-without-too-many-tears-a2e658adb9a0. The tl;dr is that the new one should use a lot less memory than the old one. How much less, you ask? I ran the dynamic network test before and after this change with the following logging statement added:
```
class Node:
def __init__(self, address, data=None):
LOGGER.error('NEW NODE')  # <--
self.address = address
self.children = set()
self.data = data
```
Then I counted all the occurrences of that statement. Before …
> Convert predecessor tree's trie to a prefix tree

- validator/sawtooth_validator/journal/block_validator.py
- validator/sawtooth_validator/journal/chain.py
- validator/tests/test_journal/block_tree_manager.py
- validator/tests/test_journal/tests.py
Correctly solving the missing predecessor issue requires redesigning how blocks are handled between the completer and chain controller. Currently, they maintain two separate block caches and there is no way for the chain controller to tell the completer it is missing something. This is by design. 
A missing predecessor is an error condition and, since the chain controller can’t request the missing predecessor from the completer by design, the only thing that makes sense to do is purge the chain based on the missing predecessor and hope the completer figures it out.
> Purge blocks from chain controller that depend on a missing predecessor

- docs/source/app_developers_guide/aws.rst
- docs/source/app_developers_guide/docker.rst
- docs/source/app_developers_guide/intro_xo_transaction_family.rst
- docs/source/transaction_family_specifications/xo_transaction_family.rst
- Add intro content to describe this section's purpose
- Describe the XO transaction family
- Rewrite "Game Rules" and replace TMI with link to Wikipedia
- Convert the two procedures into one: Merged "how to play" info
with the "play XO with xo client" procedure to explain what
the XO TF does in the relevant step
- Add Prerequisites section with:
- links to the Docker/Ubuntu/AWS dev env procedures
- new info on opening a Docker client container
- new prereq on ensuring a connection to the REST API
(with links where available)
- Move the authentication options to the end, because
they're not used in this procedure.
Also (second commit): 
- Edit the intro text in "XO Transaction Family" spec to match; 
add links to wikipedia and "Introduction to the XO Transaction Family".
And (fixup …
> Rewrite Intro to XO TF section, especially game procedure

- sdk/rust/src/messages/mod.rs
Needed for implementing `net_peerCount` in https://github.com/hyperledger/sawtooth-seth/pull/11
> Export client_peers protobuf messages

- docker/grafana/dashboards/dashboard.json
- protos/processor.proto
- sdk/go/src/sawtooth_sdk/processor/processor.go
- validator/sawtooth_validator/exceptions.py
- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/execution/processor_handlers.py
- validator/sawtooth_validator/execution/processor_iterator.py
- validator/sawtooth_validator/execution/processor_manager.py
- validator/sawtooth_validator/server/component_handlers.py
Adds a maxOccupancy field to the TpRegisterRequest proto. This will act as a limit to the number of in-flight transactions a validator can have with a given TP
Tracks the number of current in-flight transactions a validator has with a TP
Removes the _execute_or_wait_for_processor_type() method and the waiting threadpool from the executor, and shifts all wait functionality to the ProcessorManager (previously ProcessorIteratorCollection). Execution will now happen as follows:
- The executor will attempt to grab a processor from the processor iterator collection.
- The processor iterator collection will check to make sure that aprocessor of the requested type is registered. If not, the thread will wait until a suitable processor registers.
- The processor iterator collection will attempt to …
> Implement parallelism hint and handling

- validator/sawtooth_validator/execution/scheduler_parallel.py
When determining if a transaction should be replayed, ensure that any possible successors have not been unscheduled.  If they have, a `KeyError` could occur.
> Ensure that possible successor in schedule

- validator/sawtooth_validator/execution/scheduler_parallel.py
For PredecessorTree.set_writer, this saves a trip down the tree.
(You might think that `prune(address)` could be rewritten as `update(address, lambda x: x, prune=True)`, but that's not the case: if the address isn't in the tree, `update` will create a node for it, while `prune` will do nothing.)
> Add prune flag to Tree.update

- NOTICES
Current license leaves out static link exception
This update should be ported back to 1.0
> updates notice file to use complete zeromq license

- validator/sawtooth_validator/server/state_verifier.py
The processor manager was changed in 810be2d but not applied here.
This bug was able to slip through because there is no state verifier test. I created https://jira.hyperledger.org/browse/STL-1111 to add one.
> Update verify_state with executor processor manager

- docker/grafana/dashboards/dashboard.json
- validator/sawtooth_validator/metrics/metrics.py
Adding these tags dramatically increased the cardinality of tags that
needed to be stored on InfluxDB and as a result severely degraded
performance.
> Reduce metrics tags

- docs/source/cli/identity-tp.rst
- docs/source/cli/intkey.rst
- docs/source/cli/poet.rst
- docs/source/cli/sawadm.rst
- docs/source/cli/sawnet.rst
- docs/source/cli/sawset.rst
- docs/source/cli/sawtooth-rest-api.rst
- docs/source/cli/sawtooth-validator.rst
- docs/source/cli/sawtooth.rst
- docs/source/cli/settings-tp.rst
- docs/source/cli/xo.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
Line numbers aren't appropriate for the --help output shown
in the CLI Command Reference and Sys Admin Guide.
> Remove line numbers for --help usage text

- validator/sawtooth_validator/state/batch_tracker.py
- validator/tests/test_batch_tracker/__init__.py
- validator/tests/test_batch_tracker/tests.py
Prevent the caller of `get_invalid_txn_info` from reading a possibly concurrently modified collection.
This should prevent the error where faulty values are encountered while reading through the collection of transaction infos.
> Prevent concurrent modification of tracked status

- docker/grafana/dashboards/dashboard.json
- validator/sawtooth_validator/database/database.py
- validator/sawtooth_validator/database/dict_database.py
- validator/sawtooth_validator/database/indexed_database.py
- validator/sawtooth_validator/database/lmdb_nolock_database.py
- validator/sawtooth_validator/journal/block_store.py
- validator/sawtooth_validator/journal/chain.py
- validator/tests/test_block_store/tests.py
- validator/tests/test_indexing/tests.py
This adds a gauge metric for committed transactions which shows the actual number of transactions currently in the block store, which can go up and down over time as forks are resolved.
> Updated committed transactions metric

- docker/sawtooth-dev-go
go 1.9 includes math/bits and is required by the dependency ripemd160
> Update sawtooth-dev-go to use go 1.9

- validator/sawtooth_validator/networking/interconnect.py
Override OS keep-alive, as the underlying FD's will not necessarily be closed when the ZMQ socket it is, based on the underlying default Linux    settings.  Setting this to the same value as the validator's connection timeouts and interval should reduce the amount of time a socket is left open by the OS.
Also includes some minor reordering of the close/shutdown logic for a given Send/Receive thread.
Based on contributor feedback in this issue: https://github.com/zeromq/libzmq/issues/1453
> Override OS Keepalive for ZMQ Sockets

- validator/sawtooth_validator/networking/dispatch.py
- validator/sawtooth_validator/networking/handlers.py
In order to track down the root cause of [STL-1020](https://jira.hyperledger.org/browse/STL-1020), several logging additions have been made.  This should give a better indication as to where in the peering process a messages is being sent at the wrong time (i.e. before the auth/trust handshake has been completed).
> Logging improvements around Auth Rejection

- .gitignore
- perf/intkey_workload/Cargo.toml
- perf/intkey_workload/src/intkey_addresser.rs
- perf/intkey_workload/src/intkey_iterator.rs
- perf/intkey_workload/src/intkey_transformer.rs
- perf/intkey_workload/src/main.rs
```
USAGE:
intkey-workload [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-n, --batch-size <BATCH_SIZE>                Transactions in a batch [default: 1]
--display <TIME_BETWEEN_DISPLAYS>        Seconds between statistics displays [default: 30]
--invalid <INVALID>                      Probability of a transaction being invalid [default: 0.0]
-k, --key-file <KEY_FILE>                    File containing a private key to sign transactions and batches
--num-names <NUM_NAMES>                  Number of IntKey Names to set [default: 100]
--auth-password <BASIC_AUTH_PASSWORD>    Basic auth password to authenticate with the Sawtooth REST Api
-r, --rate <RATE>                            Batches per second to send to a Sawtooth REST …
```
> Add Intkey workload cli tool

- docs/source/app_developers_guide/aws.rst
> Fix typo in AWS procedure (remove unused heading)

- docker/grafana/dashboards/dashboard.json
Using non_negative_derivative(1s) hurts dashboard performance without
improving accuracy since we are only reporting every 10s.
> Convert all dashboard derivates to 10s/10

- bin/run_tests
- integration/sawtooth_integration/tests/test_state_verifier.py
There is a bug in the shutdown code for some component this depends on, which causes it to occasionally hang during shutdown. I tried a number of things to get this test passing while avoiding depending on the shutdown code to work properly, but none of them worked 100% of the time. This test is still valid, since an exception will be raised if there is a problem with state verifying before the `os._exit(0)` line is run. In other words, the `os._exit(0)` line will only be run if the test was successful.
The reason this test is failing because of the shutdown code is that the transaction execution components are being run from the same container as the test itself, which no other integration or unit test does to the same extent as here. In the other tests, only the exit code of the test …
> Short-circuit test-state-verifier shutdown

- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/gossip/gossip_handlers.py
Previously, this wasn't being passed along correctly and so the time to
live feature was not operating correctly
> Pass updated time to live to gossip on rebroadcast

- bin/run_tests
- perf/intkey_workload/unit_intkey_workload.yaml
- perf/sawtooth_perf/src/batch_gen.rs
- perf/sawtooth_perf/unit_sawtooth_perf.yaml
This PR turns on running the perf/sawtooth_perf and perf/intkey_workload unit tests. This corrects an oversight on my part.
> Add unit test yaml files for perf rust modules missing them

- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/networking/interconnect.py
In permissioned networks, it is possible for the network to request peers from connections which have not completed the authorization handshake.  Get Peer Messages will not be sent to connections that have not completed this handshake.
> Only request peers from connections which have completed handshake

- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/gossip/permission_verifier.py
- validator/sawtooth_validator/networking/dispatch.py
- validator/sawtooth_validator/networking/handlers.py
These messages indicate states that should not normally arise, e.g.
trying to unregister a connection only to find that the connection
wasn't registered in the first place. They should be logged at least
at warning level.
> Log networking irregularities as warnings

- sdk/rust/Cargo.toml
> Correct rust sdk authors in cargo.toml

- bin/get_version
The original commit fails one upgrade test.
This reverts commit dc10fa536b312fcf8660304d18abb444bfbfdf95.
> Revert "Update package versioning to include commit hash"

- sdk/go/src/sawtooth_sdk/messaging/connection.go
- sdk/go/src/sawtooth_sdk/processor/processor.go
- sdk/go/src/sawtooth_sdk/processor/worker.go
Previously, there were a number of problems with the shutdown and
reconnect code. Graceful shutdown would hang if the processor was
registering or if the validator never responded with an unregister
response. Reconnection could fail when a validator disconnected
because threads were blocked waiting for a response and would never
stop.
This commit solves these problems by using a ZMQ socket to signal
shutdown so it can be included in a poll with a receiving socket
and by aggresively closing sockets that worker threads depend on
so any send/receives will unblock and the worker threads can shutdown.
> STL-1085 Go TP Reconnect

- validator/sawtooth_validator/gossip/gossip_handlers.py
- validator/sawtooth_validator/gossip/permission_verifier.py
- validator/sawtooth_validator/gossip/signature_verifier.py
- validator/sawtooth_validator/gossip/structure_verifier.py
- validator/sawtooth_validator/journal/completer.py
- validator/sawtooth_validator/journal/responder.py
- validator/sawtooth_validator/networking/dispatch.py
- validator/sawtooth_validator/server/component_handlers.py
- validator/sawtooth_validator/server/network_handlers.py
- validator/sawtooth_validator/state/client_handlers.py
- validator/tests/test_client_request_handlers/test_submit_handlers.py
- validator/tests/test_duplicate_handler/tests.py
- validator/tests/test_responder/tests.py
This PR implements @aludvik 's idea for cutting down on repeated
message deserialization, namely, adding "preprocessors" on a
message-by-message basis. These preprocessors act on messages before
they reach the handlers, deserializing the message content and also
extracting whatever other message information is required by the
handlers. With gossip messages, for instance, there are handlers that
require the message type tag and the message time-to-live in addition
to the batch or block object contained in the message, so those three
things are extracted and stored in a tuple that is passed to the
handlers.
With these changes, the poet liveness test seems to be able to run
with a higher workload, so I've included a commit to bump the workload
rates. This consistently passes when running …
> Message handler preprocessors

- bin/build_all
- bin/build_debs
The rust debian packages were missing the built executables.
> Add rust build step prior to building debian packages

- validator/sawtooth_validator/gossip/gossip.py
In order to prevent a validator from attempting to broadcast to connections that have not fully peered, the connections should be filtered based on whether or not they have completed their authorization handshake.
This should prevent the issue where validators fail to re-peer when there is a slowdown in message processing.
> Only broadcast to fully connected peers

- docs/source/sysadmin_guide/configuring_sawtooth/cli_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/identity_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/path_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/settings_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/xo_tp_configuration.rst
- docs/source/sysadmin_guide/log_configuration.rst
Correct all config file paths and associated text in Sys Admin Guide:
* The installed /etc/sawtooth directory includes these example config files:
log_config.toml.example, path.toml.example, validator.toml.example
Changed these paths in the appropriate doc section; added new content where
necessary.
Note that the Validator topic had the wrong path to the file in sawtooth-core. The
first commit in this PR corrects that path, but the last (and largest) changes it to 
/etc/sawtooth/validator.toml.example.
* The other example config files must be downloaded from the sawtooth-core repo.
Corrected the path for the xo config file; changed text for all to say "download" 
instead of "copy".
* Also added a note about the default config directory to the topics that were
missing the note (Validator, …
> Correct config file paths in Sys Admin Guide

- MAINTAINERS.md
This list is intended to recognize current contributors to the
sawtooth-core repository who have:
- Been actively involved for a substantial amount of time
- Made significant contributions that have been critical to the success
of the project
- Frequently reviewed pull requests and left thoughtful and
constructive feedback
To come up with this list objectively, I took all contributors who have
made 50 or more commits since Jan 1, 2017. This list can be reproduced
using the GitHub insights tool. This link should take you directly to
the list.
https://github.com/hyperledger/sawtooth-core/graphs/contributors?from=2017-01-01&to=2018-03-28&type=c
The list has been sorted by first name.
> Create initial MAINTAINERS list

- rest_api/sawtooth_rest_api/state_delta_subscription_handler.py
`_latest_state_delta_event` may be None under certain circumstances. For example, when an event doesn't exist on a node - perhaps due to a restart or a fork. This change guards against:
- only an initial event is sent if it is not None
- fork checks are only done when a last event exists
> Verify _latest_state_delta_event is not None

- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- rest_api/sawtooth_rest_api/config.py
- rest_api/sawtooth_rest_api/rest_api.py
Before the REST API defaulted to only allowing a
request body size of 1MB. Now the size limit can be
configured with the config file or using the command
line. If there is not a size configured there will be
no limit on the request body size.
> Add client_max_size to rest api config

- cli/sawtooth_cli/block.py
- cli/sawtooth_cli/sawset.py
- cli/sawtooth_cli/state.py
- consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
- consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
- consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
- families/settings/tests/test_tp_settings.py
- integration/sawtooth_integration/tests/test_dynamic_network.py
- rest_api/sawtooth_rest_api/route_handlers.py
- rest_api/tests/unit/components.py
- rest_api/tests/unit/test_txn_requests.py
- sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload/workload_generator.py
- sdk/examples/xo_python/sawtooth_xo/processor/handler.py
- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/execution/scheduler.py
- validator/sawtooth_validator/execution/scheduler_serial.py
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/journal/consensus/consensus_factory.py
- validator/sawtooth_validator/journal/consensus/genesis/genesis_consensus.py
- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/networking/interconnect.py
- validator/sawtooth_validator/state/client_handlers.py
- validator/sawtooth_validator/state/state_view.py
- validator/tests/test_client_request_handlers/base_case.py
- validator/tests/test_journal/mock.py
- validator/tests/test_journal/tests.py
- validator/tests/test_journal/utils.py
- validator/tests/test_permission_verifier/tests.py
- validator/tests/test_responder/tests.py
- validator/tests/utils.py
A new version of `pycodestyle` was released yesterday (4/10/18). It introduced a new rule that binary operators should come after a line break rather than before:
```
income = (gross_wages +
taxable_interest +
(dividends - qualified_dividends) -
ira_deduction -
student_loan_interest)
income = (gross_wages
+ taxable_interest
+ (dividends - qualified_dividends)
- ira_deduction
- student_loan_interest)
```
(See https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator)
It also fixed a bug where docstrings' first lines weren't being checked for length.
> Fix new pycodestyle issues

- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- rest_api/sawtooth_rest_api/config.py
This commit changes the default from being
unlimited to 10MB, which is a common default for the
limit of the request body.
> Set default client_max_size to 10MB

- bin/run_lint_rust
- bin/run_lint_validator
- docker/sawtooth-dev-rust
- docker/sawtooth-dev-validator
- sdk/rust/src/processor/handler.rs
It turns out that clippy is too unstable to use in CI.
Signed-off-by: Nick Drozd <drozd@bitwise.io>
> Disable Rust clippy

- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- rest_api/sawtooth_rest_api/config.py
- rest_api/sawtooth_rest_api/rest_api.py
Before the REST API defaulted to only allowing a
request body size of 1MB. Now the size limit can be
configured with the config file or using the command
line. If there is not a size configured there will be
no limit on the request body size.
> BACKPORT: Add client_max_size to rest api config

- docker/compose/sawtooth-default-poet.yaml
The sawtooth-default-poet.yaml contained references to simulator_rk_pub.pem file and
poet_settings.sh w.r.to sawtooth-core repo. It should be standalone.
- Removed redundant volumes mounting
- Changed the path for simulator_rk_pub.pem to existing /etc/sawtooth/simulator_rk_pub.pem
- Added individual settings parameters based on poet_settings.sh
> Fix pem path, poet settings for default poet yaml

- validator/stdeb.cfg
Allows inclusion of non-python dependencies. In this case, libpython3.5
is required to call validator python code from the rust wrapper.
> Add stdeb.cfg for validator

- consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
- consensus/poet/core/tests/test_consensus/test_poet_block_publisher.py
Add logging the public key of the validator when claiming blocks too frequently.
Signed-off-by: Benoit Razet <benoit.razet@pokitdok.com>
> More logging when validator claims blocks too frequently

- validator/Cargo.toml
- validator/src/database/database.rs
- validator/src/database/lmdb.rs
- validator/src/database/lmdb_ffi.rs
- validator/src/database/mod.rs
- validator/src/lib.rs
- validator/src/state/merkle.rs
- validator/src/state/merkle_ffi.rs
- validator/src/state/mod.rs
This provides a Rust implementation of the Merkle trie, including FFI (on the Rust side) and tests.
Utilizing this code in the validator will be part of a future PR.
> Implement Merkle Trie in Rust

- sdk/go/src/sawtooth_sdk/processor/context.go
- sdk/go/tests/state_test.go
The golang/protobuf dependency update on 4/30 forces users to use keyed literals (e.g., `foopb.Message{Name: "Golang", Age: 8}` as opposed to `foopb.Message{"Golang", 8}`). There were a few examples of the latter that had to be updated.
https://groups.google.com/forum/#!topic/protobuf/N-elvFu4dFM
https://github.com/golang/protobuf/pull/591
> Update Go sdk to comply with golang/protobuf update

- adm/src/blockstore.rs
- adm/src/commands/keygen.rs
Adds a few minor changes for improving the local development experience on OS X.  Namely:
- Limiting the size of the LMDB db in the tests
- Selecting the `fs::MetadataExt` based on os
> Improve local development of Sawadm on OS X

- sdk/go/src/sawtooth_sdk/processor/context.go
- sdk/go/tests/state_test.go
The golang/protobuf dependency update on 4/30 forces users to use keyed literals (e.g., foopb.Message{Name: "Golang", Age: 8} as opposed to foopb.Message{"Golang", 8}). There were a few examples of the latter that had to be updated.
https://groups.google.com/forum/#!topic/protobuf/N-elvFu4dFM
golang/protobuf#591
Signed-off-by: Darian Plumb dplumb@bitwise.io
> BACKPORT Update Go sdk to comply with golang/protobuf update

- .gitignore
- bin/build_validator
- bin/sawtooth-validator
- consensus/poet/common/sawtooth_poet_common/validator_registry_view/validator_registry_view.py
- consensus/poet/common/tests/test_validator_registry_view/mocks.py
- integration/sawtooth_integration/docker/test_state_verifier.yaml
- integration/sawtooth_integration/tests/test_state_verifier.py
- validator/sawtooth_validator/database/native_lmdb.py
- validator/sawtooth_validator/ffi.py
- validator/sawtooth_validator/server/core.py
- validator/sawtooth_validator/state/client_handlers.py
- validator/sawtooth_validator/state/identity_view.py
- validator/sawtooth_validator/state/merkle.py
- validator/setup.py
- validator/src/main.rs
- validator/src/state/merkle_ffi.rs
- validator/tests/test_client_request_handlers/mocks.py
- validator/tests/test_client_request_handlers/test_state_handlers.py
- validator/tests/test_config_view/tests.py
- validator/tests/test_context_manager/tests.py
- validator/tests/test_genesis/tests.py
- validator/tests/test_identity_view/tests.py
- validator/tests/test_merkle_trie/tests.py
- validator/tests/test_scheduler/test_schedulers_with_yaml.py
- validator/tests/test_scheduler/tests.py
- validator/tests/test_scheduler/yaml_scheduler_tester.py
- validator/tests/test_state_view/tests.py
- validator/tests/unit_validator.yaml
Replaces the internals of the Python implementation of the Merkle Trie with FFI calls to the rust implementation.
> Replace Python Merkle Trie Implementation with Rust FFI calls

- validator/sawtooth_validator/server/core.py
Awhile ago, the amount of time that the Completer holds onto blocks was adjusted in order to resolve a bug dubbed the "flatline bug" (https://github.com/hyperledger/sawtooth-core/commit/df75658011e59dff0be2a8ce45a6ac2770303fec). At that time, the amount of time the Chain Controller holds onto blocks should have also been updated, but this was missed. Because of this, it became much easier for the Chain Controller and Completer to get out of sync with respect to the blocks they thought were in the system. With the two out of sync, it was possible for the Completer to send a block to the Chain Controller that was built on a block that the Chain Controller had dropped. This resulted in a forking bug deemed the "missing predecessor bug" (STL-901). This commit updates the time that the Chain …
> Adjust keep times to mitigate missing predecessors

- .gitignore
- bin/run_lint_rust
- bin/run_lint_validator
- validator/Cargo.toml
- validator/build.rs
- validator/src/lib.rs
Add build.rs, which includes code generation based on the files in protos.  Generates the source into `validator/src/proto` and generates a `mod.rs` file with each generated src file referenced in it.
Additionally, the source is only generated again when there are changes to the proto definition files.
> Rust validator protos

- bin/run_tests
- validator/tests/unit_rust_validator.yaml
Adds a docker-compose file to run `cargo test` in the validator directory
running any doc tests, unit tests, and any tests in the `validator/tests` directory.
> Add validator rust tests to build

- sdk/python/sawtooth_sdk/consensus/__init__.py
- sdk/python/sawtooth_sdk/consensus/driver.py
- sdk/python/sawtooth_sdk/consensus/engine.py
- sdk/python/sawtooth_sdk/consensus/exceptions.py
- sdk/python/sawtooth_sdk/consensus/service.py
- sdk/python/sawtooth_sdk/consensus/zmq_driver.py
- sdk/python/sawtooth_sdk/consensus/zmq_service.py
- sdk/python/tests/test_zmq_driver.py
- sdk/python/tests/test_zmq_service.py
Right now this PR includes interfaces for `Engine`, `Service`, and `Driver`, and implements `ZmqService` with unit tests, but does not include the `ZmqDriver`.
The `Service` interface is slightly different from the Rust one. Specifically, it returns dictionaries instead of lists for `get_{blocks,settings,state}`. This seems to me like a more convenient way to access the data. I can change it to match Rust, or change Rust to match this.
> Add Python Consensus SDK

- Jenkinsfile
Modify the whitelist conditional test to skip the committers whitelist
stage for the 1-0-staging branches in addition to 1-0.
> Modify Jenkins to build staging branches.

- validator/sawtooth_validator/server/core.py
Having the completer keep blocks for a longer amount of time then the chain
controller causes the two components to fall out of sync much easier.
> BACKPORT: Adjust keep times to mitigate missing predecessors

- sdk/javascript/processor/index.js
This handles cases when the apply method doesn't return a
promise, or apply throws an exception.
STL-662
STL-663
> BACKPORT Add try/catch and Promise resolve/reject to js sdk

- docs/source/sysadmin_guide/configure_sgx.rst
This reverts commit 00255c4ca834a3240c38f235cf28d3c23cad015e.
This commit broke doc generation and was merged without being
appropriately tested.
> Revert "Clarify Signature Policy selection"

- docs/source/app_developers_guide/docker.rst
> Correct dashes for --url option in intkey load example

- integration/sawtooth_integration/tests/test_state_verifier.py
- protos/merkle.proto
- validator/Cargo.toml
- validator/sawtooth_validator/database/native_lmdb.py
- validator/sawtooth_validator/server/cli.py
- validator/sawtooth_validator/server/core.py
- validator/sawtooth_validator/server/state_verifier.py
- validator/sawtooth_validator/state/merkle.py
- validator/src/database/lmdb.rs
- validator/src/database/lmdb_ffi.rs
- validator/src/lib.rs
- validator/src/state/merkle.rs
- validator/src/state/merkle_ffi.rs
- validator/tests/test_client_request_handlers/mocks.py
- validator/tests/test_config_view/tests.py
- validator/tests/test_context_manager/tests.py
- validator/tests/test_genesis/tests.py
- validator/tests/test_identity_view/tests.py
- validator/tests/test_merkle_trie/tests.py
- validator/tests/test_scheduler/test_schedulers_with_yaml.py
- validator/tests/test_scheduler/tests.py
- validator/tests/test_scheduler/yaml_scheduler_tester.py
- validator/tests/test_state_view/tests.py
Write a change log entry for each new merkle trie that records the additions for a given root and the deletions made by a successor trie.
This includes:
- some changes to have the hashes stored internally as bytes (though this is not complete)
- Refactor in LmdbDatabase to have a DatabaseReader trait
- ChangeLogEntry protobuf message
> Write change log on Merkle Trie Changes

- validator/sawtooth_validator/journal/back_pressure_handlers.py
- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/server/component_handlers.py
This PR makes some initial strides towards supporting the consensus engine api, although it does not get all the way there. It also cleans up the block publisher code to make it easier to understand when this is easy to do.
> Refactor Block Publisher to support Consensus Engine prototyping

- sdk/rust/src/consensus/engine.rs
The SDK should derive these so users can debug their engines
> Derive Debug Trait in Rust Consensus SDK

- docs/source/transaction_family_specifications/settings_transaction_family.rst
Change "remain pieces" to "remaining pieces".
> docs: Fix Grammar in Settings Transaction Family

- validator/sawtooth_validator/state/merkle.py
- validator/tests/test_merkle_trie/tests.py
Validator was getting into infinite loop when trying to set & delete context
state in one go. Set items were being handled before the deletion which was
causing some expected data to be deleted. This threw an error which was kept
the batch from being cleaned up. This further caused the scheduler to pick up
the same batch again and again after the schedule interval(infinte loop).
Proper state is ensured during rehashing bottom-up now.
Signed-off-by: rranjan3 <rajeev2.ranjan@intel.com>
> Backport: Fix infinite loop for set & delete(update) context state

- rest_api/sawtooth_rest_api/exceptions.py
- rest_api/sawtooth_rest_api/messaging.py
- rest_api/sawtooth_rest_api/route_handlers.py
Added a simple exponential backoff & retry mechanism to handle ZMQ send failures.
> Fix for ZMQ send failures in REST API

- validator/sawtooth_validator/networking/handlers.py
- validator/sawtooth_validator/server/cli.py
- validator/tests/test_authorization_handlers/test.py
Validator peering fails when using Azure endpoints such as tcp://hashblock3.westus2.cloudapp.azure.com:8800 because the 'lo' network interface characters are characters in 'cloudapp'. This fix test that the network interface string is not equal to the
host name of the endpoint. The bug number is STL-1125
Replaces #1592 and corrects the logging usage.
> Fix validator peering on Azure

- validator/src/batch.rs
- validator/src/block.rs
- validator/src/transaction.rs
These Rust structs allow for manipulation of Blocks, Batches, and Transactions
without having to deserialize fields that are bytes.
Later either a From or a TryFrom can be implemented to convert from
proto::{Block, Batch, Transaction}.
> Add Rust core datatypes of Block, Batch, Transaction

- validator/src/main.rs
The validator currently returns an exit code of 0 if there is an error loading
or calling the python main function.
> Return non-zero exit code on startup error

- docker/sawtooth-dev-rust
- sdk/rust/Cargo.toml
This fixes build issues with Rust protoc in the 1-0 branch.
> 1-0: Set Rust toolchain and dependency versions

- docs/source/app_developers_guide/creating_sawtooth_network.rst
These changes are for "Confirm Network Functionality" in "Creating a Multiple-Node Network".
- For Docker, clarify that the shell container is used for curl and Sawtooth CLI commands.
- For Ubuntu, add info about opening a terminal window on the appropriate validator node for these commands.
Also: 
- Simplify info for Ubuntu default REST API URL/port by rewording and moving notes. 
- Make other wording changes to clarify the steps. 
- Fix RST formatting problems.
> Clarify Docker container & Ubuntu window info for network conf steps

- sdk/python/sawtooth_sdk/processor/context.py
The `entries` list does not contain `TpStateEntry messages`, so the code will
throw an exception when generating the `AuthorizationException`:
```
File "/Users/.../lib/python3.6/site-packages/sawtooth_sdk/processor/context.py", line 100, in <listcomp>
addresses = [e.address for e in entries]
AttributeError: 'str' object has no attribute 'address'
```
> Use correct entries list to generate AuthorizationException in python sdk

- cli/sawtooth_cli/batch.py
- validator/sawtooth_validator/state/client_handlers.py
sawtooth batch submit with --wait throws a stack trace.
this changeset contains fix for this issue.
Signed-off-by: mithun shashidhara <mithunx.shashidhara@intel.com>
> sawtooth batch submit with --wait throws a stack trace

- validator/sawtooth_validator/networking/handlers.py
- validator/sawtooth_validator/server/cli.py
- validator/tests/test_authorization_handlers/test.py
Validator peering fails when using Azure endpoints such as
tcp://hashblock3.westus2.cloudapp.azure.com:8800 because the 'lo'
network interface characters are characters in 'cloudapp'. This
fix test that the network interface string is not equal to the
host name of the endpoint. The bug number is STL-1125
Signed-off-by: Arthur Greef <arthurgreef@live.com>
> BACKPORT: Fix validator peering on Azure

- validator/src/state/identity_view.rs
- validator/src/state/mod.rs
Implements the IdentityView with tests.  It provides views on roles and policies over a StateReader.
Completes [STL-1184](https://jira.hyperledger.org/browse/STL-1184).
> Implement Identity View in Rust

- validator/Cargo.toml
- validator/sawtooth_validator/database/native_lmdb.py
- validator/sawtooth_validator/ffi.py
- validator/src/database/lmdb.rs
- validator/src/database/lmdb_ffi.rs
- validator/src/lib.rs
Improve the python-rust interaction by adding an instance of a ctypes
PYDLL, which maintains the GIL when it calls the underlying c function.
Using the cpython Rust library, the arguments can then be translated
from Python to Rust values and passed to the Rust struct, as needed.
Additionally:
- Added dynamic dispatch on AsRef<str> for the creation of an LMDB
instance, which is needed for handling a list Strings passed by python.
- explicitly import python3-sys to use the raw PyObject pointers
> Improve python-rust boundary interaction

- validator/src/journal/chain_commit_state.rs
- validator/src/journal/mod.rs
This work is part of porting Candidate block to rust.
> Add TransactionCommitCache in Rust to store transactions committed

- docs/source/app_developers_guide/creating_sawtooth_network.rst
Double Quotes are missing in the "Creating a Sawtooth Network", step 1, #6.
This line:
`sawtooth.poet.report_public_key_pem=$(cat /etc/sawtooth/simulator_rk_pub.pem`)
Should be:
`sawtooth.poet.report_public_key_pem="$(cat /etc/sawtooth/simulator_rk_pub.pem)"`
Otherwise, the following error occurs:
> sawset:error : unrecognised argument `sawset proposal create -k`
> Missing Double Quotes in the Creating a Sawtooth Network Instructions

- validator/src/lib.rs
- validator/src/metrics/mod.rs
This is a thin wrapper around the sawtooth_validator metrics library code.
Based on #1666
> Create Rust wrapper for metrics library

- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/journal/block_validator.py
- validator/sawtooth_validator/journal/publisher.py
- validator/src/execution/execution_platform.rs
- validator/src/execution/mod.rs
- validator/src/execution/py_executor.rs
- validator/src/scheduler/mod.rs
- validator/src/scheduler/py_scheduler.rs
This PR adds two traits, ExecutionPlatform and Scheduler, and implements them both with the Python transaction processing capabilities already in master.
> Add Rust wrapper to Python transaction execution

- docs/source/cli/sawset.rst
> docs: Fix Typo in Sawset Documentation

- validator/Cargo.toml
- validator/sawtooth_validator/ffi.py
- validator/sawtooth_validator/journal/block_validator.py
- validator/sawtooth_validator/journal/chain.py
- validator/sawtooth_validator/server/core.py
- validator/src/journal/block_validator.rs
- validator/src/journal/block_wrapper.rs
- validator/src/journal/block_wrapper_ffi.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_ffi.rs
- validator/src/journal/mod.rs
- validator/src/lib.rs
- validator/src/metrics/mod.rs
- validator/tests/test_journal/block_tree_manager.py
- validator/tests/test_journal/tests.py
This is a fairly large change in the sense that it replaces the implementation of the `ChainController` with a rust implementation.  It is as straight of a 1-1 port as can be managed, given the constraints of both Rust (e.g. its constraints on memory usage, sharing, etc) and FFI calls (how rust interacts with python, across that boundary).
Adds an explicit dependency on [lazy_static](https://crates.io/crates/lazy_static)
> Implement Chain Controller In Rust

- Jenkinsfile
- docker/compose/copy-debs.yaml
Without this change, there are potentially collisions with containers
while running lint, builds or copying debs out.
> Add COMPOSE_PROJECT_NAME to Jenkinsfile

- docs/source/app_developers_guide/ubuntu.rst
Clarify between sawtooth command and sawtooth user.
Unfortunately, this causes a lot of confusion.
> docs: Clarify sudo and sawtooth Command

- families/block_info/sawtooth_block_info/injector.py
- integration/sawtooth_integration/tests/node_controller.py
- validator/sawtooth_validator/config/validator.py
- validator/sawtooth_validator/consensus/__init__.py
- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/notifier.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/gossip/gossip_handlers.py
- validator/sawtooth_validator/journal/batch_injector.py
- validator/sawtooth_validator/journal/block_wrapper.py
- validator/sawtooth_validator/networking/interconnect.py
- validator/sawtooth_validator/server/cli.py
- validator/sawtooth_validator/server/consensus_handlers.py
- validator/sawtooth_validator/server/core.py
- validator/sawtooth_validator/server/network_handlers.py
- validator/src/server/cli.rs
- validator/tests/test_consensus/__init__.py
- validator/tests/test_consensus/tests.py
- validator/tests/test_journal/tests.py
This PR adds the peripheral objects used by the consensus engine API including:
- All consensus engine API message handlers
- A Proxy object that routes requests between message handlers and internal validator objects
- A Notifier object that encapsulates sending updates to consensus engines from internal validator objects
It also implements the query services and networking services.
> Add Peripheral Consensus Engine Objects

- adm/src/commands/keygen.rs
Change permission of public key so it is readable by all.
That is, change from 0640 (rw-r-----) to 0644 (rw-r--r--).
> keygen: Fix Public Key Permission in Rust

- cli/tests/unit_cli.yaml
- families/block_info/tests/test_tp_block_info.yaml
- integration/sawtooth_integration/docker/test_block_info_injector.yaml
Add all proxy settings required for all files invoked in `./bin/run_tests -m block_info` run
> Add proxy for all run_test -m block_info related files

- families/smallbank/smallbank_rust/src/handler.rs
- sdk/examples/intkey_rust/src/handler.rs
- sdk/examples/xo_rust/src/handler/state.rs
- sdk/rust/src/processor/handler.rs
Modifies the get_state and set_state methods for TransactionContext in
the Rust SDK to take in a list of addresses to get/set instead of just
one address. This aligns with the functionality of the other SDKs. Also
modifies existing uses of SDK (smallbank_rust, inkey_rust, and xo_rust)
to call methods properly.
> Modify get_ and set_state for multiple addresses

- bin/run_docker_test
The images used to run the nose tests are not built in a previous stage
of the Jenkins build. Having docker-compose build them automatically was
counting against the test timeout interval, sometimes resulting in erroneous
test failures.
> Fix intermittent test failures from image build timeout

- sdk/python/sawtooth_processor_test/message_factory.py
Fixes the response generated by the `create_delete_response()` method of
the message_factory used for testing. This method was not setting the
status of the response.
> Fix delete response in testing message factory

- docker/compose/copy-debs.yaml
Removes explicit container names from compose files that are used in the build
process so that there are not conflicts when running builds in parallel.
> Prevent parallel job naming conflicts

- validator/src/journal/candidate_block.rs
- validator/src/journal/mod.rs
- validator/src/journal/validation_rule_enforcer.rs
The validation_rule_enforcer is used when every batch is added to a candidate block.  This incurs a cost of transforming an increasing set of batches from rust to python with every batch added.
By using the rust implementation, this transformation cost can be avoided.
> Implement validation_rule_enforcer with Rust 

- cli/tests/cli-tests.dockerfile
- cli/tests/unit_cli.yaml
Some of the CLI unit tests were inadvertently disabled in
d913e57437c18b0bbdcb698469a2f16cc2249d88
> Re-enable cli unit tests

- sdk/examples/devmode_rust/src/engine.rs
Add a simple fork resolution activity that walks back to blocks at the
same height and chooses the fork according to the block id comparison
used when they are at the same height.
> Add simple fork resolution to Devmode engine

- sdk/rust/src/consensus/zmq_driver.rs
Add a sleep after receiving a not ready response from the validator.
This will prevent the consensus engine from overwhelming the
validator while trying to register before the validator has a received a
genesis block.
> Add sleep after not ready registration

- Jenkinsfile
Tags are required to get the dev version number and JJB multibranch
fetches without tags.
> Fetch git tags in Jenkinsfile

- sdk/python/sawtooth_sdk/messaging/future.py
- sdk/python/sawtooth_sdk/messaging/stream.py
For more informative messages, include the outbound message type in the
timeout error message, to give context about what message we are waiting
on a reply.
> Include sent message type info in timeout error

- validator/sawtooth_validator/state/merkle.py
- validator/src/database/database.rs
- validator/src/database/lmdb.rs
- validator/src/state/merkle.rs
This commit introduces the idea of a duplicate log. The duplicate log is a record of the count of additional collisions at a given hash key.
When node is written to the database, if an entry already exists for it, a count is updated in the duplicate log.   When a node is deleted, the count is decremented.  Once there are no duplicates, the count is removed entirely.  Nodes may be fully deleted at this point.\\
This fixes the issue that can occur with state pruning where a fork produces a duplicate hash, whose original value was produced outside of the state pruning window.  Those values would be deleted when the fork was prune, which would cause errors validating transactions that still expected the value to be in state.
> Prevent pruning of leaves via duplicate log

- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- validator/packaging/validator.toml.example
The validator.toml examples use
`seeds = ["tcp://127.0.0.1:8801"]`
`peers = ["tcp://127.0.0.1:8801"]`
They should vary the hostname, not the port, to show the more common usage.
> Remove Example Seeds and Peers Using Port 8001

- docs/source/architecture/validator_network.rst
- Replace the broken GossipBook.pdf link with a link to a different paper;
add a Wikipedia link for a high-level definition.
- Fix the 0MQ pattern link to point to the right section of the ZeroMQ doc
- Change the footnotes to inline links, because that's the best practice
for online documentation
> Fix broken links and footnotes

- integration/sawtooth_integration/docker/test_intkey_smoke_rust.yaml
- perf/intkey_workload/unit_intkey_workload.yaml
- perf/perf-tests.dockerfile
- perf/sawtooth_perf/unit_sawtooth_perf.yaml
- perf/sawtooth_workload/unit_perf_workload.yaml
- perf/smallbank_workload/unit_smallbank_workload.yaml
- sdk/examples/intkey_python/tests/test_tp_intkey_rust.yaml
- sdk/examples/intkey_rust/Dockerfile
- sdk/rust/rust-sdk-tests.dockerfile
- sdk/rust/unit_rust_sdk.yaml
- Added proxy support for all files used during `./run_tests -m rust_sdk` run
> Add proxy for run_test -m rust_sdk test related files

- validator/src/state/merkle.rs
- validator/src/state/merkle_ffi.rs
Putting unsafe on the function definition instead of at each location of unsafe code in the function is debatable, but it reduces the errors by 30+.
> Fix some clippy lint errors and warnings in merkle_ffi

- cli/sawtooth_cli/identity.py
- cli/sawtooth_cli/sawset.py
- consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
- families/battleship/sawtooth_battleship/battleship_client.py
- sdk/examples/intkey_python/sawtooth_intkey/client_cli/create_batch.py
- sdk/examples/intkey_python/sawtooth_intkey/client_cli/generate.py
- sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_client.py
- sdk/examples/intkey_python/sawtooth_intkey/client_cli/populate.py
- sdk/examples/noop_python/sawtooth_noop/client_cli/create_batch.py
- sdk/examples/xo_python/sawtooth_xo/xo_client.py
- sdk/python/sawtooth_processor_test/message_factory.py
Timestamps have a greater chance of collision, as use of
parallel transaction processing increases (either through
threads or multiple processes).
> Use Random Number instead of Timestamp for Nonce

- docker-compose-installed.yaml
- docker/compose/copy-debs.yaml
- perf/intkey_workload/Cargo.toml
- perf/intkey_workload/Dockerfile
- perf/intkey_workload/Dockerfile-installed
- perf/smallbank_workload/Cargo.toml
- perf/smallbank_workload/Dockerfile-installed
Update the package metadata and add intkey workload. This make it easier for other repos to run tests that use these workload packages.
> Cleanup workload package CI

- docs/source/architecture/events_and_transactions_receipts.rst
1. Document REST API for transaction receipts.
2. Fix missing '=' in filter example.
> Document Transaction Receipt REST API and Fix Typo

- docs/source/architecture/rest_api.rst
- Remove API details that aren't appropriate for an architecture guide (plus, they're out of date)
- Add link to the REST API Reference (which has the current API information)
> Update and focus "REST API" in Architecture doc

- validator/src/journal/publisher.rs
Change the queue limit multiplier to a constant and bump it from 2 to 10
> Change queue limit multiplier

- cli/sawtooth_cli/identity.py
This change was left out during 1.0 release changes in identity.proto file.
This fixes identity cli app crashing for cmd options addressed in this commit.
> Backport: Update Policy.Type to EntryType in identity cli

- validator/sawtooth_validator/journal/completer.py
A newly created Completer without blocks, batches, or seen
transactions did not set a numeric gauge value until batches
and blocks were added. The default 'nan' value for the gauge
resulted in InfluxDB errors on metrics submission.
> Initialize metrics collector gauge values in completer

- docs/source/architecture/journal.rst
- Add intro sentence to clarify the point of this section
- Remove all references to a "genesis operation"
> Change "Genesis Operation" to "The Genesis Process"

- docker/compose/sawtooth-default-poet.yaml
Port 4004 was exposed in rest containers which is not required
Signed-off-by: Manoj Gopalakrishnan <manoj.gopalkrishnan@intel.com>
> Remove unnecessary ports exposed in rest container

- docs/source/architecture/journal.rst
- docs/source/architecture/scheduling.rst
- Change bullets to numbers in Executor flow list, so text makes sense
- Fix a few typos and wording problems
- Add links to Chain Controller and Block Publisher (in Journal chapter)
> Fix typos, add links for Transaction Scheduling

- docs/source/architecture/validator_network.rst
- Delete incorrect "Related Components" diagram and section
- Remove future implementation content
- Reorganize "Wire Protocol" list to clarify items (message types
and transmission methods)
- Fix typos, formatting, and design-doc language
> Update and correct Validator Network in arch doc

- docs/source/_templates/indexcontent.html
- docs/source/architecture.rst
- docs/source/contents.rst
- docs/source/introduction.rst
- New title: Architecture Guide
- Move to after the Application Developer's Guide
- Add basic intro text (more in a later PR)
- Move the PoET architecture chapter to the end (for now; it may move elsewhere soon)
> Retitle and move Architecture guide; add intro

- integration/sawtooth_integration/docker/test_devmode_engine_liveness.yaml
- integration/sawtooth_integration/tests/test_devmode_engine_liveness.py
Add the devmode engine unit test to replace the use of the poet liveness
test which has been removed.
> Add devmode liveness python unit test

- validator/src/journal/fork_cache.rs
- validator/src/journal/mod.rs
This is required for dropping inactive branches from the block manager.
> Implement cache for tracking recently used forks

- validator/src/state/settings_view.rs
The SettingsViewFactory produces SettingsView<MerkleDatabase> instances
with a particular merkle root.
> Add SettingsViewFactory in Rust

- validator/src/journal/block_scheduler.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/mod.rs
This Rust block scheduler will be used once the BlockValidator is ported
to Rust. At that point the Python BlockScheduler will be removed.
> Port block scheduler to Rust

- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/server/core.py
- validator/sawtooth_validator/state/state_view.py
- validator/src/journal/candidate_block.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
- validator/src/journal/validation_rule_enforcer.rs
- validator/src/state/identity_view.rs
- validator/src/state/mod.rs
- validator/src/state/settings_view.rs
- validator/src/state/state_view_factory.rs
- validator/src/state/state_view_ffi.rs
- validator/tests/test_journal/block_tree_manager.py
- validator/tests/test_journal/tests.py
This finalizes the implementation of the SettingsView in Rust, by providing the similar functionality to the python implementation of instance-level memoization.  Additionally, it creates a generic version of the StateViewFactory, which will return any item that implements `From<Box<StateReader>>` (useful for forthcoming work on the IdentityView).  As a result, the existing SettingsViewFactory is removed.
> Use Rust SettingsView in BlockPublisher

- validator/src/gossip/mod.rs
- validator/src/gossip/permission_verifier.rs
- validator/src/journal/block_validator.rs
This PR adds code to validate the batches and state produced, on chain rules, permissions, and duplicates and dependencies.
~~This PR is built on #1827~~
> Add block validation checks in Rust

- docs/source/_templates/sdk_TP_tutorial.rst
- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
- docs/source/transaction_family_specifications/identity_transaction_family.rst
- docs/source/transaction_family_specifications/integerkey_transaction_family.rst
- docs/source/transaction_family_specifications/settings_transaction_family.rst
- docs/source/transaction_family_specifications/smallbank_transaction_family.rst
- docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
- docs/source/transaction_family_specifications/xo_transaction_family.rst
Fix the problems reported in STL-1165 and more: 
- Correct JS version number argument (array, not string) for XOHandler example (in SDK tutorial)
- Correct the JavaScript argument for apply, as shown in XOHandler example (in SDK tutorial)
- In SDK tutorials, delete the encoding argument from the JS & Python examples
- In Transaction Family Specifications, remove  the "Encoding" subsection from the "Transaction Header" section
- Add missing "Family" subsection to BlockInfo transaction family specification
- Fix a format error in the Validator Registry txn family spec
> Remove encoding from SDK tutorials + TF specs; fix errors

- sdk/rust/src/messaging/stream.rs
- sdk/rust/src/messaging/zmq_stream.rs
- sdk/rust/src/processor/mod.rs
The `rust-zmq` library doesn't actually require mutability for sending and replying, even though our `MessageSender` trait requires it. This PR removes the `mut` requirement on both the trait and the `ZmqMessageSender` struct, and updates a few function arguments to remove the `mut` requirement as well.
As an example of where this is useful, [Seth's ValidatorClient](https://github.com/hyperledger/sawtooth-seth/blob/master/rpc/src/client.rs#L163) currently requires `&mut self` for nearly all of it's methods simply because it has a `MessageSender` in it. Without this PR, turning those into `&self` references would require wrapping it's `sender` in `Arc<Mutex<...>>` unnecessarily, and with this PR those references can simply be switched to `&self` without any further changes.
This could …
> Remove mut requirement for MessageSender

- docs/source/_templates/sdk_TP_tutorial.rst
- docs/source/transaction_family_specifications/xo_transaction_family.rst
Also:
- Move "hash collision" paragraph into the Addressing section
- Fix minor wording, punctuation, and format issues
> Add delete to XO spec & SDK tutorials; fix name fields & range

- validator/packaging/validator.toml.example
There needs to be a comma between the options in the bind section.
> validator.toml.example is missing a comma

- Jenkinsfile
> Jenkins skip whitelist check when building 1-1 branch

- validator/sawtooth_validator/execution/executor.py
When running multiple validators, if transaction processor is restarted
on one of the nodes, the validator on that node stops processing future blocks
even after the transaction processor is up.
A stopped TP is removed after it fails to respond to ping.
The TP removal procedure was not getting carried out properly due to checks of
alive_threads and _open_futures. By removal of these checks TP restart
keeps validators in sync.
Resolves: STL-1115
Signed-off-by: mithunshashidhara <mithunx.shashidhara@intel.com>
> Validator synchronization issue after transaction processor is restarted

- docs/source/app_developers_guide.rst
- docs/source/app_developers_guide/using_the_sdks.rst
The "Available SDKs" topic was at the beginning of the App Dev Guide. 
The doc flow seems better when this topic is under "Using the SDKs".
> Move SDK table to SDK section of App Dev guide

- docs/source/_templates/sdk_overview_tutorial.rst
- docs/source/app_developers_guide/sdk_table.rst
Several SDKs moved into separate repositories (Go, Java, JS, and C++)
> Fix SDK repo links in "Available SDKs" & SDK tutorials

- validator/src/journal/block_manager.rs
- validator/src/journal/block_store.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/chain_ffi.rs
This PR does 2 main things
- uses a lock to guarantee that the block store stays stable during duplicates and dependencies check that relies on the block store
- simplifies the code that was in ChainCommitState, bringing in some of that functionality to the block manager - in particular `contains_any_transactions(branch_head_id, transaction_ids)` and the corresponding batch id function.
> Modify Duplicates and Dependencies check to decrease time that persist lock must be held

- docs/source/app_developers_guide/creating_sawtooth_network.rst
Correct intro description of the multi-node environment: Change "five nodes"  
to "multiple nodes" (because the Ubuntu proc creates two nodes)  
Make Settings and Validator Registry terms consistent with the rest of the doc 
Clarify that the Ubuntu multi-node procedure starts with an existing  single-node environment                                                       
In Ubuntu proc, add curly braces to "yourname" in the user key path & file name, 
to clarify it's not a literal 
Replace placeholder "xxx" text with links to the single-node K8s proc 
Fix format problems, a bad step number (K8s proc), and several typos
> Fix typos & misc errors in App Dev multi-node proc

- docs/source/_templates/sdk_overview_tutorial.rst
- docs/source/app_developers_guide/go_sdk.rst
- docs/source/app_developers_guide/javascript_sdk.rst
- docs/source/app_developers_guide/python_sdk.rst
- docs/source/app_developers_guide/rust_sdk.rst
- docs/source/app_developers_guide/sdk_prerequisites.rst
- Move the SDK tutorial's prerequisites to a separate topic (not part of the Overview)
- Add an intro sentence to the *_sdk.rst topics
- Make minor wording and format changes for clarity
> Fix App Dev guide's SDK section; reorg & separate prereqs

- validator/sawtooth_validator/server/core.py
It is required that to monitor disconnects, a check_connections callback
is passed to the Interconnect instance (component, consensus, ...).
> Fix nonetype is not callable error when consensus engine disconnect happens

- sdk/rust/src/processor/handler.rs
This PR changes the message type sent with the add event request from `TP_RECEIPT_ADD_DATA_REQUEST` to `TP_EVENT_ADD_REQUEST`.
The wrong message prevented new event types from being added successfully.
Signed-off-by: Eloá Franca Verona <eloafran@bitwise.io>
> Fix bug in rust sdk at TransactionContext add_event

- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/generating_keys.rst
- docs/source/sysadmin_guide/installation.rst
- docs/source/sysadmin_guide/setting_up_sawtooth_poet-sim.rst
- docs/source/sysadmin_guide/systemd.rst
- docs/source/sysadmin_guide/testing_sawtooth.rst
Update and correct existing procedures; add missing steps and procedures; clarify and expand the explanatory text.  
- Group the non-SGX procedures in a new section so that you can tell what's non-SGX vs SGX
- Clarify and format the install procedure
- Expand the "Starting Sawtooth" procedure to show the actual service commands and add the PoET simulator service
- Move the key-generation steps into their own procedure ; add more info to clarify user vs validator keys and key file location
- Create a new genesis block procedure with the correct steps for a system with PoET simulator consensus
- Reorganize the non-SGX sections to be in the correct order
Also:
- Add an overview/intro to the Sys Admin Guide
- Reorganize other sections: Move SGX section after the "generic" sections (for …
> Update non-SGX install/config/run proc in Sys Admin Guide

- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
Reviewers: Please review only the file setting_allowed_txns.rst.  (The first 7 commits are in PR #1868.)  See this commit: https://github.com/hyperledger/sawtooth-core/pull/1874/commits/e28bd1a209ff673ba5502ccdb1e0440c2a51234d
This new procedure is based on existing steps in the App Dev Guide - see the Ubuntu section in "Creating a Sawtooth Network". 
https://sawtooth.hyperledger.org/docs/core/nightly/master/app_developers_guide/creating_sawtooth_network.html#configure-txn-procs-ubuntu-label
> Add new proc to set allowed txn types (Sys Admin Guide)

- docs/source/sysadmin_guide/configuring_sawtooth.rst
- docs/source/sysadmin_guide/configuring_sawtooth/cli_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/identity_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/settings_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/xo_tp_configuration.rst
- docs/source/sysadmin_guide/log_configuration.rst
- Change title to clarify that this is reference info
- Rewrite intro for clarity and style
- Add links to config procedures in the sysadmin guide
- Clarify that the log and path config files are "non-component" files
and reorg to put them after the component files
- Change title and edit the log config file topic for clarity and style
> Update + edit Config File topics in Sys Admin Guide

- docs/source/sysadmin_guide/configuring_permissions.rst
- Write new intro
- Describe policy files and policy dir
- Note that you can lock yourself out of Identity settings if you're not careful
- Correct the sawtooth identity command name (it's not identity-tp)
- Add links to relevant info
- Fix formatting throughout (including changing indents)
Also:
- Correct the first "sawset proposal create" command to start with sudo,
include the --key option
Plus: Use fancy $(cat ...) syntax to provide the user's actual public key
and add a note that this command MUST be run on the "genesis node"
- Replace the second "sawset proposal create" command to refer to
the first one (the procedure assumes it has already been done)
> Update and edit Configuring Permissions in Sys Admin Guide

- docs/source/sysadmin_guide/configure_sgx.rst
- Add steps to set Curve ZMQ key for secured network communication
- Add REST API config file steps for network settings
- Add Identity TP (sawtooth-identity-tp.service) to all service steps.
- Correct sawtooth-settings-tp typo in journalctl command
- Fix minor wording issues and make "PoET-SGX" term consistent
> Update and correct PoET-SGX proc in Sys Admin Guide

- docs/source/transaction_family_specifications/identity_transaction_family.rst
Each policy is a list of type/key pairs (not a type and key list)
Also corrected the proto code in the doc to match the contents of protos/identity.proto
> Fix info on policy entries in Identity txn fam spec

- validator/src/ffi.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
This is the first of (I hope) a few PRs to cleanup some of the FFI and concurrency code in the BlockPublisher and validator in general.
> Block Publisher FFI Cleanup

- families/smallbank/smallbank_rust/build.rs
- perf/smallbank_workload/build.rs
- sdk/rust/build.rs
- validator/build.rs
..Default::default() causes a private attribute to be accessed, while
Customize::default() is clearer.
> Fix build.rs script for breaking protoc-rust change

- validator/src/journal/block_manager_ffi.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/fork_cache.rs
This removes `mut` where it is not necessary, handles a result, and
removes unused variables and imports.
> Remove warnings from tests

- NOTICES
This updates the NOTICES file for Sawtooth 1.1.
It identifies all 3rd party modules which are run-time dependencies, including modules identified by setup.py,  cargo.toml, and dockerfile-installed files in the the following directories:
sawtooth-core\\adm
sawtooth-core\cli
sawtooth-core\\families\settings
sawtooth-core\\families\identity
sawtooth-core\\families\\block_info
sawtooth-core\\rest_api
sawtooth-core\sdk\python
sawtooth-core\sdk\\rust
sawtooth-core\signing
sawtooth-core\\validator
> Updates NOTICES file for Sawtooth 1.1

- validator/src/journal/block_manager.rs
The three locks, references_by_block_id lock,, block_by_block_id,
block_store_by_name -- if they ever overlap -- must overlap in that
order, or there can be a deadlock.
> Fix BlockManager deadlock

- sdk/examples/devmode_rust/src/engine.rs
- sdk/rust/src/consensus/engine.rs
As newtypes, they require extra machinery to play nicely with serde, and switching them to type aliases means they get serde support for free.
Signed-off-by: Kenneth Koski <knkski@bitwise.io>
> Convert consensus ID newtypes to type aliases

- sdk/rust/src/consensus/engine.rs
This will allow PBFT and other consensus code to avoid cloning by writing `PeerMessage { ... }`.
See https://github.com/hyperledger/sawtooth-pbft/blob/master/src/node.rs#L271 for an example where we could improve things
Signed-off-by: Kenneth Koski <knkski@bitwise.io>
> Derive Clone for PeerMessage

- integration/sawtooth_integration/tests/test_xo_smoke.py
A change in commit e8c3dbab causes the xo smoke test to fail when
run from the Go SDK repo. This commit fixes this behavior and changes
'supported_langs' to an array to prevent unintentional breakage in
the future.
> Fix xo smoke test so it passes in go sdk repo

- docs/Makefile
Scenario: make process interrupted after cargo doc generation.
Upon again performing make, build won't continue because .lock
file is now deleted and cargo won't generate doc again.
'rm -f' would not fail make process if file is not found, but
will delete the file if there is one.
> Safe rm in Makefile for docs

- signing/sawtooth_signing/secp256k1.py
Remove some detritus that had survived a few refactorings of the signing
library. Previously a public key object was cached to use as a factory
and that is no longer relevant.
> Remove cached pubkey previously used as a factory

- docker/lint
This change keeps rustfmt from updating to a newer version.
> 1-1: Pin rust toolchain to stable-2018-09-13 for rust linting

- docs/source/sysadmin_guide/configure_sgx.rst
> Correct copy paste error in admin guide

- docs/source/sysadmin_guide/systemd.rst
Correct another copy paste error in admin guide (to match the SGX correction).
This change is for "Setting Up a Sawtooth Node / Starting Sawtooth as a Service" (the non-SGX procedure).  
- Remove the .service extension from the journalctl unit name.
- Move the -u sawtooth-poet-engine line up to match the order used in the SGX procedure ("Using Sawtooth with PoET-SGX / Start the Sawtooth Services"). 
Also fixed formatting for the TP executable names.
> Fix typos in admin guide (no .service in journalctl)

- protos/consensus.proto
- sdk/examples/devmode_rust/src/engine.rs
- sdk/python/sawtooth_sdk/consensus/engine.py
- sdk/python/sawtooth_sdk/consensus/service.py
- sdk/python/sawtooth_sdk/consensus/zmq_driver.py
- sdk/python/sawtooth_sdk/consensus/zmq_service.py
- sdk/python/tests/test_zmq_service.py
- sdk/rust/src/consensus/engine.rs
- sdk/rust/src/consensus/zmq_driver.rs
- sdk/rust/src/consensus/zmq_service.rs
- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/gossip/gossip.py
- validator/sawtooth_validator/gossip/gossip_handlers.py
- validator/sawtooth_validator/gossip/signature_verifier.py
- validator/tests/test_consensus/tests.py
This makes one more change to the p2p messaging API, which allows consensus
engines to save messages with their signatures and enables validation of
message signatures after the fact by an engine or observer.
> Stabilize Consensus P2P messaging API

- validator/sawtooth_validator/consensus/notifier.py
- validator/sawtooth_validator/journal/chain.py
- validator/sawtooth_validator/server/core.py
- validator/src/consensus/mod.rs
- validator/src/consensus/notifier.rs
- validator/src/consensus/notifier_ffi.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_ffi.rs
This removes an inefficiency in the core validator, where it must wait for a network ack from the engine whenever it sends it a notification.
> Rewrite consensus notifier in Rust and run in background thread

- sdk/rust/src/processor/mod.rs
Previously, this was sending the incorrect message type when responding to `PING_REQUEST` messages.
> Correct the message type for PING responses.

- validator/sawtooth_validator/server/events/broadcaster.py
- validator/tests/test_events/tests.py
This change handles the case when an event subscriber connects to the validator before it has either generated or received the genesis block.
In that instance, chain head is `None`, and an exception is raised, then the subscriber is left in an invalid state. This fix mitigates that issue.
Fixes [STL-952](https://jira.hyperledger.org/browse/STL-952)
Note, this should be back-ported to the 1-1 and 1-0 branches.
> Allow subscribers to connect when no Genesis Block

- rest_api/openapi.yaml
It was spelled as hecadeximal instead of hexadecimal.
> Fix spelling of hexadecimal in openapi.yaml

- docs/source/app_developers_guide/sdk_table.rst
SDK maturity table / overview page had link of XO TP example code
for Python and Rust, whereas it pointed to SDK repository for
other languages.
The header also tells that links mentioned are for SDK, thus changed
the link in document from XO example to respective SDK code.
> Fix SDK location in SDK table page

- docs/source/sdks.rst
Split the single JavaScript link into two links to match the
other SDKs on this page. (This fix is now possible because
the JavaScript SDK docs are being published correctly.)
> Make JS links consistent in SDK doc cover page

- validator/src/journal/chain.rs
Updates the way the validator sends new blocks when a consensus engine
registers to only send valid blocks. Blocks that have not been validated
yet will be sent to the engine when they get validated.
> Fix block sync for registering consensus engines

- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
This change switches the metadata namespace and block info namespace in the
documentation for the block_info transaction family. It also rewords the description of the metadata namespace.
> Fix namespaces description in block_info docs

- ci/nightly/sawtooth-block-info-tp
- ci/nightly/sawtooth-devmode-engine
- ci/nightly/sawtooth-identity-tp
- ci/nightly/sawtooth-intkey-tp-go
- ci/nightly/sawtooth-intkey-tp-python
- ci/nightly/sawtooth-rest-api
- ci/nightly/sawtooth-settings-tp
- ci/nightly/sawtooth-shell
- ci/nightly/sawtooth-smallbank-tp-go
- ci/nightly/sawtooth-validator
- ci/nightly/sawtooth-xo-tp-go
- ci/nightly/sawtooth-xo-tp-python
This change enables us to publish nightly docker images from the bumper
branch for use in testing.
> Update ci dockerfiles to pull from bumper/nightly

- docs/source/cli/sawadm.rst
> Delete wrong sawadm subcommand name in CLI ref

- integration/sawtooth_integration/docker/test_events_and_receipts.yaml
- integration/sawtooth_integration/tests/test_events_and_receipts.py
- validator/sawtooth_validator/journal/genesis.py
- validator/sawtooth_validator/server/core.py
- validator/tests/test_genesis/tests.py
When generated the genesis block, the transaction receipts generated must also be stored in the receipt store.  These transactions must be made available for event subscribers connect receive any catch-up events based on their filters.
Additionally,
- Updated the integration test for events and receipts to check for state events as well as block events, to validate this case.
>  Store Transaction Receipts Generated at Genesis time

- rest_api/stdeb.cfg
When the rest-api docker container is configured to send metrics to InfluxDB via
an https URL, the following error is printed due to ca-certificates not being
installed in the image.
Cannot write to SERVER_URL: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:645)
> Add ca-certificates as a dependency for rest-api

- ci/sawtooth-intkey-workload
This image will be used during docker / kubernetes based testing, and is
suitable for publishing to Dockerhub.
> Create sawtooth-intkey-workload docker image

- docs/source/app_developers_guide/sdk_table.rst
- docs/source/cli/sawadm.rst
- docs/source/community/issue_tracking.rst
- docs/source/community/join_the_discussion.rst
- docs/source/sdks.rst
- docs/source/transaction_family_specifications.rst
- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
Fix errors, broken links, and major typos in the Sawtooth core 1-1 documentation:
- Correct link to Rocket.Chat consensus channel
- Clarify Sawtooth help-wanted link (must log into JIRA)
- Fix namespaces description in block_info docs
- Fix SDK location in SDK table page
- Make JS links consistent in SDK doc cover page
- Delete wrong sawadm subcommand name in CLI ref
- Fix family name of Validator Registry in Txn Fam doc
> 1.1 doc backports: fix typos

- sdk/examples/devmode_rust/src/main.rs
> Fix copy-pasta for app name in clap macro

- docker/kubernetes/sawtooth-kubernetes-default.yaml
The published image for devmode engine in rust has the name
sawtooth-devmode-engine-rust, but it was mentioned in kubernetes
deployment yaml file as sawtooth-devmode-engine.
> Rename missed sawtooth-devmode-engine to sawtooth-devmode-engine-rust

- sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_cli.py
Intkey CLI client doesn't require keyfile for 'list' and 'show' verbs.
We should avoid expecting the key file be present in the home directory
ie do not expect ~/.sawtooth/${USER}.priv file for these operations.
These two subcommands do not accept --keyfile argument either.
> Intkey CLI checks for keyfile even though not used

- validator/sawtooth_validator/ffi.py
- validator/src/pylogger.rs
The Rust main.rs already inits the PyLogger.
> Remove init of pylogger.rs from python code

- validator/sawtooth_validator/ffi.py
- validator/src/pylogger.rs
The Rust main.rs already inits the PyLogger.
> 1-1: Remove init of pylogger.rs from python code

- rest_api/stdeb.cfg
When the rest-api docker container is configured to send metrics to InfluxDB via
a https URL, the following error is printed due to ca-certificates not being
installed in the image.
Cannot write to SERVER_URL: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:645)
This change is in master #1951 
> Add ca-certificates as a dependency for rest-api - 1-1 Backport

- ci/sawtooth-intkey-workload
This image will be used during docker / kubernetes based testing, and is
suitable for publishing to Dockerhub.
This is in master #1955 
> Create sawtooth-intkey-workload docker image - 1-1 backport

- validator/src/journal/publisher.rs
Ensure that checked subtraction is used when updating the queue limit.
There are scenarios (particularly a race condition that can occur during
genesis block creation) where the current queue limit is less than the
consumed number of batches. This race condition would result in a
"panicked at 'attempt to subtract with overflow'" error.  This change
fixes this issue.
> Use checked subtraction in queue limit

- ci/sawtooth-devmode-engine-rust
We are publishing sawtooth-devmode-engine-rust to docker hub.
> Rename sawtooth-devmode-engine to match dockerhub

- sdk/rust/src/processor/mod.rs
> 1-1 BACKPORT: Correct the message type for PING responses.

- validator/src/journal/publisher.rs
Backport of PR #1981 
Ensure that checked subtraction is used when updating the queue limit.
There are scenarios (particularly a race condition that can occur during
genesis block creation) where the current queue limit is less than the
consumed number of batches. This race condition would result in a
"panicked at 'attempt to subtract with overflow'" error.  This change
fixes this issue.
> 1-1 BACKPORT: Use checked subtraction in queue limit

- sdk/examples/devmode_rust/src/main.rs
Validator will default listen on 5050 port, make example devmode
to connect on 5050 instead of 5005.
> Fix default connector port in devmode consensus engine

- docs/source/sysadmin_guide/grafana_configuration.rst
The validator and rest-api examples used the wrong port. This commit
fixes that issue.
> Correct Influxdb port in Grafana documentation

- docs/source/introduction.rst
- Remove "mutually distrusting" from consensus definition
- Update consensus interface info (mention consensus API and consensus engines)
- Add PBFT and Raft
- Improve and correct PoET description
- Clarify Dev mode info
> Update consensus section in Introduction

- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/state/client_handlers.py
- validator/src/journal/block_manager.rs
- validator/src/state/settings_view.rs
This PR has several minor fixes for various consensus proxy methods, as well as the client handlers (which has an effect on the PoET engine). 
~Probably more controversially, this removes the `panic` when a block is unref'ed in the `BlockManager` and it is already at `0`.  This panic makes the system quite unstable as a validator will crash in this situation.~
Updated to improve the panic message (and remove the controversy for a future PR).
> Consensus fixes

- docs/source/app_developers_guide/ubuntu.rst
* Install devmode engine
* Start devmode engine
* Install and CLI names vary by Sawtooth release
> Add Missing Dev Guide Ubuntu Instructions for Devmode Consensus Engine

- ci/sawtooth-build-docs
- families/settings/sawtooth_settings/src/handler.rs
- sdk/examples/intkey_rust/src/handler.rs
- sdk/examples/xo_rust/src/handler/game.rs
- sdk/examples/xo_rust/src/handler/mod.rs
- sdk/examples/xo_rust/src/handler/payload.rs
- sdk/examples/xo_rust/src/main.rs
- sdk/rust/src/consensus/zmq_driver.rs
- sdk/rust/src/processor/handler.rs
- validator/sawtooth_validator/ffi.py
- validator/src/pylogger.rs
- validator/src/state/merkle.rs
This reverts commit ba9517ec0937e0674ee561fdd6ee79d31d004f8c.
This restores proper logging in the rust code.  With the removal of this
init of pylogger, log messages from the lower layer (i.e. libsawtooth)
are not included in the logs.  This makes debugging difficult.
> Revert "Remove init of pylogger.rs from python code"

- docs/source/sysadmin_guide/grafana_configuration.rst
The validator and rest-api examples used the wrong port. This commit
fixes that issue.
This was merged to master in #1993 
> Correct Influxdb port in Grafana documentation - 1-1 backport

- docs/source/app_developers_guide/ubuntu.rst
* Install devmode consensus engine
* Start devmode consensus engine
> Backport: Add Missing Dev Guide Ubuntu Instructions for Devmode Engine

- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/installation.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/sysadmin_guide/setting_up_sawtooth_poet-sim.rst
- docs/source/sysadmin_guide/systemd.rst
- Update the consensus settings and PoET consensus engine name
in the genesis block procedure
- Update the example output in the testing procedure
- Correct the terminology (consensus engine, consensus algorithm)
- Update text to include the consensus engine component in
descriptions and steps
Note: This is a subset of the doc changes from PR #1992 (in master). This
commit contains only the essential corrections needed for the 1-1 documentation.
> 1-1 BACKPORT: Add consensus engine steps/info in Sys Admin Guide

- docs/source/_templates/partials/encoding_your_payload.rst
- docs/source/_templates/partials/submitting_to_validator.rst
- docs/source/_templates/sdk_TP_tutorial.rst
- docs/source/_templates/sdk_submit_tutorial.rst
- docs/source/_templates/template_config.yaml
- docs/source/app_developers_guide/go_sdk.rst
- docs/source/app_developers_guide/go_sdk_import.rst
1. Add information on Go SDK installation
=> Also include information on generating go protobuf files
2. Add information on Go SDK usage for constructing a client
=> Used intkey as an example to demonstrate client application
development, this is in sync with document on other
languages
3. Add information on Go SDK for submitting a request to validator
4. [minor] Change from tab to space for Go TP doc section
A Pull Request is raised on sawtooth-sdk-go repository to add intkey client application in Go.
> Document Go SDK client usage

- bin/run_lint_rust
- bin/run_lint_validator
Fix diff output formatting. Add quotes to avoid field splitting.
The diff shown by lint becomes unreadable otherwise.
Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>
> Fix rust lint output formatting

- validator/packaging/validator.toml.example
- validator/sawtooth_validator/config/validator.py
- validator/sawtooth_validator/server/cli.py
- validator/sawtooth_validator/server/core.py
This PR adds configuration settings for the validator's network, component, and signature thread pool max workers.  This allows for easier tuning of these settings during performance testing, without having to run custom builds of the validator.
Note: These settings are config file only.
> Add configuration settings for network, component and signature thread pool workers

- adm/Cargo.toml
- docs/source/app_developers_guide/rust_sdk_import.rst
- families/battleship/Cargo.toml
- families/block_info/sawtooth_block_info/Cargo.toml
- families/identity/sawtooth_identity/Cargo.toml
- families/settings/sawtooth_settings/Cargo.toml
- families/smallbank/smallbank_rust/Cargo.toml
- perf/intkey_workload/Cargo.toml
- perf/sawtooth_perf/Cargo.toml
- perf/sawtooth_workload/Cargo.toml
- perf/smallbank_workload/Cargo.toml
> Update Transaction Processors to use sawtooth-sdk = "0.2"

- validator/src/state/merkle.rs
This PR fixes a couple bugs in the merkle prune and tests.
In one of the cases for prunning, the root is supposed to be removed but that was not happening and the tests did not catch this error.
> Fix prune error

- .pylintrc
> BACKPORT 1-1: Ignore R1720: Unnecessary "elif" after "raise" (no-else-raise)

- validator/sawtooth_validator/gossip/gossip_handlers.py
- validator/sawtooth_validator/server/network_handlers.py
Instead of using the `GossipBroadcastHandler` to send peer messages to the consensus engine, use a new handler `GossipConsensusHandler`. Notifying the consensus engine isn't a "broadcast" function, so it should have a different handler. Now, the `GossipBroadcastHandler` will simply pass when it encounters a peer message.
In addition to being more correct and accurate from an understandability perspective, this change allows for correct behavior of the time-to-live (TTL) functionality for gossip. Without this change, if TTL is set to <= 1, consensus messages will never be delivered to the consensus engine. With this change, TTL can be set to any value and consensus messages will be unaffected.
> Use new handler for consensus gossip messages

- validator/sawtooth_validator/gossip/gossip.py
When returning a list of public keys in the `get_peers_public_keys`
method, `Gossip` should filter out None values.
This fixes a bug where consensus activation could not occur because None
values in the list would cause it to fail.
Corresponding 1.1 backport: #2038
> Filter out None when getting public keys in gossip

- validator/sawtooth_validator/consensus/proxy.py
When the validator accepts a registration from a consensus engine, it
will return a list of its connected peers in a StartupState object.
This fixes a bug where, if the list of peers contained a None value,
registration would fail when it attempted to encode the public key as
hex.
Corresponding master PR: #2037
> 1.1 BACKPORT: Filter out None in consensus startup info's peers

- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
Updates the values of `sawtooth.consensus.algorithm.name` and `.version`
for PBFT in the docs to be `pbft` and `0.1` respectively to match the
changes to the PBFT consensus engine. See:
https://github.com/hyperledger/sawtooth-pbft/pull/118
> Update algorithm name, version settings for PBFT

- docker/telegraf.conf
Enable sawtooth process statistics in telegraf, these can be then
tracked in grafana.
> Enable sawtooth process statistics in telegraf

- perf/smallbank_workload/Dockerfile-installed-bionic
- perf/smallbank_workload/Dockerfile-installed-xenial
This change adds sawtooth-cli to the smallbank-workload docker images. This
is necessary because smallbank-workload requires a private key at
runtime.
> Add sawtooth-signing and cli to smallbank-workload

- validator/src/journal/chain.rs
Under certain circumstances, the validator will be told to compare chains by the consensus engine that will result in an empty new chain. If this is the case, checking index `0` will result in an index-out-of-bounds panic error.  Returning an error will be logged.
~Additionally, apply new rust format changes for the latest rust version.~
> Return an error on an empty new chain

- docs/source/app_developers_guide/creating_sawtooth_network.rst
- docs/source/architecture/journal.rst
- docs/source/sysadmin_guide/configure_sgx.rst
Updates documentation to include information about the new consensus
engine settings, `sawtooth.consensus.algorithm.name` and
`sawtooth.consensus.algorithm.version`, and remove erroneous
information.
> Backport 1-1: Update docs for new consensus settings

- families/block_info/sawtooth_block_info/Cargo.toml
- families/identity/sawtooth_identity/Cargo.toml
- families/settings/sawtooth_settings/Cargo.toml
Sabre is going to be updated to be compatible with 0.3 of
the Rust SDK. This commit pins the version of the sabre
sdk to the version that is compatible with the 0.2 version
of the rust sdk.
> Update sabre-sdk version to 0.1.3 instead of master

- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/testing_sawtooth.rst
Sawtooth already uses the term "peer" for static/dynamic peering, so the
PBFT doc was overloading this term. This PR changes "peer" to "(PBFT) member node"
and adds a glossary definition for "member node".
Note: The PBFT documentation is fixed in a related-but-separate PR for
the hyperledger/sawtooth-pbft repo.
> Fix terminology for PBFT member nodes (was peers)

- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/sysadmin_guide/testing_sawtooth.rst
Updates docs to reflect change to the name of the on-chain list of
members in a PBFT network. Corresponds to this PBFT PR:
https://github.com/hyperledger/sawtooth-pbft/pull/126
> Update name of on-chain PBFT members list

- Jenkinsfile
The containers lint-validator_1, lint-rust_1, and lint-python_1 were
being left over after the build completes, this change removes these
containers.
> Run docker-compose down on run-lint.yaml

- validator/sawtooth_validator/consensus/registry.py
To support a consensus engine restarting independently of the validator,
the consensus registry must be able to register a conensus engine again.
When this happens, the engine will register with the same name and
version, but a different connection ID. The registry will simply remove
any old entries associated with the engine name and version before
adding the engine to the registry.
> Allow re-registering consensus engines

- validator/sawtooth_validator/execution/context_manager.py
- validator/src/journal/chain.rs
- validator/src/scheduler/execution_result_ffi.rs
- validator/src/scheduler/mod.rs
Fixes the `TxnExecutionResult.data` to be consistent. Before this
change, some components assumed this field was a list of
(data type,bytes) pairs, others assumed it was just a list of bytes.
Corresponding master PR: #2064
> 1-1 BACKPORT: Fix TxnExecutionResult.data field

- validator/sawtooth_validator/networking/future.py
- validator/sawtooth_validator/networking/interconnect.py
Some futures produced during peering attempts were never resolved and
_SendReceive did not clean them up in any way. On a longer time scale,
this was leading to excessive memory usage by the validator service.
This commit adds the possibility to set a timeout for a Future object.
If a timeout was set for a Future, FutureCollection is able to clean
that future after a timeout when the remove_expired method is called.
This method is called periodically by _SendReceive (the timeout is equal
to connection_timeout).
Also, futures are explicitly removed when stopping an
OutboundConnection.
Signed-off-by: Yevhenii Babichenko <babichenko@482.solutions>
> Remove futures from _SendReceive after a certain timeout.

- docs/source/sysadmin_guide/setting_allowed_txns.rst
> Remove two unused pbft settings from setting_allowed_txns

- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/notifier.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/consensus/registry.py
- validator/sawtooth_validator/server/consensus_handlers.py
- validator/sawtooth_validator/server/core.py
- validator/src/journal/chain.rs
This PR removes the NewBlockSync handler when an engine registered, which would send all forks to the engine, whether they had been validated or not.  This broke the contract with consensus engines (as it currently stands) and would cause problems with PoET networks during catch up.
While there is no active consensus engine, the notifications are queued, with activation messages having priority.
Instead of busy-waiting for the genesis block, this PR includes a new ChainObserver that will activate the configured engine, if those settings have changed.
Additionally, a timeout has been added on the notification send's expected result, so as not to hang threads while waiting on a response that might never come.
> Improve consensus engine behaviour between registration and activation

- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/consensus/registry.py
Raise an `EngineNotRegistered` exception when attempting to activate a consensus engine that has not been registered.  This will inform the callers not to do any following activities for the engine (like sending it a notification) if it hasn't yet connected.
Fixes an issue where duplicate activations were being sent to the engine due to the notifier queuing messages when there was no active engine.
> Raise and handle EngineNotRegistered

- adm/build.rs
- adm/src/commands/genesis.rs
- cli/sawtooth_cli/admin_command/genesis.py
- cli/tests/test_genesis.py
- docs/source/_includes/create-genesis-block.inc
- docs/source/app_developers_guide/ubuntu.rst
- validator/sawtooth_validator/consensus/proxy.py
When consensus is not set on-chain, fall back to PoET if PoET settings are set, otherwise devmode
> Consensus backwards compatibility fix

- docker/compose/sawtooth-default-pbft.yaml
- docs/source/sysadmin_guide/setting_allowed_txns.rst
Removes the optional PBFT settings from the docs and docker compose
file; some of the setting names are outdated, and the default values
should be used unless otherwise needed.
> Remove optional PBFT settings

- families/block_info/sawtooth_block_info/Cargo.toml
- families/identity/sawtooth_identity/Cargo.toml
- families/settings/sawtooth_settings/Cargo.toml
This will allow sabre smart contracts to be compiled on more
platforms when not compiling into wasm.
To test: Add the wasm32 target rustup target add wasm32-unknown-unknown --toolchain nightly and run both cargo build and cargo +nightly build --target wasm32-unknown-unknown (in the respective directories). Both should pass.
> Replace unix with not wasm32 in platform-specific dependencies

- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
> Correct step number in BlockInfo txn family spec

- docs/source/_templates/txn_submit_tutorial.rst
In the App Dev Guide, "Development Without and SDK", clarified that hexadecimal strings for signatures and hashes must use lower-case characters.
Note: I did not make this change for addresses (I assume that case doesn't matter for a hex address).
This PR addresses STL-1501.
> Doc: Note that hexified strings must be lower-case

- docs/source/architecture/transactions_and_batches.rst
Update "Transactions and Batches" in the Sawtooth Architecture Guide: 
- Add  note with information on low-s normalization for the transaction and batch headers, along with info that the python3 SDK and others do this for you, but some libraries don't.
- Change the existing note to a tip so it'll be visually distinct (different color).
- Also: Fixed the identical header text (sphinx reports that as an error) and added bullets so "Transaction Header, Signature, and Public Keys" is easier to skim-read.
This doc change addresses the issue reported by STL-1500.
> Arch doc: Add info on low-s normalized sig for txn + batch headers

- adm/src/commands/genesis.rs
- adm/src/main.rs
- cli/sawtooth_cli/admin_command/genesis.py
- docs/source/_includes/create-genesis-block.inc
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/cli/sawadm.rst
Adds the `--ignore-required-settings` flag to the `sawadm genesis`
command that allows bypassing the required settings check. Because the
sawtooth settings transaction family is a reference implementation, it's
possible that a different settings transaction family could be used to
set the required settings at genesis. This bypass allows `sawadm
genesis` to pass in this situation. However, the genesis chain
controller will still fail if the required settings aren't in state
as a result of the genesis block, so the same requirements are enforced.
>  Make sawadm genesis required settings optional

- docker/compose/sawtooth-default-pbft.yaml
Fixes the peering configuration in
`docker/compose/sawtooth-default-pbft.yaml`. Peering should only be
specified once between two validators; it was being specified in both
directions before, which lead to duplicate peering.
> Fix peer configuration in PBFT docker compose

- docs/Makefile
- docs/source/_includes/pbft-vs-poet-cfg.inc
- docs/source/app_developers_guide/docker_test_network.rst
Update the App Dev Guide's multi-node procedure, "Using Docker for a Sawtooth Test Network", to add PBFT info, steps, and example information. This new info requires some corrections or rewrites to existing content. 
Also updated the docs/Makefile to copy the example PBFT yaml file to the same docs directory as the PoET yaml file.
For example, the step showing how to run `ps` in the PoET Validator Registry container now shows how to check that the REST API process is running.
This PR also corrects and clarifies existing information (text and steps) in this procedure:
- Add prerequisites for Docker and Docker Engine; clarify info on shutting down a single node, if running
- Clarify which container is being used in each step
- Fix error in "sawtooth proposal create" (intro text was wrong)
- …
> Add PBFT steps to Docker NW proc; correct existing info

- protos/processor.proto
- validator/sawtooth_validator/execution/executor.py
- validator/sawtooth_validator/execution/processor_handlers.py
- validator/sawtooth_validator/execution/processor_manager.py
The PR has two commits
1. Introduce a protocol_version field for TpRegisterRequest.
2. Allow transaction processor to receive raw transaction header bytes.
RFC describes details on need to have raw (serialized version from client request) transaction header, sent to transaction processor. Transaction processor can register to get raw transaction header.
CXX SDK changes: https://github.com/hyperledger/sawtooth-sdk-cxx/pull/6
Rust SDK changes: https://github.com/hyperledger/sawtooth-sdk-rust/pull/4
Python SDK changes: https://github.com/hyperledger/sawtooth-sdk-python/pull/4
> Allow transaction processor to receive raw transaction header from client

- perf/smallbank_workload/Dockerfile-installed-bionic
- perf/smallbank_workload/Dockerfile-installed-xenial
This fixes an error in the sawtooth cli that the sdk is missing.
> Update smallbank-workload to install the sdk

- validator/src/journal/publisher.rs
Updates the way the block publisher accepts batches and adds them to its pending queue:
- Don't add a batch to the candidate block if the batch was already in the pending queue
- Don't add a batch to the pending queue if the batch is already committed
- Don't notify batch observers unless the batch is new (not already committed, not already in the pending queue)
> Fix adding batches to the publisher's pending queue

- validator/sawtooth_validator/gossip/signature_verifier.py
The self.seen_cache was been recreated everytime a block was
valid. Instead the block's header signature should be added
to the timed_cache so if a duplicate is recieved it can
be properly dropped.
> Fix GossipBlockResponseSignatureVerifier seen_cache

- Jenkinsfile
This was mistakenly left as master when it should be 1-1
> Update branch checks in Jenkinsfile to 1-1

- docs/source/app_developers_guide/ubuntu_test_network.rst
For a Sawtooth consensus engine, the executable name does not start
with "sawtooth" (except for PoET, which is sawtooth-poet-engine).
> Fix pbft-engine executable name in App Dev Guide

- docs/source/_templates/indexcontent.html
- docs/source/architecture.rst
- docs/source/contents.rst
- docs/source/introduction.rst
- docs/source/transaction_family_specifications.rst
- docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
- Add PBFT, Sabre, and Seth links to core docs
- Make consistency-related content changes for PoET, etc. (for clear/consistent titles, TOC presentation, and things like that)
- Fix issues found when adding the external doc links
> Add links to external PBFT, Sabre, and Seth docs in ST core docs

- validator/sawtooth_validator/gossip/gossip.py
Example Scenario: If there are three validators A, B and C.
These are configured such that A has B and C as peers,
B has C and A as peers, C has A and B as peers.
Every node initiates an outbound connection to the nodes
configured as their peers.
A peering request is sent when connection is established
successfully. With the above configuration the nodes may have
duplicate peers.
The default number of maximum number of peers is set to 10.
With above configuration, the limit may exceed soon with more
number of peers. Most of which are duplicate peering connections.
> Avoid duplicate peering request from same endpoint

- validator/sawtooth_validator/gossip/gossip.py
This reverts commit 898064666509ffedcd94ca47e3fd7987b997e469.
The reverted commit introduces a race condition where validators are
unable to properly bi-directionally peer.
> Revert "Avoid duplicate peering request"

- docs/source/app_developers_guide/aws.rst
- docs/source/app_developers_guide/docker.rst
- docs/source/app_developers_guide/intro_xo_transaction_family.rst
- docs/source/app_developers_guide/kubernetes.rst
- docs/source/app_developers_guide/ubuntu.rst
In the Docker, Kubernetes, AWS, and Ubuntu procedures:
- Add missing step to confirm REST API connectivity, if necessary.
- Rework existing "connect to Sawtooth" step to be consistent across the four
procedures.
- Change titles so they're unique across the doc set (for clarity and because
Sphinx complains).
- Add anchor tags for links from XO procedure.
In the "Playing with XO" procedure:
- Separate the first step (connect to Sawtooth) and expand with links to
Docker, Kubernetes, and AWS. Text info suffices for Ubuntu.
- For "confirm REST API connectivity" step, correct or add links for the
four procedures.
> Add Connect to REST API steps and links

- bin/run_bandit
Workaround for bug reported here: https://github.com/PyCQA/bandit/issues/488
> 1-1 BACKPORT: Add more specific exclude paths for bandit

- validator/sawtooth_validator/gossip/signature_verifier.py
The self.seen_cache was being recreated everytime a block was
valid. Instead the block's header signature should be added
to the timed_cache so if a duplicate is recieved it can
be properly dropped.
> Backport 1-1: Fix GossipBlockResponseSignatureVerifier seen_cache

- docker/sawtooth-shell
intkey is installed in the images created by docker-compose-installed
and in the images published to dockerhub. This commit adds intkey to the
shell generated by docker-compose.yaml for use in future testing
routines
> Add intkey cli to sawtooth-shell docker image

- docker/compose/sawtooth-default-pbft.yaml
All the other docker-compose files use the name shell for the container
named sawtooth-shell-default, this change makes the PBFT docker-compose
file consistent with the others.
> Rename sawtooth-shell in pbft docker-compose file

- bin/run_tests
- integration/sawtooth_integration/docker/test_two_families.yaml
- integration/sawtooth_integration/tests/test_block_info_injector.py
- integration/sawtooth_integration/tests/test_events_and_receipts.py
- integration/sawtooth_integration/tests/test_namespace_restriction.py
- integration/sawtooth_integration/tests/test_two_families.py
Remove the dependency on the python SDK to avoid the collisions of thegenerated protobuf classes from the essentially the same source.
This replaces the use of the IntkeyMessageFactory with direct creation of intkey transactions using the protobuf classes in the `sawtooth_validator` package.
> Remove the use of IntkeyMessageFactory in Tests

- validator/src/database/lmdb.rs
- validator/src/journal/commit_store.rs
Disambiguate the use of `last` on `LmdbDatabaseReaderCursor` between its own method and that of Iterator. This commit renames `LmdbDatabaseReaderCursor`'s methods to `seek_first` and `seek_last` to differentiate the meaning.
This fixes the performance regression that occurs with `get_chain_head`.
> Disambiguate last on LmdbDatabaseReaderCursor

- docs/source/_includes/about-nw-each-node-runs.inc
- docs/source/_includes/about-sawtooth-networks.inc
- docs/source/app_developers_guide/docker_test_network.rst
- docs/source/app_developers_guide/kubernetes_test_network.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
This PR updates "Using Kubernetes for a Sawtooth Test Network" in the App Dev Guide
to add PBFT steps and related information (intro material, overviews, links, etc.) 
alongside the existing PoET steps.
It also contains changes to make the Docker, Ubuntu, and Kubernetes procedures consistent.
> Docs: Add PBFT steps to K8s network procedure

- protos/consensus.proto
- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/consensus/registry.py
- validator/tests/test_consensus/tests.py
Adds a list of additional protocols (name/version pairs) that a consensus engine can support. Also updates how consensus engine name/version settings are inferred for backwards compatibility.
> Improve consensus backwards compatibility

- bin/run_docker_test
This feature is required for cross-repository testing.
> Improve run_docker_test to handle multiple compose files

- docs/source/_includes/consensus-node-reqs.inc
- docs/source/app_developers_guide/docker.rst
- docs/source/app_developers_guide/kubernetes.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/architecture/journal.rst
- docs/source/glossary.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/about_dynamic_consensus.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/setting_up_sawtooth_poet-sim.rst
Add new topic "About Dynamic Consensus"
- Summarizes admin tasks for setting consensus in a new network
and for changing consensus on a running network.
- For each consensus type, lists requirements and on-chain settings
- Adds links to this topic from the Introduction, App Dev Guide (Ubuntu network
procedure) and Sys Admin Guide
- Documents consensus backwards compatibility - includes information about
consensus defaults                                                            
Clean up consensus terms in Sawtooth docs
- Change "dev mode" to "Devmode" to match the consensus engine name
- Make other terms consistent and coherent (in the glossary and elsewhere)
> Add new About Dynamic Consensus topic; clean up terms

- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
Add consensus to network and component bind info in the App Dev Guide and
Sys Admin Guide
Also improve the note location in the step to start the consensus engine
on the command line
> Add consensus bind endpoint info to docs

- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
Correct the command that restricts file permissions for validator.toml
in two sections of the System Administrator's Guide:
- Setting Up a Sawtooth Network / Changing Off-chain Settings with Configuration
Files / Configure the Validator
- Using Sawtooth with PoET-SGX / Change the Validator Config File
> Fix error: change chmod to chown in SysAdmin Guide

- protos/consensus.proto
- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/consensus/registry.py
- validator/tests/test_consensus/tests.py
Backport of #2130
Adds a list of additional protocols (name/version pairs) that a consensus engine can support. Also updates how consensus engine name/version settings are inferred for backwards compatibility.
> 1-2 backport: Improve consensus backwards compatibility

- docs/source/api_references.rst
- docs/source/app_developers_guide/go_sdk.rst
- docs/source/app_developers_guide/javascript_sdk.rst
- docs/source/app_developers_guide/no_sdk.rst
- docs/source/app_developers_guide/python_sdk.rst
- docs/source/app_developers_guide/rust_sdk.rst
- docs/source/app_developers_guide/sdk_table.rst
- docs/source/app_developers_guide/using_the_sdks.rst
- docs/source/sdk_go.rst
- docs/source/sdk_javascript.rst
- docs/source/sdk_python.rst
- docs/source/sdk_rust.rst
- docs/source/sdks.rst
This PR updates the SDK-related topics in the App Dev Guide and SDK and API Reference:
- Add Java + Swift links to SDK topics; edit topics to streamline and clarify
- Fix SDK doc org: clean up + make consistent
It also contains changes to improve the intro and note for "Development Without an SDK".
> Doc: Add Java + Swift links; improve org and content

- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
Backport of #2140 
Correct the command that restricts file permissions for validator.toml
in two sections of the System Administrator's Guide:
- Setting Up a Sawtooth Network / Changing Off-chain Settings with Configuration
Files / Configure the Validator
- Using Sawtooth with PoET-SGX / Change the Validator Config File
> 1-2 backport: Fix error: change chmod to chown in SysAdmin Guide

- docs/source/_includes/consensus-node-reqs.inc
- docs/source/app_developers_guide/docker.rst
- docs/source/app_developers_guide/kubernetes.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/architecture/journal.rst
- docs/source/glossary.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/about_dynamic_consensus.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
- docs/source/sysadmin_guide/setting_up_sawtooth_poet-sim.rst
Backport of #2131 and #2142 
This PR adds a new "About Dynamic Consensus" topic (summary of requirements, settings, and tips for PBFT, PoET, Raft, and Devmode) and cleans up consensus-related terminology. It also adds information on the consensus bind endpoint to the App Dev Guide and Sys Admin Guide.
> 1-2 backport: Consensus doc changes (new topic, terms, endpoint)

- docs/source/sysadmin_guide/configure_sgx.rst
Changed "1.1" to "1.1 or later". Also removed statement that PoET-SGX would be supported in Sawtooth 1.1.
> Update note on PoET SGX support to include 1.2

- docs/source/api_references.rst
- docs/source/app_developers_guide/go_sdk.rst
- docs/source/app_developers_guide/javascript_sdk.rst
- docs/source/app_developers_guide/no_sdk.rst
- docs/source/app_developers_guide/python_sdk.rst
- docs/source/app_developers_guide/rust_sdk.rst
- docs/source/app_developers_guide/sdk_table.rst
- docs/source/app_developers_guide/using_the_sdks.rst
- docs/source/sdk_go.rst
- docs/source/sdk_javascript.rst
- docs/source/sdk_python.rst
- docs/source/sdk_rust.rst
- docs/source/sdks.rst
Backport of #2151 
This PR updates the SDK-related topics in the App Dev Guide and SDK and API Reference:
- Add Java + Swift links to SDK topics; edit topics to streamline and clarify
- Fix SDK doc org: clean up + make consistent
It also contains changes to improve the intro and note for "Development Without an SDK".
> 1-2 backport: Doc: Add Java + Swift links; improve org and content

- docs/source/sysadmin_guide/configuring_sawtooth/cli_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/identity_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/path_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/settings_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/xo_tp_configuration.rst
- docs/source/sysadmin_guide/log_configuration.rst
Add info on the required/recommended ownership and permissions for config files: Owner root, group sawtooth, and permissions 640.
> Add owner+perm info to sysadmin config file topics

- docs/source/_includes/about-network-bind-endpoint-strings.inc
- docs/source/_includes/create-genesis-block.inc
- docs/source/_includes/sawtooth-settings-list-pbft.inc
- docs/source/_includes/testing-rest-api.inc
- docs/source/app_developers_guide/aws.rst
- docs/source/app_developers_guide/kubernetes.rst
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/architecture/journal.rst
- docs/source/architecture/permissioning_requirement.rst
- docs/source/architecture/poet.rst
- docs/source/architecture/scheduling.rst
- docs/source/architecture/validator_network.rst
- docs/source/cli/sawtooth-validator.rst
- docs/source/cli/sawtooth.rst
- docs/source/glossary.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/transaction_family_specifications.rst
- docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
- Change "validator node" to "Sawtooth node" (or just "node").
- Change "validator network" to "Sawtooth network" or "validator", depending on context.
- Change "Validator Registry" (TP/TF name) to "PoET Validator Registry".
Also fix typos and wording problems noticed when making these changes.
> Doc: Fix terms for node, network, and PoET Validator Registry

- docs/source/sysadmin_guide/configuring_sawtooth/cli_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/identity_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/path_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/settings_tp_configuration.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/configuring_sawtooth/xo_tp_configuration.rst
- docs/source/sysadmin_guide/log_configuration.rst
Backport of #2157 
Add info on the required/recommended ownership and permissions for config files: Owner root, group sawtooth, and permissions 640.
> 1-2 backport: Add owner+perm info to sysadmin config file topics

- cli/stdeb.cfg
python3-sawtooth-sdk is sporadically missing from sawtooth-cli deb
package, the change in the PR hard codes it in.
> Hard code sdk dependency in cli

- docs/source/_includes/about-network-bind-endpoint-strings.inc
- docs/source/_includes/create-genesis-block.inc
- docs/source/_includes/sawtooth-settings-list-pbft.inc
- docs/source/_includes/testing-rest-api.inc
- docs/source/app_developers_guide/aws.rst
- docs/source/app_developers_guide/kubernetes.rst
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/architecture/journal.rst
- docs/source/architecture/permissioning_requirement.rst
- docs/source/architecture/poet.rst
- docs/source/architecture/scheduling.rst
- docs/source/architecture/validator_network.rst
- docs/source/cli/sawtooth-validator.rst
- docs/source/cli/sawtooth.rst
- docs/source/glossary.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/transaction_family_specifications.rst
- docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
- Change "validator node" to "Sawtooth node" (or just "node").
- Change "validator network" to "Sawtooth network" or "validator", depending on context.
- Change "Validator Registry" (TP/TF name) to "PoET Validator Registry".
Also fix typos and wording problems noticed when making these changes.
Backport of #2160
> 1-2 backport: Doc: Fix terms for node, network, and PoET Validator Registry

- cli/stdeb.cfg
python3-sawtooth-sdk is sporadically missing from sawtooth-cli deb
package, the change in the PR hard codes it in.
> Hard code sdk dependency in cli 1-2

- docs/source/sysadmin_guide/configure_sgx.rst
Changed "1.1" to "1.1 or later". Also removed statement that PoET-SGX would be supported in Sawtooth 1.1.
> 1-2 backport: Update note on PoET SGX support to include 1.2

- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/generating_keys.rst
- docs/source/sysadmin_guide/grafana_configuration.rst
- docs/source/sysadmin_guide/installation.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
- docs/source/sysadmin_guide/rest_auth_proxy.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/sysadmin_guide/systemd.rst
- docs/source/sysadmin_guide/testing_sawtooth.rst
Change the notes "tested on Ubuntu 16.04 only" to the Chime version: "tested on Ubuntu 18.04 (Bionic) only".
Also change the PoET-SGX procedure's note to say "tested with Sawtooth 1.0 on Ubuntu 16.04 only."
> Update doc notes - tested on 18.04/Bionic only

- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide/configure_sgx.rst
- docs/source/sysadmin_guide/configuring_permissions.rst
- docs/source/sysadmin_guide/creating_genesis_block.rst
- docs/source/sysadmin_guide/generating_keys.rst
- docs/source/sysadmin_guide/grafana_configuration.rst
- docs/source/sysadmin_guide/installation.rst
- docs/source/sysadmin_guide/off_chain_settings.rst
- docs/source/sysadmin_guide/rest_auth_proxy.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/sysadmin_guide/systemd.rst
- docs/source/sysadmin_guide/testing_sawtooth.rst
Backport of #2169 
Change the notes "tested on Ubuntu 16.04 only" to the Chime version: "tested on Ubuntu 18.04 (Bionic) only".
Also change the PoET-SGX procedure's note to say "tested with Sawtooth 1.0 on Ubuntu 16.04 only."
> 1-2 backport: Update doc notes - tested on 18.04/Bionic only

- docs/source/architecture.rst
- docs/source/introduction.rst
- docs/source/sysadmin_guide/about_dynamic_consensus.rst
- docs/source/transaction_family_specifications.rst
Change PBFT and Sabre 1.2 doc links from nightly/master to release/latest.
> 1-2 only: Change PBFT + Sabre doc links: nightly -> latest

- docs/source/_includes/about-sawtooth-networks.inc
- docs/source/_templates/indexcontent.html
- docs/source/contents.rst
- docs/source/introduction.rst
The doc links for PBFT, Sabre, and Seth are already in the relevant topics.  Including them as top-level TOC links didn't fit with the Sawtooth doc organization. 
This PR also fixes and clarifies text related to these external docs.
> Doc: Clean up top-level TOC (remove external doc links)

- docs/source/_includes/about-sawtooth-networks.inc
- docs/source/_templates/indexcontent.html
- docs/source/contents.rst
- docs/source/introduction.rst
Backport of #2167 
The doc links for PBFT, Sabre, and Seth are already in the relevant topics. Including them as top-level TOC links didn't fit with the Sawtooth doc organization.
This PR also fixes and clarifies text related to these external docs.
> 1-2 backport: Doc: Clean up top-level TOC (remove external doc links)

- CODEOWNERS
- MAINTAINERS.md
As described in the Sawtooth Governance RFC changes to maintainers must be approved unanimously by the current group of maintainers.
> Propose that Logan Seeley and Richard Berg be added as maintainers

- docs/source/_includes/create-genesis-block.inc
- docs/source/sysadmin_guide/about_dynamic_consensus.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
The files where I updated VERSION to 1.0 had version numbers in the examples for the other consensus engines.
> Update docs for 1.0 pbft algorithm version

- perf/smallbank_workload/Cargo.toml
Old description
`Description: [generated from Rust crate sawtooth-smallbank-workload]`
New description
`Description: Workload generator for Sawtooth Smallbank`
> Add description to smallbank workload Cargo.toml

- docs/source/_includes/create-genesis-block.inc
Correct the indent so that the tip is formatted correctly.
Also move the tip after the info about replacing the VALxKEY strings, because
the tip is less important (the example shows the current version number).
> Doc: Fix format of tip; improve info order

- docs/source/_includes/create-genesis-block.inc
Backport of #2201 
Correct the indent so that the tip is formatted correctly.
Also move the tip after the info about replacing the VALxKEY strings, because
the tip is less important (the example shows the current version number).
> 1.2 backport: Doc: Fix format of tip; improve info order

- docs/Makefile
Preserve the kubernetes pbft yaml file in the docs build artifacts for
publishing.
> Include kubernetes pbft yaml in docs artifacts

- validator/sawtooth_validator/execution/processor_manager.py
Add a trace to identify the case where transaction is
scheduled for execution and there's no TP registered
which can execute the transaction.
> Add a trace message while waiting for TP registration

- docker/grafana/dashboards/dashboard.json
The metric for "chain_head_moved_to_fork_count" moved from being under
the BlockValidator to the ChainController.  This commit corrects the
default grafana dashboard to display this data.
> Correct metric for "chain head moved"

- validator/sawtooth_validator/execution/processor_manager.py
Add a trace to identify the case where transaction is
scheduled for execution and there's no TP registered
which can execute the transaction.
> 1-2 Backport: Add a trace message while waiting for TP registration

- adm/src/commands/blockstore.rs
Updates to protobuf broke the reading of the length-delimited backup file. This PR fixes the issue.
Additionally, adds context to many of the blockstore commands error messages.
> Fix sawadm restore

- docs/source/_includes/create-genesis-block.inc
- docs/source/_includes/generate-keys.inc
- docs/source/app_developers_guide/docker_test_network.rst
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/adding_authorized_users.rst
- docs/source/sysadmin_guide/pbft_adding_removing_node.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/transaction_family_specifications/settings_transaction_family.rst
- Change the Ubuntu single- and multi-node procedures to use the user's private key for the genesis block instead of the validator key. Also change the user key name to "my_key" (to match the k8s environment) and clarify the key required for settings change proposals.
- In other procedures, make the key-related info more generic and clarify the validator key information. 
- In the Settings transaction family spec, clarify the definition of sawtooth.settings.vote.authorized_keys and add info about voting.
- Add new procedure to the Sys Admin Guide for changing the authorized users in sawtooth.settings.vote.authorized_keys, "Adding Adding Authorized Users for Settings Proposals".
- Update "Adding and Removing a PBFT Node" to clarify settings-related info and steps.
> Docs: Fix settings + key info, add auth user proc

- validator/sawtooth_validator/execution/processor_handlers.py
- validator/sawtooth_validator/server/component_handlers.py
- validator/sawtooth_validator/server/state_verifier.py
Return the TpRegisterResponse acknowledgment before adding the TP to the list of processors.  This ensures that the processor always receives the expected ack before it begins to receive any messages requesting transaction execution.
This follows a similar model to the event subscriptions.
> Return ACK before sending process requests

- docs/Makefile
Preserve the kubernetes pbft yaml file in the docs build artifacts for
publishing.
This is a backport of #2199 
> 1-2 Backport: Include kubernetes pbft yaml in docs artifacts

- docs/source/_includes/create-genesis-block.inc
- docs/source/_includes/generate-keys.inc
- docs/source/app_developers_guide/docker_test_network.rst
- docs/source/app_developers_guide/ubuntu.rst
- docs/source/app_developers_guide/ubuntu_test_network.rst
- docs/source/sysadmin_guide.rst
- docs/source/sysadmin_guide/adding_authorized_users.rst
- docs/source/sysadmin_guide/pbft_adding_removing_node.rst
- docs/source/sysadmin_guide/setting_allowed_txns.rst
- docs/source/transaction_family_specifications/settings_transaction_family.rst
Backport of #2212 
- Change the Ubuntu single- and multi-node procedures to use the user's private key for the genesis block instead of the validator key. Also change the user key name to "my_key" (to match the k8s environment) and clarify the key required for settings change proposals.
- In other procedures, make the key-related info more generic and clarify the validator key information.
- In the Settings transaction family spec, clarify the definition of sawtooth.settings.vote.authorized_keys and add info about voting.
- Add new procedure to the Sys Admin Guide for changing the authorized users in sawtooth.settings.vote.authorized_keys, "Adding Adding Authorized Users for Settings Proposals".
- Update "Adding and Removing a PBFT Node" to clarify settings-related info and steps.
> 1-2 Backport: Docs: Fix settings + key info, add auth user proc

- validator/src/journal/block_scheduler.rs
When calling `done` on the `BlockScheduler`, add the next set of blocks (the immediate successor blocks), if any, to the `processing` list.
This corrects an issue where the blocks are scheduled again due to not being marked as in-process via the above mechanism.
> Add ready blocks to processing

- perf/intkey_workload/Cargo.toml
> 1-2 Backport: Add description to intkey workload Cargo.toml

- validator/src/journal/block_scheduler.rs
Backport of #2217 
When calling `done` on the `BlockScheduler`, add the next set of blocks (the immediate successor blocks), if any, to the `processing` list.
This corrects an issue where the blocks are scheduled again due to not being marked as in process via the above mechanism.
> BACKPORT 1-2: Add ready blocks to processing

- adm/Dockerfile-installed-bionic
- adm/Dockerfile-installed-xenial
- families/block_info/Dockerfile-installed-bionic
- families/block_info/Dockerfile-installed-xenial
- families/identity/Dockerfile-installed-bionic
- families/identity/Dockerfile-installed-xenial
- families/settings/Dockerfile-installed-bionic
- families/settings/Dockerfile-installed-xenial
- families/smallbank/smallbank_rust/Dockerfile-installed-bionic
- families/smallbank/smallbank_rust/Dockerfile-installed-xenial
- perf/intkey_workload/Dockerfile-installed-bionic
- perf/intkey_workload/Dockerfile-installed-xenial
- perf/smallbank_workload/Dockerfile-installed-bionic
- perf/smallbank_workload/Dockerfile-installed-xenial
The behavior of cargo-deb was changed to generate version numbers with
tildes instead of dashes. This is causing newly built packages to sort
below older releases.
https://github.com/mmstick/cargo-deb/pull/102
> Fix versioning of packaged Rust components

- adm/Dockerfile-installed-bionic
- adm/Dockerfile-installed-xenial
- families/block_info/Dockerfile-installed-bionic
- families/block_info/Dockerfile-installed-xenial
- families/identity/Dockerfile-installed-bionic
- families/identity/Dockerfile-installed-xenial
- families/settings/Dockerfile-installed-bionic
- families/settings/Dockerfile-installed-xenial
- families/smallbank/smallbank_rust/Dockerfile-installed-bionic
- families/smallbank/smallbank_rust/Dockerfile-installed-xenial
- perf/intkey_workload/Dockerfile-installed-bionic
- perf/intkey_workload/Dockerfile-installed-xenial
- perf/smallbank_workload/Dockerfile-installed-bionic
- perf/smallbank_workload/Dockerfile-installed-xenial
The behavior of cargo-deb was changed to generate version numbers with
tildes instead of dashes. This is causing newly built packages to sort
below older releases.
https://github.com/mmstick/cargo-deb/pull/102
> 1-2 BACKPORT: Fix versioning of packaged Rust components

- validator/sawtooth_validator/consensus/handlers.py
- validator/sawtooth_validator/consensus/proxy.py
- validator/sawtooth_validator/journal/block_wrapper.py
- validator/sawtooth_validator/journal/chain.py
- validator/src/journal/block_wrapper.rs
- validator/src/journal/block_wrapper_ffi.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_ffi.rs
Updates the validator:
- Send a block to consensus as soon as it's created/received.
- Wait for a check_blocks() request from consensus to validate the
block.
- Send a BlockValid/BlockInvalid update to consensus when the block has
finished validating.
This was the original intent for consensus API behavior, and it allows
consensus to prioritize which blocks are considered.
This PR has been verified using the devmode liveness test.
> Only validate block on request from consensus

- validator/sawtooth_validator/ffi.py
- validator/sawtooth_validator/journal/block_store.py
- validator/sawtooth_validator/journal/publisher.py
These commits change the libexec style from python style to c-style (and vise versa) for selected calls based on performance testing method timings. Generally, the preference is to hold the python GIL (via pylibexec) for frequent, fast FFI calls, and to release the GIL (via libexec) for slow FFI calls.
> Change libexec style for selected calls based on perf testing results

- ci/sawtooth-build-docs
- ci/sawtooth-shell-installed
- docker/lint
- docker/sawtooth-debug-python
- docker/sawtooth-shell
- integration/sawtooth_integration/docker/integration-tests.dockerfile
- validator/Dockerfile
- validator/Dockerfile-installed-bionic
- validator/Dockerfile-installed-xenial
- validator/sawtooth_validator/gossip/gossip_handlers.py
- validator/sawtooth_validator/server/network_handlers.py
- validator/setup.py
- validator/stdeb.cfg
- validator/tests/test_duplicate_handler/tests.py
- validator/tests/validator-tests.dockerfile
In a gossip network, often multiple duplicate messages arrive from peers in short order. Previously, the duplicate handler was performing an existence check (has_block, has_batch) against the completer. Since the completer likely does not process the first message by the time the last duplicate is seen, the completer's "caches" were not filled, resulting in a high volume of block store calls (resulting in "not in" results to the duplicate handler). This change moves to an LRU cache of message signature headers managed by the handler itself. This should allow the duplicate handler to behave as expected (dropping short-term duplicates) without excessive existence check calls.
In sawtooth, message broadcasting occurs prior to the message being passed to the completer. Previously, the …
> Remove gossip duplicate and broadcast existence checks

- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/server/core.py
- validator/src/journal/candidate_block.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
- validator/tests/test_journal/block_tree_manager.py
- validator/tests/test_journal/tests.py
Updates the block publisher to use the native CommitStore for checking
committed transactions and batches rather than using the Python FFI.
> Use native Rust commit store in Publisher

- validator/sawtooth_validator/journal/publisher.py
- validator/sawtooth_validator/server/core.py
- validator/src/journal/candidate_block.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
- validator/tests/test_journal/block_tree_manager.py
- validator/tests/test_journal/tests.py
Updates the block publisher to use the native CommitStore for checking
committed transactions and batches rather than using the Python FFI.
> 1-2 Backport: Use native Rust commit store in Publisher

- integration/sawtooth_integration/docker/integration-tests.dockerfile
- integration/sawtooth_integration/docker/test_ipv6.yaml
- integration/sawtooth_integration/tests/test_ipv6.py
- rest_api/sawtooth_rest_api/rest_api.py
- validator/sawtooth_validator/networking/interconnect.py
These are two simple patches to enable using IPv6 with Sawtooth.
1) Enable the validator to bind to an IPv6 address by passing the correct ZMQ flag.
2) Do some filtering to ensure that an IPv6 address passed in bracket format is accepted by the REST API.
Please let me know if you would like to see "more" in the REST API code, or if anything else is required.
> Proposed patches to allow Validator and REST API to work with IPv6

- bin/run_tests
This commit enables the IPV6 test by default in the run_tests script.
docker-compose creates an IPV6 network even if IPV6 is not enabled
globally in Docker, so this will not cause failures where its not enabled.
> Add IPV6 tests to run_tests script

- sdk/examples/devmode_rust/src/main.rs
Validator will default listen on 5050 port, make example devmode
to connect on 5050 instead of 5005.
This is a backport of https://github.com/hyperledger/sawtooth-core/pull/1966 to 1.1 branch
> [1.1 Backport] Fix default connector port in devmode consensus engine

- docs/source/sysadmin_guide/about_dynamic_consensus.rst
Change the backwards-compatibility note in "About Dynamic Consensus" (in the
System Administrator's Guide):
- Add information to make it clear that the consensus name and version settings
are always required for a new network.
> Doc: Clarify consensus compatibility info in note

- .gitignore
- libsawtooth/Cargo.toml
- libsawtooth/src/lib.rs
- libsawtooth/src/store/btree.rs
- libsawtooth/src/store/error.rs
- libsawtooth/src/store/lmdb.rs
- libsawtooth/src/store/mod.rs
- libsawtooth/src/store/receipt_store/error.rs
- libsawtooth/src/store/receipt_store/mod.rs
- libsawtooth/src/store/redis.rs
- Add the libsawtooth crate that will provide various components used by the Sawtooth validator.
- Add the `OrderedStore` trait, which defines an interface for a key/value store that is indexed by a type with total ordering.
- Add a BTreeMap-backed implementation of the `OrderedStore` trait for an in-memory ordered store.
- Add the `TransactionReceiptStore`, which is a wrapper around an `OrderedStore` that can be used to store transaction receipts, keyed by transaction IDs, in order.
- Add the `RedisOrderedStore` struct, which is an implementation of the `OrderedStore` trait that uses a redis database.
- Add the `LmdbOrderedStore`, which is an implementation of the `OrderedStore` trait that uses an LMDB database.
> Add libsawtooth and stores

- libsawtooth/Cargo.toml
- libsawtooth/src/lib.rs
- libsawtooth/src/store/btree.rs
- libsawtooth/src/store/error.rs
- libsawtooth/src/store/lmdb.rs
- libsawtooth/src/store/mod.rs
- libsawtooth/src/store/receipt_store/mod.rs
- libsawtooth/src/store/redis.rs
Add the `LmdbOrderedStoreIter` struct that is returned by the
`LmdbOrderedStore.iter()` method. This iterator loads items into an
in-memory cache as needed and provides an iterator over the values in
the ordered store. Additionally, it provides the option to specify a
range to get only a subset of items in the database.
> Add LmdbOrderedStoreIter for iterating over an LMDB ordered store

- libsawtooth/src/store/btree.rs
- libsawtooth/src/store/lmdb.rs
- libsawtooth/src/store/mod.rs
- libsawtooth/src/store/receipt_store/error.rs
- libsawtooth/src/store/receipt_store/mod.rs
- libsawtooth/src/store/redis.rs
Add a method for getting all receipts in the store since the receipt
with the given ID.
> Transaction receipt store range queries

- docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
Sorry my last PR https://github.com/hyperledger/sawtooth-core/pull/2269 was accidenetly closed. Now i signed my commit.
> Fix typo in block info address calculation

- docs/source/app_developers_guide/kubernetes_test_network.rst
Instead of `$ kubectl log pbft-keys-xxxxx`, it should be `$ kubectl logs pbft-keys-xxxxx`.
> Doc : Fixed typo in kubernetes_test_network.rst

- docs/source/community/issue_tracking.rst
Fix a link to the list of issues labeled as `help-wanted` .
> Fix a dead link in docs

- families/block_info/sawtooth_block_info/src/handler.rs
This is similar to 5e7315a9f0e3c8863327034c036b28e70850112c, which was
a fix for the python version of block_info. To quote that commit:
"The timecheck needs to ensure that the timestamp is only ahead of
a transaction processor's local time by the value of tolerance. The use
of absolute value enforced that this time check is within tolerence of
the local time. This fails validation in the case where a node is
catching up on a chain the may contain blocks that were published more
than time-tolerence in the past.  Correcting this to ensure the the
timestamp is no more than tolerence in the future, ensures that the
transaction can still be validated during a catch up scenario."
> Fix timestamp check in block_info for catch up

- families/block_info/sawtooth_block_info/src/handler.rs
This is similar to 5e7315a9f0e3c8863327034c036b28e70850112c, which was
a fix for the python version of block_info. To quote that commit:
"The timecheck needs to ensure that the timestamp is only ahead of
a transaction processor's local time by the value of tolerance. The use
of absolute value enforced that this time check is within tolerence of
the local time. This fails validation in the case where a node is
catching up on a chain the may contain blocks that were published more
than time-tolerence in the past.  Correcting this to ensure the the
timestamp is no more than tolerence in the future, ensures that the
transaction can still be validated during a catch up scenario."
> BACKPORT: Fix timestamp check in block_info for catch up

- libsawtooth/Cargo.toml
- libsawtooth/src/store/lmdb.rs
- libsawtooth/src/store/receipt_store/mod.rs
transact v0.2 changes the `TransactionReceipt` protocol.
> Update transact dependency to 0.2

- ci/sawtooth-build-docs
An outdated version of pip was causing the 'zipp' package to fail during
installation.
> Upgrade pip during sawtooth-build-docs image build

- validator/src/state/merkle.rs
- validator/src/state/state_view_factory.rs
The python code wraps data in CBOR when added to state, and unwraps the values when read.  This reader provides the CBOR-decoded values to the rust implementations of `StateView` structs via a new implementation of the `StateReader`.
> Add DecodedMerkleStateReader for state views

- libsawtooth/Cargo.toml
- libsawtooth/build.rs
- libsawtooth/protos/batch.proto
- libsawtooth/protos/block.proto
- libsawtooth/protos/consensus.proto
- libsawtooth/protos/events.proto
- libsawtooth/protos/setting.proto
- libsawtooth/protos/transaction.proto
- libsawtooth/protos/transaction_receipt.proto
- libsawtooth/protos/validator.proto
- libsawtooth/src/protos/mod.rs
This PR starts moving protos to libsawtooth. The protos are currently copied into the libsawtooth/proto directory. This will be required when it is published and moved out to its own repo.
Currenlty the following protos files are included:
batch
block
consensus
events
setting
transaction
transaction_receipt
validator
> Add proto generation to libsawtooth

- libsawtooth/src/batch.rs
- libsawtooth/src/lib.rs
- libsawtooth/src/transaction.rs
- validator/src/batch.rs
- validator/src/batch_ffi.rs
- validator/src/block.rs
- validator/src/block_ffi.rs
- validator/src/gossip/permission_verifier.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/candidate_block.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/chain_head_lock.rs
- validator/src/journal/commit_store.rs
- validator/src/journal/commit_store_ffi.rs
- validator/src/journal/incoming_batch_queue_ffi.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
- validator/src/journal/validation_rule_enforcer.rs
- validator/src/lib.rs
- validator/src/py_object_wrapper.rs
- validator/src/scheduler/mod.rs
- validator/src/scheduler/py_scheduler.rs
Involves moving both the `Transaction` and `Batch` structs to libsawtooth, and makes the necessary changes to the validator to refer to this new location. Also creates a new `PyObjectWrapper` object which, appropriately, wraps a PyObject and implements the `ToPyObject` and `FromPyObject` traits in order to function as a go-between for the Batch struct defined in the libsawtooth module and the remaining validator code that still expects to translate this struct into a PyObject.
> Move Transaction and Batch struct to libsawtooth

- libsawtooth/src/block.rs
- libsawtooth/src/lib.rs
- validator/src/block.rs
- validator/src/block_ffi.rs
- validator/src/consensus/notifier.rs
- validator/src/consensus/notifier_ffi.rs
- validator/src/journal/block_manager.rs
- validator/src/journal/block_manager_ffi.rs
- validator/src/journal/block_scheduler.rs
- validator/src/journal/block_store.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/block_wrapper.rs
- validator/src/journal/candidate_block.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_commit_state.rs
- validator/src/journal/chain_ffi.rs
- validator/src/journal/chain_head_lock.rs
- validator/src/journal/commit_store.rs
- validator/src/journal/commit_store_ffi.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
Moves the `Block` struct to libsawtooth, and changes all references to this struct within the validator to the moved struct. This also removes the `ToPyObject` and `FromPyObject` implementations for the `Block` struct, and replaces this with From impls for the struct and the `PyObjectWrapper`.
> Move Block struct to libsawtooth

- libsawtooth/src/lib.rs
- libsawtooth/src/metrics/mod.rs
- validator/src/journal/block_manager.rs
- validator/src/journal/block_scheduler.rs
- validator/src/journal/chain.rs
- validator/src/journal/publisher.rs
- validator/src/metrics/mod.rs
- validator/src/py_object_wrapper.rs
- validator/src/state/state_pruning_manager.rs
1. Create a MetricsCollectorHandle trait that can generate
a counter and gauge objects.
2. Create traits for Counter and Gauge objects.
3. Abstract the Python implementation of MetricsCollectorHandle
and Counter/Gauge objects.
4. Use PyObjectWrapper as a generic parameter that gauge can take
in.
5. Implement PyObjectWrapper from usize, u64 and &str.
Signed-off-by: S m, Aruna <aruna.mohan@walmartlabs.com>
> Create traits for metrics module

- libsawtooth/src/gossip/mod.rs
- libsawtooth/src/gossip/permission_verifier.rs
- libsawtooth/src/journal/mod.rs
- libsawtooth/src/journal/validation_rule_enforcer.rs
- libsawtooth/src/lib.rs
- libsawtooth/src/state/mod.rs
- libsawtooth/src/state/settings_view.rs
- libsawtooth/src/state/state_view_factory.rs
- validator/src/gossip/permission_verifier.rs
- validator/src/journal/block_validator.rs
- validator/src/journal/block_validator_ffi.rs
- validator/src/journal/candidate_block.rs
- validator/src/journal/chain.rs
- validator/src/journal/chain_ffi.rs
- validator/src/journal/mod.rs
- validator/src/journal/publisher.rs
- validator/src/journal/publisher_ffi.rs
- validator/src/journal/validation_rule_enforcer.rs
- validator/src/state/mod.rs
- validator/src/state/state_view_ffi.rs
This moves a few modules over to libsawtooth, including:
* `SettingsView`
* `StateViewFactory`
* `enforce_validation_rules` function
* `PermissionVerifier` trait
> Move several modules from validator to libsawtooth

- validator/Cargo.toml
The validator needs to be available as a dynamic library because
of the FFI integration with the python code. However, using dylib
caused linker issues when pulling in the sawtooth-sabre
transaction handler, a requirement for the integration with transact.
Changing to a cdylib fixes this issue.
> Update validator library crate type to cdylib

- validator/sawtooth_validator/metrics/metrics.py
- validator/src/pymetrics.rs
Updates the Python metrics collector to no longer require a module name
on construction, and updates the construction in the Rust FFI code to
forgo the module name
The value returned by the `MetricsCollectorHandle._create_identifier`
method has been updated to a list rather than a tuple; this ensures that
the identifier is joined properly even if it only has a single item (in
the case that the module and instance are not set).
This fixes a bug that resulted in an extra `sawtooth_validator` in the
metric name reported to InfluxDB; instead of
`sawtooth_validator.{metric}`, the metric names were
`sawtooth_validator.sawtooth_validator.{metric}` because the
`sawtooth_validator` prefix is already added to all metrics sent to
InfluxDB.
> Fix metrics reporting bug

- validator/sawtooth_validator/networking/interconnect.py
This check was called when the monitor thread was notified
of a disconnection and would check all existing external
transaction processors. With the transact integration and
removal of the python executor, the check_connection
function was never set.
This commit adds a check to skip calling check_connections
if it is none.
> Check if check_connections is None before calling

- validator/sawtooth_validator/state/batch_tracker.py
- validator/tests/test_client_request_handlers/mocks.py
- validator/tests/test_client_request_handlers/test_submit_handlers.py
Updates the `chain_update` method for the batch tracker to use the
provided block for notifying of committed batches rather than checking
the commit store. This fixes a bug that was created by a recent change
to the chain controller; the chain controller now notifies of committed
batches before persisting the committed block to the commit store. This
resulted in the batch tracker not properly notifying of committed
batches.
The fix is to not check the commit store in `chain_update`, but rather
just use the batch IDs in the provided block. In addition to fixing the
bug, this avoids an unnecessary database call.
> Fix bug in batch tracker's chain_update method

- validator/sawtooth_validator/metrics/metrics.py
Fixes a typo in the `MetricsCollectorHandle._create_identifier` method.
The wrong thing was being returned from this function.
> Fix typo in _create_identifier method

- adm/Dockerfile-installed-bionic
- adm/Dockerfile-installed-xenial
Change command to only substitute first occurrence of version when building `admin tools`.
> Fix admin tools build versioning

- docker/lint
Since the release of version 2.7.0 pylint has been segfaulting during the
linting step of CI builds. This can be researched more comprehensively once
active development continues on Sawtooth.
> Pin pylint to fix CI builds

- docker/lint
Since the release of version 2.7.0 pylint has been segfaulting during the
linting step of CI builds. This can be researched more comprehensively once
active development continues on Sawtooth.
> BACKPORT 1-3: Pin pylint to fix CI builds

- adm/Cargo.toml
- adm/src/commands/batch.rs
- adm/src/commands/mod.rs
- adm/src/main.rs
Add the `batch` subcommand to sawadm. The `batch` subcommand has a `list` subcommand which lists all existing batches in the current blockchain. `batch list` has optional flags for specifying the authorizer of the request, the output format of the batches, and the URL of the Validator's REST API.
> Add 'batch' subcommand to sawadm

- ci/sawtooth-build-docs
v0.17 causes builds to fail with a UnicodeDecodeError.
> BACKPORT 1-2: Pin docutils version

- ci/sawtooth-build-docs
v0.17 causes builds to fail with a UnicodeDecodeError.
> BACKPORT 1-3: Pin docutils version

- perf/smallbank_workload/src/playlist.rs
The solution here is to reduce it a simple string, which isn't ideal
since it will no longer print the missing transaciton type. However,
this code is unrefined anyway since it panics at all, and the solution
of rewriting it with proper error handling can happen in a future change
aimed at removing the panics.
> Fix panic w/non-static String compiler warning

- perf/sawtooth_workload/src/main.rs
try!() is very old and this avoids a compiler warning.
> Replace try!() with ?

- ci/sawtooth-build-docs
The following error was being returned when using the latest
version of sphinx:
<openapi>:1:Problem in http domain: field is supposed to use role 'obj',
but that role is not in the domain.
This is caused by an incompatibility with the current version of
sphinxcontrib-httpdomain. The issues does not exist in sphinx 0.4.
> Pin sphinx to 4.0 to fix build issues

- ci/sawtooth-build-docs
The following error was being returned when using the latest
version of sphinx:
1:Problem in http domain: field is supposed to use role 'obj',
but that role is not in the domain.
This is caused by an incompatibility with the current version of
sphinxcontrib-httpdomain. The issues does not exist in sphinx 0.4.
> Backport 1-3: Pin sphinx to 4.0 to fix build issues

- ci/sawtooth-build-docs
The following error was being returned when using the latest
version of sphinx:
<openapi>:1:Problem in http domain: field is supposed to use role 'obj',
but that role is not in the domain.
This is caused by an incompatibility with the current version of
sphinxcontrib-httpdomain. The issues does not exist in sphinx 0.4.
> Backport 1-2: Pin sphinx to 4.0 to fix build issues

- bin/make_templated_docs
The 6.0 release of PyYAML (a bandit dependency) introduced a change that
requires the `Loader=` argument when using `yaml.load()`. Because we don't need
any of the additional funcationality available in `yaml.load()`, this function
was switched to `yaml.safe_load()` instead.
https://github.com/yaml/pyyaml/pull/561
> Fix doc build

- bin/make_templated_docs
The 6.0 release of PyYAML (a bandit dependency) introduced a change that
requires the `Loader=` argument when using `yaml.load()`. Because we don't need
any of the additional funcationality available in `yaml.load()`, this function
was switched to `yaml.safe_load()` instead.
https://github.com/yaml/pyyaml/pull/561
> BACKPORT 1-2: Fix doc build

- ci/sawtooth-build-docs
- docker/bandit
- docker/lint
The 1.7.2 release of Bandit drops support for python 3.6, which is the latest
available for ubuntu bionic.
> Pin bandit version

- validator/Cargo.toml
- validator/src/journal/block_validator.rs
- validator/src/journal/chain_commit_state.rs
TransactionCommitCache is currently based on a HashSet which depends on its clients to properly clean up their items in a timely fashion. However, under high load circumstances, this can be too long resulting in quiet OOM issues and in practice freezing the whole network.
This changes the TransactionCommitCache to an uluru LRU. This is safe since the commit cache is based on data that cannot change and the worst that happens on a miss is a refetch from the store.
uluru is also updated to 3.0.0 which requires a minor change to `block_validator.rs` to account for the changed construction
> change TransactionCommitCache to LRU

- validator/src/state/state_pruning_manager.rs
In the previous code, the line `Some(Ordering::reverse(self.0.cmp(&other.0)))` was incorrect because it would return the opposite of what you intended, potentially leading to incorrect ordering of elements.
Signed-off-by: Joseph Livesey [jlivesey@gmail.com](mailto:jlivesey@gmail.com)
> Fix PartialOrd implementation for prune candidate
