README.md
add incubation notice
Fixes #1 
Signed-off-by: Christopher Ferris <chrisfer@us.ibm.com>
=> add incubation notice

journal/journal_core.py
=> Using the variable to avoid duplicate code

tools/plugins/install_docker.sh
Signed-off-by: Bas van Oostveen <trbs@trbs.net>
=> removed duplicate line and fixes to indentation

extensions/mktplace/mktplace/transactions/market_place.py
=> Remove the useless line of codes

core/journal/global_store_manager.py
=> Format code style

core/sawtooth/client.py, extensions/arcade/sawtooth_xo/xo_cli.py, extensions/arcade/sawtooth_xo/xo_client.py, validator/txnserver/web_pages/forward_page.py
Address part of moving client-side validation to server-side.
This PR permits disable client-side validation.
=> Permit disable client-side validation

core/sawtooth/client.py, extensions/mktplace/mktplace/mktplace_communication.py
=> Print error detail information from server

core/sawtooth/client.py
=> Enhance messages returned by get transaction status

core/sawtooth/cli/transaction.py
Before this PR, "sawtooth_xo", or "mktplace.transactions.market_place" etc TransactionFamilies loaded, when using "sawtooth transaction list" command, it would crash. Throws "update = trans_info["Update"] KeyError: 'Update'" error. This PR fixes the bug.
=> Fix sawtooth transaction list command bug

core/sawtooth/cli/admin.py, core/sawtooth/cli/admin_sub/permissioned_validator_registry.py, validator/etc/permissioned-validators.json, validator/journal/journal_core.py, validator/sawtooth_validator/consensus/poet1/permissioned_validator_registry.py, validator/tests/integration/test_web_api.py, validator/tests/unit/keys/pv1.wif, validator/tests/unit/keys/pv2.wif, validator/tests/unit/test_permissioned_validator_registry.py, validator/txnserver/validator_cli.py
The administrator provide a validator public keys, then send a ValidatorRegistryTransaction to register the validator.
=> Use the validator registry with a whitelist

core/sawtooth/cli/transaction.py
Use '''./bin/sawtooth transaction list''' command to show a few general fields of all transactions.
And Use '''./bin/sawtooth transaction list --type /EndpointRegistryTransaction''' to show a few general and specific fields of transactions.
@dcmiddle please review this PR.
=> Fix the bug of showing transaction info

docs/source/tutorial.rst, docs/source/tutorial/genesis.sh
Signed-off-by: nickdrozd <drozd@bitwise.io>
=> Consolidate tutorial setup, update genesis script, update tutorial

core/sawtooth/manage/wrap.py, extensions/arcade/tests/sawtooth_suites/ts_nightly_arcade_poet0.py, extensions/mktplace/tests/sawtooth_suites/ts_pr_mkt_poet0.py, validator/tests/integration/test_genesis_util.py, validator/tests/integration/test_validator_restart_restore.py, validator/tests/sawtooth_suites/ts_nightly_poet0.py, validator/tests/sawtooth_suites/ts_pr_dev_mode.py, validator/tests/sawtooth_suites/ts_pr_poet0.py, validator/txnintegration/launcher_cli.py
Signed-off-by: nickdrozd <drozd@bitwise.io>
Also fix typo in test_validator_restart_restore.py
=> Add archive to test suites

core/sawtooth/manage/wrap.py
Signed-off-by: nickdrozd <drozd@bitwise.io>
=> Make archive paths general

bin/run_tests, signing/nose2.cfg, signing/tests/test_ecdsa.py
=> Move tests of ecdsa to signing package

docs/source/community.rst, docs/source/community/contributing.rst, docs/source/community/issue_tracking.rst, docs/source/community/join_the_discussion.rst
Signed-off-by: Ry Jones <rjones@linuxfoundation.org>
=> Update pointers from Slack to Chat

integration/sawtooth_integration/tests/test_intkey_smoke.py
=> Add intkey test verifier

docs/source/_templates/indexcontent.html, docs/source/contents.rst, docs/source/sawtooth_cli.rst, docs/source/sawtooth_cli/admin_genesis.rst
=> Add documentation for genesis CLI tool

validator/sawtooth_validator/journal/block_store_adapter.py, validator/sawtooth_validator/journal/block_wrapper.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/timed_cache.py, validator/tests/unit3/test_journal/block_tree_manager.py, validator/tests/unit3/test_journal/mock.py, validator/tests/unit3/test_journal/tests.py
Enhance block validator design, add block validation of completeness and signature. Enhance test framework to support this additional validation. 
Add BlockValidator test for various fork conditions to resolve. 
Clean up callback interface between BlockValidator and ChainController
=> Block validator

Jenkinsfile, bin/build_debs, ci/sawtooth-docker-test, docker/sawtooth-build-ubuntu-xenial
=> Add Jenkinsfile and supporting files for pipeline ci

Jenkinsfile
=> Ensure CI jobs always execute on the master node

Jenkinsfile, bin/run_lint, docker/sawtooth-build-ubuntu-xenial, validator/sawtooth_validator/journal/chain.py
=> add run_lint to Jenkinsfile

.gitignore, bin/docker_build_all, bin/protogen, bin/run_lint, bin/run_tests, bin/tp_validator_registry, docker/sawtooth-tp_validator_registry, docs/source/transaction_family_specifications.rst, docs/source/transaction_family_specifications/validator_registry_transaction_family.rst, poet/sawtooth_poet/__init__.py, poet/sawtooth_poet/protos/validator_registry.proto, poet/sawtooth_poet/tests/validator_registry_test/__init__.py, poet/sawtooth_poet/tests/validator_registry_test/tests.py, poet/sawtooth_poet/tests/validator_registry_test/tp_validator_registry.yaml, poet/sawtooth_poet/tests/validator_registry_test/ts_validator_registry.py, poet/sawtooth_poet/tests/validator_registry_test/validator_reg_message_factory.py, poet/sawtooth_poet/validator_registry/__init__.py, poet/sawtooth_poet/validator_registry/processor/__init__.py, poet/sawtooth_poet/validator_registry/processor/handler.py, poet/sawtooth_poet/validator_registry/processor/main.py, sdk/python/sawtooth_processor_test/tester.py
This includes the specification and transaction processor tests
=> Add the Validator Registry Transaction Family

bin/docker_build_all
=> Pass proxy info into docker container.

sdk/examples/intkey_python/sawtooth_intkey/client_cli/create_batch.py
This makes intkey batch creation set dependencies in the
inc/dec transactions for the corresponding set transaction.
=> Make intkey batch creation insert proper txn deps

docs/source/tutorial.rst, docs/source/tutorial/genesis.sh
Update 0.7 tutorial to reflect new default of
InitialConnectivity=0.
Tested by running through tutorial.
=> Update 0.7 tutorial

Jenkinsfile
=> Add repo archiving to master pipeline

integration/sawtooth_integration/tests/test_intkey_smoke.py, sdk/python/sawtooth_processor_test/message_factory.py, validator/sawtooth_validator/database/dict_database.py, validator/sawtooth_validator/database/lmdb_nolock_database.py, validator/sawtooth_validator/journal/block_builder.py, validator/sawtooth_validator/journal/block_store.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/completer.py, validator/sawtooth_validator/journal/genesis.py, validator/sawtooth_validator/journal/journal.py, validator/sawtooth_validator/journal/publisher.py, validator/sawtooth_validator/journal/transaction_cache.py, validator/sawtooth_validator/server/core.py, validator/tests/unit3/test_client_request_handlers/mocks.py, validator/tests/unit3/test_client_request_handlers/tests.py, validator/tests/unit3/test_genesis/tests.py, validator/tests/unit3/test_journal/block_tree_manager.py, validator/tests/unit3/test_journal/tests.py
Add a BlockStore Component, update it to use non locking LMDB for diskstorage.
Update the BlockStore to track Transactions and Batches. 
Update BlockValidator and BlockPublisher to check transactions dependencies. 
Update BlockValidator to generate transaction delta lists on Fork switch and BlockPublisher to rebuild the pending transaction list when the chain head is updated.
=> Block store

validator/sawtooth_validator/server/core.py
=> Fix BlockStore filename.

sdk/javascript/client/state.js, sdk/javascript/client/stream.js, sdk/javascript/protobuf/index.js, sdk/javascript/spec/protobuf/round_trip_test.js
Update the JS SDK with the protobuf message changes that removed MessageList.
Additionally:
- Fix the tests
- Fix linting issues
=> Update JS-SDK to current protobuf messages

validator/sawtooth_validator/networking/dispatch.py
=> Make sure that modifications to _send_message are threadsafe

validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/publisher.py, validator/tests/unit3/test_journal/tests.py
=> Journal fixes for BlockStore integration.

Jenkinsfile
=> Cleanup archive naming.

manage/sawtooth_manage/subproc.py
Subprocess bug fixes:
1) 'tcp' added to url
2) peers added to arguments
=> Fix sawtooth cluster subprocess issue

cli/sawtooth_cli/admin.py, cli/sawtooth_cli/block.py, cli/sawtooth_cli/cluster.py, cli/sawtooth_cli/config.py, cli/sawtooth_cli/main.py, cli/sawtooth_cli/state.py
Sawtooth cli error handling fixed.
=> Fix error handling of sawtooth cli

bin/protogen
=> Port protogen to python

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/journal/block_store.py, validator/sawtooth_validator/journal/completer.py, validator/sawtooth_validator/journal/publisher.py, validator/sawtooth_validator/journal/responder.py, validator/tests/unit3/test_completer/__init__.py, validator/tests/unit3/test_completer/mock.py, validator/tests/unit3/test_completer/test.py
Make the completer complete blocks and  check batches for missing dependencies.
=> Complete the Completer

extensions/bond/ui/client/src/main/bond/components/auth.cljs, extensions/bond/ui/client/src/main/sawtooth/utils.cljs, extensions/mktplace/navigator/client/src/main/mktplace/components/login.cljs, extensions/mktplace/navigator/client/src/main/sawtooth/utils.cljs
=> Add warning for Edge/IE that those browsers are not supported

validator/sawtooth_validator/journal/completer.py
Block dependencies may be long, especially in the case of initial load
for a new validator back to the genesis block. When a dependency is
satisfied, make sure that all outstanding work is processed in the
dependency chain. This is done iteratively because of the likelihood
of overflowing the default Python stack if done recursively.
=> Make Completer._process_incomplete_blocks() process all available work

Jenkinsfile, MAINTAINERS, bin/whitelist
=> Add Jenkinsfile whitelist

validator/sawtooth_validator/execution/context_manager.py
Avoid committing state values from the context that are None.  This
saves the context manager from writing all values from a transactions
output list, even if only some of those values have been written to by
the transaction processor.
=> Avoid committing empty state values

docs/source/txn_family_tutorial.rst
Signed-off-by: Jordan Byrd <jabyrd3@gmail.com>
=> fixed incorrect path in the docs.

Jenkinsfile, MAINTAINERS, bin/whitelist
Signed-off-by: AdamX Ludvik <aludvikX@ludvik-intel.local>
=> Add whitelist to Jenkinsfile (0-7)

Jenkinsfile
=> Add windows tests to Jenkinsfile

bin/build_debs
=> Fix build_debs to add signing directory to PYTHONPATH

validator/sawtooth_validator/journal/consensus/consensus.py
=> Update BlockVerifierInterface.verify_block signature and documentation to reflect actual usage

validator/sawtooth_validator/journal/publisher.py
=> Update BlockPublisher to check the pending queue for duplicate batches.

integration/sawtooth_integration/tests/test_intkey_smoke.py
=> Update intkey smoke test

Jenkinsfile, bin/run_tests, docker/sawtooth-build-java, docker/sawtooth-tp_intkey_java, integration/sawtooth_integration/docker/tp-intkey-java.yaml, integration/sawtooth_integration/test_suites/ts_tp_intkey.py, sdk/java/src/main/java/sawtooth/sdk/client/SendReceiveThread.java, sdk/python/sawtooth_processor_test/tester.py
This also makes some minor changes to the java sdk to bring it up to speed and adds a couple fixes to the processor testing library.
=> Add tp_intkey_java test to run_tests

docker/sawtooth-build-ubuntu-xenial
=> Update docker Ubuntu build script to install PyCA package and dependencies

validator/sawtooth_validator/journal/chain.py
=> Finish fix of squash misspelling.

docs/source/tutorial.rst
Update of the tutorial to explain startup process in light
of changes and additions to sawtooth lake, including
transaction processors and rest_api.
=> Update tutorial for startup process

protos/network.proto, protos/validator.proto, validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/journal/completer.py, validator/sawtooth_validator/journal/responder.py, validator/sawtooth_validator/networking/handlers.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/core.py
Also makes heartbeat timeouts relevant for both inbound and outbound connections, and makes a request for the head of the chain once peer registration succeeds.
=> Move handshake to network connect, chain callbacks to Gossip registration, etc

validator/sawtooth_validator/networking/interconnect.py
=> Fix typo in identities to connections map

sdk/README.md
=> remove TNG verbiage from readme

protos/client.proto, validator/sawtooth_validator/state/client_handlers.py
Even though the proto file specified there was a default timeout of 300, one never actually got added.
=> Add default timeout to client request handlers

bin/build_all, ci/sawtooth-build-debs
Also updates build_all to handle Ctrl+C correctly...
=> Fix package versioning

cli/sawtooth_cli/rest_client.py, cli/sawtooth_cli/submit.py
Added needed error handling to CLI
submit command.
=> Added error handling to CLI submit

bin/clean_all
=> Fix cleanup_all to properly clean up PoET packages

docs/source/_templates/indexcontent.html
Fixed typo in 0.7 doc index page.
=> Minor doc fix for 0.7 documentation

docs/source/_templates/indexcontent.html
Minor fix to 0.8 documentation index page.
=> Minor fix of documentation

ci/sawtooth-build-debs, ci/sawtooth-test-debs
=> Install external debs from repo in sawtooth-build-debs

bin/run_lint, manage/sawtooth_manage/docker.py, manage/sawtooth_manage/exceptions.py, manage/sawtooth_manage/subproc.py
The sys library was needed but missing.
Added import of sys.
=> Missing library in subprocess manage type

docs/source/sawtooth_developers_guide/signing_transactions.rst, signing/sawtooth_signing/secp256k1_signer.py
=> fix signing comments and docs. Compact not DER format.

ci/sawtooth-build-debs, ci/sawtooth-build-docs, ci/sawtooth-test-debs, docker/README.md, docker/sawtooth-all, docker/sawtooth-build-java, docker/sawtooth-build-javascript, docker/sawtooth-build-python, docker/sawtooth-dev-base, docker/sawtooth-dev-rest_api, docker/sawtooth-dev-test, docker/sawtooth-dev-tp_config, docker/sawtooth-dev-tp_intkey_java, docker/sawtooth-dev-tp_intkey_javascript, docker/sawtooth-dev-tp_intkey_python, docker/sawtooth-dev-tp_validator_registry, docker/sawtooth-dev-tp_xo_python, docker/sawtooth-dev-validator, docker/sawtooth-rest_api, docker/sawtooth-tp_config, docker/sawtooth-tp_intkey_python, docker/sawtooth-tp_validator_registry, docker/sawtooth-tp_xo_python, docker/sawtooth-validator
=> Document Dockerfiles

bin/run_docker_test
=> Improve logging and exception handling in run_docker_test

validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/server/core.py
=> Don't forward gossip messages with batches or blocks we've already seen

bin/intkey_jvm, sdk/README.md, sdk/examples/intkey_jvm_sc/JvmScHandler.java, sdk/examples/intkey_jvm_sc/JvmScTransactionProcessor.java, sdk/examples/intkey_jvm_sc/sawtooth_intkey/Intkey.java, sdk/examples/intkey_jvm_sc/sawtooth_intkey/cli/generate.py, sdk/examples/intkey_jvm_sc/sawtooth_intkey/cli/load.py
To test, look at the updated sdk/README.md JVM-SC Intkey Transaction Processors section and follow the steps.
=> Update the JVM-SC to work with python3 and a few other fixes

manage/sawtooth_manage/docker.py
=> Remove cluster start builtin image error message

.gitignore
=> Update gitignore for xo

extensions/bond/ui/client/src/main/bond/components/auth.cljs, extensions/mktplace/navigator/client/src/main/mktplace/components/login.cljs
=> Fix browser-unsupported message not displaying for IE users

docs/source/contents.rst, docs/source/sysadmin_guide.rst, docs/source/sysadmin_guide/log_configuration.rst, sdk/examples/intkey_python/sawtooth_intkey/processor/main.py, sdk/examples/xo_python/sawtooth_xo/processor/main.py, validator/etc/log_config.toml.example, validator/sawtooth_validator/server/cli.py
This PR also includes a couple fixups for configurable logging code and the example.
=> Add Document to Sysadmin to explain how to Configure Logging

validator/sawtooth_validator/gossip/gossip.py
=> Only stop the topology if the topology exists

validator/tests/unit3/test_journal/tests.py
=> Add block publisher unit tests

Jenkinsfile, bin/run_bandit
=> Add Bandit report to Jenkins builds

manage/sawtooth_manage/docker.py, manage/sawtooth_manage/subproc.py
Added --public-uri argument to cluster command.
Fixed for both subprocess and docker.
=> Cluster command fixed for public-uri parameter

.gitignore, bin/protogen, protos/batch.proto, protos/block.proto, protos/client.proto, protos/genesis.proto, protos/jvm_sc.proto, protos/network.proto, protos/processor.proto, protos/setting.proto, protos/state_context.proto, protos/transaction.proto, protos/validator.proto, sdk/go/src/sawtooth_sdk/noop_processor.go, tools/conf-defaults.sh, tools/guest-files/local-env.sh, tools/plugins/install_go_tools.sh
Test that everything (go, protogen, protobuf, zmq) is working by provisioning vagrant and then:
1. `protogen go`
2. `cd sdk/go/src/sawtooth_sdk`
3. `go run fake_validator.go`
4. `go run fake_processor.go`
=> Setup vagrant for Go Development

rest_api/sawtooth_rest_api/exceptions.py, rest_api/sawtooth_rest_api/route_handlers.py, sdk/examples/intkey_jvm_sc/sawtooth_intkey/cli/load.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/load.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload.py, sdk/python/sawtooth_sdk/workload/workload_generator.py
Will now need to start up a rest_api to use intkey load and intkey workload
=> Replace the use of Stream with the REST API in the intkey client_cli 

validator/tests/unit3/test_journal/block_tree_manager.py, validator/tests/unit3/test_journal/mock.py, validator/tests/unit3/test_journal/tests.py
=> Add block publisher missing dep tests

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/networking/dispatch.py, validator/sawtooth_validator/networking/interconnect.py
This commit also removes some cruft
=> Make Interconnect and Dispatcher more threadsafe

validator/sawtooth_validator/networking/interconnect.py
=> Add minimal error handling on receiving messages

docs/source/introduction.rst
=> Remove inaccurate TEE verbiage and improve intro.

consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
PoET fork resolution is changed to:
* if the new fork head is a non-PoET block, raises an exception as this is a completely unexpected turn of events
* if the current head is non-PoET but it is the immediate predecessor to the new fork head, it is reported as the blockchain changing to PoET consensus
* if the current head is non-PoET and it is not the immediate predecessor to the new fork head, it raise an exception as this is a completely unexpected turn of events
Remaining fork resolution continues as before.
To test locally:
`cd /project/sawtooth-core/integration/sawtooth_integration/docker` 
In `poet-smoke.yaml`, after the line:
`sawtooth.consensus.algorithm=poet \`
Add:
```
sawtooth.poet.target_wait_time=5 \
sawtooth.poet.initial_wait_time=0 \
```
Execute:
`run_docker_test …
=> Update PoET fork resolver with respect to non-PoET blocks.

consensus/poet/families/tests/test_tp_validator_registry.py, core_transactions/config/tests/test_tp_config.py, docs/source/app_developers_guide.rst, docs/source/app_developers_guide/testing.rst, docs/source/app_developers_guide/txn_family_tutorial.rst, sdk/examples/intkey_python/tests/test_tp_intkey.py, sdk/examples/xo_python/sawtooth_xo/xo_message_factory.py, sdk/examples/xo_python/tests/test_tp_xo.py, sdk/python/sawtooth_processor_test/mock_validator.py, sdk/python/sawtooth_processor_test/transaction_processor_test_case.py
Aside from adding documentation, this PR moderately rewrites the XO TP test to match the documentation and also renames some other parts of the TP test infrastructure (but without any functional changes).
=> Tp test doc

MAINTAINERS
=> Add S. A. Haridhakshini to MAINTAINERS whitelist

sdk/examples/intkey_go/src/sawtooth_intkey/main.go
Fixes https://jira.hyperledger.org/browse/STL-24
Signed-off-by: Jonathan Levi (HACERA) <jonathan@hacera.com>
=> [STL-24] Fix Golang SDK "index out of bound" panic

Jenkinsfile, bin/run_go_fmt, bin/tp_intkey_go, sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go, sdk/examples/intkey_go/src/sawtooth_intkey/main.go, sdk/go/src/sawtooth_sdk/logging/logger.go, sdk/go/src/sawtooth_sdk/messaging/errors.go, sdk/go/src/sawtooth_sdk/messaging/stream.go, sdk/go/src/sawtooth_sdk/processor/errors.go, sdk/go/src/sawtooth_sdk/processor/handler.go, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/go/src/sawtooth_sdk/processor/state.go
Resolve TODO comments in code, add logging, and make a couple changes to the stream interface.
=> Go SDK - Part 2

docs/source/_static/theme_overrides.css, docs/source/_templates/indexcontent.html, docs/source/conf.py, docs/source/rest_api.rst, docs/source/rest_api/endpoint_specs.rst, docs/source/rest_api/error_codes.rst, rest_api/sawtooth_rest_api/exceptions.py, rest_api/sawtooth_rest_api/openapi.yaml
- Update REST API spec to remove /stats and /status endpoints
- Move current REST API docs into REST API section
- Add new error doc
- Hack sphinx
=> Update REST API docs, adding error documentation

MAINTAINERS
=> Add Darian Plumb to MAINTAINERS list

ci/sawtooth-all, ci/sawtooth-build-debs, ci/sawtooth-rest_api, ci/sawtooth-test-debs, ci/sawtooth-tp_config, ci/sawtooth-tp_intkey_python, ci/sawtooth-tp_validator_registry, ci/sawtooth-tp_xo_python, ci/sawtooth-validator, docker/sawtooth-build-go, docker/sawtooth-build-python, docker/sawtooth-dev-test, docker/sawtooth-int-rest_api, docker/sawtooth-int-tp_config, docker/sawtooth-int-tp_intkey_python, docker/sawtooth-int-tp_validator_registry, docker/sawtooth-int-tp_xo_python, docker/sawtooth-int-validator, tools/bootstrap.d/20-package-update.sh
=> Update Dockerfiles and Vagrant with new public apt repos

consensus/poet/core/tests/test_consensus/test_poet_block_verifier.py
=> PoET Block Verifier failure tests

validator/sawtooth_validator/execution/context_manager.py, validator/tests/unit3/test_context_manager/tests.py
Implement several parallel-case context manager unit tests, but there will need to be further work in the context manager for these tests to pass.
=> Context manager unit tests

validator/sawtooth_validator/server/cli.py
=> Remove extra init_console_logging call

sdk/go/src/sawtooth_sdk/processor/processor.go
This improves the intermittent Go SDK failure so it only happens ~10% of the time (I tested locally and had 27/30 passes).
I believe the problem is that the internal message routing is sometimes still a little inefficient and there is occasionally a delay in processing the requests. Increasing the sleep from 1 to 3 seconds gave me 30/30 successes. I already created a story in my backlog to improve the routing logic so I am planning to revisit this issue when I get to that story.
=> Improve Go SDK internal message routing

consensus/poet/core/tests/test_consensus/test_poet_block_verifier.py
=>  PoET Block Verifier Success Case

tools/bootstrap.d/30-python-lib-install.sh
=> Version pin pylint in Vagrant

docs/source/sysadmin_guide.rst, docs/source/sysadmin_guide/installation.rst
=> Add instructions for installing sawtooth with apt

sdk/examples/intkey_go/src/sawtooth_intkey/main.go, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/go/src/sawtooth_sdk/processor/worker.go
To test locally, in vagrant do:
```
$ build_go
$ tp_intkey_go -v
```
Then start up a validator and run intkey workload against it.
Then you can press Ctrl+C in the tp_intkey_go window and restart tp_intkey_go to your hearts content.
=> Graceful shutdown Go

docs/source/_templates/indexcontent.html
=> Fix broken link on index page to CLI page

docs/source/app_developers_guide.rst, docs/source/app_developers_guide/environment_setup.rst, docs/source/app_developers_guide/intro_to_sawtooth.rst, docs/source/app_developers_guide/txn_family_tutorial.rst
Old Getting Started tutorial in the App Dev Guide replaced by two new tutorials:
- Environment Setup
- Getting Started with Hyperledger  Sawtooth
=> App Dev Guide: Environment setup and getting started

docs/source/transaction_family_specifications.rst, docs/source/transaction_family_specifications/integerkey_transaction_family.rst
=> Add IntegerKey transaction family specification

bin/run_tests, integration/sawtooth_integration/docker/dynamic-network.yaml, integration/sawtooth_integration/docker/poet-smoke-alt.yaml, integration/sawtooth_integration/tests/node_controller.py, integration/sawtooth_integration/tests/test_dynamic_network.py
=> Add dynamic network test

docs/source/_templates/sdk_TP_tutorial.rst, docs/source/_templates/template_config.yaml, docs/source/app_developers_guide.rst, docs/source/app_developers_guide/environment_setup.rst, docs/source/app_developers_guide/python_sdk.rst, docs/source/app_developers_guide/python_sdk_install.rst
Creation of transaction processor tutorial that uses the new template system.
Produces a Python tutorial and install guide for the Python SDK, and enables
creation of tutorials for future supported languages.
=> Txn processor tutorial and install guide for Python SDK

docker/compose/sawtooth-demo.yaml
=> Fix demo docker compose file to work with 0.8.2

cli/sawtooth_cli/admin_command/keygen.py, cli/sawtooth_cli/keygen.py, cli/tests/test_admin_keygen.py, consensus/poet/cli/tests/test_genesis/tests.py, extensions/arcade/sawtooth_battleship/battleship_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py
Although .wif filenames were changed to .priv, variable
names were not changed.
This commit changes variable names from wif to priv.
=> Change variable names from wif_filename to priv_filename

docs/source/app_developers_guide/intro_to_sawtooth.rst
Fixed missing options and wrong options for
commands in Getting Started/Intro tutorial
for app developers.
=> Small fixes to Getting Started/Intro

sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go, sdk/examples/intkey_java/IntegerKeyHandler.java, sdk/examples/intkey_javascript/integer_key_handler.js, sdk/examples/intkey_python/sawtooth_intkey/client_cli/create_batch.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/generate.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/populate.py, sdk/examples/intkey_python/sawtooth_intkey/intkey_message_factory.py, sdk/examples/intkey_python/sawtooth_intkey/processor/handler.py, sdk/examples/intkey_python/sawtooth_intkey/processor/main.py, sdk/examples/intkey_python/tests/test_tp_intkey.py, sdk/javascript/messaging/stream.js, sdk/python/sawtooth_processor_test/mock_validator.py
The commits are a little repetitive. I'd be happy to squash them if anyone would prefer it.
=> Make intkey conform to specification

docs/source/_templates/indexcontent.html
=> Add "latest release" to document version selector

validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/genesis.py, validator/sawtooth_validator/journal/publisher.py
Minor improvements to give more informative messages on validator startup, and changes to publishing state.
=> Improve Genesis and Journal Logging

COMMITTERS
=> add Richard Gendal Brown to COMMITTERS

bin/run_tests, integration/sawtooth_integration/docker/workload.yaml, integration/sawtooth_integration/tests/test_workload.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload.py
=> Add intkey workload test

docs/source/sysadmin_guide/installation.rst
Signed-off-by: n1zyz <mwagner@redhat.com>
=> add yum notice to install guide

COMMITTERS
+feihujiang
+n1zyz
+verasnt
+ryjones
=> update committers list with 4 additions

ci/sawtooth-build-docs, tools/plugins/install_sphinx.sh
=> Pin sphinx version at 1.5.6

docker/sawtooth-dev-go, docker/sawtooth-dev-python, docker/sawtooth-int-rest_api, docker/sawtooth-int-tp_config, docker/sawtooth-int-tp_intkey_python, docker/sawtooth-int-tp_validator_registry, docker/sawtooth-int-tp_xo_python, docker/sawtooth-int-validator
=> Update Dockerfiles to use ci repo for external dependencies

docs/source/_templates/indexcontent.html, docs/source/app_developers_guide/address_and_namespace.rst, docs/source/architecture/transactions_and_batches.rst, docs/source/core_developers_guide/environment_setup.rst, docs/source/introduction.rst, docs/source/sysadmin_guide/installation.rst
=> update Sawtooth name to Hyperledger Sawtooth

docs/source/community/contributing.rst, docs/source/community/issue_tracking.rst, docs/source/community/join_the_discussion.rst
Signed-off-by: MarkX Ford <markx.ford@intel.com>
Streamline some links to be more directive toward Hyperledger Sawtooth
=> Update community docs

validator/sawtooth_validator/execution/context_manager.py, validator/sawtooth_validator/execution/scheduler_serial.py, validator/tests/unit3/test_scheduler/data/simple_scheduler_test.yaml, validator/tests/unit3/test_scheduler/tests.py, validator/tests/unit3/test_scheduler/yaml_scheduler_tester.py
This PR implements a SchedulerTester that operates on yaml files with a particular data structure. A yaml file and associated scheduler test are included. The included test is a single block-single scheduler instance test.
Comments or suggestions on future features welcome.
=> Initial yaml-based scheduler tests

README.md
Signed-off-by: Kelly Olson <kelly.m.olson@intel.com>
=> Update Readme with name and status changes

validator/sawtooth_validator/server/core.py
As part of a desire to run CPU intensive secp256k1 signature
verification outside of the core validator process, a
ProcessPoolExecutor execution strategy was chosen which uses
multiprocessing to fork and execute the signature verification
methods. Due to the extensive use of threading inside the
validator process, it is quite likely that a thread is inside
a critical section of logging code when the fork occurs. If
the signature verification code makes use of logging, the
logging call will deadlock on the release of the logging lock
inside the child process (because the thread holding the lock
is frozen inside the child process). This was leading to
intermittent failures during testing.
See http://bugs.python.org/issue6721
This change introduces a fix to this issue by replacing the …
=> Replace ProcessPoolExecutor used by sig verify with ThreadPoolExcecutor

COMMITTERS
=> add 2 committers +jabyrd3 +ineffectualproperty

validator/tests/unit3/test_client_request_handlers/test_state_handlers.py, validator/tests/unit3/test_state_delta_processor/tests.py
=> Remove the duplicate definite article

cli/sawtooth_cli/block.py, cli/sawtooth_cli/state.py
=> Fix wrong notes of state and block list/show commands

sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go
=> Use const instead of var for package constants

.gitignore, bin/build_all, bin/run_lint, bin/tp_supplychain_python, families/supplychain_python/nose2.cfg, families/supplychain_python/sawtooth_supplychain/__init__.py, families/supplychain_python/sawtooth_supplychain/addressing.py, families/supplychain_python/sawtooth_supplychain/processor/__init__.py, families/supplychain_python/sawtooth_supplychain/processor/handler.py, families/supplychain_python/sawtooth_supplychain/processor/main.py, families/supplychain_python/sawtooth_supplychain/supplychain_exceptions.py, families/supplychain_python/sawtooth_supplychain/time_utils.py, families/supplychain_python/sawtooth_supplychain_test/supplychain_message_factory.py, families/supplychain_python/setup.py, families/supplychain_python/tests/test_tp_supplychain.py, families/supplychain_python/tests/tp-supplychain-python.yaml
Signed-off-by: Cian <cian.montgomery@intel.com>
=> Initial version of the Supplychain transaction processor.

.gitignore, bin/build_burrow_evm, bin/protogen, bin/run_go_fmt, bin/tp_burrow_evm, docker/sawtooth-dev-go, families/burrow_evm/src/burrow/evm/snative.go, families/burrow_evm/src/burrow/evm/vm.go, families/burrow_evm/src/protos/evm.proto, families/burrow_evm/src/sawtooth_burrow_evm/handler/handler.go, families/burrow_evm/src/sawtooth_burrow_evm/handler/sawtooth_app_state.go, families/burrow_evm/src/sawtooth_burrow_evm/handler/state_manager.go, tools/plugins/install_go_tools.sh
STL-112 and STL-113 will use this to implement the EVM TP.
=> STL-124 Implement EVM AppState interface using processor.State

consensus/poet/cli/sawtooth_poet_cli/genesis.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_key_state_store.py, consensus/poet/core/tests/test_consensus/test_poet_key_state_store.py, consensus/poet/families/sawtooth_validator_registry/validator_reg_message_factory.py, consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py, consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
In testing SGX implementation, I found inconsistencies in the core and simulator code that needed to be brought into alignment so that the SGX enclave would work.
=> Fixes to bring core/simulator into alignment with SGX

COMMITTERS
=> Update Cian's github username in COMMITTERS

validator/sawtooth_validator/execution/scheduler_serial.py, validator/tests/unit3/test_scheduler/tests.py
I am working on getting the context manager unit tests to pass, and found this error: When batches are added relatively slowly during block publishing, all of the transaction results could be set before more batches are added. I refactored the checking for whether a state hash needs to be calculated into two methods:
* if the state hash had been specified on the batch (similar to block validation)
* if the state hash hadn't been calculated yet (which is called only after finalize has been called and the scheduler is complete, similar to block publishing). 
I provided a unit test that fails on master but passes after the fix commit.
=> Fix to serial scheduler production of state root

rest_api/sawtooth_rest_api/rest_api.py
UNKNOWNB size is a little confusing, change it to UNKNOWN size.
=> UNKNOWNB to UNKNOWN

cli/sawtooth_cli/admin_command/config.py, consensus/poet/cli/sawtooth_poet_cli/config.py, consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/utils.py, families/config/sawtooth_config/processor/handler.py, manage/sawtooth_manage/vnm.py, sdk/python/sawtooth_processor_test/mock_validator.py, sdk/python/sawtooth_sdk/client/config.py, validator/sawtooth_validator/config/logs.py, validator/sawtooth_validator/config/path.py
Unnecessary "else" after "return", so remove them.
=> Remove unnecessary else

protos/transaction.proto
The same transaction is not clearly defined. Changed it.
=> Fix the comment of the nonce field

docker/compose/sawtooth-default.yaml, docs/source/app_developers_guide/intro_to_sawtooth.rst, integration/sawtooth_integration/docker/config-smoke.yaml, integration/sawtooth_integration/docker/intkey-go-smoke.yaml, integration/sawtooth_integration/docker/intkey-java-smoke.yaml, integration/sawtooth_integration/docker/intkey-javascript-smoke.yaml, integration/sawtooth_integration/docker/intkey-python-smoke.yaml, integration/sawtooth_integration/docker/poet-smoke.yaml, integration/sawtooth_integration/docker/two_families.yaml, integration/sawtooth_integration/docker/workload.yaml, integration/sawtooth_integration/docker/xo-javascript-smoke.yaml, integration/sawtooth_integration/docker/xo-smoke.yaml, integration/sawtooth_integration/tests/node_controller.py, integration/sawtooth_integration/tests/test_shutdown_smoke.py, manage/sawtooth_manage/docker.py, manage/sawtooth_manage/subproc.py, validator/packaging/systemd/sawtooth-validator, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/core.py
public_uri -> endpoint
network_endpoint -> bind
join -> seed
This PR is built on top of and waiting on  #513.
=> Rename Validator command line arguments

docker/compose/sawtooth-default.yaml, integration/sawtooth_integration/docker/config-smoke.yaml, integration/sawtooth_integration/docker/intkey-go-smoke.yaml, integration/sawtooth_integration/docker/intkey-java-smoke.yaml, integration/sawtooth_integration/docker/intkey-javascript-smoke.yaml, integration/sawtooth_integration/docker/intkey-python-smoke.yaml, integration/sawtooth_integration/docker/poet-smoke.yaml, integration/sawtooth_integration/docker/two_families.yaml, integration/sawtooth_integration/docker/workload.yaml, integration/sawtooth_integration/docker/xo-javascript-smoke.yaml, integration/sawtooth_integration/docker/xo-smoke.yaml, integration/sawtooth_integration/tests/node_controller.py, integration/sawtooth_integration/tests/test_shutdown_smoke.py, manage/sawtooth_manage/subproc.py, validator/packaging/systemd/sawtooth-validator, validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/core.py
=> Replace network_endpoint and component_endpoint with --bind

docs/source/architecture/rest_api.rst
=> Update REST API Architecture doc to include sort query

consensus/poet/cli/sawtooth_poet_cli/enclave.py, consensus/poet/cli/sawtooth_poet_cli/genesis.py, consensus/poet/cli/sawtooth_poet_cli/poet_enclave_module_wrapper.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py, consensus/poet/core/tests/test_consensus/test_signup_info.py, consensus/poet/core/tests/test_consensus/test_wait_certificate.py, consensus/poet/core/tests/test_consensus/test_wait_timer.py, consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
=> Provide data directory to PoET enclave on initialization

sdk/go/src/sawtooth_sdk/client/encoder.go, sdk/go/src/sawtooth_sdk/client/signer.go
=> Add missing copyright headers

sdk/examples/xo_python/sawtooth_xo/xo_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_client.py
Judge whether the setted rest api rul starts with("http://").
=> Set the default rest api url for XO

consensus/poet/core/tests/test_consensus/test_poet_block_publisher_finalize_block.py
=>  test cases for PoetBlockPublisher finalize_block()

integration/sawtooth_integration/docker/basic-auth-proxy.yaml
=> Fix Basic Auth test config using incorrect CLI flags

consensus/poet/cli/sawtooth_poet_cli/enclave.py, consensus/poet/cli/sawtooth_poet_cli/genesis.py
=> Rename --enclave_module option to --enclave-module

ci/ns-control
=> Add sawtooth-poet-cli to sawtooth metapackage

docker/compose/sawtooth-default.yaml, docs/source/app_developers_guide/intro_to_sawtooth.rst, integration/sawtooth_integration/docker/basic-auth-proxy.yaml, integration/sawtooth_integration/docker/config-smoke.yaml, integration/sawtooth_integration/docker/intkey-go-smoke.yaml, integration/sawtooth_integration/docker/intkey-java-smoke.yaml, integration/sawtooth_integration/docker/intkey-javascript-smoke.yaml, integration/sawtooth_integration/docker/intkey-python-smoke.yaml, integration/sawtooth_integration/docker/poet-smoke.yaml, integration/sawtooth_integration/docker/two_families.yaml, integration/sawtooth_integration/docker/workload.yaml, integration/sawtooth_integration/docker/xo-javascript-smoke.yaml, integration/sawtooth_integration/docker/xo-smoke.yaml, integration/sawtooth_integration/tests/node_controller.py, manage/sawtooth_manage/docker.py, manage/sawtooth_manage/subproc.py, rest_api/packaging/systemd/sawtooth-rest_api, rest_api/sawtooth_rest_api/rest_api.py
stream_url -> connect
port and host -> bind
This PR is build on top of and is waiting on #529.
=> Rename Rest Api command line arguments

docs/source/community/contributing.rst
=> Fix markup typo in JIRA comment section

rest_api/packaging/rest_api.toml.example
=> Update rest api config example to match the bind default

COMMITTERS
=> Add Saurabh Badhwar to COMMITTERS

bin/run_tests, integration/sawtooth_integration/docker/xo-all-lang-smoke.yaml, integration/sawtooth_integration/tests/integration_tools.py, integration/sawtooth_integration/tests/test_two_families.py, integration/sawtooth_integration/tests/test_xo_smoke.py, sdk/examples/xo_javascript/xo_handler.js, sdk/examples/xo_python/sawtooth_xo/processor/handler.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_message_factory.py, sdk/examples/xo_python/tests/test_tp_xo.py
This PR is based on the xo-smoke PR (#564)
=> Xo state format

cli/sawtooth_cli/admin.py
=> Let the admin cmd has the same style

cli/sawtooth_cli/batch_status.py, cli/sawtooth_cli/main.py
=> Add the batch-status command

integration/sawtooth_integration/tests/integration_tools.py, sdk/examples/xo_javascript/xo_handler.js, sdk/examples/xo_python/sawtooth_xo/processor/handler.py, sdk/examples/xo_python/sawtooth_xo/xo_client.py, sdk/examples/xo_python/sawtooth_xo/xo_message_factory.py, sdk/python/sawtooth_processor_test/message_factory.py
=> Add Merkle Address validity test to MessageFactory

consensus/poet/core/sawtooth_poet/poet_consensus/mock_consensus_state.py, consensus/poet/core/tests/test_consensus/test_poet_block_publisher.py, consensus/poet/core/tests/test_consensus/test_poet_block_publisher_finalize_block.py, consensus/poet/core/tests/test_consensus/test_poet_block_verifier.py
=> refactoring: create a mock consensus state

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
=> Update to fix code that will trigger error in new version of PyLint

families/burrow_evm/src/sawtooth_burrow_evm/processor/main.go, integration/sawtooth_integration/docker/burrow-evm-smoke.yaml
=> Update EVM ports to 4004

sdk/examples/xo_python/sawtooth_xo/xo_client.py
=> Fix Xo show 404 message

validator/sawtooth_validator/gossip/signature_verifier.py, validator/tests/test_message_validation/tests.py
=> Code Refactoring for signature verifier module

validator/sawtooth_validator/gossip/structure_verifier.py, validator/sawtooth_validator/server/core.py, validator/tests/test_message_validation/tests.py
Validate the transaction_ids field  contains a list of transaction header_signatures and must be the same order as the transactions field in a batch.
=> Validate the transaction_ids field

docs/source/sysadmin_guide/installation.rst
=> Fix typo breaking doc generation

sdk/examples/intkey_javascript/integer_key_handler.js, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/java/src/main/java/sawtooth/sdk/processor/TransactionProcessor.java, sdk/javascript/processor/index.js, sdk/javascript/protobuf/index.js
This PR Also includes some fix ups to intkey javascript around handling a value of 0.
This PR is built on top of #585.
=> Add TpPing handling to the Java, Javascript and Go sdks

sdk/examples/xo_python/sawtooth_xo/xo_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_client.py
`% sudo apt-get update`
`% sudo apt-get install -y apache2`
`% sudo a2enmod headers`
`% sudo a2enmod proxy_http`
`% vi /tmp/.password`
```
sawtooth:$apr1$cyAIkitu$Cv6M2hHJlNgnVvKbUdlFr.
#EOF
```
`% sudo vi /etc/apache2/sites-enabled/000-default.conf`
```
<VirtualHost *:80>
ServerAdmin sawtooth@sawtooth
DocumentRoot /var/www/html
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
<Location />
Options Indexes FollowSymLinks
AllowOverride None
AuthType Basic
AuthName "Enter password"
AuthUserFile "/tmp/.password"
Require user sawtooth
Require all denied
</Location>
</VirtualHost>
ProxyPass /sawtooth http://localhost:8080
ProxyPassReverse /sawtooth http://localhost:8080
RequestHeader set X-Forwarded-Path "/sawtooth"
#EOF
```
`% sudo apachectl start`
To …
=> Add xo CLI auth

docs/source/_templates/sdk_TP_tutorial.rst, docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/ubuntu.rst
Added CLI example to the App Dev Guide, to
demonstrate how to play a game using the
incuded XO txn processor, or a user-written
txn processor.
=> Add xo CLI examples to App Dev Guide

README.md
=> Updates readme file to identify Creative Commons as license for docs

bin/build_ext_debs, bin/install_packaging_deps
=> Add CXX ProtoBuf deb file generation to the build_ext_debs script.

validator/sawtooth_validator/gossip/structure_verifier.py
Check whether block has duplicate batches and check whether batch has duplicate transactions. A block which has duplicate batches would be dropped. A batch which has duplicate transactions would be dropped.
=> Check whether block/batch has duplicate batches/transactions

ci/sawtooth-all, ci/sawtooth-build-debs, ci/sawtooth-build-docs, ci/sawtooth-rest_api, ci/sawtooth-test-debs, ci/sawtooth-tp_config, ci/sawtooth-tp_intkey_python, ci/sawtooth-tp_validator_registry, ci/sawtooth-tp_xo_python, ci/sawtooth-validator, docker/sawtooth-dev-go, docker/sawtooth-dev-python, docker/sawtooth-int-rest_api, docker/sawtooth-int-tp_config, docker/sawtooth-int-tp_intkey_python, docker/sawtooth-int-tp_validator_registry, docker/sawtooth-int-tp_xo_python, docker/sawtooth-int-validator, tools/bootstrap.d/20-package-update.sh
Cherry-picked from master and removed doc updates.
=> Modify signing keys

validator/tests/unit3/test_scheduler/tests.py
This is a PR against the parallel-scheduler branch that eases the merge conflicts between master and this branch.
=> Remove duplicate test

validator/tests/test_scheduler/tests.py
This eases merge conflicts between master and the
parallel scheduler branch.
=> Reformat tests similar to parallel-scheduler branch

bin/build_all, bin/build_cxx, docker/sawtooth-dev-cxx, tools/conf-defaults.sh, tools/plugins/install_cxx_tools.sh
=> Add docker file for CXX build and build_cxx script to build the CXX sdk.

bin/run_tests
=> Fix the help of run_tests

tools/plugins/install_go_tools.sh
=> Export GOPATH when setting up vagrant

families/burrow_evm/src/sawtooth_burrow_evm/processor/handler/handler.go, sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go, sdk/examples/xo_go/src/sawtooth_xo/handler/handler.go, sdk/go/src/sawtooth_sdk/processor/errors.go, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/go/src/sawtooth_sdk/processor/worker.go
Send back an error message and optional extended data on a `TpProcessResponse`
=> Send TP Error Messages on Response (Go SDK)

docs/source/transaction_family_specifications.rst, docs/source/transaction_family_specifications/xo_transaction_family.rst
=> Add xo transaction family specification

docs/source/_templates/sdk_TP_tutorial.rst, docs/source/_templates/template_config.yaml, docs/source/app_developers_guide.rst, docs/source/app_developers_guide/java_sdk.rst
- Add TP tutorial for Java SDK
- Update Javascript and Python addressing section to conform with XO spec
=> Add TP Tutorial for Java SDK

consensus/poet/core/tests/test_consensus/test_wait_certificate.py, consensus/poet/core/tests/test_consensus/test_wait_timer.py
=> modified test_wait_timer.py to allow faster testing without sleeps

docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/ubuntu.rst
Revised Using Sawtooth With Docker to follow new outline,
and added additional information and sub-sections.
=> Revised and added to Using Sawtooth with Docker

docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/ubuntu.rst
* fix `sawtooth batch submit` example
* reorder settings and intkey in ubuntu guide
=> Fix getting started guides.

bin/run_lint, bin/run_tests, bin/supplychain, families/supplychain/protos/record.proto, families/supplychain/python/sawtooth_supplychain/cli/__init__.py, families/supplychain/python/sawtooth_supplychain/cli/agent.py, families/supplychain/python/sawtooth_supplychain/cli/application.py, families/supplychain/python/sawtooth_supplychain/cli/common.py, families/supplychain/python/sawtooth_supplychain/cli/init.py, families/supplychain/python/sawtooth_supplychain/cli/main.py, families/supplychain/python/sawtooth_supplychain/cli/record.py, families/supplychain/python/sawtooth_supplychain/cli/reset.py, families/supplychain/python/sawtooth_supplychain/client.py, families/supplychain/python/sawtooth_supplychain/processor/handler.py, families/supplychain/python/sawtooth_supplychain/processor/main.py, families/supplychain/python/tests/int_supplychain_python.yaml, families/supplychain/python/tests/test_supplychain_cli.py, families/supplychain/python/tests/test_supplychain_integration.py, families/supplychain/python/tests/unit_supplychain_python.yaml
=> Add SupplyChain CLI and python client to the Sawtooth REST API

sdk/examples/xo_python/sawtooth_xo/processor/handler.py
This PR updates the xo python handler to match the transaction family tutorial and the xo transaction family spec (https://github.com/hyperledger/sawtooth-core/pull/655).
=> Rewrite xo python handler to match documentation

validator/sawtooth_validator/execution/executor.py
By Isolating the dictionary of open futures to a given executor thread,
an issue where the transaction is being processed by one executor thread
(as part of one schedule), as well as by another thread (due to it being
part of a claimed block on another validator).  Prior to this fix, the
dictionary of open futures was shared across threads, but the sharing
would result in an uncaught exception in the above scenario.
=> Isolate open futures per executor thread

validator/sawtooth_validator/journal/responder.py
=> Prevent exceptions from being printed on stale responder response

families/burrow_evm/src/sawtooth_burrow_evm/common/evm_address.go, families/burrow_evm/src/sawtooth_burrow_evm/common/state_address.go, families/burrow_evm/src/sawtooth_burrow_evm/processor/handler/handler.go, families/burrow_evm/tests/addresses_test.go, integration/sawtooth_integration/tests/burrow_evm_intkey_test.go, integration/sawtooth_integration/tests/burrow_evm_perm_test.go, sdk/go/src/sawtooth_sdk/client/encoder.go, sdk/go/tests/client_test.go
=> Replace MustEncode() and MustDecode() calls with Go hex lib

ci/sawtooth-build-docs, docs/source/architecture.rst, docs/source/architecture/poet.rst, docs/source/conf.py
This is a roughly 1-to-1 transposition of the PoET spec doc to sphinx.
I have also written a PoET primer which I have not converted to sphinx at: https://docs.google.com/a/intel.com/document/d/1se5sye23o8muot-TrYSK4Yl_Ue92Uh4yf5dHLSBt4_Y/edit?usp=sharing
I think this doc would be good to add as well (in another PR), either as another standalone doc or integrated into the spec.
=> STL-393 - PoET Spec

consensus/poet/common/tests/test_validator_registry_view/tests.py, consensus/poet/families/sawtooth_validator_registry/protos/validator_registry.proto, consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py, consensus/poet/families/tests/test_tp_validator_registry.py, consensus/poet/families/tests/validator_reg_message_factory.py
=> fix validator registry re-registration logic

bin/build_debs
=> Build debs for ias_client and ias_proxy

integration/sawtooth_integration/tests/node_controller.py, integration/sawtooth_integration/tests/test_dynamic_network.py
=> Add scheduler options to dynamic network test

COMMITTERS
=> add Ghadi Shayban to committers list

consensus/poet/cli/sawtooth_poet_cli/main.py, consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/main.py, families/settings/sawtooth_settings/processor/main.py, families/supplychain/python/sawtooth_supplychain/cli/main.py, families/supplychain/python/sawtooth_supplychain/processor/main.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/main.py, sdk/examples/intkey_python/sawtooth_intkey/processor/main.py, sdk/examples/xo_python/sawtooth_xo/processor/main.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py
=> Add version options for intkey, xo and supplychain etc.

bin/supplychain-sds, docker/sawtooth-dev-python, families/supplychain/python/packaging/supplychain_sds.toml.example, families/supplychain/python/packaging/supplychain_sds_log_config.toml.example, families/supplychain/python/sawtooth_supplychain/subscriber/config.py, families/supplychain/python/sawtooth_supplychain/subscriber/exceptions.py, families/supplychain/python/sawtooth_supplychain/subscriber/init.py, families/supplychain/python/sawtooth_supplychain/subscriber/main.py, families/supplychain/python/sawtooth_supplychain/subscriber/subscriber.py, tools/conf-defaults.sh, tools/plugins/install_psycopg2.sh
This PR introduces a state delta subscriber for the supplychain family.
Note, this requires a Postgres Database setup with the tables specified in #714.  There may be some setup scripts that need to be added for testing.
=> Supplychain State Delta Subscriber

docs/source/_templates/sdk_submit_tutorial.rst, docs/source/_templates/template_config.yaml, docs/source/app_developers_guide.rst, docs/source/app_developers_guide/python_sdk.rst, sdk/javascript/client/encoders.js, sdk/python/sawtooth_sdk/client/encoding.py, signing/sawtooth_signing/secp256k1_signer.py
Expand Python Client SDK to include some features in JS SDK. Includes ~~signing module for creating keys and signatures, and~~ an encoding module for creating and encoding Batches and Transactions.
=> Add encoding batches and transactions to Python SDK

protos/validator.proto
Signed-off-by: joeldudleyr3 <joel.dudley@r3.com>
=> Fixes typo in 'coorelate'.

docs/source/examples.rst, docs/source/examples/private_utxo/overview.rst, docs/source/examples/private_utxo/private_utxo_transaction_family.rst, families/private_utxo/protos/asset_type.proto, families/private_utxo/protos/holding.proto, families/private_utxo/protos/payload.proto, families/private_utxo/protos/utxo_document.proto
=> Initial documentation and specs for the Private UTXO example.

COMMITTERS
=> add new committers

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/main.py, families/settings/sawtooth_settings/processor/main.py, sdk/python/sawtooth_sdk/client/log.py, validator/sawtooth_validator/server/log.py
=> Add datestamps to registry/settings/rest_api/validator logs

protos/validator.proto
Signed-off-by: Chris Khan <chriskhan@MacBook-NonDev-06.local>
=> fix typo in protobuf def

COMMITTERS
=> add new committer to COMMITTERS

consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_state.cpp
Signed-off-by: jamescarlyle <james@r3cev.com>
Fixed small grammatical error in comment.
=> fixed grammatical error in comment

protos/state_context.proto, sdk/python/sawtooth_sdk/processor/state.py, validator/sawtooth_validator/execution/context_manager.py, validator/sawtooth_validator/execution/tp_state_handlers.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/state/merkle.py, validator/tests/test_context_manager/tests.py, validator/tests/test_merkle_trie/__init__.py, validator/tests/test_merkle_trie/tests.py
Update the Python Sdk, the ContextManager and the MerkleDatabase to handle deletes of keys.
=> State context delete

validator/packaging/validator.toml.example, validator/sawtooth_validator/config/validator.py, validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/core.py, validator/tests/test_config/tests.py
=> Add scheduler option to validator config

perf/sawtooth/sawtooth_workload/src/batch_gen.rs, perf/sawtooth/sawtooth_workload/src/playlist.rs
Also, adds an extra assertion in a test
=> Transaction signing fixes

.gitignore, bin/build_all, bin/identity-tp, bin/protogen, bin/run_lint, bin/run_tests, cli/sawtooth_cli/identity.py, cli/sawtooth_cli/main.py, families/identity/nose2.cfg, families/identity/protos/identities.proto, families/identity/sawtooth_identity/processor/handler.py, families/identity/sawtooth_identity/processor/main.py, families/identity/tests/sawtooth_identity_test/identity_message_factory.py, families/identity/tests/test_tp_identity.py, families/identity/tests/test_tp_identity.yaml, protos/identity.proto
This PR includes the first pass a an identity transaction processor that allows you to set roles and policies.  It also includes unit tests and extends sawtooth cli to be able to set roles and policies from the command line. This is the first step needed to be able to implement on-chain permissioning.
=> Initial Identity Transaction Processor.  

validator/sawtooth_validator/state/identity_view.py, validator/tests/test_identity_view/__init__.py, validator/tests/test_identity_view/tests.py
This PR is built off of #747. I will rebase on master after that PR goes in. Only the last 2 commits are part of this PR.
=> Implement IdentityView

validator/sawtooth_validator/networking/interconnect.py
Add exception handling to catch and log exceptions that may occur during
the interconnect's monitoring and heartbeat loops.
=> Add exception handling to heartbeat/monitor

sdk/examples/xo_python/packaging/systemd/sawtooth-xo-tp-python, sdk/examples/xo_python/packaging/systemd/sawtooth-xo-tp-python.service, sdk/examples/xo_python/setup.py
=> Add systemd service for xo-tp-python

.gitignore, families/track_and_trade/client/package.json, families/track_and_trade/client/public/index.html, families/track_and_trade/client/src/main.js, families/track_and_trade/client/styles/main.scss, families/track_and_trade/client/webpack.config.js, families/track_and_trade/server/db/index.js, families/track_and_trade/server/index.js, families/track_and_trade/server/package.json, families/track_and_trade/server/scripts/bootstrap_database.js
Includes server, client, database, mvc, styling library, and build tools in an initial Hello World style implementation.
Closes #STL-625
https://jira.hyperledger.org/browse/STL-625
=> Add initial Track and Trade app components

bin/run_go_fmt, families/seth/src/sawtooth_seth/cli/account_create.go, families/seth/src/sawtooth_seth/cli/account_list.go, families/seth/src/sawtooth_seth/cli/contract_call.go, families/seth/src/sawtooth_seth/cli/contract_create.go, families/seth/src/sawtooth_seth/cli/permissions_set.go, families/seth/src/sawtooth_seth/client/client.go, families/seth/src/sawtooth_seth/client/response.go, families/seth/src/sawtooth_seth/processor/handler/handler.go, families/seth/src/sawtooth_seth/processor/handler/sawtooth_app_state.go, families/seth/src/sawtooth_seth/processor/handler/state_manager.go, families/seth/src/sawtooth_seth/processor/handler/transaction_handlers.go, families/seth/src/sawtooth_seth/processor/main.go, integration/sawtooth_integration/tests/seth_intkey_test.go, integration/sawtooth_integration/tests/seth_perm_test.go
=> Add wait option in Seth client

validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/networking/dispatch.py, validator/sawtooth_validator/networking/future.py, validator/sawtooth_validator/networking/interconnect.py
Remove some superfluous locks, including `ThreadsafeDict`
=> Remove locks

docs/source/transaction_family_specifications.rst, docs/source/transaction_family_specifications/identity_transaction_family.rst
=> Add Identity Transaction Family Specification

validator/sawtooth_validator/execution/scheduler_parallel.py
=> Speed up parallel scheduler unscheduled_transaction determination

families/track_and_trade/client/package.json, families/track_and_trade/client/src/main.js, families/track_and_trade/server/api/auth.js, families/track_and_trade/server/api/errors.js, families/track_and_trade/server/api/index.js, families/track_and_trade/server/api/users.js, families/track_and_trade/server/db/index.js, families/track_and_trade/server/db/state.js, families/track_and_trade/server/db/users.js, families/track_and_trade/server/package.json, families/track_and_trade/server/scripts/bootstrap_database.js
Although more work is required to complete [STL-627](https://jira.hyperledger.org/browse/STL-627),  this PR importantly includes the initial work building out the Server's API, which will be needed for other contributors to complete their tasks.
=> Add Server API with initial POST /users route

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/networking/dispatch.py, validator/sawtooth_validator/networking/interconnect.py
- Trap uncaught exceptions per thread in gossip and dispatcher
- Serialize the messages outside of the async loop, to minimize time within the loop
- Stop the event loop on next tick, to allow the cancelled tasks time to properly shutdown
=> Minor Networking Performance and Stability Improvements

docker/sawtooth-dev-python
=> Install PyFormance library

validator/sawtooth_validator/config/path.py, validator/tests/test_config/tests.py
=> Fix policy_dir in PathConfig

bin/build_all, bin/build_debs, ci/sawtooth-identity-tp, docker/sawtooth-int-identity-tp, families/identity/packaging/systemd/sawtooth-identity-tp, families/identity/packaging/systemd/sawtooth-identity-tp.service, families/identity/setup.py, integration/sawtooth_integration/tests/test_systemd.sh
=> Package Identity Transaction Processor

integration/sawtooth_integration/tests/test_dynamic_network.py, validator/sawtooth_validator/execution/scheduler_parallel.py, validator/tests/test_scheduler/data/dependencies.yaml, validator/tests/test_scheduler/test_schedulers_with_yaml.py, validator/tests/test_scheduler/tests.py
This PR also turns on use of the parallel scheduler in test_dynamic_network. I have been running this test locally without error.
=> Implement handling of dependencies in ParallelScheduler

COMMITTERS
=> Add Ryan Banks to committers list

validator/sawtooth_validator/execution/context_manager.py, validator/tests/test_context_manager/tests.py
This fixes the bug that @aludvik and @nick-drozd were both seeing.
=> Fix bug when getting and setting to wildcarded and non-wildcarded addresses

bin/run_tests, docker/sawtooth-dev-javascript
This PR fixes a few errors in the build / test process.
=> Build errors

validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/journal.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/state/state_delta_processor.py, validator/tests/test_journal/mock.py, validator/tests/test_journal/tests.py
Also implements this interface for the StateDeltaProcessor
=> Create ChainObserver interface

bin/build_all, docker/compose/sawtooth-local.yaml, docker/compose/smallbank-local-mounted.yaml, docker/sawtooth-dev-javascript, docker/sawtooth-dev-python, docker/sawtooth-validator-mounted, docker/telegraf.conf, stat_collection/docker/grafana/dashboards/Default-1504733628866.json, stat_collection/docker/grafana/datasources/influxdb.json, stat_collection/docker/grafana/grafana.ini, stat_collection/docker/grafana/grafana_entrypoint.sh, stat_collection/docker/grafana/sawtooth-stats-grafana, stat_collection/docker/influxdb/influxdb_entrypoint.sh, stat_collection/docker/influxdb/sawtooth-stats-influxdb, stat_collection/docker/metrics.yaml
This merges in the metrics work and adds telegraf support to (a new) validator image and the smallbank docker compose file.
=> Initial smallbank grafana, influxdb support

.gitignore, families/track_and_trade/client/src/app_state.js, families/track_and_trade/client/src/fish_form.js, families/track_and_trade/client/src/main.js, families/track_and_trade/client/src/transactions.js
Adds a new form for adding a new fish to the system.  This does not submit the transaction, but sets up the framework for doing so, minus the transaction creation and submission.
Additionally, updates the gitignore to include the JS artifacts.
=> Initial "Track New Fish" Form

families/track_and_trade/client/package.json, families/track_and_trade/processor/sawtooth_track_and_trade/processor/handler.py, families/track_and_trade/server/blockchain/index.js, families/track_and_trade/server/blockchain/protos.js, families/track_and_trade/server/db/blocks.js, families/track_and_trade/server/db/index.js, families/track_and_trade/server/db/state.js, families/track_and_trade/server/index.js, families/track_and_trade/server/package.json, families/track_and_trade/server/scripts/bootstrap_database.js
Adds a process to the T&T Server which will listen for Track and Trade state changes on the blockchain, and sync those with the Rethink database. Deltas are maintained by storing multiple versions of each document with a `startBlockNum` and an `endBlockNum`. This allows older versions of documents to be queried, as well as making it possible to walk back forks when they occur.
This closes [#STL-626](https://jira.hyperledger.org/browse/STL-626).
This PR is not particularly easy to test, but if you were going to try to, you would:
- Start up a validator
- Start up a REST API (must be on a port other than `8080`)
- Start up the T&T Transaction Processor
- Start up the T&T Server and RethinkDB:
- cd `families/track_and_trade_server`
- Make sure you `npm install` and `npm run init`
- `npm …
=> Use State Delta Export to populate RethinkDB

validator/sawtooth_validator/execution/scheduler.py, validator/sawtooth_validator/execution/scheduler_parallel.py, validator/sawtooth_validator/execution/scheduler_serial.py, validator/tests/test_journal/mock.py, validator/tests/test_scheduler/tests.py
This is an incremental PR for STL-631
=> Add txn execution results to scheduler interface

validator/sawtooth_validator/execution/scheduler_parallel.py, validator/tests/test_scheduler/data/dependencies.yaml, validator/tests/test_scheduler/yaml_scheduler_tester.py
=> Fix parallel scheduler assumption of dependencies within the scheduler

validator/sawtooth_validator/networking/dispatch.py
=> Add a timeout to Dispatcher future results

validator/sawtooth_validator/gossip/gossip.py
=> Refresh peer list to see if connections drop on idle network

bin/generate_cli_output, docs/source/cli/poet.rst
Add missing enclave sub-command missing from docs.
=> Fix missing poet cli command doc.

families/track_and_trade/server/blockchain/index.js
Fixes a routing bug, and includes default falsey values for fields in objectified protobufs.
=> Fix bug where Proposal deltas were not being imported

validator/sawtooth_validator/gossip/gossip.py
This includes an increasing retry frequency and
reordering of _get_peers_of_endpoints, and adding
EndpointInfo namedtuple.
=> Add timeout and retry for endpoint authorization in gossip.

docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
=> Correct Validator Registry Family Name in Docs

validator/sawtooth_validator/execution/scheduler_serial.py, validator/sawtooth_validator/state/merkle.py, validator/tests/test_context_manager/tests.py, validator/tests/test_scheduler/data/deletes_test.yaml, validator/tests/test_scheduler/test_schedulers_with_yaml.py, validator/tests/test_scheduler/yaml_scheduler_tester.py
This PR is built on top of #835 to use the new test file layout, and is only the last 4 commits. I will rebase when #835 is merged.
Note: I included a yaml scheduler test with deletes that passes, but I was able to get it to fail with some more lines. I wanted to get this up with better state delete functionality and will debug the failure this week.
EDIT:
Now this PR is the last 5 commits.
=> Fix state delete

families/track_and_trade/server/api/index.js, families/track_and_trade/server/blockchain/batcher.js, families/track_and_trade/server/blockchain/deltas.js, families/track_and_trade/server/blockchain/index.js
To test you must:
1. Create a user by submitting a JSON `POST` request to `localhost:3000/api/users`:
```
{
"username": <string>,
"password": <string>,
"email": <string, email>,
"publicKey": <string, valid public key>
}
```
2. Save the `authorization` string that is returned.
3. Create a transaction signed by the with the same key
4. Encode in a `TransactionList` and submit as the body in a `POST` request to `localhost:3000/api/transactions`. Set the headers to:
```
"Authorization": <string, the authorization key>
"Content-Type": "application/octet-stream"
```
=> Add transaction submission route to T&T Client Server

docs/source/rest_api/error_codes.rst, families/seth/src/protos/seth.proto, families/seth/src/sawtooth_seth/client/client.go, families/seth/src/sawtooth_seth/client/response.go, families/seth/src/sawtooth_seth/processor/handler/handler.go, families/seth/src/sawtooth_seth/processor/handler/transaction_handlers.go, integration/sawtooth_integration/tests/seth_intkey_test.go, rest_api/openapi.yaml, rest_api/sawtooth_rest_api/error_handlers.py, rest_api/sawtooth_rest_api/exceptions.py, rest_api/sawtooth_rest_api/rest_api.py, rest_api/sawtooth_rest_api/route_handlers.py, rest_api/tests/unit/test_receipt_requests.py, validator/sawtooth_validator/execution/tp_state_handlers.py, validator/sawtooth_validator/journal/block_store.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/state/batch_tracker.py, validator/tests/test_client_request_handlers/mocks.py, validator/tests/test_client_request_handlers/test_submit_handlers.py
Would like to get an opinion from @zac how hard it would be to make it possible to wait for a receipts to appear. Hoping to get this merged without that for now though.
=> STL-459 Seth Transaction Receipts

bin/run_lint, cli/sawtooth_cli/exceptions.py, integration/sawtooth_integration/tests/integration_tools.py, integration/sawtooth_integration/tests/seth_intkey_test.go, integration/sawtooth_integration/tests/seth_perm_test.go, integration/sawtooth_integration/tests/test_block_info_injector.py, integration/sawtooth_integration/tests/test_dynamic_network.py, integration/sawtooth_integration/tests/test_events_and_receipts.py, integration/sawtooth_integration/tests/test_intkey_smoke.py, integration/sawtooth_integration/tests/test_poet_smoke.py, integration/sawtooth_integration/tests/test_two_families.py, integration/sawtooth_integration/tests/test_xo_smoke.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/exceptions.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_client.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_client.py
Remove sleeps from integration tests
=> Remove sleeps from integration tests

bin/run_tests, sdk/python/nose2.cfg, sdk/python/sawtooth_sdk/processor/state.py, sdk/python/tests/test_state.py, sdk/python/tests/unit_python_sdk.yaml
=> Update Python SDK for receipts and events

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/networking/handlers.py, validator/sawtooth_validator/server/core.py, validator/tests/test_authorization_handlers/test.py
=> Enforce rate limiting on Ping messages if the connection is not Authorized

validator/sawtooth_validator/gossip/gossip.py
=> Improve gossip connection log messages

sdk/rust/src/messaging/zmq_stream.rs
=> Remove Message Sender Drop

validator/sawtooth_validator/gossip/gossip.py
This includes adding locks around temp_endpoints
=> Replace Condition in Gossip with Lock

validator/packaging/log_config.toml.example, validator/sawtooth_validator/server/cli.py
=> Update log config example file to have full path

bin/run_tests, integration/sawtooth_integration/tests/test_events_and_receipts.py, rest_api/tests/unit/test_batch_requests.py, rest_api/tests/unit/test_block_requests.py, rest_api/tests/unit/test_receipt_requests.py, rest_api/tests/unit/test_state_requests.py, rest_api/tests/unit/test_submit_requests.py, rest_api/tests/unit/test_txn_requests.py
This will allow us to use the protobuf package with C++
=> Update test to import from the correct package

validator/sawtooth_validator/gossip/gossip.py
The underlying interconnect message will throw a ValueError if a
connection_id has been removed.  While broadcast was guarding against
this, the general send method was not.  This change corrects the issue
such that both will catch the error and cleanup any peer information
associated with the connection id
=> Prevent any gossip send from throwing ValueError

validator/sawtooth_validator/gossip/gossip.py
This should make it easier to read the logs. Also update log message on authorization completion to show the endpoint  and the corresponding connection id.
=> Update endpoint authorization log message to include connection_id

validator/sawtooth_validator/journal/responder.py, validator/tests/test_responder/mock.py, validator/tests/test_responder/tests.py
And add NetworkAcks back from responder handlers.
=> Update Responder to not re-request blocks/batches

families/track_and_trade/client/src/services/api.js
getPublicKey method for @peterschwarz
=> Add getPublicKey method to API service

docs/source/transaction_family_specifications.rst, docs/source/transaction_family_specifications/blockinfo_transaction_family.rst
=> Add BlockInfo Transaction Family Specification

families/track_and_trade/client/src/components/forms.js, families/track_and_trade/client/src/views/signup_form.js
As per design, adds password confirmation with a clear warning
information the user that a lost password is unrecoverable.
_Screenshot:_
=> Add password confirmation to T&T client user signup

docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/ubuntu.rst
=> Add scheduler configuration to App Developer docs

bin/build_ext_debs, ci/sawtooth-build-debs
=> Add Pyformance deb creation to build_ext_debs

COMMITTERS
=> Add chenette to the COMMITTERS list

docker/compose/smallbank-local-mounted.yaml, validator/sawtooth_validator/config/validator.py, validator/sawtooth_validator/journal/journal.py, validator/sawtooth_validator/journal/publisher.py, validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/core.py, validator/setup.py
of the pending batch queue over time
=> Add metrics to validator to measure the size

families/track_and_trade/processor/sawtooth_track_and_trade/processor/handler.py, families/track_and_trade/server/api/index.js, families/track_and_trade/server/api/records.js, families/track_and_trade/server/db/agents.js, families/track_and_trade/server/db/index.js, families/track_and_trade/server/db/records.js, integration/sawtooth_integration/tests/test_track_and_trade.py
The query is a little complex at one point. Is there a cleaner way to do `do` scoping? Is there any other way to assign variables in Reql?
=> Add T&T records endpoints

families/track_and_trade/client/src/components/tables.js, families/track_and_trade/client/src/main.js, families/track_and_trade/client/src/views/add_fish_form.js, families/track_and_trade/client/src/views/list_agents.js
Adds a list of agents page.  
Still requires the filter form element for typing a filter
=> Add agents list

docker/sawtooth-dev-go, docker/sawtooth-int-intkey-tp-go, docker/sawtooth-int-noop-tp-go, docker/sawtooth-int-seth-tp, docker/sawtooth-int-xo-tp-go, families/seth/src/sawtooth_seth/cli/account_create.go, families/seth/src/sawtooth_seth/cli/account_import.go, families/seth/src/sawtooth_seth/cli/account_list.go, families/seth/src/sawtooth_seth/cli/contract_call.go, families/seth/src/sawtooth_seth/cli/contract_create.go, families/seth/src/sawtooth_seth/cli/data.go, families/seth/src/sawtooth_seth/cli/permissions_set.go, integration/sawtooth_integration/tests/seth_intkey_test.go, integration/sawtooth_integration/tests/seth_perm_test.go, sdk/c/loader.c, sdk/go/src/sawtooth_sdk/client/pem_loader.go, sdk/go/src/sawtooth_sdk/client/signer.go, sdk/go/tests/client_test.go
Adds Seth support for importing PEM encoded, password protected private keys using OpenSSL.
=> STL 566 - Seth Key Storage Security

bin/run_tests, docker/compose/sawtooth-seth-rpc.yaml, families/seth/rpc/comp_seth_rpc.yaml, families/seth/rpc/src/block.rs, families/seth/rpc/src/network.rs, families/seth/rpc/tests/mock_validator.py, families/seth/rpc/tests/rpc_client.py, families/seth/rpc/tests/test_seth_rpc.py
Establish a pattern for testing the seth-rpc and write tests for existing methods
=> Seth RPC component tests

bin/build_ext_debs
=> Update to new version of pyformance

integration/sawtooth_integration/tests/seth_blockhash_test.go, integration/sawtooth_integration/tests/seth_blocknum_test.go, integration/sawtooth_integration/tests/seth_timestamp_test.go
=> Handle SDK error return value in opcode tests

families/track_and_trade/client/package.json, families/track_and_trade/client/src/main.js, families/track_and_trade/client/src/views/list_fish.js
=> Add Fish List

sdk/cxx/include/sawtooth/address_mapper.h, sdk/cxx/include/sawtooth/future_message.h, sdk/cxx/include/sawtooth/global_state.h, sdk/cxx/include/sawtooth/message_dispatcher.h, sdk/cxx/include/sawtooth/transaction_processor.h, sdk/cxx/src/address_mapper.cpp, sdk/cxx/src/message_dispatcher.cpp, sdk/cxx/src/transaction_processor.cpp
This PR adds support to the C++ SDK for responding to TP_PING requests from the validator.
=> Add support for TP_PING message in C++ SDK

families/track_and_trade/processor/sawtooth_track_and_trade/processor/handler.py
Because the numbers for property page maxes are so high (256 entries per page, 65535 pages), there isn't any good way to test this logic in the automated test. It can be tested manually by going into the T&T handler file and lowering the numbers
```
PROPERTY_PAGE_MAX_LENGTH = 10
TOTAL_PROPERTY_PAGE_MAX = 10
```
and also going into the T&T test and increasing the number of updates sent
```
for i in range(125):
self.assert_valid(
sensor_stark.update_properties(
'fish-456',
{'temperature': i}))
```
=> Implement T&T TP property page incrementing

.gitignore, bin/build_seth_go, bin/build_seth_rust, bin/protogen, docker/sawtooth-dev-go, docker/sawtooth-dev-rust, families/seth/rpc/src/account.rs, families/seth/rpc/src/block.rs, families/seth/rpc/src/logs.rs, families/seth/rpc/src/main.rs, families/seth/rpc/src/messages/mod.rs, families/seth/rpc/src/network.rs, families/seth/rpc/src/requests.rs, families/seth/rpc/src/transaction.rs
Create a validator client abstraction for simplifying interactions with the validator and caching data
Build protobuf messages for seth rpc
=> Seth-RPC abstractions and messags

validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/journal.py, validator/tests/test_journal/tests.py
=> Add current chain head metric gauge to ChainController

validator/sawtooth_validator/metrics/wrappers.py, validator/sawtooth_validator/networking/future.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/core.py
=> Add timer for interconnect's send response time

tools/package_groups/ubuntu-16.04-deps
=> Add vagrant plugin script to install pyformance

.gitignore, bin/protogen, docker/compose/sawtooth-seth-rpc.yaml, families/seth/rpc/Cargo.toml, families/seth/rpc/src/block.rs, families/seth/rpc/src/main.rs, families/seth/rpc/src/requests.rs, families/seth/rpc/tests/rpc_client.py, families/seth/rpc/tests/test_seth_rpc.py, protos/client.proto, sdk/rust/src/messages/mod.rs, sdk/rust/src/messaging/zmq_stream.rs, validator/sawtooth_validator/journal/block_store.py, validator/sawtooth_validator/state/client_handlers.py
Implement block calls
Also do some other stuff that needs doin'
=> STL-676 Add Seth RPC Block Calls

families/track_and_trade/client/src/views/fish_detail.js
Additionally:
- Correct temp to parse as float
- Reload data when transactions commit
=> Allow users to accept or reject proposals

validator/sawtooth_validator/metrics/wrappers.py
=> Make gauge wrapper support defaults

validator/sawtooth_validator/networking/handlers.py
=> Handle KeyError returned from is_outbound_connection

validator/sawtooth_validator/networking/interconnect.py
Exactly what it says on the tin
=> Fix shutdown over all_tasks

docs/source/transaction_family_specifications/sawtooth_burrow_evm_family.rst
@aludvik and @dplumb94 Let me know if I missed something.
=> Update Seth Transaction Family Specification

validator/sawtooth_validator/gossip/gossip.py
This Pr also renames Topology to ConnectionManager.
=> Implement reconnect to static peers

families/track_and_trade/client/src/views/signup_form.js, families/track_and_trade/server/api/index.js, families/track_and_trade/server/api/records.js, families/track_and_trade/server/api/users.js, families/track_and_trade/server/blockchain/batcher.js, families/track_and_trade/server/blockchain/index.js, families/track_and_trade/server/db/agents.js
This should prevent orphan users in the database.
=> Require Agents on the blockchain before user creation

families/track_and_trade/client/src/components/forms.js, families/track_and_trade/client/src/views/add_fish_form.js, families/track_and_trade/client/src/views/fish_detail.js
- fixes typos
- adds agent name detection to add fish form
- prevents partial matches
- closes multi-select dropdown on deselect.
=> Polish authorizing reporters

families/seth/src/sawtooth_seth/processor/handler/sawtooth_event_fireable.go
based on the information in this doc: [Seth-RPC, Seth Events, Solidity Events, EVM LOGX opcodes](https://docs.google.com/document/d/1bgBYZ12vrSwE8VKNJ_N_MeN6cF9SiLm996aSGjlInqM/)
=> Fix Seth event structure

docs/source/sysadmin_guide.rst, docs/source/sysadmin_guide/configure_sgx.rst
=> Add SGX sysadmin documentation

families/track_and_trade/server/blockchain/deltas.js, families/track_and_trade/server/db/index.js
- Server no longer sends back 200 OK on bad query
- Delta Exports are now handled in their entirety before moving on to the next
=> Fix server bugs

docker/grafana/dashboards/sawtooth_performance.json
=> Add grafana Sawtooth Performance dashboard

validator/sawtooth_validator/execution/context_manager.py
=> Make sure contexts get deleted even if the state hash doesn't change

docs/source/architecture.rst, docs/source/architecture/scheduling.rst
=> Add architecture doc section on transaction scheduling

families/seth/rpc/tests/test_seth_rpc.py
=> Refactor seth-rpc unit tests and add tests for missing resources

families/track_and_trade/server/api/users.js, families/track_and_trade/server/blockchain/index.js, families/track_and_trade/server/blockchain/protos.js, families/track_and_trade/server/package.json, families/track_and_trade/server/scripts/example_fish_data.json, families/track_and_trade/server/scripts/seed_example_data.js
Adds a general purpose script for seeding Track and Trade with blockchain data from a JSON file. Includes a JSON file for FishNet data.
=> Add script for loading example data into Track and Trade

signing/sawtooth_signing/secp256k1_signer.py
=> Optimize signing by caching public key object

validator/sawtooth_validator/networking/dispatch.py, validator/sawtooth_validator/server/core.py
=> Add dispatch timer metric tagged by dispatch handler

Jenkinsfile
=> Change branch name to 0-8 in whitelist check

COMMITTERS
=> Add cclauss to COMMITTERS

protos/network.proto, protos/processor.proto, protos/validator.proto, sdk/cxx/src/message_dispatcher.cpp, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/java/src/main/java/sawtooth/sdk/processor/TransactionProcessor.java, sdk/javascript/processor/index.js, sdk/javascript/protobuf/index.js, sdk/python/sawtooth_sdk/processor/core.py, sdk/rust/src/messaging/stream.rs, validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/networking/handlers.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/core.py, validator/tests/test_authorization_handlers/test.py
=> Replace TpPing and TpPingResponse with PingRequest and PingResponse

sdk/python/sawtooth_sdk/processor/context.py
=> Update add_event and add_receipt_data to raise InternalError

validator/sawtooth_validator/networking/interconnect.py
Adding or removing of connections should be an atomic operation. Instances of remove_connection can be called from multiple threads, which can cause an issue where one thread things there is a connection, but it is has been removed from the connections dict by another thread before its own call to delete the connection.
Fix for this type of exception occurrence:
```
2017-10-18 16:15:07 [lr7-node3]    ERROR                     Thread-24                     dispatch Unhandled exception while determining next
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/sawtooth_validator/networking/dispatch.py", line 171, in do_next
self._determine_next(message_id, future)
File "/usr/lib/python3/dist-packages/sawtooth_validator/networking/dispatch.py", line 183, in _determine_next …
```
=> Add lock around connection add/remove

bin/generate_cli_output, docs/source/app_developers_guide/intro_xo_transaction_family.rst, docs/source/cli/xo.rst, integration/sawtooth_integration/tests/test_xo_smoke.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_client.py
This PR updates the XO tutorial and doc generation to reflect recent changes to the CLI. It also makes some minor changes to the XO CLI error messages and fixes an error in `generate_cli_output`.
=> Xo doc updates

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py, docs/source/_templates/sdk_TP_tutorial.rst, families/battleship/sawtooth_battleship/processor/battleship_transaction.py, families/block_info/sawtooth_block_info/processor/handler.py, families/identity/sawtooth_identity/processor/handler.py, families/settings/sawtooth_settings/processor/handler.py, families/supplychain/python/sawtooth_supplychain/processor/handler.py, sdk/examples/intkey_python/sawtooth_intkey/processor/handler.py, sdk/examples/xo_python/sawtooth_xo/processor/handler.py, sdk/python/sawtooth_sdk/processor/context.py, sdk/python/tests/test_context.py
=> Remove StateEntry from the Python SDK

validator/sawtooth_validator/networking/interconnect.py
This fixes the issues seen where if an outbound connection goes away unexpectedly, the connection is not correctly removed when it fails the heartbeat. This causes a validator to try to send a message to the shutdown connection which causes the validator to block forever.
=> Correctly clean up outbond connection on heartbeat

cli/sawtooth_cli/config.py
Improve the help text for `sawtooth config` and all of its subcommands.
=> Improve help text for `sawtooth config`

families/settings/sawtooth_settings/processor/main.py
Add a description and epilog for the settings-tp command.
=> Improve help text for settings-tp

validator/sawtooth_validator/networking/interconnect.py
=> Use connection_id correctly in inbound authorization

bin/build_cxx, docker/sawtooth-int-intkey-tp-cxx, sdk/cxx/include/sawtooth/future_message.h, sdk/cxx/include/sawtooth/message_dispatcher.h, sdk/cxx/include/sawtooth/message_stream.h, sdk/cxx/include/sawtooth/transaction_processor.h, sdk/cxx/src/address_mapper.cpp, sdk/cxx/src/global_state.cpp, sdk/cxx/src/message_dispatcher.cpp, sdk/cxx/src/message_stream.cpp, sdk/cxx/src/transaction_processor.cpp, sdk/examples/intkey_cxx/int_key_transaction_processor.cpp
Network fixes From Jamie and some SDK updates from Dan.
=> Update c++ SDK and fix network connections.

protos/validator.proto, sdk/cxx/src/global_state.cpp, sdk/python/sawtooth_processor_test/message_types.py, sdk/python/sawtooth_sdk/processor/context.py, sdk/python/tests/test_context.py, validator/sawtooth_validator/execution/tp_state_handlers.py, validator/sawtooth_validator/server/component_handlers.py
=> Rename TP_STATE_DEL to TP_STATE_DELETE

ci/sawtooth-validator
=> Add sawtooth-poet-cli to install list

protos/state_context.proto, protos/validator.proto, sdk/go/src/sawtooth_sdk/processor/context.go, sdk/go/tests/state_test.go, sdk/python/sawtooth_processor_test/message_factory.py, sdk/python/sawtooth_processor_test/message_types.py, sdk/python/sawtooth_sdk/processor/context.py, sdk/python/tests/test_context.py, validator/sawtooth_validator/execution/tp_state_handlers.py, validator/sawtooth_validator/server/component_handlers.py, validator/tests/test_events/tests.py, validator/tests/test_receipt_store/tests.py
Replace TpAddReceiptData with TpReceiptAddData 
Replace TpAddEvent with TpEventAdd
=> Rename  TP Event and Receipt messages to match pattern

bin/build_ext_debs
=> Update pyformance version to 0.4

validator/sawtooth_validator/gossip/gossip.py
=> Add better locking around temp_endpoints in ConnectionManager

validator/sawtooth_validator/concurrent/atomic.py, validator/sawtooth_validator/concurrent/thread.py, validator/sawtooth_validator/concurrent/threadpool.py, validator/sawtooth_validator/execution/context_manager.py, validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/publisher.py, validator/sawtooth_validator/networking/dispatch.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/core.py
This PR depends on #1041 and hopefully captures and logs all exceptions from threads
=> Instrumented threading

docs/source/cli/sawtooth.rst
=> Add "sawtooth keygen" usage to CLI Reference

validator/sawtooth_validator/concurrent/threadpool.py
=> Fix missing variable declaration

Jenkinsfile
=> Update branch name for consensus-prototype branch

sdk/examples/intkey_python/setup.py
=> Fix entrypoint for intkey cli

ci/sawtooth-publish-python-sdk
=> Add Dockerfile for publishing to PyPI

bin/poet-validator-registry-tp
=> Add consensus/poet/common to os path

docker/compose/sawtooth-local.yaml
Additionally expose ports for use from the host machine.
=> Fix CLI args in local compose file

protos/network.proto, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/gossip/permission_verifier.py, validator/sawtooth_validator/gossip/signature_verifier.py, validator/sawtooth_validator/gossip/structure_verifier.py, validator/sawtooth_validator/journal/completer.py
=> Make content_type in GossipMessage an enum

perf/smallbank_workload/src/playlist.rs
Add PAYLOAD_TYPE_UNSET to match statements to fix build failure.
=> Add UNSET type to match statements

bin/generate_cli_output, cli/sawtooth_cli/admin.py, cli/sawtooth_cli/admin_command/genesis.py, cli/sawtooth_cli/admin_command/keygen.py, cli/sawtooth_cli/batch.py, cli/sawtooth_cli/block.py, cli/sawtooth_cli/config.py, cli/sawtooth_cli/identity.py, cli/sawtooth_cli/keygen.py, cli/sawtooth_cli/main.py, cli/sawtooth_cli/state.py, cli/sawtooth_cli/transaction.py, consensus/poet/cli/sawtooth_poet_cli/enclave.py, consensus/poet/cli/sawtooth_poet_cli/genesis.py, consensus/poet/cli/sawtooth_poet_cli/main.py, docs/source/cli/intkey.rst, docs/source/cli/poet.rst, docs/source/cli/rest_api.rst, docs/source/cli/sawtooth.rst, docs/source/cli/validator.rst, docs/source/cli/xo.rst, families/identity/sawtooth_identity/processor/main.py, rest_api/sawtooth_rest_api/rest_api.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_cli.py, sdk/examples/xo_python/sawtooth_xo/xo_cli.py, validator/sawtooth_validator/server/cli.py
There are no doubt gaps and irregularities here, but this PR should bring the CLI documentation to a mostly complete state. Reviewers should go through their favorite sections and look for errors and other areas where improvements can be made.
=> Update CLI documentation

validator/sawtooth_validator/journal/chain.py
=> Add a duplicate check when adding pending blocks

COMMITTERS
=> Add rberg2 to COMMITTERS

consensus/poet/families/packaging/systemd/sawtooth-poet-validator-registry-tp.service, families/identity/packaging/systemd/sawtooth-identity-tp.service, families/settings/packaging/systemd/sawtooth-settings-tp.service, rest_api/packaging/systemd/sawtooth-rest-api.service, sdk/examples/intkey_python/packaging/systemd/sawtooth-intkey-tp-python.service, sdk/examples/xo_python/packaging/systemd/sawtooth-xo-tp-python.service, validator/packaging/systemd/sawtooth-validator.service
=> Make sawtooth services restart on failure

validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/server/network_handlers.py, validator/tests/test_has_block_handler/__init__.py, validator/tests/test_has_block_handler/mock.py, validator/tests/test_has_block_handler/tests.py, validator/tests/test_journal/block_tree_manager.py
Also changes the check in chain controller for if we have a block to check the block cache instead of block store
=> Add a handler to gossip message that checks if we already have the block

validator/sawtooth_validator/execution/executor.py
=> Remove request header parsing

protos/client_peers.proto, protos/validator.proto, rest_api/openapi.yaml, rest_api/sawtooth_rest_api/rest_api.py, rest_api/sawtooth_rest_api/route_handlers.py, rest_api/tests/unit/test_peers_request.py, validator/sawtooth_validator/server/component_handlers.py, validator/sawtooth_validator/state/client_handlers.py, validator/tests/test_client_request_handlers/mocks.py, validator/tests/test_client_request_handlers/test_peer_handler.py
=> Add /peers route to get the validator peers

docs/source/app_developers_guide/docker.rst
=> Update docs to reflect sawtooth-all rename

families/block_info/sawtooth_block_info/processor/handler.py, families/seth/src/sawtooth_seth/processor/handler/handler.go, families/smallbank/smallbank_go/src/sawtooth_smallbank/handler/handler.go, sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go, sdk/examples/intkey_javascript/integer_key_handler.js, sdk/examples/noop_go/src/sawtooth_noop/handler/handler.go, sdk/examples/xo_go/src/sawtooth_xo/handler/handler.go, sdk/examples/xo_javascript/xo_handler.js, sdk/go/src/sawtooth_sdk/processor/context.go, sdk/go/src/sawtooth_sdk/processor/errors.go, sdk/go/src/sawtooth_sdk/processor/handler.go, sdk/go/src/sawtooth_sdk/processor/processor.go, sdk/go/src/sawtooth_sdk/processor/worker.go, sdk/javascript/processor/context.js, sdk/javascript/processor/exceptions.js, sdk/javascript/processor/handler.js, sdk/javascript/processor/index.js, sdk/python/sawtooth_sdk/processor/context.py, sdk/python/sawtooth_sdk/processor/core.py, sdk/python/sawtooth_sdk/processor/exceptions.py, sdk/python/sawtooth_sdk/processor/handler.py
This PR fills in missing TP SDK docstrings (with an eye towards doc autogeneration) and changes the Go and JS transaction handlers to accept multiple versions.
=> SDK docstrings / TP versions

README.md
Fix docs URL. Also remove inclubation notice header.
=> Update readme for docs URL and incubation->active

docs/source/sysadmin_guide/configuring_sawtooth.rst, docs/source/sysadmin_guide/configuring_sawtooth/identity_tp_configuration.rst, docs/source/sysadmin_guide/configuring_sawtooth/settings_tp_configuration.rst, families/identity/packaging/identity.toml.example, families/identity/sawtooth_identity/processor/config/identity.py, families/identity/sawtooth_identity/processor/main.py, families/settings/packaging/settings.toml.example, families/settings/sawtooth_settings/processor/config/settings.py, families/settings/sawtooth_settings/processor/main.py, sdk/python/sawtooth_sdk/processor/config.py, sdk/python/sawtooth_sdk/processor/exceptions.py, sdk/python/sawtooth_sdk/processor/log.py
This PR is built on top of #1086 and #1104 and satisfies STL-348 and STL-850
=> Add Configs for Identity and Setting Transaction Processors

integration/sawtooth_integration/tests/test_events_and_receipts.py, validator/sawtooth_validator/server/events/broadcaster.py
Also considering a namespace commit for event types.
=> Event Broadcaster Improvements for 1.0

docs/source/app_developers_guide/event_subscriptions.rst, docs/source/app_developers_guide/no_sdk.rst
This is a first pass "brain-dump" for how to subscribe to events. @chenette will be doing a second pass after this is merged to clean it up.
=> Document event subscriptions

validator/sawtooth_validator/gossip/signature_verifier.py
=> Drop Block/Batches the sig verifier has already validated

bin/build_ext_debs, docker/sawtooth-dev-python, rest_api/setup.py, rest_api/tests/unit/components.py, rest_api/tests/unit/test_batch_requests.py, rest_api/tests/unit/test_block_requests.py, rest_api/tests/unit/test_peers_request.py, rest_api/tests/unit/test_receipt_requests.py, rest_api/tests/unit/test_state_requests.py, rest_api/tests/unit/test_submit_requests.py, rest_api/tests/unit/test_txn_requests.py
'cause 1.3.5 has segfaults
This will break until the new deb is in `repo.sawtooth.me/ci`.
This is blocking #1111 and #1105
=> Upgrade aiohttp to 2.3.2

bin/build_all, bin/build_debs, docker/sawtooth-int-block-info-tp, families/block_info/packaging/block-info.toml, families/block_info/packaging/block-info.toml.example, families/block_info/packaging/systemd/sawtooth-block-info-tp, families/block_info/packaging/systemd/sawtooth-block-info-tp.service, families/block_info/sawtooth_block_info/processor/__init__.py, families/block_info/sawtooth_block_info/processor/config/block_info.py, families/block_info/sawtooth_block_info/processor/main.py, families/block_info/setup.py
=> Package block info tp

validator/sawtooth_validator/database/indexed_database.py, validator/sawtooth_validator/state/client_handlers.py, validator/tests/test_client_request_handlers/mocks.py, validator/tests/test_client_request_handlers/test_batch_handlers.py, validator/tests/test_client_request_handlers/test_block_handlers.py, validator/tests/test_client_request_handlers/test_peer_handler.py, validator/tests/test_client_request_handlers/test_state_handlers.py, validator/tests/test_client_request_handlers/test_submit_handlers.py, validator/tests/test_client_request_handlers/test_txn_handlers.py
=> Validate client block get by id input

sdk/cxx/include/sawtooth/global_state.h, sdk/cxx/src/global_state.cpp, sdk/examples/intkey_cxx/int_key_transaction_processor.cpp, sdk/examples/intkey_java/IntegerKeyHandler.java, sdk/examples/xo_java/XoHandler.java, sdk/java/src/main/java/sawtooth/sdk/processor/State.java
Signed-off-by Krishna Bhamidi <bhamidik@hotmail.com>
=> Changed get, set, delete to setState, getState, deleteState.

Jenkinsfile, bin/build_all, bin/build_debs
=> Fix bug so go packages are archived properly

sdk/javascript/index.js, sdk/javascript/protobuf/index.js, sdk/javascript/signing/core.js, sdk/javascript/signing/secp256k1.js
Update exports from the root index.js.  Includes:
- signing
- protobuf
- all protobufs are exported, as well
=> Add newRandomPrivateKey to JS Signing Context

ci/ns-control
=> Remove sawtooth-manage from meta-package

docs/source/sysadmin_guide/configuring_sawtooth/cli_configuration.rst
=> Add URL info to CLI config file doc

docs/source/app_developers_guide/event_subscriptions.rst, docs/source/architecture/events_and_transactions_receipts.rst
- Rewrote and added content
- Added subtitles to clarify steps
- Inserted an example of event catch-up 
- Added "Unsubscribing to Events" subsection (with examples)
=> Edit and expand "Subscribing to Events" doc

validator/sawtooth_validator/execution/scheduler_serial.py
=> Notify schedule condition on failed batch

validator/sawtooth_validator/concurrent/atomic.py, validator/sawtooth_validator/journal/block_validator.py, validator/sawtooth_validator/journal/chain.py, validator/tests/test_journal/tests.py
This increments on STL-848. It handles 1 and 3 in the description.
=> (consensus) Move trackers into validator

validator/sawtooth_validator/config/validator.py, validator/tests/test_config/tests.py
=> Change default scheduler from serial to parallel

rest_api/sawtooth_rest_api/messaging.py, rest_api/sawtooth_rest_api/state_delta_subscription_handler.py
Fixes [STL-849](https://jira.hyperledger.org/browse/STL-849)
=> Fix REST API Hang on WebSocket close

validator/sawtooth_validator/journal/block_cache.py, validator/sawtooth_validator/journal/chain.py
=> Remove blocks from block_cache if they are in the block_store

validator/sawtooth_validator/journal/chain.py, validator/tests/test_journal/block_tree_manager.py
=> Fix variable name typos

docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst, validator/packaging/validator.toml.example, validator/sawtooth_validator/config/validator.py, validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/core.py, validator/tests/test_config/tests.py
=> Make min and max peer connectivity configurable

COMMITTERS
=> Add rberg2 to 0-8 COMMITTERS

COMMITTERS
=> Add committer to list

docs/source/_templates/sdk_submit_tutorial.rst, docs/source/_templates/txn_submit_tutorial.rst
=> Fix ECDSA typo

docs/source/_templates/indexcontent.html
=> Remove core dev guide and faq from index

consensus/poet/core/tests/test_consensus/test_wait_certificate.py, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp, validator/sawtooth_validator/journal/block_wrapper.py
Reverts hyperledger/sawtooth-core#1205
=> Revert "Update NULL_BLOCK_IDENTIFIER to be 128 characters long."

bin/build_all
=> Add details to the build_all script help

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/journal/responder.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/events/broadcaster.py, validator/sawtooth_validator/server/network_handlers.py, validator/tests/test_events/tests.py
This will fix several areas where we have a small memory leak around futures that never get results. Also, this will greatly reduce the number of Network Acks the network will have to deal with.
=> Implement ability to send a message without keeping the future around.  

perf/sawtooth_perf/src/batch_gen.rs, perf/sawtooth_workload/src/main.rs, perf/smallbank_workload/src/main.rs, perf/smallbank_workload/src/playlist.rs, sdk/rust/src/signing/mod.rs, sdk/rust/src/signing/secp256k1.rs
Updates the Rust SDK to match the newer terminology used by the Python,
Javascript, and Go SDKs.
=> Rename signing Algorithm to Context in Rust SDK

docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
=> Add pem file creation methods for poet_enclave_sgx.toml

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/networking/interconnect.py
=> Fix fire and forget from an outbound connection

.gitignore
Particularly those artifacts generated by poet sgx builds
and also some from recommended smallbank procedures.
=> Update gitignore for build and test artifacts

docs/source/cli/settings-tp.rst
=> Fix typo in first sentence (repeated word)

bin/generate_cli_output, bin/sawnet, cli/sawtooth_cli/block.py, cli/sawtooth_cli/network_command/__init__.py, cli/sawtooth_cli/network_command/compare.py, cli/sawtooth_cli/network_command/fork_graph.py, cli/sawtooth_cli/network_command/parent_parsers.py, cli/sawtooth_cli/rest_client.py, cli/sawtooth_cli/sawnet.py, cli/tests/test_network.py, docs/source/cli.rst, docs/source/cli/sawnet.rst
Do `sawnet compare --help` for usage.
=> Create command for comparing across multiple nodes

docs/source/sysadmin_guide/installation.rst
=> Remove note for "Coming Soon: Yum + RPM instructions"

ci/sawtooth-intkey-tp-go, ci/sawtooth-smallbank-tp-go, ci/sawtooth-xo-tp-go, docker/compose/sawtooth-default-go.yaml, docker/compose/sawtooth-smallbank-go.yaml, sdk/examples/xo_go/packaging/ubuntu/control
This relies on some dockerhub repos that aren't created yet, so this should be merged as close to an RC as possible.
=> Add go dockerfiles and compose files

protos/network.proto, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/gossip/permission_verifier.py, validator/sawtooth_validator/journal/responder.py, validator/sawtooth_validator/server/core.py, validator/tests/test_permission_verifier/tests.py, validator/tests/test_responder/tests.py
also remove unused function from IdentityCache
=> Add Time To Live to Gossip Message and Requests

validator/sawtooth_validator/execution/scheduler_parallel.py
Properly handle unscheduled batch execution results for batches which
have been unscheduled.  Any transaction that has been removed from the
result map should throw a UnscheduledTransactionError, which will
result in a `None` result.
On unschedule_incomplete_batches, that batches also must be removed from
the ordered batch list in the schedule.
Any batch requested that is not found, should also return `None` for the
batch result.
=> Handle unscheduled batch results: Parallel

cli/setup.py
=> Package sawnet command

bin/build_all, bin/build_poet_sgx, docker/sawtooth-dev-poet-sgx
=> Add PoET sgx build to build_all script.

validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/networking/dispatch.py
=> Return ack if a duplicate response is recieved

COMMITTERS
=> Add Andrew Donald Kennedy to COMMITTERS

docker/compose/sawtooth-default.yaml
Signed-off-by: Arthur Greef <arthurgreef@live.com>
=> Fix docker compose up failure

cli/sawtooth_cli/network_command/compare.py, cli/tests/test_network.py
@jsmitchell I am pretty sure I got the tree printing to work. Let me know if you can break it. It is based on git's tree printing.
=> Improve sawnet command usability

docker/compose/sawtooth-local.yaml
Signed-off-by: Arthur Greef <arthurgreef@live.com>
=> Fix docker compose failure

consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py, integration/sawtooth_integration/tests/intkey_client.py, validator/sawtooth_validator/concurrent/threadpool.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/gossip/gossip_handlers.py, validator/sawtooth_validator/journal/block_wrapper.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/server/cli.py
This PR makes small changes to make logging cheaper and less noisy. The biggest change in terms of output is removing the size of messages from the `%s receiving %s` message in `interconnect`.
=> Improve logging

docker/sawtooth-dev-python, docker/sawtooth-dev-rust, docker/sawtooth-int-block-info-tp, docker/sawtooth-int-identity-tp, docker/sawtooth-int-intkey-tp-cxx, docker/sawtooth-int-intkey-tp-go, docker/sawtooth-int-intkey-tp-python, docker/sawtooth-int-poet-validator-registry-tp, docker/sawtooth-int-rest-api, docker/sawtooth-int-settings-tp, docker/sawtooth-int-smallbank-tp-go, docker/sawtooth-int-validator, docker/sawtooth-int-xo-tp-go, docker/sawtooth-int-xo-tp-python, docker/sawtooth-validator-mounted
Signed-off-by: Cian Montgomery <cian@cianmontgomery.com>
=> Update apt-key to use proxy friendly port.

docker/compose/sawtooth-local.yaml
=> Remove default network from sawtooth-local.yaml

docs/source/introduction.rst
=> Rewrite introduction for Sawtooth documentation

families/settings/sawtooth_settings/processor/handler.py, families/settings/tests/sawtooth_settings_test/settings_message_factory.py, families/settings/tests/test_tp_settings.py, validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/journal/publisher.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/state/settings_cache.py, validator/sawtooth_validator/state/settings_view.py, validator/tests/test_journal/block_tree_manager.py, validator/tests/test_journal/tests.py, validator/tests/test_setting_cache/__init__.py, validator/tests/test_setting_cache/mocks.py, validator/tests/test_setting_cache/tests.py
=> Add SettingsCache and SettingsObserver

validator/sawtooth_validator/database/database.py, validator/sawtooth_validator/database/lmdb_nolock_database.py, validator/sawtooth_validator/state/merkle.py
This PR makes some small optimizations to hotspots in the database code. At least I think they're optimizations -- it's hard to tell without reliable profiling.
=> Database optimizations

bin/build_cxx_intkey, bin/build_cxx_sdk, sdk/cxx/CMakeLists.txt, sdk/cxx/include/exceptions.h, sdk/cxx/include/sawtooth/address_mapper.h, sdk/cxx/include/sawtooth/global_state.h, sdk/cxx/include/sawtooth/message_dispatcher.h, sdk/cxx/include/sawtooth/transaction_handler.h, sdk/cxx/include/sawtooth/transaction_processor.h, sdk/cxx/include/sawtooth_sdk.h, sdk/cxx/src/address_mapper.cpp, sdk/cxx/src/global_state.cpp, sdk/cxx/src/transaction_processor.cpp, sdk/examples/intkey_cxx/CMakeLists.txt, sdk/examples/intkey_cxx/int_key_transaction_processor.cpp
Rework to CXX SDK build and API. Protobuf example is added to intkey CXX TP and intkey CLI.
=> CXX SDK Rework

NOTICES
This file satisfies obligations for 3rd-party open source components on which Sawtooth depends for run-time execution.
=> Adds NOTICES file for Sawtooth 3rd party run-time dependencies

Jenkinsfile
This allows Jenkins to find "$CHANGE_AUTHOR"
=> Update Jenkinsfile to use 1-0 for whitelist

bin/build_rust, bin/protogen, docker/sawtooth-dev-rust, sdk/rust/Cargo.toml, sdk/rust/build.rs
Transitions the Rust SDK from using protogen to build.rs.
=> Enhance rust sdk build

integration/sawtooth_integration/tests/test_peer_list.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/server/core.py
=> 1.0: Request Chain Head from Peers, if None

sdk/rust/Cargo.toml
Small PR to add build.rs to the sdk toml.
=> Add build.rs to toml

ci/sawtooth-build-debs, ci/sawtooth-build-docs, ci/sawtooth-publish-js-sdk, docker/sawtooth-dev-cxx, docker/sawtooth-dev-go
Signed-off-by: Cian Montgomery <cian@cianmontgomery.com>
=> Update docker file to proxy friendly apt-key url.

COMMITTERS
Signed-off-by: Cian Montgomery <cian@cianmontgomery.com>
=> Add eugeneYYY to the committers list.

BUILD.md, README.md
=> Add BUILD.md with core developer setup instructions.

NOTICES
=> Adds NOTICES file to 1-0 branch

LICENSE
=> updated to use long form apache license and add 3rd party licenses

.gitignore, bin/build_all, bin/intkey-tp-rust, bin/run_tests, integration/sawtooth_integration/docker/test_intkey_smoke_rust.yaml, sdk/examples/intkey_python/tests/test_tp_intkey_rust.yaml, sdk/examples/intkey_rust/Cargo.toml, sdk/examples/intkey_rust/src/handler.rs, sdk/examples/intkey_rust/src/main.rs, sdk/python/sawtooth_processor_test/message_factory.py
Copyright Years differ depending on when the file was created.
=> Add Intkey TP Written in Rust

docs/source/_templates/sdk_submit_tutorial.rst
Fixes a small typo in the documentation
=> Fix typo in python sdk submit transactions

docs/source/introduction.rst
=> Add acknowledgement statements to Introduction

bin/build_rust, bin/intkey-tp-rust, protos/processor.proto, sdk/examples/intkey_rust/Cargo.toml, sdk/rust/Cargo.toml, sdk/rust/src/messaging/stream.rs, sdk/rust/src/messaging/zmq_stream.rs, sdk/rust/src/processor/handler.rs, sdk/rust/src/processor/mod.rs
This pr includes adding a monitor socket and handling a
disconnection from the validator, and ability to respond to
ping requests. Also the handling of wrong message types of
has been updated to match the other SDK and unwraps have
been removed in the processor.
Also includes some other random fixups.
=> Complete the Transaction Processor for the rust sdk

validator/sawtooth_validator/server/cli.py
=> Log version on validator startup

validator/sawtooth_validator/server/cli.py
=> Backport: Log version on validator startup

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_settings_view.py, consensus/poet/core/sawtooth_poet/poet_consensus/wait_certificate.py, consensus/poet/core/sawtooth_poet/poet_consensus/wait_timer.py, consensus/poet/core/tests/test_consensus/test_consensus_state.py, consensus/poet/core/tests/test_consensus/test_consensus_state_store.py, consensus/poet/core/tests/test_consensus/test_poet_settings_view.py, consensus/poet/core/tests/test_consensus/test_wait_certificate.py, consensus/poet/core/tests/test_consensus/test_wait_timer.py, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.h, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/poet.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.edl, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_shared/poet.h, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.h, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.i, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/wait_timer.cpp, consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
=> Update minimum wait timer in poet

docs/source/introduction.rst
Backport PR #1366  to the 1-0 branch.
=> Backport: Add acknowledgement statements to Introduction

validator/sawtooth_validator/execution/context_manager.py, validator/sawtooth_validator/execution/scheduler_parallel.py, validator/tests/test_scheduler/tests.py
I am putting this PR here so I can build debs to run further tests on it. The explanation of the errors are in PR #1382 .
=> 1-0 backport: Fix for two errors dealing with unscheduling

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_settings_view.py, consensus/poet/core/sawtooth_poet/poet_consensus/wait_certificate.py, consensus/poet/core/sawtooth_poet/poet_consensus/wait_timer.py, consensus/poet/core/tests/test_consensus/test_consensus_state.py, consensus/poet/core/tests/test_consensus/test_consensus_state_store.py, consensus/poet/core/tests/test_consensus/test_poet_settings_view.py, consensus/poet/core/tests/test_consensus/test_wait_certificate.py, consensus/poet/core/tests/test_consensus/test_wait_timer.py, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.h, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/poet.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.edl, consensus/poet/sgx/sawtooth_poet_sgx/libpoet_shared/poet.h, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.h, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.i, consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/wait_timer.cpp, consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py, docs/source/architecture/journal.rst
backport https://github.com/hyperledger/sawtooth-core/commit/0d41952b962fbf0fcb97cb2306029c5dd85a2245 and 
https://github.com/hyperledger/sawtooth-core/pull/1381/commits/da4119577754386b957e6f453f6187ea0bd09942 from master to 1-0
=> 1-0 Backport Remove Minimum Wait Time setting

docs/source/_templates/sdk_submit_tutorial.rst
Signed-off-by: Cian Montgomery <cian@cianmontgomery.com>
=> Fix small typos in javascript sdk docs.

sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_workload.py
=> Add key-file option to intkey workload

perf/smallbank_workload/src/playlist.rs
Use full length addresses, and generate random account names.
=> Two small smallbank workload fixes

validator/sawtooth_validator/concurrent/threadpool.py, validator/sawtooth_validator/journal/completer.py, validator/sawtooth_validator/server/core.py
These are some completer metrics that will be useful in measuring proposed fixes for the flatline bug. There will be more.
=> Add some completer metrics

validator/sawtooth_validator/journal/publisher.py
Adds a dict to maintina logging states that may be entered or exited
asynchronously within the publishers processing cycle.  Adds the
"consensus_not_ready" state, which tracks that condition related to
block publishing readiness, according to the publisher.
=> Log consensus readiness at boundaries

BUILD.md
Light edit: Correct grammar & typos; rewrite per Sawtooth doc conventions
=> Edit BUILD.md content

bin/run_go_fmt, docker/compose/smallbank-local-mounted.yaml, families/smallbank/smallbank_go/src/sawtooth_smallbank/main.go
=> Add max-queue-size and worker-thread-count to smallbank

bin/build_cxx_xo, bin/intkey-tp-cxx, bin/xo-tp-cxx, sdk/cxx/include/sawtooth/address_mapper.h, sdk/cxx/include/sawtooth/transaction_processor.h, sdk/cxx/include/sawtooth_sdk.h, sdk/cxx/src/address_mapper.cpp, sdk/cxx/src/transaction_processor.cpp, sdk/examples/intkey_cxx/address_mapper.cpp, sdk/examples/intkey_cxx/address_mapper.h, sdk/examples/intkey_cxx/int_key_transaction_processor.cpp, sdk/examples/xo_cxx/CMakeLists.txt, sdk/examples/xo_cxx/address_mapper.cpp, sdk/examples/xo_cxx/address_mapper.h, sdk/examples/xo_cxx/xo_transaction_processor.cpp
Added CXX XO example
Fixed CRTL-C handler and TP unregistration on exit
Modified AdrresMapper API to make it more generic
=> CXX XO example and fixed CTRL-C handling

docs/source/architecture/journal.rst
Signed-off-by: Adam Parker <adam.parker@ayokasystems.com>
=> Fix typo in example for validator configuration

validator/sawtooth_validator/concurrent/atomic.py, validator/sawtooth_validator/execution/executor.py, validator/sawtooth_validator/journal/block_validator.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/journal/chain_commit_state.py, validator/tests/test_journal/tests.py
This depends on #1403 and includes a number of other chain controller refactor commits from the consensus-prototype branch
=> Rewrite duplicate/missing transaction/batch checks

validator/sawtooth_validator/server/cli.py
=> Log version after logging configuration is applied

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_key_state_store.py
Fix root cause of STL-1050 and add protections for backwards
compatibility with Sawtooth v1.0.1
Issue introduced in #1288 
Will want to backport #1288 and this PR together. Presumably into v1.0.2.
=> Fix STL-1050 incorrect poet key state store use

integration/sawtooth_integration/tests/poet_liveness_data/validator-0.toml, integration/sawtooth_integration/tests/poet_liveness_data/validator-2.toml, integration/sawtooth_integration/tests/poet_liveness_data/validator-4.toml, validator/sawtooth_validator/server/cli.py
Also log the scheduler type on validator start.
=> Add parallel scheduler to poet liveness

bin/clean_all, bin/run_bandit, bin/run_lint
=> Removed core directory entries in bin scripts

bin/clean_all, bin/run_lint
=> Removed extensions dir entries in bin scripts

validator/sawtooth_validator/execution/scheduler_parallel.py, validator/tests/test_scheduler/data/long_chain_of_inputs_outputs.yaml, validator/tests/test_scheduler/test_schedulers_with_yaml.py
=> Fix off by one error in parallel scheduler

docker/sawtooth-dev-javascript
Signed-off-by: ashish kumar mishra <ashish.k.mishra@intel.com>
=> Added support for proxy in sawtooth-dev-javascript

.gitignore, integration/sawtooth_integration/docker/test_poet_liveness.yaml
Also change the intkey TPs to Go to match the LR networks.
=> Add smallbank to poet liveness test

docker/grafana/dashboards/dashboard.json, validator/sawtooth_validator/metrics/wrappers.py, validator/sawtooth_validator/networking/interconnect.py
This PR replaces the dispatcher queue size logging message with a gauge metric, and adds a dashboard panel to track it.
=> Add dispatcher queue size metric

validator/sawtooth_validator/journal/publisher.py
Compute the pending batch queue limit by adding the number of batches in
a chain head (i.e. a block) to the rolling average, instead of using the
number of committed batches, which may be across multiple blocks (in the
case of switching forks of length > 1).  For a network that is able to
process transactions at a high rate, this will max out as a function of
max batches per block.
=> Compute pending batch queue limit by block bounds

bin/build_java_intkey, bin/build_java_sdk, bin/build_java_xo
=> Safer regex and readability in build_java_x files

docs/source/_templates/sdk_TP_tutorial.rst, docs/source/_templates/template_config.yaml, docs/source/app_developers_guide.rst, docs/source/app_developers_guide/go_sdk.rst, sdk/examples/xo_javascript/xo_handler.js
The code samples are now more modular.
=> Replace code samples in Xo tutorial

sdk/examples/intkey_cxx/int_key_transaction_processor.cpp
Add range checks to set, inc, and dec
=> Fix STL-166 cxx intkey out of spec

docs/source/app_developers_guide.rst, docs/source/app_developers_guide/overview.rst, docs/source/introduction.rst
=> Improve App Dev Guide intro; add overview of Sawtooth TFs

docs/source/_templates/sdk_TP_tutorial.rst
This PR is based on #1473 
The main features:
- Inclusion of simplified entry point.
- inclusion of caption tags for each code sample
- Slight reorganization of code sample for clarity
=> Update xo tutorial code samples for readability and clarity

cli/sawtooth_cli/identity.py
This was missed when the attribute name was changed.
=> Replace Policy.Type with Policy.EntryType in policy list

sdk/examples/xo_cxx/address_mapper.h, sdk/examples/xo_cxx/xo_transaction_processor.cpp
- Method args in xo_transaction_processor.cpp have const reference
- Make XoTransactionPayload constructor explicit
- Make AddressMapper constructor explicit
=> Update xo cxx code

docs/source/architecture/poet.rst
Sections edited:
- z-test
- Population Size and Local Mean Computation
- Comments on Multi-user or Multi-ledger SGX Enclave Service
=> Updated PoET specs readability

COMMITTERS
=> Add Pankaj Goyal to COMMITTERS

perf/intkey_workload/src/intkey_transformer.rs
=> Add condition to intkey workload to set unsatisfiable dependency

validator/sawtooth_validator/networking/dispatch.py
I'm putting up this PR to test a hypothesis about why https://github.com/hyperledger/sawtooth-core/pull/1489 failed its LR run. The hypothesis is that callbacks are sometimes being executed in the dispatcher thread rather than in the intended threadpool threads. These callbacks can potentially perform expensive computations, slowing down the dispatcher and thereby slowing down everything.
=> Execute dispatcher callback directly

perf/intkey_workload/src/intkey_transformer.rs
=> Add condition to intkey workload to use a wildcarded address

docs/source/app_developers_guide/docker.rst
This is a major rewrite/reorg for the content, based on the previous rewrite for the AWS procedure.
Note that the actual commands have not changed, except for new Docker commands to check the logs.
=> Rewrite Docker install procedure

perf/intkey_workload/src/intkey_transformer.rs, perf/intkey_workload/src/main.rs
This differs from #1509 in that this dependency is able to be satisfied, but unnecessary, while #1509 was for dependencies that could not be satisfied.  This PR finishes STL-1017.
=> Add option to intkey-workload to set an unnecessary dependency

validator/sawtooth_validator/database/lmdb_nolock_database.py
See https://github.com/hyperledger/sawtooth-core/pull/1517 for discussion
=> Add LMDBNoLockDatabase.get

validator/sawtooth_validator/execution/scheduler_parallel.py
Running 3000 transactions through a 3-node network with 100 transactions per batch, `ParallelScheduler.unschedule_incomplete_batches` takes around 5% of total CPU time. Changing a certain scheduler data structure from a list to a dict reduces that practically nothing.
Here are before and after graphs from validator 1:
Here are before and after graphs from validator 2:
One could be forgiven for thinking these numbers are bogus. I certainly did at first. But I reran the test several times and the results always come out the same.
=> Make unscheduler faster

docs/source/app_developers_guide/ubuntu.rst
This is a major rewrite/reorganization. Most of the text has changed. Also:
- I changed/added several commands, such as a step to start xo-tp-python
(to be consistent with the Docker and AWS demo environments) and several
commands to check the logs.
- I updated the output to match the current release.
=> Rewrite Ubuntu install procedure

bin/get_version
=> Update package versioning to include commit hash

COMMITTERS
=> Fix alphabetization of COMMITTERS list

docker/compose/sawtooth-default-poet.yaml
This file pulls hyperledger/sawtooth-..:1.0 images and starts a 5 node poet network with intkey and xo transaction processors.
=> Create sawtooth-default-poet compose file

docs/source/app_developers_guide/about_event_subscriptions.rst, docs/source/app_developers_guide/about_events.rst, docs/source/app_developers_guide/event_subscriptions.rst, docs/source/app_developers_guide/web_socket_event_subscription.rst, docs/source/app_developers_guide/zmq_event_subscription.rst
Reorganize, expand information, and clarify steps.
=> Rewrite "Subscribing to Events" (was "Event Subscription")

docs/source/app_developers_guide/intro_xo_transaction_family.rst
This commit adds a step to start the XO TP, changes the title, and improves wording throughout.
=> Add "start XO TP" step to Play XO section of App Dev Guide

docs/source/app_developers_guide/aws.rst, docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/installing_sawtooth.rst, docs/source/app_developers_guide/ubuntu.rst
Wording (not technical) changes so that the Docker and AWS procedures match
the most recent changes for the Ubuntu procedure for setting up a Sawtooth development environment.
=> Ensure consistency for Sawtooth setup procedures (Docker/Ubuntu/AWS)

bin/build_debs, bin/build_rust, perf/intkey_workload/packaging/ubuntu/changelog, perf/intkey_workload/packaging/ubuntu/control
=> Build intkey-workload debs

rest_api/sawtooth_rest_api/rest_api.py
=> Fix default bind port in rest-api cli help text 

sdk/rust/src/messaging/zmq_stream.rs
When the stream is shutting down, route receives a DisconnectedError and
then tries to forward this error on to all of its channles. However,
these channels tend to already have been cleaned up, causing a send
error. This commit handles this send error by logging it, rather than
panicing. This panic was seen during shutdown.
=> Rust SDK: Handle send errors on disconnect

.gitignore, Jenkinsfile, bin/build_all, bin/build_validator, bin/run_lint_validator, bin/sawtooth-validator, docker/sawtooth-dev-validator, docker/sawtooth-int-validator, integration/sawtooth_integration/docker/test_dynamic_network.yaml, validator/Cargo.toml, validator/sawtooth_validator/server/cli.py, validator/setup.py, validator/src/main.rs
=> Wrap Validator Python main with Rust main

docker/sawtooth-dev-javascript
- improve script code safety
- add support for https_proxy as well
=> Update proxy support in sawtooth-dev-javascript

validator/Cargo.toml, validator/sawtooth_validator/server/cli.py, validator/src/main.rs, validator/src/pylogger.rs, validator/src/server/cli.rs, validator/src/server/mod.rs
The CLI arguments are parsed in main.rs and then JSON-serialized and
passed over into Python. There's no special reason to use JSON; it's
just a quick and simple way to get data over the wall.
=> Rustify validator CLI

.env, adm/Dockerfile-installed, ci/sawtooth-meta, ci/sawtooth-shell-installed, cli/Dockerfile-installed, consensus/poet/cli/Dockerfile-installed, consensus/poet/common/Dockerfile-installed, consensus/poet/core/Dockerfile-installed, consensus/poet/families/Dockerfile-installed, consensus/poet/sgx/Dockerfile-installed, consensus/poet/simulator/Dockerfile-installed, docker-compose-installed.yaml, docker/compose/copy-debs.yaml, families/block_info/Dockerfile-installed, families/identity/Dockerfile-installed, families/settings/Dockerfile-installed, families/smallbank/smallbank_go/Dockerfile-installed, rest_api/Dockerfile-installed, sdk/cxx/Dockerfile-installed, sdk/examples/intkey_go/Dockerfile-installed, sdk/examples/intkey_python/Dockerfile-installed, sdk/examples/noop_go/Dockerfile-installed, sdk/examples/noop_go/packaging/ubuntu/control, sdk/examples/xo_go/Dockerfile-installed, sdk/examples/xo_python/Dockerfile-installed, sdk/python/Dockerfile-installed, signing/Dockerfile-installed, utility/ias_client/Dockerfile-installed, utility/ias_proxy/Dockerfile-installed, validator/Dockerfile-installed
This PR is a subset of the changes proposed in https://github.com/Cargill/sawtooth-rfcs/blob/c006-docker-compose-builds/text/0000-docker-compose-builds.md
=> C009 installed dockerfiles

docs/source/app_developers_guide/creating_sawtooth_network.rst
=> Fix Validator Registry container name in multi-node procedure

.gitignore, docker-compose.yaml, docker/sawtooth-shell, families/settings/Dockerfile, rest_api/Dockerfile, sdk/examples/intkey_python/Dockerfile, sdk/examples/xo_python/Dockerfile, validator/Dockerfile
This PR is a subset of the changes proposed in https://github.com/Cargill/sawtooth-rfcs/blob/c006-docker-compose-builds/text/0000-docker-compose-builds.md
=> C010 mounted dockerfiles

validator/sawtooth_validator/state/merkle.py, validator/src/state/merkle.rs, validator/src/state/merkle_ffi.rs
Implements the `prune` function on the MerkleDatabase. This function prunes a single trie, using its change log, by either:
- A parent trie is pruned based on the deletions that occurred with its only successor
- A trie with no successors is pruned by deleting all of the additions
If a trie has multiple successors, it is not deleted. 
Additionally, it adds the FFI layer for python access 
Note this is built on top of #1617
=> Implement Prune Functionality in MerkleDatabase

validator/src/journal/block_manager.rs, validator/src/journal/block_store.rs, validator/src/journal/mod.rs
This work is based off of the ideas in this RFC pull request: https://github.com/hyperledger/sawtooth-rfcs/pull/5. 
~The persist method is not yet implemented, but I wanted to get eyes on the work so far.~
=> Implement BlockManager in Rust

adm/Cargo.toml, families/smallbank/smallbank_rust/Cargo.toml, perf/intkey_workload/Cargo.toml, perf/sawtooth_perf/Cargo.toml, perf/sawtooth_workload/Cargo.toml, perf/smallbank_workload/Cargo.toml, sdk/examples/intkey_rust/Cargo.toml, sdk/rust/Cargo.toml, validator/Cargo.toml
=> Update protoc to 2.0

validator/src/journal/mod.rs, validator/src/journal/publisher.rs
First few structs for block publisher
=> Add initial rust publisher

validator/src/journal/publisher.rs
Rust port of `IncomingBatchQueue`
=> Incoming batch queue

validator/src/scheduler/execution_result_ffi.rs, validator/src/scheduler/mod.rs, validator/src/scheduler/py_scheduler.rs
This is built off of #1604. This PR is just the last commit.
=> Modify ExecutionResult returned by Scheduler

validator/src/journal/publisher.rs
This commit changes the IncomingBatchSender/Receiver to use batch::Batch
instead of proto::batch::Batch.
=> Modify IncomingBatchSender/Receiver to use Rust Batch

validator/sawtooth_validator/journal/block_wrapper.py, validator/src/block.rs, validator/src/journal/block_wrapper.rs, validator/src/journal/block_wrapper_ffi.rs, validator/src/journal/mod.rs, validator/src/scheduler/execution_result_ffi.rs, validator/src/scheduler/mod.rs
Implements Rust BlockWrapper and python<->rust conversions.
Replaces #1681
=> Implement Rust BlockWrapper

validator/src/block_ffi.rs, validator/src/journal/candidate_block.rs, validator/src/journal/chain_commit_state.rs, validator/src/lib.rs, validator/src/scheduler/execution_result_ffi.rs, validator/src/scheduler/py_scheduler.rs
These fixes are required for the BlockPublisher PR.
=> Fixes to CandidateBlock, TransactionCommitCache, and PyScheduler

docs/source/app_developers_guide/creating_sawtooth_network.rst
Updates the documentation. 
Signed-off-by: Eloá Franca Verona <eloafran@bitwise.io>
=> Change sawtooth-poet-shell to sawtooth-shell-default

sdk/examples/intkey_rust/Cargo.toml, sdk/examples/intkey_rust/src/main.rs
+ Remove unnecessary dependencies
+ Update dependencies that are necessary
+ Make error messages clearer
=> Clean up Rust Intkey example

bin/run_lint, docker-compose-installed.yaml, docker/compose/copy-debs.yaml, integration/Dockerfile-installed, integration/setup.py, sdk/examples/intkey_python/Dockerfile-tests-installed, sdk/examples/intkey_python/setup_tests.py, sdk/examples/xo_python/Dockerfile-tests-installed, sdk/examples/xo_python/setup_tests.py
=> Add files to build packages for SDK testing

docs/source/transaction_family_specifications/smallbank_transaction_family.rst
=> Fix small bank document typo

validator/src/state/merkle.rs
Make the duplicate check when a fork is being removed (i.e. a chain has been dropped and the head of the fork is being removed).
Adds a test to verify this.
=> Ensure that duplicates are not pruned on forks

.gitignore, bin/build_all, bin/build_rust, bin/run_tests, bin/xo-tp-rust, docker/compose/sawtooth-build.yaml, sdk/examples/xo_python/tests/test_tp_xo_rust.yaml, sdk/examples/xo_rust/Cargo.toml, sdk/examples/xo_rust/Dockerfile, sdk/examples/xo_rust/src/handler/game.rs, sdk/examples/xo_rust/src/handler/handler.rs, sdk/examples/xo_rust/src/handler/mod.rs, sdk/examples/xo_rust/src/handler/payload.rs, sdk/examples/xo_rust/src/handler/state.rs, sdk/examples/xo_rust/src/main.rs
Add a processor for the XO transaction type to the Rust SDK examples
=> Add Rust XO Transaction Processor

consensus/poet/cli/sawtooth_poet_cli/registration.py, consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
These are a few small changes to prepare the PoET code for use by the consensus engine.
=> Poet modifications

.dockerignore, Jenkinsfile
=> Add timestamps to Jenkins build logs

docs/source/_templates/sdk_TP_tutorial.rst, docs/source/_templates/sdk_overview_tutorial.rst, docs/source/_templates/template_config.yaml, docs/source/app_developers_guide/rust_sdk.rst, docs/source/app_developers_guide/rust_sdk_import.rst, docs/source/app_developers_guide/using_the_sdks.rst
Add:
+ Information on using Sawtooth in Rust
+ XO transaction processor tutorial in Rust
=> docs: Add Rust SDK Documentation

sdk/python/sawtooth_sdk/consensus/zmq_driver.py, sdk/python/sawtooth_sdk/consensus/zmq_service.py, sdk/python/tests/test_zmq_driver.py
This PR contains some miscellaneous fixups and improvements to the Python CSDK.
=> Python Consensus SDK Improvements

docs/source/app_developers_guide/creating_sawtooth_network.rst, docs/source/architecture/journal.rst, docs/source/architecture/scheduling.rst
Correct and clarify to describe current architecture of genesis batch and
block creation; add links to relevant topics in other sections.
=> Update "Genesis Operation" section of Journal (in Arch doc)

Jenkinsfile, ci/sawtooth-build-docs, docker/sawtooth-dev-python, docker/sawtooth-validator-mounted
Tags are required to get the dev version number and JJB multibranch
fetches without tags.
=> Build fixups

docs/source/architecture/permissioning_requirement.rst
- Change title to Permissioning Design (was ~ Requirements )
- Add overview and intro text to summarize and clarify section content
- Remove text about needing to design and implement an incentive system
for a public Sawtooth network
- Fix design-doc language (change "will", "must", "should", etc.)
=> Update Permissioning section in Architecture doc

validator/src/journal/block_store.rs
modifications:
- added iter() method
- delete returns the blocks deleted
These changes are needed so that only reference counts are needed to be stored about blocks, and not meta-information like block_num for blocks that are in a block store and referenced by other blocks.
=> Modify BlockStore trait

docs/source/architecture/injecting_batches_block_validation_rules.rst
- Change journal ref to BlockPublisher (and add link to journal chapter)
- Clarify family_name in NofX rule
- Fix typos, design-doc language, and formatting
=> Update Injecting Batches chapter in arch doc

integration/sawtooth_integration/docker/test_devmode_engine.yaml, integration/sawtooth_integration/docker/test_devmode_engine_liveness.yaml, integration/sawtooth_integration/docker/test_peer_list.yaml, integration/sawtooth_integration/tests/test_devmode_engine.py
Add integration tests for the Devmode engine, which will exercise the consensus engine API's via the this engine
=> Add Devmode Engine Test and Liveness test

validator/sawtooth_validator/concurrent/atomic.py, validator/sawtooth_validator/consensus/handlers.py, validator/sawtooth_validator/consensus/notifier.py, validator/sawtooth_validator/consensus/proxy.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/server/consensus_handlers.py, validator/sawtooth_validator/server/core.py, validator/tests/test_consensus/tests.py
A couple of peering updates implementations were missed that are needed by Raft.
=> Implement Peering Updates

validator/sawtooth_validator/journal/block_manager.py, validator/src/journal/block_manager.rs, validator/src/journal/block_manager_ffi.rs, validator/src/journal/mod.rs, validator/tests/test_block_manager/__init__.py, validator/tests/test_block_manager/tests.py
~This only adds functions that are used by the completer and proxy on
the block cache.~
=> Add BlockManager ffi functions

rest_api/openapi.yaml
Update /state and /state/{address} API references. Add
detail for partial address support.
Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>
=> Update state API in Endpoint Specifications

docs/source/sdks.rst
=> Fix Python & JS link inconsistencies in SDK API Reference cover page

validator/src/ffi.rs, validator/src/journal/fork_cache.rs, validator/src/journal/validation_rule_enforcer.rs, validator/src/metrics/mod.rs, validator/src/state/error.rs, validator/src/state/identity_view.rs, validator/src/state/merkle.rs, validator/src/state/settings_view.rs
This PR fixes some of the clippy lint in areas that don't have a PR up right now.
=> Fixes for some of the clippy lint

sdk/examples/devmode_rust/src/engine.rs
In order to reduce the logging noise during debug, add a log guard that will only add the messages about "Not ready to summarize" or "finalize" on the first occurrence. Once the summary or finalization result is returned, the guard is disabled.
=> Add log guard for devmode debug msgs

docker/kubernetes/sawtooth-kubernetes-default-poet.yaml, docker/kubernetes/sawtooth-kubernetes-default.yaml, docs/Makefile
The PR gets the kubernetes files in the repo and preserves them in the documentation build artifacts, so the links in the kubernetes documentation @chenette is working on will work.
=> K8s config files

validator/tests/test_journal/tests.py
This fixes the master failure seen https://build.sawtooth.me/job/Sawtooth-Hyperledger/job/sawtooth-core/job/master/23/
=> Fix failure on master build

docs/source/app_developers_guide/sdk_table.rst
=> Add explanation of "Community support only" in SDK table

docs/source/app_developers_guide/creating_sawtooth_network.rst
=> Add Set Allowed TPs step to multi-node procs in App Dev Guide

sdk/rust/src/consensus/zmq_driver.rs, sdk/rust/src/processor/mod.rs, validator/src/database/lmdb.rs, validator/src/journal/block_validator.rs, validator/src/journal/chain.rs, validator/src/journal/chain_commit_state.rs, validator/src/journal/chain_ffi.rs
This resolves several of the lints in validator and sawtooth_sdk rust.
=> Resolve some Clippy Rust lints

docs/source/sysadmin_guide/grafana_configuration.rst
rest-api section added
and a few fix ups here and there
=> Update grafana / influx documentation

docs/source/sysadmin_guide/configure_sgx.rst
* add steps to install and start / restart poet-engine
* add validator configuration for consensus port
* change configuration file code blocks to ini to prevent odd syntax
highlighting
=> Update sgx guide for bumper

docs/source/sysadmin_guide/rest_auth_proxy.rst
=> Update and improve the rest auth proxy document.

ci/sawtooth-block-info-tp, ci/sawtooth-devmode-engine, ci/sawtooth-identity-tp, ci/sawtooth-intkey-tp-python, ci/sawtooth-meta, ci/sawtooth-rest-api, ci/sawtooth-settings-tp, ci/sawtooth-shell, ci/sawtooth-validator, ci/sawtooth-xo-tp-python, docker/compose/sawtooth-default-poet.yaml, docker/compose/sawtooth-default.yaml, docker/sawtooth-av, docs/source/app_developers_guide/docker.rst, docs/source/app_developers_guide/ubuntu.rst, docs/source/sysadmin_guide/configure_sgx.rst, docs/source/sysadmin_guide/installation.rst, rest_api/Dockerfile-installed
Forward port of changes made to the 1.1 branch.
=> Master bumper updates

docs/source/sysadmin_guide/grafana_configuration.rst
- Fix intro (remove duplicate note, add procedure summary)
- Add REST API to validator for the Docker container note
- Make placeholder passwords consistent
- Clarify either/or choice for uploading the 1.0 dashboard
- Add links for config files (in case the config_dir path was changed)
- Edit titles and steps to use active phrases; clarify wording and fix
format throughout
=> Edit Grafana procedure in Sys Admin Guide

docs/source/architecture/scheduling.rst, docs/source/sysadmin_guide/off_chain_settings.rst, docs/source/sysadmin_guide/setting_up_sawtooth_poet-sim.rst, docs/source/sysadmin_guide/testing_sawtooth.rst
This new procedure describes how to create and change the configuration files for the validator, REST API and (optionally) CLI configuration.
This PR also includes additional steps for the "Testing Sawtooth" procedure to check the list of peers.
=> Add proc to change off-chain config (Sys Admin Guide)

docs/source/sysadmin_guide/configure_sgx.rst
Add note on planned availability of PoET SGX in Sawtooth release 1.1
=> Update PoET-SGX proc with note on 1.1 availability

docs/source/architecture/transactions_and_batches.rst
Signed-off-by: Scott Rudiger <scottrudiger@gmail.com>
=> Fix typo in transactions_and_batches.rst

sdk/rust/src/consensus/zmq_service.rs
=> Fix lint in sdk associated with new rustfmt version

docs/source/community/join_the_discussion.rst
=> Correct link to Rocket.Chat consensus channel

validator/sawtooth_validator/server/cli.py, validator/sawtooth_validator/server/log.py
Signed-off-by: yarasan <yarasan@users.noreply.github.com>
=> Fix file permission error while starting up validator #505

adm/Cargo.toml, families/settings/sawtooth_settings/Cargo.toml, families/smallbank/smallbank_rust/Cargo.toml, perf/intkey_workload/Cargo.toml, perf/sawtooth_perf/Cargo.toml, perf/sawtooth_workload/Cargo.toml, perf/smallbank_workload/Cargo.toml, sdk/examples/devmode_rust/Cargo.toml, sdk/examples/intkey_rust/Cargo.toml, sdk/examples/xo_rust/Cargo.toml, sdk/rust/Cargo.toml
Renames the rust SDK, and updates the Cargo.toml files in core.
=> 034 crates changes

adm/Cargo.toml, families/smallbank/smallbank_rust/Cargo.toml, perf/intkey_workload/Cargo.toml, perf/sawtooth_perf/Cargo.toml, perf/sawtooth_workload/Cargo.toml, perf/smallbank_workload/Cargo.toml, sdk/examples/devmode_rust/Cargo.toml, sdk/examples/intkey_rust/Cargo.toml, sdk/examples/xo_rust/Cargo.toml, sdk/rust/Cargo.toml
Renames the rust SDK, and updates the Cargo.toml files in core.
=> 034 crates changes backport

validator/sawtooth_validator/networking/interconnect.py
Code to answer empty ZeroMQ messages and honor the probing on the listening external socket.
Implement #STL-1446
=> Implement the ZMQ_PROBE_ROUTER flag response.

rest_api/tests/unit/test_batch_requests.py, rest_api/tests/unit/test_block_requests.py, rest_api/tests/unit/test_txn_requests.py, sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload/sawtooth_workload.py, sdk/python/sawtooth_sdk/processor/exceptions.py, sdk/python/sawtooth_sdk/processor/handler.py, signing/sawtooth_signing/core.py, validator/sawtooth_validator/database/database.py, validator/sawtooth_validator/exceptions.py, validator/sawtooth_validator/execution/scheduler_parallel.py, validator/sawtooth_validator/journal/consensus/consensus.py, validator/sawtooth_validator/state/identity_view.py
Back-port the changes made to address the updates in pylint 2.2.0 (see #1952 for change in master).
=> 1-1 backport pylint fixes

ci/nightly/sawtooth-block-info-tp, ci/nightly/sawtooth-devmode-engine, ci/nightly/sawtooth-identity-tp, ci/nightly/sawtooth-intkey-tp-python, ci/nightly/sawtooth-intkey-workload, ci/nightly/sawtooth-rest-api, ci/nightly/sawtooth-settings-tp, ci/nightly/sawtooth-shell, ci/nightly/sawtooth-smallbank-tp-go, ci/nightly/sawtooth-smallbank-workload, ci/nightly/sawtooth-validator, ci/nightly/sawtooth-xo-tp-python
=> Add nightly dockerfiles for docker hub

ci/sawtooth-devmode-engine-rust, docker/kubernetes/sawtooth-kubernetes-default.yaml
This is in master #1950 and this is pending approval #1962
=> Devmode engine rust 1 1

docs/source/introduction.rst
=> Remove Private UTXO from Sawtooth doc Introduction

sdk/rust/Cargo.toml
=> Increment sdk/rust Cargo.toml version

sdk/python/sawtooth_sdk/consensus/zmq_driver.py, sdk/rust/src/consensus/zmq_driver.rs
Updates the Python and Rust Consensus SDKs to support version 1.1
validators in addition to later versions.
=> Update consensus SDKs for backwards compatibility

families/block_info/stdeb.cfg, families/identity/stdeb.cfg
=> Specify explicit dependencies for two families TPs

integration/sawtooth_integration/docker/test_events_and_receipts.yaml, integration/sawtooth_integration/tests/test_events_and_receipts.py, validator/sawtooth_validator/journal/genesis.py, validator/sawtooth_validator/server/core.py, validator/tests/test_genesis/tests.py
=> 1-1 BACKPORT: Store Transaction Receipts Generated at Genesis time

sdk/python/sawtooth_sdk/consensus/zmq_driver.py
Fix the Python SDK's `ZmqDriver._wait_until_active` method to properly
wait for the activation message. Fixes a bug that caused the engine to
never actually process the activation.
=> Fix Python SDK's activation procedure

ci/sawtooth-build-docs
Additionally, add latexmk for building pdfs.
=> 1-1: Unpin sphinx doc

docs/source/sysadmin_guide/testing_sawtooth.rst
This commit was merged to master in PR #1992.
=> 1-1 BACKPORT: Correct FAQ link in Sys Admin Guide/Testing proc

validator/src/state/merkle.rs
Transaction is submitted to handle simultaneous read and write
to multiple addresses in merkle tree.
"merkle_db_update" is called with both update items and delete
items. If update items have common parent with delete items,
and delete items remove common parent required by update items a
node is left to be added without a correct parent chain.
Processing delete items leaves behind the broken parent chain.
Solution: Remove parent node of item to be deleted only if its
path is not in parent chain of update items.
Alternate option I was thinking about, keep boolean along with node in path_map, to indicate if it's deleted / added item. Please review and suggest edits. Also can I modify earlier unit test case itself?
=> Parent not found when trying to delete & update simultaneously

validator/sawtooth_validator/networking/interconnect.py
=> Disable linting of failing zmq import

validator/sawtooth_validator/ffi.py, validator/src/pylogger.rs
=> 1-1 BACKPORT Restore Rust Logging

docs/source/app_developers_guide/ubuntu.rst
For Sawtooth 1.2.x **nightly**, new settings are now required for the
Devmode consensus engine that was previously defaulted in 1.1 and before.
That is,
* sawtooth.consensus.algorithm.name=Devmode
* sawtooth.consensus.algorithm.version=0.1
Setting these values need to be documented in Step 3 of
docs/source/app_developers_guide/ubuntu.rst
These changes are for 1.2 nightly and are not required for 1.1 and earlier.
=> Add Missing Devmode setting in Dev Guide Ubuntu Install Instructions

ci/ns-control, ci/sawtooth-shell-installed, cli/Dockerfile, cli/Dockerfile-installed-bionic, cli/Dockerfile-installed-xenial, cli/setup.py, cli/tests/cli-tests.dockerfile, families/battleship/tests/battleship-tests.dockerfile, families/identity/tests/identity-tests.dockerfile, families/settings/tests/settings.dockerfile, rest_api/Dockerfile-installed-bionic, rest_api/Dockerfile-installed-xenial, rest_api/tests/rest-api-tests.dockerfile, validator/Dockerfile, validator/Dockerfile-installed-bionic, validator/Dockerfile-installed-xenial, validator/setup.py, validator/tests/validator-tests.dockerfile
=> Update core for combined python-sdk/signing package

docker/grafana/sawtooth-stats-grafana
=> Upgrade Grafana docker image to to 6.0.0

BUILD.md
Signed-off-by: Jason <j_walker@cargill.com>
`build.md`
- add links for navigating
- add tips/notes on transient build errors
=> Clean up links and add learnings from walking the doc

validator/sawtooth_validator/gossip/structure_verifier.py
Opening this to rebase https://github.com/hyperledger/sawtooth-core/pull/1949
=> Verify that dependencies are not empty strings

validator/sawtooth_validator/journal/genesis.py, validator/sawtooth_validator/server/core.py, validator/src/journal/block_manager.rs, validator/src/journal/block_manager_ffi.rs, validator/src/journal/chain.rs, validator/src/journal/publisher.rs, validator/tests/test_genesis/tests.py
Implements BlockRef type which is used for Ref-C and Ref-D, but not
Ref-B.
=> Fix block manager ref counting

ci/sawtooth-build-docs, docs/Makefile
=> Xetex pdf 1 1

perf/smallbank_workload/src/main.rs, validator/src/journal/block_manager.rs
=> Fix line-wrapping due to new rustfmt

docs/source/app_developers_guide/intro_xo_transaction_family.rst
=> Fix links and terminology in Playing XO tutorial

docker/compose/sawtooth-default-pbft.yaml
=> Add compose file for 5 node pbft network

docs/source/cli/sawadm.rst, docs/source/sysadmin_guide/configure_sgx.rst, docs/source/sysadmin_guide/configuring_sawtooth/path_configuration_file.rst, docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst, docs/source/sysadmin_guide/log_configuration.rst
=> Docs: Fix broken+inconsistent note/important code

docker/compose/sawtooth-default-pbft.yaml
=> Add missing key in pbft compose file

docker/kubernetes/pbft-keys-configmap.yaml, docker/kubernetes/sawtooth-create-pbft-keys.yaml, docker/kubernetes/sawtooth-kubernetes-default-pbft.yaml
=> Add kubernetes files for 5 node pbft network

docker/sawtooth-shell
=> Add missing dependency to local shell dockerfile

ci/nightly/sawtooth-shell, ci/sawtooth-shell
This reverts commit c16e4933a905d3a6e315f7b5f198063f4dedc265.
=> Revert "Remove PoET cli from published docker images"

docker-compose-installed.yaml
Add devmode to docker-compose-installed networks
=> Add devmode to docker compose installed

validator/sawtooth_validator/state/settings_view.py
Fixes a leak where SettingsViews were never being garbage collected.
This was caused by a SettingsView's LRU cache entries for the
get_settings method containing a reference to self; this meant that even
when a SettingsView was no longer referenced externally, it would still
not be garbage collected because it internally referenced itself.
A new function decorator, `memoized_method`, is used for the
`SettingsView.get_settings` method. This decorator wraps the `lru_cache`
decorator and uses a weak reference to allow garbage collecting the
settings view. This decorator can be used to memoize any instance
method.
=> Fix SettingsView leak caused by LRU cache usage

validator/sawtooth_validator/gossip/permission_verifier.py, validator/sawtooth_validator/journal/responder.py
Add log guards to avoid repeated messages while waiting for a genesis block. Namely in:
* PermissionVerifier
* Gossip Block Responder
=> A log guards to avoid repeated message

validator/sawtooth_validator/gossip/signature_verifier.py, validator/sawtooth_validator/networking/future.py
Additionally, fix a typo in the signature verification handler.
=> Fix concurrent modifications of futures collection

validator/sawtooth_validator/state/settings_view.py
Backport of #2104
Fixes a leak where SettingsViews were never being garbage collected.
This was caused by a SettingsViews' LRU cache entries for the
get_settings method containing a reference to self; this meant that even
when a SettingsView was no longer referenced externally, it would still
not be garbage collected because it internally referenced itself.
A new function decorator, `memoized_method`, is used for the
`SettingsView.get_settings` method. This decorator wraps the `lru_cache`
decorator and uses a weak reference to allow garbage collecting the
settings view. This decorator can be used to memoize any instance
method.
=> 1-1 BACKPORT: Fix SettingsView leak caused by LRU cache usage

validator/src/journal/publisher.rs
Backport of #2107
Updates the way the block publisher accepts batches and adds them to its pending queue:
Don't add a batch to the candidate block if the batch was already in the pending queue
Don't add a batch to the pending queue if the batch is already committed
Don't notify batch observers unless the batch is new (not already committed, not already in the pending queue)
=> 1-1 BACKPORT: Publisher batch appending

validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/state/settings_cache.py, validator/tests/test_setting_cache/tests.py
Couple small fixes to make the settings cache more performant.
=> Settings cache performance enhancements

validator/sawtooth_validator/gossip/permission_verifier.py, validator/src/gossip/permission_verifier.rs, validator/src/journal/block_validator.rs, validator/tests/test_journal/mock.py, validator/tests/test_permission_verifier/tests.py
Couple small fixes to make the settings cache more performant.
=> Identity cache performance enhancements

docker/kubernetes/sawtooth-kubernetes-default-pbft.yaml, docker/kubernetes/sawtooth-kubernetes-default-poet.yaml, docker/kubernetes/sawtooth-kubernetes-default.yaml
We want to use the user key here.
=> Use user keys for genesis and proposal in Kubernetes files

Jenkinsfile
=> Update branch checks in Jenkinsfile to 1-2

ci/sawtooth-build-docs
Upstream bug report here
https://github.com/sphinx-doc/sphinx/issues/6440
=> Pin Sphinx to 2.0.1 to workaround bug in 2.1.0 1-1

families/block_info/sawtooth_block_info/Cargo.toml, families/identity/sawtooth_identity/Cargo.toml, families/settings/sawtooth_settings/Cargo.toml
=> Replace rust-crypto fork with rust-crypto-wasm 0.3

Jenkinsfile
This change will cause Jenkins to trigger a build every day.
=> Update the cron branch check

docs/source/_includes/create-genesis-block.inc, docs/source/sysadmin_guide/about_dynamic_consensus.rst, docs/source/sysadmin_guide/setting_allowed_txns.rst
=> Update docs for 1.0 pbft algorithm version - 1-2 backport

ci/nightly/sawtooth-intkey-workload, ci/nightly/sawtooth-smallbank-workload, ci/sawtooth-intkey-workload, ci/sawtooth-smallbank-workload
These changes were merged into chime in PR https://github.com/hyperledger/sawtooth-core/pull/2181
=> Improve workload docker images

families/identity/sawtooth_identity/Cargo.toml
=> Add description to identity tp Cargo.toml

validator/sawtooth_validator/journal/block_store.py
Addresses 2 problems with the original routing via get_data_by_id:
- Raise expected exception types
- Treat block number as u64 type throughout
Signed-off-by: JAG-UK <jon.geater@gmail.com>
=> Fix retrieval of blocks by number in python block_store

CODEOWNERS, MAINTAINERS.md
Since these changes have already been approved by the current list of maintainer, this PR only requires 2 approvals.
=> 1-2 Backport Maintainer updates

families/identity/sawtooth_identity/Cargo.toml
=> 1-2 Backport: Add description to identity tp Cargo.toml

ci/ns-control
=> Add sawtooth-identity-tp to sawtooth meta package

perf/smallbank_workload/Cargo.toml
Old description
Description: [generated from Rust crate sawtooth-smallbank-workload]
New description
Description: Workload generator for Sawtooth Smallbank
=> Backport 1-2: Add description to smallbank workload Cargo.toml

docs/source/sysadmin_guide/off_chain_settings.rst
=> Update ZMQ key generation example to use python3

docs/source/sysadmin_guide/off_chain_settings.rst
=> 1-2 Backport: Update ZMQ key generation example to use python3

docker/compose/sawtooth-default-pbft.yaml, docker/kubernetes/sawtooth-kubernetes-default-pbft.yaml
This is a backport of pr #2180 to 1-2
=> Update pbft settings 1 2 backport

perf/intkey_workload/Cargo.toml
=> Add description to intkey workload Cargo.toml

families/block_info/sawtooth_block_info/Cargo.toml
=> Add description to block info Cargo.toml

validator/sawtooth_validator/execution/processor_handlers.py, validator/sawtooth_validator/server/component_handlers.py, validator/sawtooth_validator/server/state_verifier.py
=> 1-2 backport:  Return ACK before sending process requests 

families/block_info/sawtooth_block_info/Cargo.toml
=> 1-2 Backport: Add description to block info Cargo.toml

docker/compose/copy-debs.yaml
=> Archive sawtooth-smallbank-tp-rust artifacts in Jenkins

docker/kubernetes/sawtooth-kubernetes-default-pbft.yaml, docs/source/app_developers_guide/kubernetes_test_network.rst
=> 1-2 BACKPORT: Update example kube file to use rust smallbank tp

docker/kubernetes/sawtooth-kubernetes-default-pbft.yaml, docs/source/app_developers_guide/kubernetes_test_network.rst
=> Update example kube file to use rust smallbank tp

validator/sawtooth_validator/networking/interconnect.py
Using all_tasks to cancel tasks is dangerous, as it can result in a concurrent modification of the list of tasks.  The prescribed approach is to collect the tasks that may be cancelled in a list, and iterate over those tasks when cancelling.  This will avoid cancelling the cancel task itself (and other shutdown tasks).
=> Collect futures for explicit cancellation

cli/sawtooth_cli/rest_client.py
Signed-off-by: Alexander Zhovnuvaty <a.zhovnuvaty@gmail.com>
=> Add default adapter for CLI and handle an error when it is invalid

adm/Cargo.toml, adm/Dockerfile-installed-bionic, adm/Dockerfile-installed-xenial
Signed-off-by: Kirill Vusik <kirillvusik@coherentsolutions.com>
=> Improve sawadm package name and metadata

validator/sawtooth_validator/consensus/handlers.py, validator/sawtooth_validator/consensus/proxy.py, validator/sawtooth_validator/journal/block_wrapper.py, validator/sawtooth_validator/journal/chain.py, validator/sawtooth_validator/networking/interconnect.py, validator/src/journal/block_wrapper.rs, validator/src/journal/block_wrapper_ffi.rs, validator/src/journal/chain.rs, validator/src/journal/chain_ffi.rs
This PR is a backport of #2229 and #2232
=> 1-2 Backport: block validation updates and future collection

validator/sawtooth_validator/journal/completer.py, validator/sawtooth_validator/server/core.py, validator/tests/test_completer/test.py
=> 1-2 Backport: Use chain controller get_chain_head in completer

docker/lint
=> Pin pylint at 2.3.1 in 1-1

cli/sawtooth_cli/batch.py, cli/sawtooth_cli/block.py, cli/sawtooth_cli/identity.py, cli/sawtooth_cli/state.py, cli/sawtooth_cli/transaction.py, cli/tests/test_config.py, integration/sawtooth_integration/tests/test_ipv6.py, integration/sawtooth_integration/tests/test_peer_list.py, integration/sawtooth_integration/tests/test_two_families.py, perf/smallbank_workload/src/smallbank_transformer.rs, validator/sawtooth_validator/consensus/proxy.py, validator/sawtooth_validator/execution/context_manager.py, validator/sawtooth_validator/execution/scheduler_parallel.py, validator/sawtooth_validator/gossip/gossip.py, validator/sawtooth_validator/journal/consensus/genesis/genesis_consensus.py, validator/sawtooth_validator/journal/genesis.py, validator/sawtooth_validator/state/client_handlers.py, validator/src/journal/block_store.rs, validator/src/journal/chain_commit_state.rs, validator/src/state/merkle.rs, validator/src/state/settings_view.rs, validator/tests/test_context_manager/tests.py, validator/tests/test_merkle_trie/tests.py, validator/tests/test_receipt_store/tests.py, validator/tests/test_state_view/tests.py
=> Fix lint issues

docker/lint, perf/smallbank_workload/src/smallbank_transformer.rs, validator/src/journal/block_store.rs, validator/src/journal/chain_commit_state.rs, validator/src/state/merkle.rs, validator/src/state/settings_view.rs
=> Pin pylint at 2.3.1 in 1-2

validator/sawtooth_validator/networking/handlers.py, validator/sawtooth_validator/networking/interconnect.py, validator/sawtooth_validator/server/component_handlers.py, validator/sawtooth_validator/server/core.py, validator/sawtooth_validator/server/network_handlers.py, validator/sawtooth_validator/server/state_verifier.py, validator/tests/test_authorization_handlers/test.py
=> 1.2 Backport: Enable heartbeats for all zmq connections

validator/src/database/error.rs, validator/src/execution/execution_platform.rs, validator/src/execution/py_executor.rs, validator/src/journal/block_manager.rs, validator/src/journal/block_manager_ffi.rs, validator/src/journal/block_store.rs, validator/src/journal/block_validator.rs, validator/src/journal/candidate_block.rs, validator/src/journal/chain.rs, validator/src/journal/chain_ffi.rs, validator/src/journal/commit_store.rs, validator/src/journal/publisher.rs, validator/src/journal/publisher_ffi.rs, validator/src/state/error.rs, validator/src/state/identity_view.rs, validator/src/state/merkle.rs, validator/src/state/mod.rs, validator/src/state/settings_view.rs, validator/src/state/state_view_factory.rs
This diff was created by running 'cargo fix'.
=> Fix Rust compiler warnings in validator

validator/src/database/lmdb.rs, validator/src/database/lmdb_ffi.rs, validator/src/journal/block_manager.rs, validator/src/journal/block_scheduler.rs, validator/src/journal/block_store.rs, validator/src/journal/block_validator.rs, validator/src/journal/block_validator_ffi.rs, validator/src/journal/block_wrapper.rs, validator/src/journal/chain.rs, validator/src/journal/chain_commit_state.rs, validator/src/journal/chain_ffi.rs, validator/src/journal/fork_cache.rs, validator/src/journal/publisher.rs, validator/src/lib.rs, validator/src/pylogger.rs, validator/src/scheduler/mod.rs, validator/src/state/error.rs, validator/src/state/identity_view.rs, validator/src/state/merkle.rs, validator/src/state/settings_view.rs, validator/src/state/state_view_ffi.rs
Crate-level visibility assists finding/removing unused code and should help resolve various clippy errors as well.
=> Change visibility of modules to crate-level

docker/compose/sawtooth-default.yaml
This PR closes https://jira.hyperledger.org/browse/STL-273
http://localhost:8009/
=> Add Swagger-UI

docker/compose/sawtooth-local.yaml
Related PR: https://github.com/hyperledger/sawtooth-core/pull/2276
=> Add Swagger-UI to sawtooth-local.yaml

docker/lint, docker/sawtooth-dev-go, families/smallbank/smallbank_go/Dockerfile-installed, sdk/examples/intkey_go/Dockerfile-installed, sdk/examples/noop_go/Dockerfile-installed, sdk/examples/xo_go/Dockerfile-installed
https://github.com/golang/go/issues/34689
=> Update go 1.11 to fix build issue with dependency 1-1

RELEASE_NOTES.md
=> Add release notes for 1.2.4 and 1.2.3

libsawtooth/RELEASE_NOTES.md
=> Add release notes for libsawtooth v0.3

libsawtooth/Cargo.toml
=> Increment libsawtooth Cargo.toml to version 0.3.0

docs/source/architecture/injecting_batches_block_validation_rules.rst, docs/source/architecture/permissioning_requirement.rst
Signed-off-by: Hans Jin <hans_jin@126.com>
=> Fix terminology: injecting transactions into blocks-> batches

adm/build.rs, adm/src/config.rs, families/block_info/sawtooth_block_info/build.rs, families/identity/sawtooth_identity/build.rs, families/settings/sawtooth_settings/build.rs, families/smallbank/smallbank_rust/build.rs, justfile, libsawtooth/src/lib.rs, perf/sawtooth_perf/src/batch_gen.rs, perf/sawtooth_perf/src/batch_submit.rs, perf/sawtooth_perf/src/source.rs, perf/sawtooth_perf/src/workload.rs, perf/smallbank_workload/build.rs, perf/smallbank_workload/src/main.rs, perf/smallbank_workload/src/playlist.rs, validator/build.rs, validator/src/journal/block_manager.rs, validator/src/journal/block_validator.rs, validator/src/journal/candidate_block.rs, validator/src/journal/chain.rs, validator/src/journal/chain_ffi.rs, validator/src/journal/publisher.rs, validator/src/scheduler/py_scheduler.rs, validator/src/state/error.rs
Doesn't pass 'just lint' yet, but getting closer.
=> More linting cleanup

RELEASE_NOTES.md
=> Add release notes for 1.2.5

Jenkinsfile, bin/authorize-cicd, docs/source/architecture/poet.rst
Revise PoET doc text and Jenkins scripts to use inclusive terminology. I believe this captures all issues in sawtooth-core. I will copy the Jenkins commit to the other repos after review.
=> Inclusive terminology

families/battleship/Cargo.toml, families/block_info/sawtooth_block_info/Cargo.toml, families/block_info/sawtooth_block_info/src/lib.rs, families/block_info/sawtooth_block_info/src/main.rs, families/identity/sawtooth_identity/Cargo.toml, families/identity/sawtooth_identity/src/lib.rs, families/identity/sawtooth_identity/src/main.rs, families/settings/sawtooth_settings/Cargo.toml, families/settings/sawtooth_settings/src/lib.rs, families/settings/sawtooth_settings/src/main.rs, families/smallbank/smallbank_rust/Cargo.toml, families/smallbank/smallbank_rust/src/lib.rs, families/smallbank/smallbank_rust/src/main.rs
Updates the smart contracts to have a lib file/library crate so that they may be used externally which is necessary for integrating Transact.
=> Update contracts to include library crate

ci/nightly/sawtooth-block-info-tp, ci/nightly/sawtooth-identity-tp, ci/nightly/sawtooth-intkey-workload, ci/nightly/sawtooth-rest-api, ci/nightly/sawtooth-settings-tp, ci/nightly/sawtooth-shell, ci/nightly/sawtooth-smallbank-tp-rust, ci/nightly/sawtooth-smallbank-workload, ci/nightly/sawtooth-validator
=> 1-3 :Update ci/nightly dockerfiles to use droptarget nightly

adm/Cargo.toml, adm/src/blockstore.rs, adm/src/commands/blockstore.rs, adm/src/commands/genesis.rs, adm/src/commands/keygen.rs, adm/src/database/lmdb.rs, adm/src/wrappers.rs
Signed-off-by: Isabel Tomb <tomb@bitwise.io>
=> Update all adm code to Rust edition 2018

RELEASE_NOTES.md
=> Add release notes for 1.2.6

validator/Cargo.toml
=> Update cylinder dep to 0.2

docs/source/community/contributing.rst
Add a bullet point about the whitelist and how to get added to it.
=> Add info about the authlist check in contributing

validator/src/server/cli.rs
- Respect minimum-peer-connectivity value: Fixes [STL-1709](https://jira.hyperledger.org/browse/STL-1709)
- Rename args for consistency
=> Fix for minimum-peer-connectivity and arg consistency changes

validator/src/server/cli.rs
Signed-off-by: Will Ryan <will.ryan@gluwa.com>
=> Backport 1-3: Rename args for consistency and respect min peers value

validator/src/server/cli.rs
Signed-off-by: Will Ryan <will.ryan@gluwa.com>
=> Backport 1-2: Rename args for consistency and respect min peers value

validator/src/state/merkle_ffi.rs
This change removes the use of `MerkleLeafIterator` as the type of the iterator, as this is an implementation detail not specified in the contract for the `MerkleRadixTree::leaves` function.  The return value is a dynamic boxed iterator.
=> Remove explicit use of MerkleLeafIterator

adm/src/commands/batch.rs, adm/src/main.rs
Signed-off-by: Chris Eckhardt <eckhardt@bitwise.io>
=> Add batch show subcommand to sawadm CLI

adm/src/commands/batch.rs, adm/src/main.rs
Signed-off-by: Chris Eckhardt <eckhardt@bitwise.io>
=> Add batch status subcommand to sawadm CLI

CODE_OF_CONDUCT.md
Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
=> Add default CODE_OF_CONDUCT

validator/sawtooth_validator/journal/back_pressure_handlers.py
This change replaces the use of whitelist with "allowlist" where appropriate.
=> Replace whitelist with allowlist

.github/workflows/build.yml
This action uses just to lint, build, and unit test the rust code.
=> Add just-based github build action

families/battleship/src/game.rs, perf/sawtooth_perf/src/workload.rs, perf/smallbank_workload/src/playlist.rs, perf/smallbank_workload/src/smallbank_transformer.rs, validator/src/journal/block_manager.rs, validator/src/journal/block_wrapper.rs, validator/src/metrics/mod.rs, validator/src/permissions/state_source.rs, validator/src/state/merkle.rs
Originally worked through in [#2458](https://github.com/hyperledger/sawtooth-core/pull/2458), but since we're seeing so many test failures there now, this attempts to clear up some of the noise when building PRs.
=> Fix compiler and clippy errors

.github/workflows/build.yml, adm/src/blockstore.rs, adm/src/database/lmdb.rs, justfile
The expectation is that this will pass the build github action.
=> Fix GitHub actions pythonpath and disable broken adm lmdb tests
