journal/consensus/poet/poet_enclave_simulator/wait_timer.cpp

On OS X (at least 10.11) <random> needs to be included to successfully
run setup.py build.

fix os x build

---

sawtooth/cli.py
sawtooth/client.py
tests/test_ledger_web_client.py

#10
This pr implements "sawtooth block list|show [--url URL]"
The command '''#sawtooth block list''' lists the committed block IDs
The command '''#sawtooth block show blockID''' shows the contents of the block 

Extend the sawtooth CLI to support for listing blocks

---

setup.py

```sawtooth-validator``` requires ```requests``` 
It is installed by ```sawtooth-dev-tools``` but was not included in the ```install_requires``` of ```setup.py```

add requests to install_requires

---

extensions/mktplace/setup.py
tools/bootstrap.d/30-python-lib-install.sh
tools/requirements-testing.txt
validator/setup.py

Merge the different places where Python dependencies are specified
into one (DRY) place. This should make it easier to maintain the list
since there is only one place where they are specified.
The different Sawtooth packages should now correctly specify their own dependencies
which means that with this patch using ```pip install -e .``` or ```python setup.py
develop``` should also work correctly.
For example using the following ```requirements.txt``` placed in ```sawtooth-core``` as ```requirements-dev-venv.txt```:
```
-e core/
-e validator/
-e extensions/mktplace
-e extensions/arcade
```
Sawtooth will install in a virtualenv on OSX.
```
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements-dev-venv.txt
```
Passing the tests
```
$ cd core
$ nose2
... …
```

install_requires as the one place for requirements

---

extensions/mktplace/mktplace/transactions/account_update.py
extensions/mktplace/mktplace/transactions/asset_type_update.py
extensions/mktplace/mktplace/transactions/asset_update.py
extensions/mktplace/mktplace/transactions/exchange_offer_update.py
extensions/mktplace/mktplace/transactions/holding_update.py
extensions/mktplace/mktplace/transactions/liability_update.py
extensions/mktplace/mktplace/transactions/market_place_object_update.py
extensions/mktplace/mktplace/transactions/participant_update.py
extensions/mktplace/mktplace/transactions/sell_offer_update.py

[Here](https://github.com/hyperledger/sawtooth-core/blob/master/extensions/mktplace/mktplace/transactions/market_place_object_update.py#L120) checks that names must be unique, but when transactions apply, the store don't bind name to the transaction identifier,  this is a bug. This PR fixes this bug.

Fix the bug of marketplace name must be unique

---

extensions/mktplace/mktmain/client_cli.py

Everytime we invoke [client_cli.main()](https://github.com/hyperledger/sawtooth-core/blob/master/extensions/mktplace/tests/integration/test_all_transactions.py#L65), Logger().addHandler(clog) [here](https://github.com/hyperledger/sawtooth-core/blob/master/extensions/mktplace/mktmain/client_cli.py#L1532), too many handlers are added. So test_transactions_reg() throws two replicated warnings,  test_transactions_unr() throws three replicated warnings etc. This PR fixes the bug.

Fix too many replicated warnings are throwed

---

extensions/mktplace/mktplace/mktplace_client.py
extensions/mktplace/mktplace/mktplace_state.py
extensions/mktplace/mktplace/transactions/account_update.py
extensions/mktplace/mktplace/transactions/participant_update.py

As #19 has been merged, [is_valid_name()](https://github.com/hyperledger/sawtooth-core/blob/master/extensions/mktplace/mktplace/transactions/market_place_object_update.py#L120) checks to see if this name already exists, [apply()](https://github.com/hyperledger/sawtooth-core/blob/master/extensions/mktplace/mktplace/transactions/market_place_object_update.py#L157) updates the name map etc. So _register() and __unregister() are useless, remove them.

Remove _register and _unRegister function

---

validator/tests/integration/test_web_api.py
validator/txnserver/web_pages/forward_page.py
validator/txnserver/web_pages/prevalidation_page.py

if [error response](https://github.com/hyperledger/sawtooth-core/blob/master/validator/txnserver/web_pages/base_page.py#L164) or [another error response](https://github.com/hyperledger/sawtooth-core/blob/master/validator/txnserver/web_pages/base_page.py#L171) returned, we need to return these messages immediately. And I add an integration test.

Fix the bug of posting unknown message

---

core/sawtooth/client.py
extensions/bond/libor/libor_client.py
extensions/bond/sawtooth_bond/updates/libor.py
extensions/bond/tests/test_libor_txn_family.py
extensions/mktplace/mktplace/mktplace_client.py
validator/gossip/signed_object.py
validator/tests/unit/test_journal_transactions.py
validator/tests/unit/test_message_packet.py
validator/tests/unit/test_signed_object.py

The style of most of keys in minfo is camel case, I think we'd better maintain consistent style.

Maintain consistent style

---

validator/gossip/message.py
validator/gossip/signed_object.py
validator/tests/unit/test_signed_object.py

I think [signingkey](https://github.com/hyperledger/sawtooth-core/blob/master/validator/gossip/signed_object.py#L117) and [SignatureKey](https://github.com/hyperledger/sawtooth-core/blob/master/validator/gossip/signed_object.py#L128) here isn't really a signing key, it is just the name of the key related to the signature. I renamed them to avoid confusing and fixed the wrong case in test_signed_object.

Rename signingkey and SignatureKey

---

bin/run_lint

Print linted files from missed module  when using 'run_lint -n' command

Print more linted files when using 'run_lint -n' command

---

bin/run_tests

Usage:
./bin/run_tests [-m Module]
Options:
-h          print usage and exit
-m Module   only run tests of module, <core, validator, mktplace, bond, arcade>

Add module option in run_tests

---

validator/journal/journal_core.py

The removed logger info is duplicate of [here](https://github.com/hyperledger/sawtooth-core/blob/master/validator/journal/journal_core.py#L747)

Remove duplicate logger info messages

---

integration/sawtooth_integration/docker/intkey-smoke.yaml
integration/sawtooth_integration/docker/xo-smoke.yaml
rest_api/sawtooth_rest_api/routes.py
sdk/python/sawtooth_sdk/client/stream.py

The depends_on portion of the transaction processor service
definition is necessary because they reference a service
with a particular container that the docker dns gives
an address.
The sleeps on integration_test service is necessary until we have a way to get the rest_api status of if the validator is ready. ~~The other sleeps are necessary for unknown reasons that hopefully will be solved in my work this sprint, but if not we should figure out why they are necessary.~~ The socket id was not being set correctly in the python sdk. It was classname-pid which was not guaranteed to be unique in docker.

Fix failing smoke tests

---

bin/protogen
core_transactions/config/protos/config.proto
core_transactions/config/sawtooth_config/processor/handler.py
core_transactions/config/tests/sawtooth_config_test/config_message_factory.py
docs/source/transaction_family_specifications/config_transaction_family.rst
protos/setting.proto
validator/sawtooth_validator/state/config_view.py
validator/sawtooth_validator/state/state_view.py
validator/tests/unit3/test_config_view/__init__.py
validator/tests/unit3/test_config_view/tests.py
validator/tests/unit3/test_state_view/__init__.py
validator/tests/unit3/test_state_view/tests.py

**Add StateView and its Factory**
StateViewFactory provides read-only views into state stored in a merkle tree database. These views can provide a window into the state which can be used throughout a block of processing without concern of the state being changed underneath the process.
**Add ConfigView and its Factory**
ConfigView is a specialized StateView which translates keys into state addresses and transforms state entries into their respective values. This can be used by validator components to read on-chain settings at viewed from the lens of a specific point in the chain.

Add State Views and Config View specialization 

---

Jenkinsfile

This will discard builds older than 31 days from Jenkins.

Add discard builds property to Jenkinsfile

---

validator/sawtooth_validator/exceptions.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py

This implements an authentication handshake and transport encryption using ZMQ's CurveZMQ support (ec based on edwards). The support is implemented in the shared Interconnect object, but is only enabled for the network (validator to validator) instance. In the future, we can also enable this for the intercomponent instance, but that will require changes to 'clients'.

Implement CurveZMQ security for the network

---

cli/sawtooth_cli/block.py
cli/sawtooth_cli/main.py
cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/state.py
integration/sawtooth_integration/tests/test_intkey_smoke.py
protos/client.proto
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/routes.py
sdk/examples/sawtooth_xo/xo_client.py
validator/sawtooth_validator/journal/block_store_adapter.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py

* Add `head` parameter to all endpoints
- Specificies a block id, which will be treated as the chain head
- Update response envelope to include `head` and `link`
* Update state routes to bring in line with spec
- No more fetching or specifying merkle root
- `head` can be used to specify a particular tree instead
- Without `head`, routes default to most recent tree
* Update Rest Api error handling as needed to implement changes
* Refactor ClientHandlers to handle genesis changes, and make
future refactors easier
* Update xo and inkey smoke tests to use new `/state`

Add head parameter, update /state endpoint

---

cli/sawtooth_cli/admin.py
cli/sawtooth_cli/admin_command/genesis.py
cli/tests/test_genesis.py
tools/guest-files/local-env.sh
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py

The data directory changes from `<USER_HOME>` to either `<SAWTOOTH_HOME>/data`, if the `SAWTOOTH_HOME` environment variable is set, or `/var/lib/sawtooth` as the default.
This is made available to `admin genesis` and available for use in all future admin commands.
Additionally:
- `Validator` takes `data_dir` as an argument, and it provided the above by the cli
- Updates unit tests and adds a test for defaulting to the data dir

Change Data Dir from USER_HOME

---

validator/tests/unit3/test_client_request_handlers/__init__.py
validator/tests/unit3/test_client_request_handlers/mocks.py
validator/tests/unit3/test_client_request_handlers/tests.py

Make test doctrings much more comprehensive, also add a handful of
additional asserts to make tests somewhat more robust.

Expand ClientRequestHandler unit test doctrings

---

protos/processor.proto
protos/validator.proto
sdk/python/sawtooth_processor_test/message_types.py
sdk/python/sawtooth_processor_test/tester.py
sdk/python/sawtooth_sdk/client/exceptions.py
sdk/python/sawtooth_sdk/client/future.py
sdk/python/sawtooth_sdk/client/stream.py
sdk/python/sawtooth_sdk/processor/core.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/processor_handlers.py
validator/sawtooth_validator/execution/processor_iterator.py
validator/sawtooth_validator/server/core.py

After this, python transaction processors can stop (if allowed to do so gracefully (1 keyboardinterrupt)) even during load. The tps can also recover after validator shutdown, even during load. The validator still needs at least 2 keyboard interrupts to stop it.
The protos are updated, so if seeking to test it, run protogen.

Sequence independent validator-transaction processor shutdown, restart

---

cli/sawtooth_cli/admin.py
cli/sawtooth_cli/admin_command/genesis.py
cli/sawtooth_cli/admin_command/keygen.py
cli/sawtooth_cli/admin_command/utils.py
cli/tests/test_genesis.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_genesis/tests.py

This adds the `admin keygen` subcommand, which produces a key file in the validator's `keys` directory.
The validator loads the key and passes it to the `GenesisController`, for use when signing the genesis block.
This key will most likely, be used by journal, as well, to sign blocks, after #98 is merged.

Generate Validator Signing Key and Use for Genesis Block

---

cli/sawtooth_cli/cluster.py

Removed expected column from custer status and
refactored status command to simplify based
on current functionality.

Remove expected column from cluster status

---

core_transactions/config/tests/sawtooth_config_test/tp-config.yaml
docker/sawtooth-tp_config
docker/sawtooth-tp_intkey_python
docker/sawtooth-tp_xo_python
integration/sawtooth_integration/docker/intkey-smoke.yaml
integration/sawtooth_integration/docker/tp-intkey-python.yaml
integration/sawtooth_integration/docker/tp-xo-python.yaml
integration/sawtooth_integration/docker/xo-smoke.yaml
manage/sawtooth_manage/docker.py
poet/sawtooth_poet/tests/validator_registry_test/tp_validator_registry.yaml
poet/sawtooth_poet/validator_registry/processor/main.py
rest_api/sawtooth_rest_api/rest_api.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/load.py
sdk/examples/intkey_python/sawtooth_intkey/processor/main.py
sdk/examples/sawtooth_xo/processor/main.py
sdk/python/sawtooth_sdk/client/stream.py

The fix was disabling the monitor socket right after it receives a disconnect event and disconnecting but not closing the external socket on validator disconnect. After this, the validator can stop and restart with no ill effects on the transaction processor.
Also, the hard-coded "tcp://" is removed from the Stream python class as we might want to support other transport protocols. Then main modules used in bins are updated to specify tcp, as well as docker files and the docker manage library.

Bug fix for transaction processors maxing cpu on validator disconnect

---

rest_api/sawtooth_rest_api/routes.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/load.py
sdk/python/sawtooth_sdk/client/stream.py

Previously it was possible to restart the rest api without restarting the validator. Then it was possible to restart the validator without restarting the rest api, but not while the rest api was waiting for a response from the validator. This PR makes it possible to restart the validator while the rest api is waiting for a response. It will return a 503 Service Unavailable. 
This PR also fixes similar behavior in the intkey load cli, where if the validator stopped before returning responses to all messages an uncaught error would happen. This PR catches that error and logs a message.

Rest api restart

---

bin/run_tests
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
rest_api/tests/unit_rest_api.yaml

Add the infrastructure for unit testing the Rest Api within `run_tests`, including a simplified mock validator that responds to ZMQ requests with mock data.
Add tests for both `/blocks`, and `/state`, the routes that are currently up to spec.
Also add small fixups to the rest api, adding a timeout option, and taking advantage of aiohttp's recently fixed `match_info` property (no more weird hacks to get a `+`!).

Add unit tests for Rest Api

---

validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/publisher.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_journal/block_tree_manager.py
validator/tests/unit3/test_journal/tests.py

Journal and its subcomponents use this key, in place of the temporary key, to
sign blocks, similar to the GenesisController.
Additionally:
- Add doc string to Journal and BlockPublisher constructors
- whitespace cleanup

Pass Identity Key to Journal

---

validator/sawtooth_validator/exceptions.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/consensus/consensus_factory.py
validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/publisher.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_genesis/tests.py
validator/tests/unit3/test_journal/block_tree_manager.py
validator/tests/unit3/test_journal/mock_consensus.py
validator/tests/unit3/test_journal/tests.py

During genesis block construction, the consensus module can be loaded based on the settings supplied by the sawtooth_config transaction family.  The module is then used to correctly initialize and finalize the block before committing it to the block store.
The consensus module is also before it is used during Journal's processing of blocks.

Determine and use Consensus Module using On-chain Settings 

---

validator/sawtooth_validator/consensus/poet1/poet_enclave_simulator/enclave_wait_certificate.py
validator/sawtooth_validator/consensus/poet1/poet_enclave_simulator/poet_enclave_simulator.py
validator/sawtooth_validator/consensus/poet1/poet_transaction_block.py
validator/sawtooth_validator/consensus/poet1/signup_info.py
validator/sawtooth_validator/consensus/poet1/wait_certificate.py
validator/sawtooth_validator/consensus/poet1/wait_timer.py
validator/tests/unit/poet1/test_enclave_wait_certificate.py
validator/tests/unit/poet1/test_wait_certificate.py

Remove keyword arguments when calling into PoET enclave.
Renamed block_digest to block_hash everywhere to stay consistent with enclave.
Passing enclave wait timer object when creating wait certificate.
Fixed struct unpacking in PoET simulator that didn't work on Windows (but inexplicably worked on Linux).
Fix identifier property in wait certificate work across enclaves.
Force encoded PoET public key to string.
Fixed bug in wait timer duration creation.

Update to work with PoET1

---

protos/network.proto
protos/validator.proto
validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/chain_id_manager.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/responder.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_genesis/tests.py
validator/tests/unit3/test_journal/tests.py

The best way to test that this works (since we do not have network tests yet) is the following. You will see one validator create the genesis block. When you start loading transaction the non-genesis validator will not process any blocks and will send out a GossipBlockRequest message. Once it recives the genesis block, you will see it start processing batches. Currently, for this to work the validators need to be peered in both directions and they will continue to send batches back and forth forever. 
In terminal:
sawtooth admin genesis
validator -vv --peers tcp://0.0.0.0:8801
In new terminal:
validator --network-endpoint tcp://0.0.0.0:8801 --component-endpoint tcp://0.0.0.0:40001 --peers tcp://0.0.0.0:8800 -vv
In new terminal:
tp_intkey_python tcp://localhost:40000 -vv
In new terminal: …

Add block and batch request messages

---

cli/sawtooth_cli/block.py

Since block ids have grown from 88 to 128 characters, update the
block list CLI command to avoid truncating them.

Fix block ids being truncated with sawtooth block list

---

validator/sawtooth_validator/networking/dispatch.py
validator/sawtooth_validator/networking/interconnect.py
validator/tests/unit3/test_dispatcher/tests.py

This changes the Dispatcher's single send_message to a dict indexed by connection identifier, and sets up new message dispatch on the receiving side (messages sent from ROUTER -> DEALER which are not responses).

Add bidirectional message dispatch and respond on receiving connection

---

validator/sawtooth_validator/journal/consensus/poet1/poet_enclave_simulator/enclave_wait_certificate.py
validator/sawtooth_validator/journal/consensus/poet1/poet_enclave_simulator/poet_enclave_simulator.py
validator/sawtooth_validator/journal/consensus/poet1/poet_transaction_block.py
validator/sawtooth_validator/journal/consensus/poet1/signup_info.py
validator/sawtooth_validator/journal/consensus/poet1/wait_certificate.py
validator/sawtooth_validator/journal/consensus/poet1/wait_timer.py
validator/tests/unit3/test_poet1/test_enclave_wait_certificate.py
validator/tests/unit3/test_poet1/test_wait_certificate.py

Changes include:
* Rename wait certificate block_digest to block_hash to make everything consistent with PoET enclave
* Remove keyword arguments when calling into PoET enclave as apparently SWIGged C++ code does not like it
* Correctly provide enclave wait timer to PoET enclave when trying to create a wait certificate

Bringing in Fixes to PoET1 code before major re-implementation occurs

---

validator/sawtooth_validator/journal/block_store.py

Fix get_block_by_batch_id to properly return a block.
Previously, iterating over a BlockStore instance would throw an
error, and calling `len` on one would return the total number of
indexed keys (including `"chain_head_id"`), which is not especially
meaningful. Fix these to now more correctly throw `NotImplementedError`s.

Fix BlockStore: get_block_by_batch_id, __iter__, __len__

---

docs/source/_templates/indexcontent.html

Added bond family guide to the indexcontent.html file.
Causes bond family guide to appear in main frame upon
loading docs.

Minor doc fix for bond family guide

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/gossip/gossip_handlers.py
validator/sawtooth_validator/server/core.py

This adds an identity registration mechanism to gossip and broadcasts out to connected identities on the router socket.

Manage gossip identities and broadcast to ROUTER connected peers

---

protos/client.proto
protos/validator.proto
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/mocks.py
validator/tests/unit3/test_client_request_handlers/tests.py

Makes it possible to query for the status of a batch by id from either API. Batches can have one of three statuses:
• `COMMITTED` - batch was found in block chain
• `PENDING` - batch found in batch cache, but not in chain
• `REJECTED` - batch not found
Also includes unit tests for the new requests to both APIs

Add requests for batch status to REST and ZMQ APIs

---

.gitignore
sdk/javascript/client/deferred.js
sdk/javascript/client/stream.js
sdk/javascript/package.json
sdk/javascript/processor/exceptions.js
sdk/javascript/processor/index.js
sdk/javascript/protobuf/index.js
sdk/javascript/spec/client/deferred_test.js
tools/package_groups/ubuntu-16.04-deps

The Javascript client can handle disconnects from the server, and reconnects, as well as handles SIGTERM by sending the Unregister event before shutting down.
Additionally, updates the Debian package for ZMQ from `libzmq-dev` to `libzmq3-dev`.  This is needed  as the former is version 2.x, which is missing the monitor feature, and the later is (currently) 4.x, which has it. The monitor feature is required for handling validator disconnects.

JS SDK: Handle disconnects and SIGTERM

---

extensions/bond/ui/client/src/main/sawtooth/http.cljs
extensions/mktplace/navigator/client/src/main/sawtooth/http.cljs

Not sending the correct charset name for UTF-8 causes an error (which only seems to occur on some pathways through express)

Send correct charset name for UTF-8

---

protos/client.proto
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
validator/sawtooth_validator/gossip/signature_verifier.py

Update the `POST /batches` REST API endpoint to match the OpenAPI spec.
Includes:
- Add `link` to response envelope with appropriate `/batch_status` url
- Send back `400` when invalid batches are submitted
- Unit tests for `POST /batches`

Update POST /batches to match spec

---

cli/sawtooth_cli/config.py
cli/sawtooth_cli/rest_client.py

Adds the subcommand `propose` under the `sawtooth config` command tree.
This command submits proposals to the validator, in order to change the
on-chain configuration settings of a running validator (and therefore
validator network).

Add "propose" sawtooth config command

---

poet/sawtooth_poet/validator_registry/processor/handler.py
validator/sawtooth_validator/journal/consensus/poet/poet_enclave_simulator/poet_enclave_simulator.py
validator/tests/unit3/test_poet/test_wait_certificate.py
validator/tests/unit3/test_poet/test_wait_timer.py

Changes include:
* Updated PoET simulator to no longer encode/decode private/public keys as the signing module uses string representing WIF/hex encodings for keys, respectively.
* Updated validator registry transaction processor accordingly to match PoET simulator.
* Re-enabled some unit tests for wait timer and certificate as they are not dependent upon final integration of new PoET consensus into the new architecture.

Fix PoET simulator based upon canonical key representation in signing module

---

bin/run_tests
poet/sawtooth_poet/validator_registry/state/__init__.py
poet/sawtooth_poet/validator_registry/state/validator_registry_view.py
poet/tests/unit3/test_validator_registry_view/__init__.py
poet/tests/unit3/test_validator_registry_view/mocks.py
poet/tests/unit3/test_validator_registry_view/tests.py
poet/tests/unit3/test_validator_registry_view/utils.py
poet/tests/unit_poet.yaml

The ValidatorRegistryView provides access to the validator registry's
on-chain information about validators stored within a particular state view.
This access is read-only.
Additionally, added unit tests for poet code, which get run by CI

Add ValidatorRegistryView for registry info

---

protos/validator.proto
validator/sawtooth_validator/gossip/gossip_handlers.py
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py

This moves GOSSIP_PING and GOSSIP_ACK to lower level NETWORK
message types, moves the PingHandler from the gossip package to
the networking package, and implements heartbeat pings over
connections on the ZMQ ROUTER socket.

Implement heartbeat ping on inbound connections

---

bin/protogen

In order to build validator registry transactions in the PoET consensus block publisher, it needs the resulting protobuf Python for the validator registry transaction to be in the same directory as all other protobuf resulting files used by the validator.

Add validator protobuf output directory for validator registry protobuf result

---

validator/sawtooth_validator/journal/publisher.py

The publisher should be using the chain head when building a new block instead of the chain head's previous block.

Change publisher so that when building a block it uses the current chain head to create the state view

---

validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/publisher.py

Consensus block publishers should be able to assume that the signer public key is set in the block header provided to its initialize_block() method.

Ensure that the block header signer public key is set before handing to consensus block publisher

---

docker/sawtooth-base
tools/conf-defaults.sh
tools/plugins/install_cryptography.sh

To bring PoET simulator in line with SGX implementation, we need the PyCA package to be present.

Add installation of Python cryptography package and its dependencies to vagrant/docker

---

docs/source/sysadmin_guide/packaging_sles.rst
docs/source/sysadmin_guide/packaging_ubuntu.rst
docs/source/tutorial.rst

URLs pointed to old intelledger github org. Updated them to point to hyperledger.

fix git clone url in docs

---

cli/sawtooth_cli/config.py
cli/tests/test_config.py
rest_api/sawtooth_rest_api/routes.py

The sawtooth config subcommands are rearranged into meaningful subgroups,`proposal` and `settings`.
The `proposal` subcommand group, is made up of the `create` subcommand. This takes the place of the `set` and `propose` commands by combining them into one operation, which either records a file or submits the settings to the validator.
The `settings` subcommand group is made up (currently) of the `list` subcommand. This command displays the list of current on-chain settings, read from a validator's REST api.  The settings may be outputed as key/value text (the default), CSV, JSON or YAML.
Additionally:
- Corrects an issue with the rest api not returning empty fields from protobuf objects.

Rearrange Setting Subcommands and add `settings list`

---

protos/client.proto
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
validator/sawtooth_validator/gossip/signature_verifier.py
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/mocks.py
validator/tests/unit3/test_client_request_handlers/tests.py

Add the capability to specify that requests for batch status, or submissions of new batches, should wait to return until all the batches have been committed to the blockchain, or a timeout has expired.
This covers both the REST and ZMQ APIs, and adds unit tests for all new capabilities.

Add wait-for-commit to batch status requests and batch submits

---

rest_api/sawtooth_rest_api/routes.py

With `including_default_value_fields` set to `True` in the `MessageToDict` function, `batch_statuses` will always come back with a value, even if not set.

Fix POST /batches sometimes using wrong status

---

validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/processor_handlers.py
validator/sawtooth_validator/execution/processor_iterator.py
validator/sawtooth_validator/execution/tp_state_handlers.py
validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/gossip/gossip_handlers.py
validator/sawtooth_validator/gossip/signature_verifier.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/journal/responder.py
validator/sawtooth_validator/networking/dispatch.py
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_dispatcher/mock.py
validator/tests/unit3/test_dispatcher/tests.py

This includes replacing keeping track of both outgoing and incoming connections separately and consolidates them into one dictionary owned by interconnect. This allows gossip handlers to know nothing about the type of connection that it is broadcasting to. 
Also fixes the problem with peered validators rebroadcasting the same messages over and over again.

Add connection collection to Interconnect and stop Rebroadcasting to originally sender

---

validator/sawtooth_validator/journal/publisher.py

Disable BlockPublisher speculative building on published blocks prior to

---

cli/sawtooth_cli/config.py
cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/state.py
core_transactions/config/sawtooth_config/processor/handler.py

Add a `sawtooth config proposals` subcommand to list the currently pending proposals, when a validator is in "Ballot" mode for setting application.
Additionally:
* Allow for differentiation of return values by status.
* Only check approval_threshold > 1

Add CLI tool to list Pending Proposals 

---

poet/sawtooth_poet/tests/validator_registry_test/tests.py
poet/sawtooth_poet/tests/validator_registry_test/ts_validator_registry.py
poet/sawtooth_poet/tests/validator_registry_test/validator_reg_message_factory.py
poet/sawtooth_poet/validator_registry/processor/handler.py
validator/sawtooth_validator/journal/consensus/poet/poet_enclave_simulator/poet_enclave_simulator.py

Update brings both PoET simulator and validator registry transaction processor closer to IAS:
* Uses same method (RSA-SHA256) to sign attestation verification report
* Adds fields to attestation verification report and proof data to bring into alignment with response from IAS.
* Updates validator registry transaction processor unit tests for new signing and fields
Note - the enclave report body in the simulated attestation report has not been updated yet to mimic the sgx_quote_t structure used by the real IAS report.  That is a PR to follow later once the sgx_structs Python module is available to this repo.

NML 2127 - Update PoET simulator and validator registry transaction processor to match IAS

---

cli/tests/test_admin_keygen.py

Test written for command 'sawtooth admin keygen'.
Tests for valid key as output of keygen, and
test of --force option working to overwrite
existing key files.

Add test for CLI keygen command

---

cli/tests/test_admin_keygen.py

Fix conflict caused by test_admin_keygen test
The test_admin_keygen test caused a test failure, due
to the fact that a utility had been moved after the
PR was submitted.
Test now uses new utility get_key_dir instead
of ensure_directory.

Fix conflict new cli test

---

cli/sawtooth_cli/batch.py
cli/sawtooth_cli/block.py
cli/sawtooth_cli/main.py
cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/state.py
cli/sawtooth_cli/tty.py
protos/client.proto
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/mocks.py
validator/tests/unit3/test_client_request_handlers/tests.py

End-to-end solution for batch fetching. Includes:
- `batch list` and `batch show` commands for the Sawtooth CLI
- `GET /batches` and `GET /batches/{batch_id}` routes for the REST API
- `ClientBatchList` and `ClientBatchGet` messages for the ZMQ API
- Unit tests for REST and ZMQ APIs
- Major refactor to `client_handlers.py` to be more straightforward, better documented
- Various minor bug fixes and cleanup

Add capability for clients to request batches

---

cli/sawtooth_cli/config.py
core_transactions/config/protos/config.proto
core_transactions/config/sawtooth_config/processor/handler.py
core_transactions/config/tests/sawtooth_config_test/test_config.py

Add the CLI subcommand to submit a vote for an outstanding proposal. The vote is guarded against double voting, and against missing proposals.  A vote is submitted to a validator, where it is tallied by the transaction family
Additionally:
- Reject setting proposal vote ties
- Correct typos
- code cleanup

Add CLI subcommand `config proposal vote`

---

protos/client.proto
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/mock_stream.py
rest_api/tests/unit/test_rest_api.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/tests.py

Add an id filter parameter to the `GET /batches` and `GET /blocks` endpoints in the REST API. Allows you to fetch multiple resource by specifying arbitrary ids.
Use this parameter to update the response envelope to a `POST /batches`, so that when all batches are committed, a `/batches` link is sent, rather than a `/batch_status` link.

Add id filter parameter to /batches and /blocks, update POST

---

.gitignore
bin/poet
bin/run_lint
bin/run_tests
consensus/poet/cli/sawtooth_poet_cli/config.py
consensus/poet/cli/sawtooth_poet_cli/exceptions.py
consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/cli/sawtooth_poet_cli/main.py
consensus/poet/cli/tests/test_genesis/__init__.py
consensus/poet/cli/tests/test_genesis/tests.py
consensus/poet/cli/tests/unit_cli.yaml

Add a cli tool for creating genesis transactions, required to bootstrap the use of the PoET consensus module.  During the process to create a Validator Registry transaction, signup data is retrieved from the PoET enclave (either via the simulator or an actual SGX enclave), and stored in a well-known location (namely `<data dir>/poet_signup_data`).  This data will be used by the consensus module when it is first initialized in the validator.
Additionally:
- Clean up some git ignore needs

Add PoET genesis CLI tool

---

bin/run_tests
consensus/poet/common/sawtooth_poet_common/sgx_structs/__init__.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_attributes.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_basename.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_cpu_svn.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_key_id.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_measurement.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_quote.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_report.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_report_body.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_report_data.py
consensus/poet/common/sawtooth_poet_common/sgx_structs/_sgx_struct.py
consensus/poet/common/tests/test_sgx_structs/__init__.py
consensus/poet/common/tests/test_sgx_structs/tests.py
consensus/poet/common/tests/test_sgx_structs/unit_sgx_structs.yaml
consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_validator_registry/tests.py
consensus/poet/families/tests/test_validator_registry/validator_reg_message_factory.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py

Updates the PoET simulator and validator registry transaction processor:
* Python wrapper classes created for supporting the enlcave quote and embedded structures found in IAS attestation verification report. Classes support serializing/deserializing between Python objects and binary layout of corresponding C/C++ structs.
* Simulator uses SGX structs wrapper to create enclave quote layout the same as used by SGX enclave implementation
* Simulator and validator registry transaction processor verify enclave quote in attestation verification report in the same was as SGX enclave implementation
* Validator registry transaction processor unit tests updated for new enclave quote layout

Nml 2127 - Update PoET simulator and Validator Registry Transaction Processor to Support Enclave Quote Structure

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/common/tests/test_validator_registry_view/tests.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/families/sawtooth_validator_registry/protos/validator_registry.proto
consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_validator_registry/tests.py
consensus/poet/families/tests/test_validator_registry/validator_reg_message_factory.py
docs/source/transaction_family_specifications/validator_registry_transaction_family.rst
sdk/python/sawtooth_processor_test/message_factory.py
validator/sawtooth_validator/journal/block_store.py

Update the testing framework to allow for consistent transaction.header_signatures. 
Remove block_num from ValidatorRegistryPayload.
Fix small typo in the block store.

Replace block_num with transaction_id in ValidatorInfo.

---

Jenkinsfile
bin/build_ext_debs
bin/install_packaging_deps
docker/sawtooth-build-debs
tools/plugins/build_and_install_debs.sh

The easiest way to test this locally is to do:
```
$ cd sawtooth-core
$ docker build . -f docker/sawtooth-build-debs -t sawtooth-build-debs
$ docker run -v $(pwd):/project/sawtooth-core sawtooth-build-debs
```
This should work from any environment with access to a docker-engine.
On success, you should see all the debs in sawtooth-core/build/debs:
```
libsecp256k1-0_0.1~20161228-1_amd64.deb
libsecp256k1-dev_0.1~20161228-1_amd64.deb
python3-aiohttp_1.3.5-1_amd64.deb
python3-async-timeout_1.2.0-1_all.deb
python3-bitcoin_1.1.42-1_all.deb
python3-chardet_2.3.0-1_all.deb
python3-cryptography-vectors_1.7.2-1_all.deb
python3-cryptography_1.7.2-1_amd64.deb
python3-grpcio-tools_1.1.3-1_amd64.deb
python3-grpcio_1.1.3-1_amd64.deb
python3-multidict_2.1.4-1_amd64.deb
python3-protobuf_3.2.0-1_all.deb …
```

Add crypto deb

---

cli/sawtooth_cli/main.py
cli/sawtooth_cli/submit.py

CLI command 'sawtooth submit' command created.
Uses rest api.
Submits batches from file, such as intkey or
config batches.

CLI submit command

---

bin/build_intkey_javascript
bin/build_javascript_sdk
protos/state_context.proto
sdk/java/src/main/java/sawtooth/sdk/client/State.java
sdk/javascript/client/state.js
sdk/javascript/protobuf/index.js
sdk/python/sawtooth_sdk/processor/state.py
validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/execution/tp_state_handlers.py

When the context_manager returns an AuthorizationException, TpStateGetResponse and TpStateSetResponse will set have the status of AUTHORIZATION_ERROR. The sdk's version of state should then throw an InvalidTransactionError. 
Also add a missing logging statement in context manager and missing step when building javascript.

Return Authorization Error status to Transaction Processor

---

bin/run_docker_test
bin/run_tests
docker/sawtooth-build-python
docker/sawtooth-rest_api
docker/sawtooth-test
integration/sawtooth_integration/docker/intkey-smoke.yaml
integration/sawtooth_integration/docker/shutdown-smoke.yaml
integration/sawtooth_integration/docker/xo-smoke.yaml
integration/sawtooth_integration/tests/test_shutdown_smoke.py
tools/plugins/install_aiohttp.sh
validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/processor_iterator.py
validator/sawtooth_validator/execution/scheduler.py
validator/sawtooth_validator/execution/scheduler_serial.py
validator/sawtooth_validator/networking/future.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_context_manager/tests.py
validator/tests/unit3/test_journal/mock.py
validator/tests/unit3/test_scheduler/tests.py

After this PR a validator will be able to gracefully shutdown with one SIGINT or SIGTERM if given time, from a resting state. This doesn't handle shutdown under load, as that still isn't always graceful.
The run_docker_test script is modified for not stopping until the test container exits, so that other containers can exit which should be orchestrated by the test container.

Graceful validator shutdown

---

validator/sawtooth_validator/execution/scheduler_serial.py
validator/tests/unit3/test_scheduler/tests.py

The serial scheduler marks the schedule as complete when it recieves
responses, not when its queue is empty.  If the queue size is used to
determine comleteness, the schedule is marked as complete before a
transaction processor has replied with a result - this results in
genesis batch processing failing.

Mark the schedule as complete on set response

---

validator/sawtooth_validator/execution/executor.py

The TypeError on invalid keyword argument wasn't displayed due to
running in a threadpool.

Fix incorrect keyword argument

---

sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload.py
sdk/python/sawtooth_sdk/processor/core.py
sdk/python/sawtooth_sdk/workload/workload_generator.py

Logs if the wrong type of message is received by the transaction processor or if we do not have a handler to deal with the header family, encoding, and version. 

Add graceful error handling when finding handlers in TP

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/wait_timer.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/consensus/consensus.py
validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/unit3/test_devmode_consensus/tests.py
validator/tests/unit3/test_journal/mock_consensus.py

This update changes the consensus module interface for BlockPublisher, BlockVerifier, and ForkResolver to take a state view factory object on creation instead of a state view object.  It allows them to be able to create an arbitrary state view based upon that state root hash of any block in the store.

Updated consensus module interfaces

---

validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py

BlockWrapper.block_header is actually BlockWrapper._block_header. Should use BlockWrapper.header instead. Also need to encode signer_pubkey and header_signature before hashing. (Issues found while running a two node network with devmode)

Fix Devmode ForkResolver issues

---

protos/client.proto
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/base_case.py
validator/tests/unit3/test_client_request_handlers/test_batch_handlers.py
validator/tests/unit3/test_client_request_handlers/test_block_handlers.py
validator/tests/unit3/test_client_request_handlers/test_state_handlers.py

Allows clients to send in a `PagingControls` object with their "List" requests, which allow using either ids or indexes to navigate variably sized pages of results.
Sends back a `PagingResponse` object with the information needed to construct further PagingControl queries.

Add paging controls and responses to client list request handlers

---

Jenkinsfile
bin/run_bandit
docker/sawtooth-build-python
tools/bootstrap.d/30-python-lib-install.sh

Installs bandit in vagrant and sawtooth-build-python.
Turns on security linting through bandit for python code. Only reports
security issues of severity MEDIUM or higher. Does not fail the build
yet, because there are issues that need fixing first.

Add security report to pipeline (won't fail build)

---

cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/submit.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/routes.py
rest_api/tests/unit/test_rest_api.py

If `--wait` is set on `sawtooth submit`, the CLI will waits for commit before printing the timestamp. If the Api times out before the batches commit, it will print a table with the batch ids and their statuses.

Add --wait flag to sawtooth cli submit command

---

tools/Vagrantfile

Fixes a bug with vagrant 1.9.3 on Windows

Set host_ip in Vagrantfile to 127.0.0.1

---

validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/consensus/consensus_factory.py
validator/sawtooth_validator/journal/consensus/genesis/__init__.py
validator/sawtooth_validator/journal/consensus/genesis/genesis_consensus.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/unit3/test_genesis_consensus/__init__.py
validator/tests/unit3/test_genesis_consensus/tests.py

Add a consensus module for handling consensus of genesis blocks only. These blocks have no state associated with them, and therefore have no special information needed during block publishing or validation.
Add block id to the consensus selection to facilitate the defaults at the boundaries of the genesis block and genesis+1 blocks. In the case of the `NULL_BLOCK_IDENTIFIER`, the genesis consensus is the default. After that, `devmode` is the default.

Add Genesis Consensus Module

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py

This updates the PoET consensus module so that if it encounters a block not created by a PoET consensus module, it will stop walking back the block chain.

Update the PoET consensus module so that it stops on non-PoET block

---

bin/run_docker_test
integration/sawtooth_integration/docker/shutdown-smoke.yaml
integration/sawtooth_integration/tests/test_shutdown_smoke.py

This reverts the changes to run_docker_test that were made in a prior pr. Also rewrites shutdown-smoke to not require containers to be named.

Fix shutdown smoke

---

validator/sawtooth_validator/journal/publisher.py

While the publisher is waiting for the last block to be committed,
the publisher was throwing away batches that have dependencies
present in that block. This adds the batches in the block to the
committed_txn_cache so when the dependencies are checked the
soon to be comitted batches are accounted for.

Fix Dropping batches that have satisfied dependencies

---

validator/sawtooth_validator/journal/publisher.py

The publisher should not call `check_claim_block()` if the consensus module returns False from `initialize_block()`.  `Publisher._build_block()` is now returning `None` in this case so that it doesn't think that it has a block it should try to claim.

Stop publisher from calling check_claim_block() if initialize_block() returns False

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
validator/sawtooth_validator/journal/block_wrapper.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py
validator/sawtooth_validator/journal/publisher.py
validator/sawtooth_validator/state/state_view.py

* Added member and static methods to the `BlockWrapper` class to make it a little easier for code to get the state view associated with a particular block.
* Updated `StateViewFactory.create_view` to default the state hash to `None` if not provided and also to return the default Merkle database is the state root hash is `None`.  This hopefully will alleviate some of the code from having to know about/use `INIT_ROOT_KEY`

Make it a little easier to get state view for corresponding block

---

bin/run_tests

While we are debugging the problem with fork resolution when using the PoET consensus module, the PoET smoke test will be temporarily disabled to allow PRs to build cleanly.  Once the PoET consensus module is fixed, this test will be re-enabled.

Temporarily disable PoET smoke test during run_tests

---

docs/source/sawtooth_developers_guide.rst
docs/source/sawtooth_developers_guide/intkey_workload.rst

Documentation on 'intkey workload' added to
developer's guide. This replaced the article on the
simulator from version 0.7 of Sawtooth Lake.

Tutorial on intkey workload generator

---

Jenkinsfile
sdk/examples/intkey_java/IntegerKeyHandler.java
sdk/java/pom.xml
sdk/java/src/main/java/sawtooth/sdk/client/Future.java
sdk/java/src/main/java/sawtooth/sdk/client/FutureByteString.java
sdk/java/src/main/java/sawtooth/sdk/client/FutureError.java
sdk/java/src/main/java/sawtooth/sdk/client/SendReceiveThread.java
sdk/java/src/main/java/sawtooth/sdk/client/State.java
sdk/java/src/main/java/sawtooth/sdk/client/Stream.java
sdk/java/src/main/java/sawtooth/sdk/processor/TransactionProcessor.java
sdk/java/src/main/java/sawtooth/sdk/processor/exceptions/ValidatorConnectionError.java

TransactionProcessor should do the following:
On TP shutdown: TransactionProcessor will finish handling messages and send an unregister request. Finally shutdown.
On ValidatorShutdown: Set any futures to FutureError (which will throw ValidatorConnectionError if accessed) and try to reregister all handlers.
Also some include some fixups to the java sdk, add multiple handler functionally with find_handler, and added timeout to futures.

Update to Java TransactionProcessor to shutdown gracefully. 

---

cli/sawtooth_cli/batch.py
cli/sawtooth_cli/block.py
cli/sawtooth_cli/state.py

Used argparse formatter_class.RawDescriptionHelpFormatter
to cause epilogs for cli commands with epilogs to display
properly. The epilogs are formatted correctly and should not
wrap.

Fix CLI epilogs to diplay properly

---

cli/sawtooth_cli/cluster.py
manage/sawtooth_manage/docker.py
manage/sawtooth_manage/subproc.py

The cluster start command (sawtooth cluster start) now starts one instance of the 
rest_api. 
Added to both docker and subprocess.

Add rest_api startup to cluster command

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/cli/tests/test_genesis/tests.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state_store.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_consensus_state_store.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/publisher.py

This PR:
* Creates PoET consensus state class to manage per-block consensus state
* Creates PoET consensus state store for managing consensus stat objects, mapping a block ID to the consensus state at that point in time
* Updates the PoET block verifier to create consensus state for a block if it successfully verifies it
* Updates the PoET genesis tool to persist the sealed signup data in the consensus store at a well-known location
* Updates the PoET block publisher to look in the consensus store for sealed signup data so that it can give it to the PoET enclave

Create PoET consensus state store

---

validator/sawtooth_validator/server/core.py

Preserve the LMDB files for the merkle tree and the block store across
restarts of the validator.  Prior to this commit, these databases were
in use, and persisting to disk, but being deleted at startup time.

Preserve LMDB files

---

validator/sawtooth_validator/journal/chain.py

Updated `ChainController.on_block_validated()` to properly manage the pending blocks queue based upon the result of the block validation.
To test this fix:
1.  In `validator/sawtooth_validator/execution/executor.py` line 230, replace:
`self._executing_threadpool = ThreadPoolExecutor(max_workers=5)`
with
`self._executing_threadpool = ThreadPoolExecutor(max_workers=100)`
2.  In `integration/sawtooth_integration/docker/poet-smoke.yaml`, after the line:
`sawtooth.consensus.algorithm=poet \`
add the following lines:
`sawtooth.poet.target_wait_time=5 \`
`sawtooth.poet.initial_wait_time=0 \`
3.  Run the PoET smoke test:
`cd integration/sawtooth_integration/docker`
`run_docker_test poet-smoke.yaml`
Hopefully test will pass.

Fix chain controller block processing issues

---

rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_submit_requests.py

The python SDK defined futures are not asynchronous, and resolving one's `result` for a single request was blocking the entire Rest Api. Wrap that synchronous call in an asynchronous `Executor` to free up the Rest Api's event loop for other requests.
Also includes a small tweak to Rest Api tests to remove a magic number.

Fix bug where Rest Api was unable to handle concurrent requests

---

bin/run_tests
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/publisher.py

As was obliquely mentioned in hyperledger/sawtooth-core#297 the thread pool in the TransactionExecutor would get exhausted with lower PoET wait times and stop processing. I tested this fix by setting sawtooth.poet.wait_time=2 and sawtooth.poet.initial_wait_time=0 in the poet-smoke.yaml test.

Fix the exhaustion of ThreadPool in TransactionExecutor

---

cli/sawtooth_cli/batch.py
cli/sawtooth_cli/block.py
cli/sawtooth_cli/format_utils.py
cli/sawtooth_cli/main.py
cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/state.py
cli/sawtooth_cli/transaction.py
cli/sawtooth_cli/tty.py
protos/client.proto
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_txn_requests.py
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/test_batch_handlers.py
validator/tests/unit3/test_client_request_handlers/test_block_handlers.py
validator/tests/unit3/test_client_request_handlers/test_txn_handlers.py

- Add `get_transaction` method to block store and refactors some error handling
- Add transaction client handlers to validator with unit tests
- Add `/transactions` route to Rest Api, with unit tests
- Refactor similar CLI commands to use new `format_utils` module with common formatting logic
- Add `transaction list` and `transaction show` commands to CLI
- Correct some typos

Add transaction fetching to Rest Api, ZMQ Api, and CLI

---

docs/source/tutorial.rst

Validator now requires parameter --public-uri to
start.

Update tutorial for validator required parameter

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/cli/tests/test_genesis/tests.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_config_view.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_key_state_store.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_consensus_state_store.py
consensus/poet/core/tests/test_consensus/test_poet_config_view.py
consensus/poet/core/tests/test_consensus/test_poet_key_state_store.py

Introduces the following changes:
* PoET consensus state statistics are now reset whenever a non-PoET block is encountered in the chain and the sealed signup data is removed from the consensus state as that needs to be maintained on a per-PoET public key basis.
* A utility class to manage and persist locally on a validator key state for its PoET key.  This includes the sealed signup data associated with it as well as whether or not it has been refreshed because the block claim limit has been reached with that key.
* The PoET genesis CLI and block publisher have been changed to use the PoET key state store for sealed signup data.
* A utility class to query PoET configuration settings.
* The PoET block verifier now enforces the key block claim limit when determining the validity of a block. …

Enforce and abide by PoET key block claim limit

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_config_view.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_consensus_state_store.py
consensus/poet/core/tests/test_consensus/test_poet_config_view.py

Per the PoET specification, whenever a validator adds or updates signup information to the validator registry, it is not allowed to claim a block until some number of blocks after the block in which its validator registry information was committed.  This PR:
* Updates the PoET configuration view to contain the configurable block claim delay value.
* Updates the consensus state to keep track of the total number of blocks claimed.  Note that it is not sufficient to simply rely upon a block's number as PoET consensus state statistics, etc., are reset whenever a non-PoET block is encountered.
* Updates the PoET utils to accurately keep track of the total block claim count.
* Updates the per-validator state to keep track of the block number in which a validator's current PoET public key …

Enforce and abide by PoET block claim delay

---

integration/sawtooth_integration/docker/config-smoke.yaml
integration/sawtooth_integration/tests/test_config_smoke.py

As part of NML-2202, create an integration test for
CLI config tool. This test is not yet complete, but
does test the ability of the tool to submit a sample
transaction to the config TP, and to list the results.
Compares resulting listing to original input.

Create tests for config CLI tool - integration test

---

integration/sawtooth_integration/docker/poet-smoke.yaml
manage/sawtooth_manage/docker.py
validator/sawtooth_validator/server/cli.py

This change allows multiple --peers and --join arguments and allows comma-delimited (but not space delimited) params provided to a single instance of the argument.

Change --peers and --join from argparse nargs='+' to append style arguments

---

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_config_view.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_consensus_state_store.py
consensus/poet/core/tests/test_consensus/test_poet_config_view.py

Per the PoET specification, validators are limited in how frequently they may claim blocks - i.e., the zTest.  If it is determined that allowing a validator to win an election (i.e., claim a block and have it added to the blockchain) would cause it to claim blocks more frequently than a configurable statistical rate, the block is rejected.
This PR updates:
* adds a fixed duration block count property to the PoET configuration view.  This value indicates the number of blocks which will have their local mean computed by using a simple ratio of target to initial wait times.  These blocks are not considered when performing the zTest.
* updates the PoET enclave factory to use the new PoET configuration view's fixed duration block count property.
* refactors existing PoET policy tests (key …

Enforce and abide by PoET block claim frequency policy (zTest)

---

validator/sawtooth_validator/journal/chain.py
validator/tests/unit3/test_journal/block_tree_manager.py
validator/tests/unit3/test_journal/mock.py
validator/tests/unit3/test_journal/tests.py

Enforce the value of the block chain id (found in the data dir) by
dropping a received genesis block if it does not match.

Drop genesis block if not block-chain-id

---

cli/sawtooth_cli/cluster.py

Error message output by 'sawtooth cluster start" when
a processor is not specified has been made more
specific, explaining where to find the processors
that come with Sawtooth Lake, etc.

sawtooth cluster start error message

---

bin/run_tests
integration/sawtooth_integration/docker/config-smoke.yaml

Fixed config smoke test to account for PR #326
which changes arguments to validator.
Also added --host argument to rest_api container.

Fixed config smoke test

---

cli/sawtooth_cli/cluster.py
manage/sawtooth_manage/subproc.py

Cluster command now stores only essential info in state file.
Other info is calculated or provided by the node controllers.
Docker and subprocess are the current node controller types.

Make sawtooth cluster command less dependent on state file

---

validator/sawtooth_validator/execution/scheduler_serial.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/unit3/test_journal/block_tree_manager.py
validator/tests/unit3/test_journal/mock.py
validator/tests/unit3/test_journal/tests.py

This PR contains 3 changes:
1) refactor the block publisher to move all of the logic managing a candidate block out of the BlockPublisher into a helper class. This also changed the policy for checking transaction dependencies to be done only in the context of a Candidate block that is being built. 
2) Update the block publisher to have a batch limit per block, to allow for block sizes to be controlled. 
3) Checks for duplicate transactions in batches. Look in the current chain and CandidateBlock to make sure that any transaction in a batch added has not been previously committed to the chain.

Nml 2165 - Add rate batch limit to block publisher. 

---

rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_submit_requests.py
rest_api/tests/unit/test_txn_requests.py
sdk/python/sawtooth_sdk/workload/workload_generator.py
validator/sawtooth_validator/state/client_handlers.py

Previously the Rest Api sent back errors which were simple text strings. New errors are a JSON envelope with an `"error"` property that is an object with three properties:
- `"code"`: A fixed integer code specific to the error
- `"title"`: A short headline describing the error
- `"message"`: A longer human readable description of what broke
Included in this PR:
- Overhaul in design of Api Errors and Error Traps to facilitate readable definitions
- Existing errors expanded and refactored with codes, titles, and messages
- Route handlers updated to support new errors
- Existing unit tests updated to check for new errors
- New bad header error to handle malformed resource headers from the validator
- Specs/documentation updated
- Small validator bug fix

Overhaul Rest Api error handling

---

validator/sawtooth_validator/journal/responder.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_responder/__init__.py
validator/tests/unit3/test_responder/mock.py
validator/tests/unit3/test_responder/tests.py

The Responder will keep track of received requests that it could not fulfill. When it receives a response to the broadcasted request message, it will send the message back to the  originally requester. This is done using a TimedCache to store the requests, and two new handlers.
For example:
A broadcasts a  request to B
B cannot fulfill the request so B broadcast the request to C
C can fulfill the request and send a Response to B
B receives the response and sends it to A 
This PR also adds Responder unit tests for the above expected behavior.

Add Routed Batch and Block Response Handling to the Responder

---

validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/scheduler.py
validator/sawtooth_validator/execution/scheduler_serial.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/unit3/test_context_manager/tests.py
validator/tests/unit3/test_scheduler/tests.py

The constructor to the SerialScheduler is changed in this PR, to accept the optional keyword argument always_persist, which can be used in genesis block construction to write the state change to the underlying database no matter what the resulting merkle hash is. When always_persist is False, the only time the state change is written to the underlying database is when the merkle root provided on the block boundary in add_batch equals the computed merkle root from the state changes.

Only write to state on genesis and block validation

---

validator/sawtooth_validator/execution/context_manager.py
validator/tests/unit3/test_context_manager/tests.py

Before, if there were no updates in the contexts being squash, a state_root_hash of None would be returned causing possible valid batches (No "InvalidTransactionErrors") to be found as invalid. This is a proposed fix for handling no-op transactions, assuming that we wish to allow such transactions. A consequence of this would be possible creation of "no-op" blocks, or a block that does not include a state change. As such that block would have the same state_root_hash as the previous block. 

Update squash to return current state_root if there are no updates.

---

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_config_view.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/sawtooth_poet/poet_consensus/utils.py
consensus/poet/core/sawtooth_poet/poet_consensus/wait_certificate.py
consensus/poet/core/sawtooth_poet/poet_consensus/wait_timer.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_consensus_state_store.py
consensus/poet/core/tests/test_consensus/test_poet_config_view.py
consensus/poet/core/tests/test_consensus/test_wait_certificate.py
consensus/poet/core/tests/test_consensus/test_wait_timer.py

This _should_ be the last big PoET-related PR (fingers crossed).  It completes the transition from the 0-7-based architecture/implementation to the new 0-8 architecture.  This PR:
* adds the remaining generic PoET configuration settings (target wait time, et al) to the PoET configuration view, updates the PoET configuration view to cache values so it doesn't have to re-fetch them (as the state view is read-only and they cannot change for the particular instantiation of the PoET configuration view), and adds unit tests for checking them
* removes the `sawtooth.poet.fixed_duration_count` setting as it is redundant because of `sawtooth.poet.population_estimate_sample_size` and also brings code closer to spec (spec does not define a separate fixed duration count and instead has defined the …

Compute Local Mean in Consensus State and More Refactoring Goodness

---

docs/source/app_developers_guide/getting_started.rst
tools/Vagrantfile

Update of Vagrant file and tutorial. 
Tutorial explains how to set env variables used by proxy.
Vagrant file does not notify about proxyconf unless http_proxy 
or https_proxy are set.

Update of Vagrant file and tutorial for proxy 

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_config_view.py
consensus/poet/core/sawtooth_poet/poet_consensus/signup_info.py
consensus/poet/core/tests/test_consensus/test_consensus_state.py
consensus/poet/core/tests/test_consensus/test_poet_config_view.py
consensus/poet/core/tests/test_consensus/test_signup_info.py
consensus/poet/core/tests/test_consensus/test_wait_certificate.py
consensus/poet/core/tests/test_consensus/test_wait_timer.py
consensus/poet/families/sawtooth_validator_registry/protos/validator_registry.proto
consensus/poet/families/sawtooth_validator_registry/validator_reg_message_factory.py
consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_tp_validator_registry.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py

This update adds an additional test in the PoET block verifier and publisher to check that the signup information for the validator was committed to the blockchain within a small number of blocks of it being created.  Specifically, when a validator generates its signup information it includes in the information a nonce, which is the block ID of the current head chain.  When validating the signup information is "fresh" other validators will look at the nonce and compare it to some number of previous blocks.  The number is configurable, but defaults to a delay of zero, meaning that the validator's signup information must be committed in the block immediately after the block referenced in the nonce.  This test can be relaxed by increasing the allowed delay.
Updates in this PR include:
* Adds …

Implement Validator Signup Recent Block Test Plus Unit Test Goodness

---

ansible/roles/sawtooth-genesis/tasks/main.yaml
ansible/roles/sawtooth-validator/defaults/main.yaml
cli/sawtooth_cli/admin_command/keygen.py
cli/sawtooth_cli/config.py
cli/sawtooth_cli/keygen.py
cli/tests/test_admin_keygen.py
cli/tests/test_config.py
consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/cli/tests/test_genesis/tests.py
core/sawtooth/cli/admin_sub/clean.py
core/sawtooth/cli/submit.py
docs/source/app_developers_guide/getting_started.rst
extensions/arcade/sawtooth_battleship/battleship_cli.py
extensions/arcade/tests/test_battleship.py
integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/tests/test_config_smoke.py
sdk/examples/xo_python/sawtooth_xo/xo_cli.py
validator/sawtooth_validator/server/keys.py

Commands 'sawtooth admin keygen' and 'sawtooth keygen'
updated to produce files with extensions .priv & .pub
instead of .wif & .addr
Files ending in .priv are equivalent to the files that
ended in .wif.

Update keygen artifacts to produce .pub & .priv files

---

validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py

DevMode consensus is updated to, before looking at block header data:
* if the new fork head is not a DevMode block, raises an exception
* if the current fork head is not a DevMode block and is the immediate predecessor to the new fork, it immediately accepts the new fork head as that indicates that consensus mode is changing
* if the current fork head is not a DevMode block and also is not the immediate predecessor to the new fork head, it raises an exception
Easiest way I found to test was manually (fingers crossed these instructions work) in multiple xterms:
Start up a validator:
```
sawtooth admin keygen --force
sawtooth config proposal create -k /home/ubuntu/sawtooth/keys/validator.wif sawtooth.consensus.algorithm=poet -o config.batch
poet genesis -k …
```

Update DevMode consensus to handle non-DevMode blocks.

---

cli/sawtooth_cli/config.py
core_transactions/config/sawtooth_config/config_message_factory.py
core_transactions/config/sawtooth_config/processor/handler.py
core_transactions/config/tests/test_tp_config.py
docs/source/transaction_family_specifications/config_transaction_family.rst
integration/sawtooth_integration/docker/config-smoke.yaml
integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/tests/test_config_smoke.py

Remove the non-ballot or non-voting mode from the sawtooth config transaction family reference implementation.  This change requires that there be at least on public key set in the authorized keys list before any setting can be changed.
The end result is a more secure model for handling configuration changes on-chain.
With the chain in the config transaction family requiring votes by authorized key, this PR introduces a new subcommand for `sawtooth config`: `genesis`.  Genesis provides a simple way to add authorized keys and set the vote threshold for accepting or rejecting a proposal.
Additionally:
- config smoke adds the genesis step
- poet smoke adds the genesis step

Remove non-ballot mode from sawtooth config

---

consensus/poet/core/tests/test_consensus/test_poet_block_verifier.py

Adds unit test to verify proper PoET block verifier behavior when:
- the block is a non-PoET block (i.e., the block header consensus field does not contain a serialized wait certificate)
- the wait certificate is not valid

Create PoET block verifier unit tests for wait certificates.

---

protos/state_delta.proto
validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_store.py
validator/tests/unit3/test_context_manager/tests.py
validator/tests/unit3/test_scheduler/tests.py
validator/tests/unit3/test_state_delta_store/tests.py

Creates a StateDeltaStore, where state changes can be stored.  These deltas are stored when the context manager performs the squash operation _and_ the state updates will be persisted.  
The purpose of storing these deltas is to support State Delta Subscriptions by external processes.

Store State Deltas

---

integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/tests/integration_tools.py
integration/sawtooth_integration/tests/test_config_smoke.py
integration/sawtooth_integration/tests/test_intkey_smoke.py
integration/sawtooth_integration/tests/test_poet_smoke.py
integration/sawtooth_integration/tests/test_two_families.py
integration/sawtooth_integration/tests/test_xo_smoke.py

In the smoke test, there is a periodic failure, based around the timing
in the system.  The rest api may or may not be ready, the validator may
not have a genesis block, and so forth, before the tests run.  This
commit takes the `_wait_for` from the test_config_smoke, and moves it to a
new package, `integration_tools` as `wait_for_status`.  This function
will give the system time to settle out, if needed, before running the
tests.
A convenience method `wait_for_rest_apis` takes a list of `"host:port"`
values and checks the `/blocks` endpoint for 200 responses.

Fix periodic test failure in smoke tests

---

.gitignore
bin/make_templated_docs
docs/Makefile
docs/source/_templates/partials/encoding_your_payload.rst
docs/source/_templates/partials/submitting_to_validator.rst
docs/source/_templates/partials/warning_header
docs/source/_templates/sdk_submit_tutorial.rst
docs/source/_templates/template_config.yaml
docs/source/_templates/txn_submit_tutorial.rst
docs/source/app_developers_guide.rst
docs/source/app_developers_guide/javascript_sdk.rst
docs/source/app_developers_guide/writing_clients.rst
rest_api/sawtooth_rest_api/openapi.yaml
tools/plugins/install_sphinx.sh

Adds a new templating system to doc generation.
- Jinja2 templates can be added to the `docs/source/_templates/` directory, and output targets can be added to `template_config.yaml`.
- The `make` commands will build template targets into regular RST files before rendering them with sphinx.
- Generated files are stored in the `docs/source/_autogen/` directory.
Uses the new templating system to write three similar Transaction submission tutorials for Python, JavaScript, and the JavaScript SDK.

Implement doc templating, and add templated txn making tutorials

---

integration/sawtooth_integration/tests/integration_tools.py
integration/sawtooth_integration/tests/test_poet_smoke.py

This fixes issues with both the assert on failure, and the incorrectly
formatted url for testing the rest api.

Fix poet smoke rest timeouts

---

protos/state_delta.proto
protos/validator.proto
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/unit3/test_state_delta_processor/tests.py

Add the protobuf messages for State Delta Export subscribe and
unsubscribe.  This includes requests and responses, as well as the
message codes for the values.
Adds the `StateDeltaProcessor` to manage subscribers for state deltas.
Introduces a pair of handlers for registering and unregistering the
subscibers.
Subscribers are rejected if their registration request does not have a
block id that is in the current chain.

Delta subscription handlers

---

rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
sdk/examples/intkey_python/sawtooth_intkey/processor/main.py
sdk/examples/xo_python/sawtooth_xo/processor/main.py
sdk/python/sawtooth_sdk/messaging/stream.py

This PR causes the python sdk stream class to not hide errors, and exceptions on connecting to the validator will cause the class to raise an exception on instantiation.

Fix python sdk stream class hiding errors

---

protos/state_delta.proto
protos/validator.proto
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/unit3/test_journal/mock.py
validator/tests/unit3/test_journal/tests.py
validator/tests/unit3/test_state_delta_processor/tests.py

On block commit, the `ChainController` calls out to a `StateDeltaProcessor` instance to publish state changes to its subscribers.

Publish State Change Deltas on Block Commit

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py

Connections that are used for getting candidate peers or an
unsuccessful peer request are removed. Also, send unregister
peer request to peers and disconnect messages to all connection
on validator shutdown.
Update gossip in core to have min and max peer connectivity set to 1:
self._gossip = Gossip(self._network,
public_uri=public_uri,
peering_mode=peering,
initial_join_endpoints=join_list,
initial_peer_endpoints=peer_list,
minimum_peer_connectivity=1,
maximum_peer_connectivity=1,
topology_check_frequency=1)
To test, start up the following validators one at a time (waiting for it to be completely started up) : 
validator -vvv --public-uri tcp://localhost:8800 --peering dynamic
validator --network-endpoint tcp://0.0.0.0:8801 --component-endpoint tcp://0.0.0.0:40001 --join …

Implement Connection Maintenance 

---

sdk/examples/intkey_java/IntegerKeyHandler.java
sdk/examples/intkey_java/pom.xml

This change allows us to encode the intkey state HashMap in
the correct format to work with the python intkey and javascript
intkey examples. Jackson was formatting it to be an indefinite
map instead of a definite map. This caused the state root hash
to be different on validation when running a mixed network.
To test:
build_all
start up a validator and connect both a tp_intkey_python -vv and a tp_intkey_java
run intkey workload
You should see both transaction processors receiving transactions and blocks being build.

Replace jackson-dataformat-cbor with co.nstant.in.cobr in Intkey Java

---

docs/source/architecture/transactions_and_batches.rst

Signed-off-by: VerasNt <d.verasnt@gmail.com>

A typo correction in the notes section. alway -> always

---

integration/sawtooth_integration/tests/test_shutdown_smoke.py

Disable shutdown smoke tests until STL-120 is complete.  These test cause periodic failures due to the shutdown activities not being properly implemented.  While the argument could be made that we should keep things painful, so as to force ourselves to fix it, it makes the PR process (especially with external contributors) particularly painful.
See: https://jira.hyperledger.org/browse/STL-120

Disable shutdown smoke tests

---

integration/sawtooth_integration/docker/config-smoke.yaml
integration/sawtooth_integration/docker/intkey-go-smoke.yaml
integration/sawtooth_integration/docker/intkey-java-smoke.yaml
integration/sawtooth_integration/docker/intkey-javascript-smoke.yaml
integration/sawtooth_integration/docker/intkey-python-smoke.yaml
integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/docker/two_families.yaml
integration/sawtooth_integration/docker/xo-javascript-smoke.yaml
integration/sawtooth_integration/docker/xo-smoke.yaml
rest_api/sawtooth_rest_api/rest_api.py
sdk/python/setup.py

Adds a logger to the REST API, and replaces the existing access logger with an expanded access logger that no longer uses `print` statements.
This PR does not close STL-69 (https://jira.hyperledger.org/browse/STL-69), but establishes the groundwork for a more robust logger which will.

Add proper logger to REST API

---

consensus/poet/cli/sawtooth_poet_cli/config.py
consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_verifier.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_enclave_factory.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/tests/test_consensus/test_poet_block_verifier.py
consensus/poet/core/tests/test_consensus/test_signup_info.py
consensus/poet/core/tests/test_consensus/test_wait_certificate.py
consensus/poet/core/tests/test_consensus/test_wait_timer.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/consensus/consensus.py
validator/sawtooth_validator/journal/consensus/dev_mode/dev_mode_consensus.py
validator/sawtooth_validator/journal/consensus/genesis/genesis_consensus.py
validator/sawtooth_validator/journal/genesis.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/publisher.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py
validator/tests/unit3/test_devmode_consensus/tests.py
validator/tests/unit3/test_genesis/tests.py
validator/tests/unit3/test_genesis_consensus/tests.py
validator/tests/unit3/test_journal/block_tree_manager.py
validator/tests/unit3/test_journal/mock_consensus.py
validator/tests/unit3/test_journal/tests.py

The legacy way in which the PoET enclave simulator determined configuration was by having a dictionary (aka, kwargs) passed in to its initialize function.  This PR replaces the kwargs with the location of the validator's configuration directory.  The enclave should use a `toml` file for any configuration and the file should be found in the configuration directory.
Changes:
* The consensus module block publisher, block verifier, and fork resolver interfaces has been updated to take a configuration directory parameter
* All code that touches these interfaces have been updated
* The PoET enclave simulator has been updated to use the config directory to locate its `toml` file (if it exists) and use it for configuration

Update PoET Enclave Simulator to not Use kwargs for Configuration

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_key_state_store.py
consensus/poet/core/tests/test_consensus/test_poet_key_state_store.py

The PoET block publisher keeps track of its active PoET public key by storing it in a class variable so that it is persisted across creation of PoET block publisher objects.  While this works, it leads to headaches when running tests.  This update removes the class variable and puts it in the PoET key state store.

Remove active key state class variable in PoET block publisher

---

validator/sawtooth_validator/exceptions.py
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/unit3/test_block_store/tests.py
validator/tests/unit3/test_state_delta_processor/tests.py

When a state delta export subscriber registers with a known block id that is older than the current chain head, send the subscriber all the events that have occurred in the interim.   This allows the subscriber to behave as if it received all the correct events.
Additionally:
* Add a Predecessor Iterator on block store

Send "catch-up" State Delta Events on Subscribe

---

validator/sawtooth_validator/journal/responder.py
validator/tests/unit3/test_responder/mock.py

Logs a statement saying that there is no chain head and that
the responder cannot respond to block requests. Also
adds the requester to the exclude list on broadcast.
This reduces the amount of duplicate requests in the system.
This should ~~remove~~ reduce the periodic failure in poet-smoke because of the following error.  "AssertionError:RestApi/blocks is not available within 10 attempts" 
The AssertionError was being caused by two validators peering when neither of them had the genesis block, causing the network to be flooded with block requests.
There is another issue within the dispatcher/signature verifier that is also throwing causes the same assertion error. A new Jira story has been created to investigate further.

Responder should not broadcast if it there is no chain head

---

docs/source/architecture.rst
docs/source/architecture/rest_api.rst
docs/source/rest_api/endpoint_specs.rst
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_submit_requests.py

Includes tweaks to the REST API and spec:
- POSTs no longer return `200` statuses
- `openapi.yaml` now documents only currently implemented aspects of the API

Add REST API Architecture doc

---

validator/sawtooth_validator/execution/executor.py

This will cause TpProcessRequest to be re-sent if the response returned is an InternalError. If you only have on TP running against a validator, this will most likely cause the TpProcessRequest to be re-sent repeatedly forever. However, if you have two TPs running and one can handle the transaction, progress will still be made. 
To Test:
Add the following line to sdk/examples/intkey_python/sawtooth_intkey/processor/handler.py:
49    def apply(self, transaction, state):
50 +      raise InternalError('Test InternalError')
51          content = cbor.loads(transaction.payload)
Start up a validator 
Start up  tp_intkey_python 
Run intkey workload.
You should see the Internal Error repeat forever. 
I created a Jira Task to write Unit …

If an InternalError is returned from a TP, resend TpProcessRequest.

---

validator/sawtooth_validator/execution/scheduler_parallel.py
validator/tests/unit3/test_scheduler/tests.py

This includes consolidating the use of create_transaction and
create_batch, adding setUp and tearDown to TestParallelScheduler,
adding test to TestParallelScheduler that should also work from
TestSerialScheduler, and adding the previous context_id to
create_context in test_transaction_order_with_dependencies.
Two tests are currently failing.

Add current serial scheduler test to parallel scheduler test

---

validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py

Defaults to SerialScheduler. If you want to use the ParallelScheduler create a validator.toml file in
the config directory. In the file, add the following line: 
scheduler = "parallel"
This PR also adds a command line option to ./bin validator 
--scheduler {serial,parallel}
The type of scheduler to be used.
Built on top of #451 for the lint fixes.

Add configuration option to select between schedulers 

---

docs/Makefile
docs/source/app_developers_guide/environment_setup.rst

Removed use of git clone in the App Dev Guide,
Environment setup section.

App Dev Guide should not use git or repo

---

docs/source/app_developers_guide/environment_setup.rst
docs/source/app_developers_guide/intro_to_sawtooth.rst
docs/source/cli/sawtooth.rst

Removed references to 'sawtooth cluster' from docs,
since the cluster command will be removed.

Remove references to sawtooth cluster from docs

---

docker/compose/sawtooth-default.yaml

This removes the need for the app developer to manually create the key
themselves before using the CLI commands.

Run sawtooth keygen in client compose container

---

cli/sawtooth_cli/rest_client.py

Previously, the Sawtooth CLI mishandled 404 errors when fetching
resources, causing a stack trace to be be printed to the console
when running a 'sawtooth show' command with a bad id.
This replaces the stack trace with a more sensible error message.

Remove stacktraces on 404 from sawtooth show command

---

.gitignore
bin/noop
bin/tp_noop_go
docker/sawtooth-dev-go
docker/sawtooth-int-tp_noop_go
sdk/examples/noop_go/src/sawtooth_noop/handler/handler.go
sdk/examples/noop_go/src/sawtooth_noop/main.go
sdk/examples/noop_python/sawtooth_noop/__init__.py
sdk/examples/noop_python/sawtooth_noop/client_cli/__init__.py
sdk/examples/noop_python/sawtooth_noop/client_cli/create_batch.py
sdk/examples/noop_python/sawtooth_noop/client_cli/exceptions.py
sdk/examples/noop_python/sawtooth_noop/client_cli/main.py
sdk/examples/noop_python/sawtooth_noop/client_cli/workload.py

These commits add a Go noop transaction processor which immediately returns when invoked without parsing payload or accessing state. Also included is a python client which includes a workload generator to submit noop transactions. The transaction payload consist of an 8 byte random nonce to give the transactions unique signatures.
Submission of solely noop transactions results in moving the block chain forward without changes to the state root hash.
This is intended for use in performance/integration testing.

Add no-op transaction processor and workload client

---

protos/state_delta.proto
protos/validator.proto
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/unit3/test_state_delta_processor/tests.py

Add Get State Delta handler to request state delta events by block ID.
This is useful for pre-catching up a client, in the case where they don't want to flood the network with many event messages.
Adds tests to verify that the subscriber sending a list of known block ids will return true if the request contains some known ids.

Add Get State Deltas Handler

---

sdk/examples/intkey_javascript/integer_key_handler.js

Improve readability of the Javascript Intkey implementation such that the app
developers using JS will have an easier time to understand how to write a
transaction processor.
These changes were added based on feedback at the Consensys 2017 hackathon

Improve intkey Example Readability

---

docs/source/app_developers_guide/intro_to_sawtooth.rst

The output shown below isn't the logging output of the validator, but the logging output of the intkey transaction processor.

Fix the bug of document

---

bin/run_lint
families/supplychain_python/sawtooth_supplychain_test/__init__.py

This corrects the the path that lint expects to find the supply chain family and fixes a lint import error. 

Add linting to Supply Chain

---

sdk/javascript/client/encoders.js

Fix typo in JS Client SDK doctring, and reword for clarity

---

rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py

Basic CORS support is required if a user is going to query a running
REST API from another server (e.g. from a single-page-app that is
submitting transactions, but hosted elsewhere).
This is to support the OMI Summer Lab.  A task to add configuration options to the REST API cli tool has been created in [STL-313](https://jira.hyperledger.org/browse/STL-313)

Basic CORS Support

---

docs/source/rest_api/error_codes.rst
protos/client.proto
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_txn_requests.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/unit3/test_client_request_handlers/base_case.py
validator/tests/unit3/test_client_request_handlers/mocks.py
validator/tests/unit3/test_client_request_handlers/test_batch_handlers.py
validator/tests/unit3/test_client_request_handlers/test_block_handlers.py
validator/tests/unit3/test_client_request_handlers/test_state_handlers.py
validator/tests/unit3/test_client_request_handlers/test_txn_handlers.py

Results to endpoints that list resources can now be sorted validator-side (pre-pagination) using the `sort` query parameter. It accepts a comma-separated list of keys which can be modified with some useful syntax:
- dot-notation indicates nested keys
- the header can be explicitly or implicity referenced
- starting with a minus sign indicates descending order
- ending with ".length" indicates the lengths should be compared
- additional key strings are tie-breakers for earlier ones
- example: `sort=-header.transaction_ids.length,signer_pubkey`
Includes a full set of unit tests.

Add sort query to REST API

---

consensus/poet/cli/sawtooth_poet_cli/enclave.py
consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/cli/sawtooth_poet_cli/main.py
consensus/poet/cli/sawtooth_poet_cli/poet_enclave_module_wrapper.py
consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_tp_validator_registry.py
consensus/poet/families/tests/validator_reg_message_factory.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/tests/node_controller.py

This updates the VR TP to use valid enclave measurement values found in the config settings on the blockchain.   Updates include:
* Add functions to retrieve the enclave measurement and basename for the simulator enclave
* Add a shutdown function to simulator enclave to bring it into alignment with the SGX implementation
* Adds a wrapper around the enclave for convenience of the poet CLI
* Adds a new sub-command to the poet CLI to print out the enclave measurement
* Updates the VR TP to use the config settings for valid enclave measurement values
* Updates all affected tests
Resolves: STL-144
To test:
To test this locally, start up a validator as such (the instructions assume you are running inside Vagrant VM):
```
sawtooth admin keygen validator
sawtooth config genesis --key …
```

Update Validator Registry TP to Use Config Setting for Enclave Measurement

---

sdk/examples/xo_python/sawtooth_xo/xo_cli.py
sdk/examples/xo_python/sawtooth_xo/xo_client.py

Previously the --wait cli option for create was parsed but nothing was done with it. Now, when this argument is parsed the cli will pause until the transaction has been committed to the block or an error is returned.
Note: _Currently when the XO transaction processor finds that a transaction is invalid (such as in the case of a "Game already exists" error) the Rest API status remains as 'PENDING'. This means that the cli will pause until the specified timeout has elapsed, or until the batch cache is cleared (in the case of the --wait wait option being passed with no argument). This should be fixed in the future when invalid transactions are given an 'INVALID' status in the Rest API._

Fix XO create wait option

---

docs/source/_templates/sdk_TP_tutorial.rst

Some vagrant-specific terms remained in the txn processor
tutorial. This commit removes remaing vagrant-specific
terms or steps.

Remove vagrant-specific terms or steps from TP tutorial

---

ci/sawtooth-build-debs
docker/sawtooth-dev-python
tools/package_groups/ubuntu-16.04-deps
validator/packaging/validator.toml.example
validator/sawtooth_validator/config/validator.py
validator/sawtooth_validator/server/cli.py
validator/setup.py
validator/tests/unit3/test_config/tests.py

This commit adds a ValidatorConfig object, an example
validator config file, and updates the validator cli to
check for a config file and combine it with any command
line options set.
Important to note the public-uri is no longer "required" to
be set on the command line, but if it is not set by either
the command line or the config file the validator will
shutdown.

Implement capability to use a validator config file

---

bin/build_go
bin/run_go_fmt
bin/seth
docker/sawtooth-dev-go
families/burrow_evm/src/sawtooth_burrow_evm/client/create.go
families/burrow_evm/src/sawtooth_burrow_evm/client/exec.go
families/burrow_evm/src/sawtooth_burrow_evm/client/load.go
families/burrow_evm/src/sawtooth_burrow_evm/client/main.go
families/burrow_evm/src/sawtooth_burrow_evm/client/show.go
families/burrow_evm/src/sawtooth_burrow_evm/client/utils.go
families/burrow_evm/src/sawtooth_burrow_evm/handler/handler.go
families/burrow_evm/src/sawtooth_burrow_evm/handler/sawtooth_app_state.go
families/burrow_evm/src/sawtooth_burrow_evm/handler/state_manager.go
families/burrow_evm/src/sawtooth_burrow_evm/main.go
tools/plugins/install_go_tools.sh

NOTE: The first 4 Go SDK commits are also in a separate PR against master.
To start the TP:
```
build_go
tp_burrow_evm -vv
```
To test the TP with the client, you can use:
```
seth load -k 8ff78a756a018e41cdd0364bfe88cb4547867eae27a0ee03fd3a585000775d90 -i 6060604052341561000c57fe5b5b60b08061001b6000396000f300606060405263ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360fe47b1811460435780636d4ce63c146055575bfe5b3415604a57fe5b60536004356074565b005b3415605c57fe5b6062607d565b60408051918252519081900360200190f35b60008190555b50565b6000545b905600a165627a7a72305820ec5f770aeda092d29c5a11c326a9ca0c377f3342db5d8eabfdbc2f8ffc23e25d0029 --url http://rest_api:8080
seth exec -k 8ff78a756a018e41cdd0364bfe88cb4547867eae27a0ee03fd3a585000775d90 -t …
```

Create Burrow EVM TP

---

docker/compose/sawtooth-default.yaml
docs/source/app_developers_guide/intro_to_sawtooth.rst

In order to be able to make config changes, the genesis block
must now contain the setting for the authorized key that
can submit config changes. Docs and default docker compose
file were updated to account for this, so that the intro doc
will work for both Ubuntu and docker installs.

Update docs and default docker compose file for config changes

---

bin/build_all
bin/run_tests
docker/apache-basic_auth_proxy
integration/sawtooth_integration/docker/basic-auth-proxy.yaml
integration/sawtooth_integration/tests/test_basic_auth_proxy.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_submit_requests.py

Updates the REST API to handle proxy urls when building a response `link`. It will now look for an `X-Forwarded-Host` header, and an `X-Forwarded-Path` header, and prefer those to the default host/path.
Also includes a new integration test which will set up an Apache 2 Basic Auth proxy in front of the REST API, and confirm it can be properly authorized, and sends back correct links.

Update REST API to handle proxying properly

---

bin/run_tests

I deleted these lines while working on the dynamic-network test and
accidentally included the deletion in a previous commit.

Re-enable poet-smoke test

---

validator/sawtooth_validator/gossip/signature_verifier.py
validator/tests/unit3/test_message_validation/tests.py

Verify the payload field of a transaction matches the payload_sha512 field of the header.

Verify the payload field of a transaction matches the header

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_tp_validator_registry.py
consensus/poet/families/tests/validator_reg_message_factory.py
integration/sawtooth_integration/docker/poet-smoke.yaml
integration/sawtooth_integration/tests/node_controller.py

NOTE - This PR is built on STL-144 (PR #534).  That PR needs to be merged before this PR.  I will rebase it once that PR is merged.  Only the last two commits are new code for this PR.
This updates the VR TP to use valid enclave basename values found in the config settings on the blockchain.   Updates include:
* Updates the VR TP to use the config settings for valid enclave basename values
* Updates all affected tests
Resolves: STL-146
To test:
To test this locally, start up a validator as such (the instructions assume you are running inside Vagrant VM):
```
sawtooth admin keygen validator
sawtooth config genesis --key ~/sawtooth/keys/validator.priv -o config-genesis.batch
sawtooth config proposal create -k ~/sawtooth/keys/validator.priv sawtooth.consensus.algorithm=poet …
```

Update Validator Registry TP to Use Config Setting for Enclave Basename

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/signup_info.py
consensus/poet/core/tests/test_consensus/test_signup_info.py
consensus/poet/core/tests/test_consensus/test_wait_certificate.py
consensus/poet/core/tests/test_consensus/test_wait_timer.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py

This change supports the removal of multi-tenancy support in the PoET enclave.

Remove validator address from functions that don't need it

---

tools/Vagrantfile
tools/plugins/install_cryptography.sh
tools/plugins/install_js_tools.sh

Fix the apt-get args to include `-y -q` for all dependencies, as a change
in the dependencies caused the need for interaction during `vagrant up`
This includes, leiningen, ruby and sass
Match the ports currently used by the validator and rest api: 8800, 40000, 8080->18080

Update Vagrant plugins and ports

---

docs/source/architecture/rest_api.rst
docs/source/sysadmin_guide.rst
docs/source/sysadmin_guide/rest_auth_proxy.rst

Includes a generic reference for forwarding headers, and a step-by-step
guide through a basic Apache proxy setup.

Add documentation for putting an authed proxy in front of REST API

---

cli/sawtooth_cli/batch.py
cli/sawtooth_cli/block.py
cli/sawtooth_cli/parent_parsers.py
cli/sawtooth_cli/rest_client.py
cli/sawtooth_cli/state.py
cli/sawtooth_cli/submit.py
cli/sawtooth_cli/transaction.py

This PR adds support for Basic Auth proxies. In order to test it, you'll need to build one. These are the instructions for setting up a simple authed Apache proxy in vagrant.
```
% sudo apt-get update
% sudo apt-get install -y apache2
% sudo a2enmod headers
% sudo a2enmod proxy_http
```
```
% vi /tmp/.password
```
Edit the file to look like this:
```
sawtooth:$apr1$VHIPQ4Wi$k7PbIPqcfVp1NVKWhkIbS0
```
This saves the password `"sawtooth"` for the user `sawtooth`. You can generate new files like this at the site: http://www.htaccesstools.com/htpasswd-generator/. However, the config file below only allows the user `sawtooth`, so that would need to be modified as well.
```
% sudo vi /etc/apache2/sites-enabled/000-default.conf
```
Edit the file to look like this:
```
<VirtualHost *:80> …
```

Add Basic Auth support to Sawtooth CLI

---

validator/packaging/validator.toml.example
validator/sawtooth_validator/config/validator.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py

If the network key pair is not defined or if there is no validator config file, the network will default to being unsecure. 
This PR is build on top of #541

Move the Curve ZMQ keys into the validator config file. 

---

integration/sawtooth_integration/docker/config-smoke.yaml
integration/sawtooth_integration/tests/node_controller.py
rest_api/packaging/rest_api.toml.example
rest_api/sawtooth_rest_api/config.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/rest_api.py
rest_api/tests/unit/test_config.py
sdk/python/sawtooth_sdk/client/config.py

This commit adds a RestApiConfig object, an example
rest_api config file, and updates the rest_api to check
for a config file and combine it with any command line
options set.

Implement capability to use a rest api config file

---

docker/compose/sawtooth-default.yaml

Without this change, the container names are prefixed with the directory
name where the compose file is located. Having unpredictable container
names is problematic for documentation purposes.

Add container_names to sawtooth-default compose file

---

docker/apache-basic_auth_proxy
integration/sawtooth_integration/docker/basic-auth-proxy.yaml
integration/sawtooth_integration/tests/test_basic_auth_proxy.py
rest_api/sawtooth_rest_api/route_handlers.py

Adds proper scheme/protocol, host, and path parsing to REST API using either the standard `Forwarded` header, or more commonly used `X-Forwarded` headers.
Adds a test to `basic_auth_proxy`, ensuring it works properly in with both HTTP and HTTPS.

Add HTTPS test to auth proxy integration tests

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py

When refactoring PoET fork resolver code, accidentally left in a second deserialization of the new fork head wait certificate.  Removed it.

Remove unnecessary double deserialization of wait certificate

---

integration/sawtooth_integration/tests/test_intkey_smoke.py

Intkey smoke occasionally fails tests due to block commits occasionally
taking longer than 1 second.  Wait for the expected block number before
verifying the state to mitigate this issue.

Wait for expected block num

---

bin/build_go

This is intended to allow running bin/build_go without having
GOPATH set in the developer's environment.

Explicitly set GOPATH in bin/build_go

---

cli/sawtooth_cli/submit.py

When the status of a batch is COMMITTED, the printing output is COMMITTE. Fixed it.

Fix truncated committed status for the submit cli

---

integration/sawtooth_integration/tests/test_intkey_smoke.py

Revert the fix to intkey smoke that waited for successful block updates.
This failed by timeout out the tests, as this would never return.
Restored the use of a simple sleep, though the time has been bumped up
to 10 seconds.
This should be correctly fixed with issue [STL-321](https://jira.hyperledger.org/browse/STL-321)

Revert the intkey smoke fix

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py
consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/signup_info.py
consensus/poet/core/tests/test_consensus/test_poet_block_publisher.py

The nonce field in the request for the attestation verification report from IAS is limited to 32 bytes.  When creating signup information, restrict the nonce to 32 bytes.
If you want to try to run it (you need SGX hardware and be able to build for Linux):
Rename `poet_enclave_sgx.toml.example` to `poet_enclave_sgx.toml` and move to the validator's configuration directory.  Edit the file to have the correct SPID and path to SPID cert PEM file.
In a console:
```
sawtooth admin keygen validator
sawtooth config genesis --key <path>/validator.priv -o config-genesis.batch
sawtooth config proposal create -k <path>/validator.priv \
sawtooth.consensus.algorithm=poet \
sawtooth.poet.enclave_module_name=poet_enclave_sgx.poet_enclave \ …
```

Restrict signup information nonce to 32 bytes

---

ci/sawtooth-build-docs

Removes this error:
Traceback (most recent call last):
File "/project/sawtooth-core/bin/validator", line 34, in <module>
from sawtooth_validator.server.cli import main
File "/project/sawtooth-core/validator/sawtooth_validator/server/cli.py", line 20, in <module>
import netifaces
ImportError: No module named 'netifaces'

Fix missing python3 netifaces dependencies in the CI docs build.

---

integration/sawtooth_integration/tests/test_basic_auth_proxy.py

Test will now wait for both the REST API and Apache proxy to be ready before running any tests. Also includes some changes to the error logs to improve clarity and readability.

Fix intermittent 503 error from auth proxy integration test and clean up logs

---

docs/source/app_developers_guide/address_and_namespace.rst

The current document is inaccurate, due to changes to the
config transaction family.
The intkey transaction family is now used as the
simple example, and the config transaction family taken
out, but a link is provided.

Update Namespaces and Address Config Example

---

protos/state_delta.proto
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/test_state_delta_processor/tests.py

Add `previous_block_id` to `StateDeltaEvent`, to enable subscribers to fetch deltas for blocks they may have missed.

Add previous_block_id to StateDeltaEvent

---

protos/processor.proto

Add a message field for a standard error message, for use on Internal
Error or Invalid Transaction statuses
Add extended_data to provide a field for application-specific data that
can be passed from a transaction processor to a client.

Add error information to TpProcessResponse

---

sdk/javascript/processor/exceptions.js
sdk/javascript/processor/index.js
sdk/javascript/processor/state.js
sdk/python/sawtooth_processor_test/mock_validator.py

Report the error and extended information back to the validator via the new fields on TpProcessRequest. 
Additionally, add a timeout to the State `get` and `set` methods.

Report Errors in JS SDK Transaction Processors

---

sdk/python/sawtooth_sdk/processor/core.py
sdk/python/sawtooth_sdk/processor/exceptions.py

Transaction Processors developed with the Python SDK, which reject a
transaction with the InvalidTransaction or InternalError exceptions,
will now automatically send the error messages back to the validator,
as well as optional byte-encoded data.

Send messages and data from Python SDK on TP errors

---

validator/sawtooth_validator/execution/context_manager.py
validator/tests/test_context_manager/tests.py

The ContextManager now requires 70 lowercase hex character
addresses, or will raise AuthorizationException.
STL-403

Add state address enforcement to the ContextManager

---

consensus/poet/families/tests/tp-validator-registry.yaml
families/config/tests/tp-config.yaml
families/supplychain/python/tests/tp-supplychain-python.yaml
sdk/examples/intkey_python/tests/tp-intkey-go.yaml
sdk/examples/intkey_python/tests/tp-intkey-java.yaml
sdk/examples/intkey_python/tests/tp-intkey-javascript.yaml
sdk/examples/intkey_python/tests/tp-intkey-python.yaml
sdk/examples/xo_python/tests/tp-xo-javascript.yaml
sdk/examples/xo_python/tests/tp-xo-python.yaml
sdk/python/sawtooth_processor_test/mock_validator.py
sdk/python/sawtooth_processor_test/transaction_processor_test_case.py

This changes the default bind address of the mock validator used for
TP tests, then implements an environment variable to override the
new default when executed within docker-compose-based tests.

Modify TransactionProcessorTestCase to work outside docker

---

docker/compose/sawtooth-default.yaml

There is a typo in the entrypoint for rest_api docker container. It should be --bind and not -bind

fix the typo in the entrypoint for rest_api docker container

---

sdk/python/sawtooth_sdk/processor/state.py

Previously this typo was likely getting swallowed by the base `Exception.__init__`, but now throws a `TypeError` with the new *_TpResponseError* parent class.

Fix incorrectly instantiated transaction errors in Python SDK

---

protos/processor.proto
protos/validator.proto
sdk/python/sawtooth_sdk/processor/core.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/processor_iterator.py
validator/sawtooth_validator/networking/future.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py

This PR currently only works for python transaction processor. If solution is approved handling of TpPings will need to be added to all other sdks. 
A monitor socket is listening for disconnect events and notifies the executor that it should check all connected transaction processors to see if they are still connected. This is done by sending a TpPing response and waiting for a TpPingResponse is returned. If a transaction processor is found to not be connected, it should be removed from processors and all pending futures are set to an internal error (causing them to be rescheduled on a new processor).
The reasons that this ping message is needed, is that the zmq disconnect event only returns the following information: remote endpoint, event int, and a FD. I was not able to correlate a FD …

Allow Executor to recover after a TP Crash.

---

validator/sawtooth_validator/execution/scheduler_serial.py

Handle the case where there are no batches.

Skip state root calculation if no batches

---

cli/sawtooth_cli/config.py
docs/source/app_developers_guide/docker.rst
integration/sawtooth_integration/tests/test_config_smoke.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/create_batch.py

- Rewords the Docker tutorial for clarity and accuracy.
- Modifies the behavior of `sawtooth config settings list` to truncate at screen width instead of after just 15 characters.
- Modifies the args and help text of `intkey create_batch` for clarity, substituting _"key count"_ for the non-standard _"word pool"_
- Reduces defaults of `intkey create_batch` to just a single batch with a few transactions.

Using Sawtooth with Docker cleanup

---

families/settings/sawtooth_settings/processor/main.py

Match tp_intkey_python's argument format for defaulting the endpoint the
tp_settings transaction processor will connect to.
This allows us to start the processor like so:
```
$ tp_settings
```
which is the documented method.

Default endpoint in tp_settings

---

bin/run_tests
integration/sawtooth_integration/docker/permission.yaml
integration/sawtooth_integration/tests/test_permission.py
validator/sawtooth_validator/gossip/permission_verifier.py
validator/sawtooth_validator/server/core.py

The signing keys that are allowed to submit batches will be
stored in the validator setting sawtooth.validator.allowed_signing_key.
A batch signed by an unknown signing key will cause the batch to be
dropped. If no signing keys are set, all signing keys are accepted.

Implement signing key-based client batch submit permissioning

---

validator/sawtooth_validator/execution/context_manager.py
validator/tests/test_context_manager/tests.py

As a consequence of another PR review, @aludvik and I realized that this checking for if an address was under any namespace in the inputs or outputs for a Context wasn't correct. This PR fixes the checking and provides a unit test.

Correct input, output namespace checking

---

validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/tp_state_handlers.py
validator/tests/test_context_manager/tests.py

This PR enforces that inputs and outputs are 0-70 lowercase hex characters, or fails the transaction. It also makes it so that addresses under a namespace can be correctly found using 'get' on the context manager. Prior to this PR, it was possible to set an address that was partially specified in the outputs, but it wasn't possible to 'get' the address and always find the correct value for that context.
STL-121

Context Manager namespace enforcement and namespace support

---

docs/source/app_developers_guide/docker.rst

Section on configuring Docker to work with proxy servers
added to App Dev Guide, for Windows, macOS and Linux.

Added help for proxy setup in Docker to App Dev Guide

---

sdk/examples/intkey_python/sawtooth_intkey/client_cli/load.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload.py
sdk/python/sawtooth_sdk/workload/workload_generator.py

% sudo apt-get update % sudo apt-get install -y apache2 % sudo a2enmod headers % sudo a2enmod proxy_http
% vi /tmp/.password
.password should match this:
sawtooth:$apr1$cyAIkitu$Cv6M2hHJlNgnVvKbUdlFr.
#EOF
% sudo vi /etc/apache2/sites-enabled/000-default.conf
000-default.conf should match this:
<VirtualHost *:80>
ServerAdmin sawtooth@sawtooth
DocumentRoot /var/www/html
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
<Location />
Options Indexes FollowSymLinks
AllowOverride None
AuthType Basic
AuthName "Enter password"
AuthUserFile "/tmp/.password"
Require user sawtooth
Require all denied
</Location>
</VirtualHost>
ProxyPass /sawtooth http://localhost:8080
ProxyPassReverse /sawtooth http://localhost:8080
RequestHeader set X-Forwarded-Path "/sawtooth" …

Implement auth for Intkey CLI

---

sdk/java/src/main/java/sawtooth/sdk/processor/TransactionProcessor.java
sdk/java/src/main/java/sawtooth/sdk/processor/exceptions/InternalError.java
sdk/java/src/main/java/sawtooth/sdk/processor/exceptions/InvalidTransactionException.java
sdk/java/src/main/java/sawtooth/sdk/processor/exceptions/SawtoothException.java

Send back the message and optional extended data on the `TpProcessResponse`.

Send back transaction failure information via the Java SDK

---

validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/execution/scheduler_parallel.py
validator/tests/test_scheduler/tests.py

As of this PR, all scheduler unit tests pass and poet-smoke with a heterogeneous scheduler network passes often, but not always. STL-488 and STL-476 will hopefully improve that.
Note: Any transaction that uses dependencies will not work with the parallel scheduler at this point. https://jira.hyperledger.org/browse/STL-499 When STL-499 is complete, dependencies will work with the parallel scheduler.

Implement state handling for parallel scheduler

---

sdk/examples/xo_python/sawtooth_xo/xo_client.py

Currently using the `--wait` option with `xo create` causes a different response than all other commands. This PR fixes this inconsistency.
_note: A future PR should add more descriptive responses for all Xo transactions._

Fix Xo wait response message

---

docs/source/transaction_family_specifications/settings_transaction_family.rst

Before the doc said that if authorized keys are empty
all public keys are allowed, now no proposal can be
made until a key is set.

Update Settings Specification for authorized key change

---

bin/make_templated_docs
docs/source/_templates/sdk_submit_tutorial.rst
docs/source/_templates/template_config.yaml
docs/source/_templates/txn_submit_tutorial.rst
docs/source/app_developers_guide.rst
docs/source/app_developers_guide/no_sdk.rst
docs/source/app_developers_guide/writing_clients.rst

Makes Python 3 the only language used for example code for manually generating transactions and submitting them to a validator. Also includes some necessary rewording, some rewording for clarity, some ToC rejiggering, and a tweak to the doc generation script.
Closes #STL-438

Remove JS Examples from "No SDK" Txn Submit Doc

---

protos/client.proto
rest_api/tests/unit/components.py
rest_api/tests/unit/test_submit_requests.py
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/batch_tracker.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/test_client_request_handlers/base_case.py
validator/tests/test_client_request_handlers/mocks.py
validator/tests/test_client_request_handlers/test_submit_handlers.py

BatchTracker utilizes the observer pattern to collect notifications from elsewhere in the validator about the progress of submitted batches. Other validator components call the appropriate notify method at points where a status change has occurred.
All batch status and wait-for-commit client code, including unit tests, has been refactored to query this new BatchTracker, which can be queried for the current statuses of batches, or send out a notification itself when all specified batches are no longer PENDING.

Refactor existing wait/status functionality with new BatchTracker

---

cli/sawtooth_cli/batch.py
cli/sawtooth_cli/rest_client.py
docs/source/architecture/rest_api.rst
protos/client.proto
rest_api/sawtooth_rest_api/openapi.yaml
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_submit_requests.py
sdk/examples/xo_python/sawtooth_xo/xo_client.py
sdk/python/sawtooth_sdk/workload/workload_generator.py
validator/sawtooth_validator/execution/executor.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/batch_tracker.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/test_client_request_handlers/mocks.py
validator/tests/test_client_request_handlers/test_submit_handlers.py

This PR expands the BatchTracker to track invalid Batches, which transaction was rejected, and any data associated with the transaction. This data is then sent back through both the ZMQ and REST APIs with a more robust list of status objects, rather than a simple id to status hashmap.

Send back invalid transaction data through APIs

---

validator/tests/test_scheduler/data/batch_fails_valid_txn.yaml
validator/tests/test_scheduler/tests.py
validator/tests/test_scheduler/yaml_scheduler_tester.py

The first three commits make the yaml testing framework better. The yaml test added in the last commit will be improved by a change to the yaml testing framework, in a future PR. It will also be able to be passed based on work done under issue STL-476, coming in a future PR. This PR is against the parallel-scheduler branch.

Yaml tester fixes, increase in yaml tests

---

consensus/poet/core/sawtooth_poet/poet_consensus/consensus_state.py
consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/tests/test_consensus/test_poet_block_publisher.py

The consensus state and block publisher error messages when PoET policy will be violated have been demoted from error to informational logging messages.

Change PoET policy logging error messages to informational

---

cli/sawtooth_cli/main.py
cli/setup.py

Ref #644
Implement a "--version, -V" argument for the sawtooth command. And if this way is accepted, I'll make the same for all installed commands.

Add a version option for cli

---

rest_api/sawtooth_rest_api/messaging.py
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_submit_requests.py
rest_api/tests/unit/test_txn_requests.py

Use of the sawtooth python SDK Stream required blocking for the results
of concurrent futures, within the confines of an asyncio loop.  In order
to avoid blocking the loop on waits, a thread pool executer was
introduced to handle these futures.
This commit replaces the concurrent stream with an asyncio-based
Connection class.  This class performs all operations on an asyncio
loop, which is shared with the aiohttp application.  All calls to and
from the validator are handled using coroutines.
This is in support of STL-223

REST API: Replace SDK Stream with asyncio Connection

---

validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/journal/chain.py
validator/tests/test_journal/block_tree_manager.py
validator/tests/test_journal/mock.py
validator/tests/test_journal/tests.py

Block and Transaction completness is already enforced by the completer. The duplicate checks are removed from the BlockValidator. 
Journal unit test enhancements to allow for BadTransaction simulation and remove unimplemented test.

Remove Block and Transaction completness checks from Journal

---

validator/sawtooth_validator/execution/context_manager.py
validator/tests/test_scheduler/tests.py
validator/tests/test_scheduler/yaml_scheduler_tester.py

This PR depends on #680 and is made against the parallel-scheduler branch. The first commit is unrelated to the second commit, but is a cleanup commit from a prior PR. The second commit implements the ability to assert that input addresses for a transaction have particular values in state.

Add ability for yaml scheduler tester to calculate state for each transaction

---

ci/sawtooth-publish-js-sdk
sdk/javascript/README.md
sdk/javascript/package.json
sdk/javascript/processor/index.js
sdk/javascript/protobuf/index.js

Also fixes some small typos that broke the JS SDK, and adds a prepublish hook to run tests and compile protobufs.
Note that this Docker will only run if you are in a clean tagged version of that Sawtooth repo.

Add Dockerfile for publishing JS SDK to NPM

---

docs/source/rest_api.rst
docs/source/rest_api/state_delta_websockets.rst
protos/state_delta.proto
rest_api/sawtooth_rest_api/messaging.py
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/state_delta_subscription_handler.py
sdk/examples/noop_python/sawtooth_noop/client_cli/workload.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/state/state_delta_processor.py
validator/tests/test_state_delta_processor/tests.py

Provide state delta events over a web socket connection.  
Subscriptions are limited to only starting at the current block.  Web socket-based subscribers cannot specify the block they start with, unlike ZMQ subscribers (the REST API doesn't maintain a cache of the state changes). 
Users of the web socket may request specific events by block id, to get missed events if necessary, but the expectation is that they will have queried the state directly for the current value, and then subscribe to future events.

Provide State Delta Events via Web Socket

---

validator/sawtooth_validator/execution/processor_handlers.py
validator/sawtooth_validator/execution/processor_iterator.py

Namespaces is a list type, so log it as a list type, not as a string type.

log readable namespaces

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/tests/test_consensus/test_poet_block_publisher.py

The PoET block publisher has been updated so that the PoET key pair is always restored from the key state store.

Ensure that PoET enclave always has key state restored properly.

---

docs/source/examples/supplychain/supplychain_transaction_family.rst
families/supplychain/protos/agent.proto
families/supplychain/protos/application.proto
families/supplychain/protos/payload.proto
families/supplychain/protos/record.proto

This PR fixes spelling/grammar errors and misaligned code blocks in the Supply Chain Transaction Family document. It does not alter the wording or flow of this document.
It also addresses some inaccurate and unclear docstrings in the Supply Chain proto-files. These have been reworded somewhat more heavily than the Transaction Family document.
This PR does not alter any functionality.

Fix typos and inaccuracies in Supply Chain documentation

---

cli/sawtooth_cli/main.py
rest_api/sawtooth_rest_api/rest_api.py
validator/sawtooth_validator/server/cli.py

Implement a "--version, -V" argument for the rest api and validator commands.

Add version option for rest api and validator

---

docs/source/_templates/sdk_submit_tutorial.rst
docs/source/_templates/txn_submit_tutorial.rst

Also clarifies the reasoning behind when a state address is valid, and
when it is not.

Fix invalid inputs/outputs used in txn submit docs

---

sdk/java/pom.xml
sdk/java/src/main/java/sawtooth/sdk/client/sawtooth/sdk/client/Signing.java

*Includes*
- wif reading
- public key derivation from the private key
- transaction signing using the 'compact signature' scheme
*Does not cover*
- payload verification
This has been verified by signing a payload in Java, then verifying it in Python.
I had to exclude a transitive scrypt lib inclusion, as it had a signed but invalid jar.

STL-461 Java SDK transaction signing

---

rest_api/sawtooth_rest_api/rest_api.py

As logs are stored in a "sawtooth" directory, labeling the REST API's
log file "sawtooth_rest_api" is redundant, and does not match the pattern
used by other log files. Renamed to "rest_api".

Remove redundant "sawtooth" from REST API log name

---

consensus/poet/sgx/tests/test_sgx/test_poet_enclave_wait_certificate.py

The broken unit test blocks fixing a higher priority bug.
Disable for now. Added STL-616 in Jira to address.
The unit tests are out of sync with the simulator unit tests.
To bring them into better alignment the waittimer timeout constant needs to
be available to the test module.
See:
poet/core/tests/test_consensus/test_wait_certificate.py
poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
pot/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp

Disable broken unit test for create wait certs.

---

docs/source/architecture/validator_network.rst
docs/source/faq.rst

Removes outdated reference to hard coded zmq server keys.
Updates the FAQ to no long reference 0.7 and correctly explains how to configure the validator in 0.8.

Minor doc updates. 

---

families/supplychain/python/sawtooth_supplychain/processor/main.py
rest_api/sawtooth_rest_api/rest_api.py
sdk/examples/intkey_python/sawtooth_intkey/processor/main.py
sdk/examples/xo_python/sawtooth_xo/processor/main.py
sdk/python/sawtooth_sdk/client/config.py
sdk/python/setup.py
validator/sawtooth_validator/config/logs.py
validator/setup.py

TOML does not support enough data types to support the SysLog handler type in
python logging. YAML does.

Support YAML format for logging config

---

validator/sawtooth_validator/journal/chain.py

During fork resolution, when finding a common ancestor, a miss to the block cache will cause an exception.  While the callback is notified that block validation has failed, the blocks in the new chain are not marked as invalid.  This commit corrects the issue.
Additionally, it removes the calling of the callback from `_find_common_height`, since it raise an error that is caught by its calling function that results in the callback being executed.

Invalidate block on cache miss

---

.gitignore
bin/build_all
bin/build_rust
bin/protogen
docker/sawtooth-dev-rust
sdk/rust/Cargo.toml
sdk/rust/src/lib.rs
sdk/rust/src/messages/mod.rs

Add the tools necessary to compile a Sawtooth Rust SDK, including the
core protobuf messages. This includes a docker container for doing rust
development.

Add Rust SDK with compiled Protobuf

---

sdk/examples/xo_python/sawtooth_xo/processor/handler.py

Using namespace_prefix variable, not using '5b7349'

Using namespace prefix

---

docs/source/community/contributing.rst

Previously our contributing guide was missing any guidance on commit message formatting, which may have confused some outside contributors. This PR codifies some common git conventions in our documentation.

Add commit message guidelines to contributing guide

---

.gitignore
bin/run_tests
perf/sawtooth/sawtooth_workload/Cargo.toml
perf/sawtooth/sawtooth_workload/src/batch_gen.rs
perf/sawtooth/sawtooth_workload/src/main.rs
perf/sawtooth/sawtooth_workload/unit_perf_workload.yaml
sdk/rust/unit_rust_sdk.yaml

Initial tool for generating batches from a length-delimited source of transactions.  
The batches produced are not yet signed.

Initial Batch Generation Tool

---

sdk/rust/Cargo.toml
sdk/rust/src/lib.rs
sdk/rust/src/signing/mod.rs
sdk/rust/src/signing/secp256k1.rs

This implements the majority of signing library support, with the
exception of key generation.

Add initial Rust signing SDK and secp2561k support

---

perf/sawtooth/sawtooth_workload/Cargo.toml
perf/sawtooth/sawtooth_workload/src/batch_submit.rs
perf/sawtooth/sawtooth_workload/src/main.rs

This consumes length delimited signed Batches from an input file
and posts BatchLists at a single Sawtooth REST API endpoint at
the specified rate.
Open items:
- Define format for combined target/rate argument
- Support multiple target rates
- Support direct ZMQ target

Initial implementation of workload batch submission

---

docker/compose/sawtooth-local.yaml
stat_collection/docker/grafana/datasources/influxdb.json
stat_collection/docker/grafana/grafana_entrypoint.sh
stat_collection/docker/grafana/sawtooth-stats-grafana
stat_collection/docker/influxdb/influxdb_entrypoint.sh
stat_collection/docker/influxdb/sawtooth-stats-influxdb
stat_collection/docker/metrics.yaml

This PR adds docker-compose files that build containers containing InfluxDB, Grafana, and local Sawtooth files.
_Note: Prior to running either docker-compose file, a user must create the sawtooth_stats Docker network with the command: `$ docker network create sawtooth_stats`. This allows communication between the containers._
The metrics.yaml docker compose file automatically run scripts that will set up a framework for
stat collection:
- After InfluxDB is started, a post to the InfluxDB HTTP API is made that creates a database called "metrics"
- After Grafana is started, a JSON file is read from the `stat_collection/docker/grafana/datasources` directory, which is posted to the Grafana HTTP API. This request establishes a connection between the InfluxDB "metrics" database.
Note: other …

Add influx and grafana docker files for stat collection

---

perf/sawtooth/sawtooth_workload/src/main.rs
perf/sawtooth/sawtooth_workload/src/playlist.rs

Ensure source and dest ids are different
For transactions that require two customer ids, ensure that the randomly selected keys are different. This requires that the CLI needs a minimum of 2 accounts to properly generate accounts.

Ensure different ids

---

validator/sawtooth_validator/gossip/gossip.py

Attempts to cleanup the connection status using an old field name.

Fix connection status delete

---

sdk/rust/src/signing/mod.rs
sdk/rust/src/signing/secp256k1.rs

This stores the secp256k1 context in the Secp256k1Algorithm struct
as was the original intent, avoiding the recreation of the context
on each signing/verification/key call.

Rust sdk fix secp256k1 context handling

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py
consensus/poet/core/sawtooth_poet/poet_consensus/signup_info.py
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.h
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/signup_data.cpp
consensus/poet/sgx/tests/test_sgx/test_poet_enclave_signup_info.py
consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py

Hardware counters must be released when no longer needed.
This change adds a simple policy to poet to release counters
after a validator registration has exhausted its allowed
number of blocks published (k test).
The SGX enclave is also updated to throw an error if PoET
attempts to unseal signup data that references a defunct counter.
The block publisher now traps for that event to no longer use
that signup data and puts it into the condition where it seeks
to sign up again.
See Also STL-642 to add HW Counter simulation to poet simulator.
Broader poet core tests will be appropriate when that feature is added.

Fix HW Counter management. Release old signups.

---

cli/setup.py

Without this dependency, the resulting deb package fails to pull
in the requests package and will fail on the requests import.

Add requests dependency to sawtooth-cli package

---

cli/sawtooth_cli/config.py
cli/sawtooth_cli/identity.py
families/identity/sawtooth_identity/processor/handler.py
families/identity/tests/sawtooth_identity_test/identity_message_factory.py
families/identity/tests/test_tp_identity.py

Only those pub keys that are in the setting sawtooth.identity.allowed_keys should be allowed to sign identity transactions. If an identity transaction is received signed by someone else, the transaction is deemed invalid. 
This PR is build on top of #766 Implement Off-Chain Transactor Permissioning. This Pr will be rebased once that PR is merged.

Update Identity Transaction Processor to accept transaction from allowed signers

---

docs/source/sysadmin_guide.rst
docs/source/sysadmin_guide/transactor_permissioning.rst

The following PR is adds description to the sysadmin guide about how to use Transactor Permissioning.
This PR is built on top of #766 Implement Off-Chain Transactor Permissioning as this document covers it as well.

Transactor Permissioning Documentation

---

protos/events.proto
protos/txn_receipt.proto
protos/validator.proto
validator/sawtooth_validator/journal/receipt_store.py
validator/tests/test_receipt_store/tests.py

This PR adds a receipt store object, transaction receipt protobuf messages, message handlers, and tests that they all function. The receipt store will be used once the transaction execution results are returned from the executor.

Create Transaction Receipt Store and Handlers

---

consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.i

Fix the formatting of error messages when bad quotes are encountered.

Fix AVR ValueError messages

---

validator/sawtooth_validator/state/batch_tracker.py
validator/tests/test_client_request_handlers/test_submit_handlers.py

An uncaught typo was causing client requests for batch status to fail
when told to wait for commit when batch was already committed. The typo
has been fixed and a new test has been added to cover that condition.

Fix wait-for-commit failing when already committed

---

.gitignore
bin/build_python
bin/run_bandit
bin/supplychain-rest-api
docker/sawtooth-dev-python
families/supplychain/python/packaging/supplychain_rest_api.toml.example
families/supplychain/python/sawtooth_supplychain/rest_api/__init__.py
families/supplychain/python/sawtooth_supplychain/rest_api/config.py
families/supplychain/python/sawtooth_supplychain/rest_api/exceptions.py
families/supplychain/python/sawtooth_supplychain/rest_api/main.py
families/supplychain/python/sawtooth_supplychain/rest_api/route_handlers.py
families/supplychain/python/sawtooth_supplychain/rest_api/sql.py
families/supplychain/python/sawtooth_supplychain/subscriber/init.py
families/supplychain/python/sawtooth_supplychain/subscriber/subscriber.py
families/supplychain/rest_api/openapi.yaml
tools/package_groups/ubuntu-16.04-deps

Add the REST API for the supplychain family.  This API is backed by a postgres database, which is populated via the supplychain state delta subscriber.  It includes a modification to the API spec, simplifying the paging model.  This makes querying pages with filtering far easier to do.
Additionally, change the use of NULL's for `end_block_num` in the state export tables to using 2^63-1 (MAX_U64, effectively), as this makes the queries much easier for paging and values at particular block number.

Add Supplychain REST API 

---

protos/block.proto
protos/state_delta.proto

int32 for block num size is too small for long-term deployments.  Increasing this to uint64 should avoid any size constraints in the long term.

Increase block_num size from int32 to uint64

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/networking/future.py

**Fix invalid field access**
Correct an error caused by accessing the incorrect (and non-existent) _connections field of the Topology class. This error caused the connection status/known connections to be left in an incorrect state, which effects peering.
Additionally:
**Capture unhandled exceptions on future callbacks** 
Callbacks in futures that throw exceptions get swallowed when executing in the thread pool.  This commit adds a try/except block around the callback to trap and log those exceptions.

Fix gossip error

---

consensus/poet/simulator/sawtooth_poet_simulator/poet_enclave_simulator/poet_enclave_simulator.py
validator/sawtooth_validator/gossip/gossip.py

From recent long-running instances:
- Fix remove temporary connection callback
Using partial with this function caused it to receive too many arguments. Wrapping it in a function that takes the correct number of arguments to act as a future callback.
- Add release_signup_data to the PoET simulator module
Add the release_signup_data function at the module level.  This was missing from the simulator vs the SGX implementation.

Gossip and Poet Simulator Fixes

---

bin/run_lint
docker/compose/sawtooth-seth.yaml
docker/compose/sawtooth-xo.yaml
families/block_info/sawtooth_block_info/injector.py
families/block_info/sawtooth_block_info/processor/handler.py
integration/sawtooth_integration/docker/test_block_info_injector.yaml
integration/sawtooth_integration/tests/test_block_info_injector.py
validator/sawtooth_validator/journal/batch_injector.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/test_journal/mock.py
validator/tests/test_journal/tests.py

Add feature to inject batches into the beginning of a block and create a new BlockInfoInjector which utilizes this feature. Also add tests.
This is an incremental PR towards the completion of STL-567. It implements the portion of the task that is required by the Solidity Developer Compatibility epic and unblocks STL-495.
This PR also depends on the context manager fix @boydjohnson has up.
Phase 2 - Injection before and after a batch
Phase 3 - Injection at the end of a block

Implement Batch Injection - Phase 1/3

---

integration/sawtooth_integration/docker/seth_intkey_test.yaml
integration/sawtooth_integration/docker/seth_perm_test.yaml
integration/sawtooth_integration/docker/test_basic_auth_proxy.yaml
integration/sawtooth_integration/docker/test_config_smoke.yaml
integration/sawtooth_integration/docker/test_intkey_smoke_go.yaml
integration/sawtooth_integration/docker/test_intkey_smoke_java.yaml
integration/sawtooth_integration/docker/test_intkey_smoke_javascript.yaml
integration/sawtooth_integration/docker/test_intkey_smoke_python.yaml
integration/sawtooth_integration/docker/test_permission.yaml
integration/sawtooth_integration/docker/test_two_families.yaml
integration/sawtooth_integration/docker/test_workload.yaml
integration/sawtooth_integration/docker/test_xo_smoke_all.yaml
integration/sawtooth_integration/docker/test_xo_smoke_go.yaml
integration/sawtooth_integration/docker/test_xo_smoke_java.yaml
integration/sawtooth_integration/docker/test_xo_smoke_javascript.yaml
integration/sawtooth_integration/docker/test_xo_smoke_python.yaml
integration/sawtooth_integration/tests/test_intkey_smoke.py
integration/sawtooth_integration/tests/test_two_families.py

Currently the intkey smoke and two-family tests verify that the entire
state is initially empty. This will work if the validator is started
with an empty genesis batch, as it is in these tests' compose files:
sawtooth admin keygen && \
sawtooth admin genesis && \
sawtooth-validator -v \
--endpoint tcp://validator:8800 \
--bind component:tcp://eth0:4004 \
--bind network:tcp://eth0:8800 \
However, if the genesis batch is non-empty, then state won't be empty,
and the tests will fail:
sawtooth admin keygen && \
sawtooth keygen my_key && \
sawtooth config genesis -k /root/.sawtooth/keys/my_key.priv && \
sawtooth admin genesis config-genesis.batch && \
sawtooth-validator -vv \
--endpoint tcp://validator:8800 \
--bind component:tcp://eth0:4004 \
--bind network:tcp://eth0:8800 \
This commit fixes …

Restrict smoke tests to appropriate namespaces

---

validator/sawtooth_validator/networking/future.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py

Move the future callback threadpool up to the Interconnect. This fixes an issue caused by the future callback pool being shutdown from a thread in the same pool.  With `wait=True`, the caller of shutdown calls `join()` on all the threads in the pool.  If the calling thread is in the same pool, it fails due to not being able to join with itself.
By pulling this threadpool up to the Interconnect level allows the pool to be shutdown when the interconnect is stopped.

Move Future Callback Threadpool Up to Interconnect 

---

rest_api/sawtooth_rest_api/messaging.py
validator/sawtooth_validator/execution/executor.py

Catch and log any unhandled exceptions in the various threads of the executor.
Also, correct a cancelled error usage in the rest api

Capture Unhandled Exceptions in Executor

---

bin/run_tests
integration/sawtooth_integration/docker/test_event_broadcaster.yaml
integration/sawtooth_integration/tests/test_event_broadcaster.py
protos/events.proto
protos/validator.proto
validator/sawtooth_validator/journal/block_event_extractor.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/server/events/__init__.py
validator/sawtooth_validator/server/events/broadcaster.py
validator/sawtooth_validator/server/events/extractor.py
validator/sawtooth_validator/server/events/handlers.py
validator/sawtooth_validator/server/events/subscription.py
validator/tests/test_events/tests.py
validator/tests/test_journal/tests.py
validator/tests/test_receipt_store/tests.py

Creates the core components of the event subscription system within sawtooth and creates a BlockEventExtractor for generating block_commit events.
A couple things are missing:
1. Event catch-up
2. A "pull" system with supporting messages and handlers (similar to `StateDeltaGetEventsRequest`)
I will circle back and add these once transaction execution results exist.

Create core event system and block commit events

---

validator/sawtooth_validator/execution/scheduler_serial.py
validator/tests/test_scheduler/tests.py
validator/tests/test_scheduler/yaml_scheduler_tester.py

This commit also updates tests and testing framework to not set an
invalid transaction result and expect further transactions within
a batch.
STL-579

Update serial scheduler to fail fast on invalid batch

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/core.py

Instead the Authorization handler will notify gossip that a connection it initialized has been authorized in both directions. At that point gossip can either try to peer or request the peers of that connection depending on the temp stored endpoints. 
This fixes the timing issue where one validator sends a gossip messages before both directions are authorized causing an AuthorizationViolation to be sent and the connection to be closed.

Remove callback used for Gossip Peering

---

protos/authorization.proto
protos/validator.proto
validator/packaging/validator.toml.example
validator/sawtooth_validator/config/validator.py
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/cli.py
validator/sawtooth_validator/server/core.py
validator/tests/test_authorization_handlers/mock.py
validator/tests/test_authorization_handlers/test.py
validator/tests/test_config/tests.py

Also add the following to sawtooth_validator command line to change AuthType for network
sawtooth-validator -vv --network-auth challenge
Built on top of #822 Remove callback used for Gossip Peering

Implement Challenge Authorization

---

validator/sawtooth_validator/networking/interconnect.py

Shutdown future callback threadpool after connection stops, for cleaner
overall shutdown.

Reorder interconnect stop

---

validator/sawtooth_validator/execution/scheduler_parallel.py
validator/tests/test_scheduler/data/complex_batches_multiple_failures.yaml
validator/tests/test_scheduler/data/enclosing_writer_fails.yaml
validator/tests/test_scheduler/test_schedulers_with_yaml.py
validator/tests/test_scheduler/yaml_scheduler_tester.py

The main difference with the new yaml scheduler method is that it calls finalize after next_transaction.
There are some small fixes to the parallel scheduler: the fix having to do with predecessors was found from writing more yaml tests. There is also a fix to reduce iteration in finding the next available transaction.

New Yaml scheduler tester method

---

validator/sawtooth_validator/journal/chain.py

In the case of wrong genesis node, on_block_validated would be called
twice, resulting in an exception due to a double cleanup attempt.
Removing the call and relying on the exception to break the flow (which
results in the normal call), fixes the issue.

Remove extra on_block_validated call

---

validator/sawtooth_validator/journal/completer.py

If we have already send a request for a block or a batch, the completer should not send another request. 

Update Completer to not resend request for block/batches

---

validator/sawtooth_validator/networking/handlers.py
validator/tests/test_authorization_handlers/test.py

Reject connection to endpoints that are local interfaces. 

Enforce that public validator endpoints cannot contain interfaces

---

validator/sawtooth_validator/journal/block_cache.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/journal/journal.py
validator/sawtooth_validator/journal/responder.py
validator/sawtooth_validator/journal/timed_cache.py
validator/sawtooth_validator/state/batch_tracker.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/test_client_request_handlers/mocks.py
validator/tests/test_journal/tests.py

Adds the concept of purge frequency internally to TimedCaches. Every time a value is set, if the specified purge frequency has elapsed (default 30s), the cache will be purged. This removes the need to manually purge TimedCaches.
Updates all uses of TimedCaches (and BlockCaches) to take advantage of this behavior, and the BatchTracker class to use init parameters instead of global variables to configure the wait times. Also reduces the BatchTracker keep time from 1 hour, to 10 minutes.

Make TimedCaches self-purging, and improve BatchTracker's cache usage

---

bin/build_all
docker/track-and-trade-server
families/track_and_trade/server/api/index.js
families/track_and_trade/server/db/agents.js
integration/sawtooth_integration/docker/test_track_and_trade.yaml
integration/sawtooth_integration/tests/test_track_and_trade.py

This PR adds the `/agents` endpoint and adds the server and database to the T&T test.
Two TODOs:
1. The assertion that checks the `/agents` endpoint isn't as rigorous as it could be, as it doesn't assert anything about the records agents report on. The desired TP behavior regarding reporter authorization and transfer of ownership hasn't been thought through very well, so I'd like to put off testing that until we figure out exactly what it should do.
2. Currently transactions are submitted to the rest api. When possible, I'd like to convert the test to submit transactions directly to the server and cut out the rest api entirely if possible.

T&T /agents endpoint and DB testing

---

.gitignore
sdk/rust/Cargo.toml
sdk/rust/src/messaging/mod.rs
sdk/rust/src/messaging/stream.rs
sdk/rust/src/messaging/zmq_stream.rs

Introduce the Message Stream and ZQM implementation to the rust sdk. A
stream can create a `MessageReceiver` (which is simply a standard `mpsc`
receiver for inbound - that is, not replies -  message results), and a
`MessageSender`, which adds several send and reply methods, as well as
a close method.
The `MessageSender` is cloneable, so it can be cloned and safely used
across threads.  The `MessageReceiver` is not, and therefore must be
owned by one and only one thread. Any muliplexing is up to the user of
the receiver to add on top.
Note: This does *not* have socket monitoring.

Add ZMQ stream to Rust SDK

---

.gitignore
families/track_and_trade/client/package.json
families/track_and_trade/client/public/index.html
families/track_and_trade/client/scripts/compile_protos.js
families/track_and_trade/client/src/components/forms.js
families/track_and_trade/client/src/components/modals.js
families/track_and_trade/client/src/main.js
families/track_and_trade/client/src/services/api.js
families/track_and_trade/client/src/services/payloads.js
families/track_and_trade/client/src/services/transactions.js
families/track_and_trade/client/src/views/login_form.js
families/track_and_trade/client/src/views/signup_form.js
families/track_and_trade/client/webpack.config.js
families/track_and_trade/server/api/index.js
families/track_and_trade/server/blockchain/batcher.js
families/track_and_trade/server/blockchain/index.js
families/track_and_trade/server/db/state.js
families/track_and_trade/server/scripts/bootstrap_database.js

This PR builds out many client-side components and services in support of allowing users to signup and login.
- **API service**: sends HTTP requests to the server API with authorization
- **Payloads service**: encodes Protobuf payloads
- **Transactions service**: 
- wraps payloads in a signed transaction
- submits transactions to the API
- manages encryption and storage of private key
- **Signup form**: 
- creates a user in the db and a new Agent in the blockchain
- encrypts a new private key for escrow storage
- stores the auth token from the API
- **Login form**:  stores the auth token from the API
- **/info endpoint**: returns batcher pubkey and route info
- start up a validator at `tcp://localhost:4004`
- start up the T&T processor with `./bin/track-and-trade-tp`
- setup and start the …

Implement T&T client signup/login

---

validator/sawtooth_validator/networking/dispatch.py

A potential places where exception could be thrown and swallowed is in the future callback for "determine next".  Replacing the `partial` call with a wrapper function that performs a try/catch should highlight any errors that may occur during the "determine next" operation.

Catch Unhandled Exceptions on determine_next

---

.gitignore
docker/compose/sawtooth-seth-rpc.yaml
families/seth/rpc/Cargo.toml
families/seth/rpc/src/account.rs
families/seth/rpc/src/block.rs
families/seth/rpc/src/error.rs
families/seth/rpc/src/log.rs
families/seth/rpc/src/main.rs
families/seth/rpc/src/network.rs
families/seth/rpc/src/requests.rs
families/seth/rpc/src/transaction.rs

Creates the core request handling part of the rpc server and creates empty methods for all the calls that need to be implemented. Implements a few methods as well. Unit tests to follow later, but you can test manually with:
`./bin/build_all -l python -l rust`
`docker-compose -f docker/compose/sawtooth-seth-rpc.yaml`
`curl -d '{"jsonrpc": "2.0", "method": "eth_blockNumber", "id": 1}' -H "Content-Type: application/json" 0.0.0.0:3030`

STL-572 Initial Seth RPC Implementation

---

validator/sawtooth_validator/networking/dispatch.py

In order to figure out if the incoming message queue is becoming saturated, log the size of the queue after a there are more than 10 messages backed up.

Warn if dispatch queue is too large

---

families/track_and_trade/client/src/components/navigation.js
families/track_and_trade/client/src/fish_form.js
families/track_and_trade/client/src/main.js
families/track_and_trade/client/src/services/transactions.js
families/track_and_trade/client/src/views/dashboard.js
families/track_and_trade/client/src/views/login_form.js
families/track_and_trade/client/src/views/signup_form.js
families/track_and_trade/server/api/index.js

Places all FishNet components into a reusable layout including a navbar. Adds a Dashboard page with a description of the project.
**To Test:**
Start a validator at `tcp://localhost:4004`.
Then from the root sawtooth-core directory:
```
./bin/track-and-trade-tp -vv &
```
```
cd families/track_and_trade/server/
npm install
npm run init
rethinkdb &
PRIVATE_KEY='1111111111111111111111111111111111111111111111111111111111111111' node index.js &
```
```
cd ../client
npm install
npm run build
```
Now navigate to `http://localhost:3000/fish`. You should see a simple landing page with a description of the project. There should be a navbar above, with a _Login/Signup_ button to the left. Using the signup form should create a new user as before. Once logged in, you should see the _Add Fish_ link in …

Add navbar and dashboard page to T&T client

---

sdk/python/sawtooth_sdk/messaging/stream.py
sdk/python/sawtooth_sdk/workload/workload_generator.py
validator/sawtooth_validator/networking/interconnect.py

Iterating over a copy of the tasks prevents errors due to concurrent modifications of the underlying task list.

Iterate over Asyncio Tasks using a copy

---

sdk/python/sawtooth_sdk/messaging/stream.py
sdk/python/sawtooth_sdk/workload/workload_generator.py
validator/sawtooth_validator/networking/interconnect.py

To avoid concurrent modifications of the `all_tasks` set, wrap the call in a list before iterating.

Properly copy sets as lists

---

families/track_and_trade/client/src/components/navigation.js
families/track_and_trade/client/src/main.js

These links will all redirect to the dashboard as they have not been
implemented yet, but adding them will allow screenshhots to be taken
of the finished pages, including a finished (in appearance) navbar.
This will unblock some documentation tasks.
Screenshots of the completed navbars:
_Logged Out:_
_Logged In:_

Add placeholder links to FishNet navbar

---

docs/source/sysadmin_guide/permissioning.rst
validator/sawtooth_validator/gossip/permission_verifier.py
validator/sawtooth_validator/server/core.py
validator/tests/test_permission_verifier/tests.py

If a GossipMessage is recieved for a new block, and block's signer
pubkey matches the connections pubkey, check to see if they are
allowed to publish blocks by checking network.consensus.

Add new Network role network.consensus

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_block_publisher.py

This is the probable cause of the "poet_key_state is invalid: Incorrect padding" exception being raised in the publisher.

Fix lack of base64 encoding on dummy data

---

families/track_and_trade/client/src/services/payloads.js
families/track_and_trade/client/src/views/add_fish_form.js
families/track_and_trade/processor/sawtooth_track_and_trade/processor/handler.py

There were three bugs preventing new Record from being submitted:
Values/types were being set improperly in the fish form, Locations
were being set improperly in the client, and Locations were being
set improperly in the Transaction Processor. This commit fixes these.

Fix fish submission for T&T

---

docs/source/architecture.rst

Architecture doc needs to lead with State agreement. This is clear from
repeated questions from those ramping on sawtooth.

Reorder architecture toc in docs

---

families/track_and_trade/client/package.json
families/track_and_trade/client/public/index.html
families/track_and_trade/client/src/components/forms.js
families/track_and_trade/client/src/components/layout.js
families/track_and_trade/client/src/main.js
families/track_and_trade/client/src/services/api.js
families/track_and_trade/client/src/services/transactions.js
families/track_and_trade/client/src/views/agent_detail.js
families/track_and_trade/client/styles/main.scss

Adds an Agent detail page, accessible through the URL `http://localhost:3000/#!/agents/{PUBLIC KEY}`. This is just a public key and name for most Agents, but the logged in user, they will see additional profile information, and be able to edit it.
This closes [PR-658](https://jira.hyperledger.org/browse/STL-658)
_Screenshot_:
To test, follow the [setup instructions in PR-879](https://github.com/hyperledger/sawtooth-core/pull/879), and navigate to the profile page via the navbar.

Add Agent Detail Page to FishNet

---

validator/sawtooth_validator/journal/chain.py
validator/tests/test_journal/block_tree_manager.py
validator/tests/test_journal/mock_consensus.py
validator/tests/test_journal/tests.py

Previously the BlockValidator had used the chain_head of when the Block was
queued for validation. This caused wasted block validations, as if a Block
was earlier in the queue was determined to be the chain_head the later
would detect the change after it finished validation and would requeue
the validation. If that requeue was not at the front of the queue then
the same case would happen again.

BlockValidator now uses current chain_head when checking a block.

---

docs/source/app_developers_guide/docker.rst

rest of doc uses braces around argument to sample commands to indicate argument
Signed-off-by: crow15 <crowe.ny@gmail.com>

made example command consistent for arguments

---

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
consensus/poet/families/tests/test_tp_validator_registry.py
consensus/poet/families/tests/validator_reg_message_factory.py
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.i

Fix attestation verification report checking in the swig code to handle
exceptions raised logging the error rather than throwing a stack trace.

Allow out of date warnings in poet

---

protos/network.proto
validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/journal/responder.py
validator/sawtooth_validator/networking/interconnect.py
validator/tests/test_responder/tests.py

If the same message is received again drop the message. It has already been handled. 
Also includes increasing the keep time for caches in the completer and adding a check to make sure the send_last_message does not shutdown the server thread.

Add Nonces to Gossip Request Messages

---

families/track_and_trade/client/package.json
families/track_and_trade/client/src/components/data.js
families/track_and_trade/client/src/main.js
families/track_and_trade/client/src/services/parsing.js
families/track_and_trade/client/src/services/transactions.js
families/track_and_trade/client/src/views/list_fish.js
families/track_and_trade/client/src/views/property_detail.js
families/track_and_trade/client/styles/main.scss
families/track_and_trade/server/api/index.js
families/track_and_trade/server/blockchain/index.js

Adds a property detail page which lists a history of value updates, and if properly authorized displays a form to submit new updates. Currently includes a map for location, but no graph widget.
To test, follow the setup instructions in [PR-889](https://github.com/hyperledger/sawtooth-core/pull/889). Then signup a new user, create a new record, and navigate to the property detail url:
```
http://localhost:3000/fish/#!/properties/{RECORD ID}/{PROPERTY NAME}
```
_Screenshots:_

Add basic property detail page

---

families/track_and_trade/client/src/components/forms.js
families/track_and_trade/client/src/main.js
families/track_and_trade/client/src/services/payloads.js
families/track_and_trade/client/src/utils/records.js
families/track_and_trade/client/src/views/add_fish_form.js
families/track_and_trade/client/src/views/fish_detail.js
families/track_and_trade/client/src/views/list_fish.js
families/track_and_trade/server/db/records.js
families/track_and_trade/server/scripts/create_fish_type_batch.js

Add initial fish detail screen, which allows the user to transfer
ownership/custodianship, and update any property for which the user is
an authorized reporter.
Additionally,
- refactors common record-related items into `utils/records.js`
- fixes some linting issues

Add basic fish detail screen

---

families/track_and_trade/client/src/services/parsing.js
families/track_and_trade/client/src/views/add_fish_form.js
families/track_and_trade/client/src/views/fish_detail.js
families/track_and_trade/client/src/views/property_detail.js

All units now go through a limited set of parsing functions, ensuring floating point values get converted into integer millionths and back again and are displayed the same way.

Unify unit handling in FishNet

---

families/track_and_trade/client/package.json
families/track_and_trade/client/src/components/data.js
families/track_and_trade/client/src/views/property_detail.js

Line graphs will appear for any int/float type data. For tilt and shock, a line graph is used with a calculated "amplitude" value. Tilt's x/y values are converted into a quantity of movement with pythagorean's theorem, and Shock's accel/duration are converted to a degree of shock with simple division (shorter duration means greater shock).
_Screenshot_:

Add Line Graphs to Property Detail Page

---

families/seth/rpc/src/calls/logs.rs
families/seth/rpc/src/client.rs
families/seth/rpc/src/filters.rs
families/seth/rpc/src/main.rs

This commit adds implementation for the various `eth_new*Filter` calls
and `uninstallFilter`.  The filters are stored in a map by an ID that is
incremented with each creation.

Add create filter endpoints

---

families/seth/rpc/src/calls/block.rs
families/seth/rpc/src/calls/logs.rs
families/seth/rpc/src/client.rs

With a running seth rpc service, create a new block filter:
```
$  curl -H 'content-type: application/json' -d '{"jsonrpc": "2.0", "id": "curl", "method": "eth_newBlockFilter", "params": [] }' http://localhost:3030
{"jsonrpc":"2.0","result":"0x0","id":"curl"}
```
Test that it works (it will return no blocks, since it assumes you already know the current block):
```
$  curl -H 'content-type: application/json' -d '{"jsonrpc": "2.0", "id": "curl", "method": "eth_getFilterChanges", "params": ["0x0"] }' http://localhost:3030
{"jsonrpc":"2.0","result":[],"id":"curl"}
```
Submit a transaction (any that will produce a new block will do) and then repeat the above call.  You should get a block id in the response:
```
$  curl -H 'content-type: application/json' -d '{"jsonrpc": "2.0", "id": "curl", …
```

Implement eth_getFilterChanges for block filters.

---

families/track_and_trade/client/src/services/api.js
families/track_and_trade/client/src/views/login_form.js
families/track_and_trade/client/src/views/signup_form.js

With this change, the server will never see a plain text persion
of FishNet's password. Even a completely compromised server would
be unable to decrypt a FishNet user's private key.

Hash client password before sending to server

---

families/seth/rpc/src/calls/logs.rs

This commit returns the log events, regardless of filter values.  The
events are transformed into the correct JSON values for viewing, but not
filtered based on topics or address, as specified by calls to
`eth_newFilter` or the filter values provided directly to the method.

Return logs from eth_getFilterChanges, etc (Part 1 of 2)

---

families/track_and_trade/client/src/views/fish_detail.js
families/track_and_trade/client/src/views/list_agents.js
families/track_and_trade/client/src/views/list_fish.js
families/track_and_trade/client/src/views/property_detail.js
families/track_and_trade/server/db/records.js
families/track_and_trade/server/package.json
families/track_and_trade/server/scripts/example_fish_updates.json
families/track_and_trade/server/scripts/update_example_data.js

This PR adds a new script which can update seeded FishNet data at regular intervals, as well as data refreshing on the client, to allow for live demos.
If running for very long, it has a tendency to encounter a difficult to nail down bug with state delta importing. Everything will continue to run, but you may see unusual values in state. By default the script will stop after submitting 25 sets of updates over 250s, which should be reasonably safe.

Live Demo for FishNet

---

sdk/examples/noop_python/sawtooth_noop/client_cli/workload.py

#881 with the obligatory signoff
Added missing imports:
* import getpass
* from base64 import b64encode
Signed-off-by: Chris Clauss <cclauss@bluewin.ch>

Add missing imports

---

sdk/examples/intkey_jvm_sc/sawtooth_intkey/cli/load.py

LOGGER is used on lines 49, 52, 55, and 57.  Without this change NameError might be raised at runtime.
Signed-off-by: Chris Clauss cclauss@bluewin.ch

import logging and define LOGGER

---

docker/sawtooth-dev-go

A pull request was merged into the gomock repo that breaks it. This package is
not a runtime dependency, it is only used for tests, so just pin it to a
working, stable version. This can be reverted once the problem is addressed by
the gomock repository.

Pin gomock v1.0.0

---

docs/source/_static/version_switcher.js
docs/source/_templates/indexcontent.html

Note that as coded, this solution will only work at URLs starting
with https://sawtooth.hyperledger.orgs/docs/
Signed-off-by: Zac Delventhal <zac@bitwise.io>

Add a dynamic version selector to master docs

---

docs/source/_static/version_switcher.js
docs/source/_templates/indexcontent.html

Note that as coded, this solution will only work at URLs starting
with https://sawtooth.hyperledger.orgs/docs/
Signed-off-by: Zac Delventhal <zac@bitwise.io>

Add a dynamic version selector to 0-8 docs

---

validator/tests/test_completer/test.py

Implement  #882 in a way that satisfies the DCO bot.
Signed-off-by: cclauss <cclauss@bluewin.ch>

Remove unused method _generate_id()

---

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
families/battleship/sawtooth_battleship/processor/handler.py
families/block_info/sawtooth_block_info/processor/handler.py
families/identity/sawtooth_identity/processor/handler.py
families/settings/sawtooth_settings/processor/handler.py
sdk/examples/intkey_python/sawtooth_intkey/processor/handler.py
sdk/examples/xo_python/sawtooth_xo/processor/handler.py
sdk/python/sawtooth_sdk/processor/handler.py

The other SDKs have an interface defined for TransactionHandlers, but python did not. This PR adds an Abstract Base Class that all TransactionHandlers should inherit from. It also updates the ValidatorRegistryTransactionHandler to expect context instead of state.

Add TransactionHandler Abstract Base Class to Python SDK

---

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py

Replace workaround that wrote an empty value to a state address with the delete
method so that the address is actually expunged from state.

Update validator registry to use state delete

---

validator/sawtooth_validator/server/core.py

Before the network thread pool was being used. It should be using
the client thread pool.

Switch thread pool used for client batch structure verification

---

bin/run_docker_test
bin/run_lint
validator/tests/test_completer/test.py
validator/tests/test_journal/tests.py

I got sick of searching through `run_docker_test`'s output to find which test failed.
```
Removing 5459c35180f3a1eff0d229556e579892c40b0b97b3db022e8ea3c0ba8c41225e_rest-api_1 ... [32mdone[0m
[2B[4A[2K
Removing 5459c35180f3a1eff0d229556e579892c40b0b97b3db022e8ea3c0ba8c41225e_intkey-tp-java_1 ... [32mdone[0m
[4BRemoving network 5459c35180f3a1eff0d229556e579892c40b0b97b3db022e8ea3c0ba8c41225e_default
/data/jenkins/workspace/jenkins-Sawtooth-Hyperledger-sawtooth-core-PR-1012-8
INFO:__main__:Bringing up with ['docker-compose', '-p', '5459c35180f3a1eff0d229556e579892c40b0b97b3db022e8ea3c0ba8c41225e', '-f', './sdk/examples/xo_python/tests/test_tp_xo_java.yaml', 'up', '--abort-on-container-exit']
Creating network "5459c35180f3a1eff0d229556e579892c40b0b97b3db022e8ea3c0ba8c41225e_default" …
```

Make run_docker_test output more helpful

---

families/smallbank/smallbank_go/src/sawtooth_smallbank/handler/handler.go
sdk/examples/intkey_go/src/sawtooth_intkey/handler/handler.go
sdk/examples/xo_go/src/sawtooth_xo/handler/handler.go
sdk/go/src/sawtooth_sdk/processor/context.go
sdk/go/src/sawtooth_sdk/processor/errors.go
sdk/go/src/sawtooth_sdk/processor/worker.go
sdk/javascript/processor/context.js
sdk/javascript/processor/exceptions.js
sdk/javascript/processor/index.js
sdk/python/sawtooth_sdk/processor/context.py
sdk/python/sawtooth_sdk/processor/core.py
sdk/python/sawtooth_sdk/processor/exceptions.py

This allows TransactionHandler to return a better error message if an AuthorizationException occurs. If the transaction handler does not handle the AuthorizationException, the transactor processor will return an InvalidTransaction by default. 
This also fixes the issue where if an AuthorizationException occurs in go, many transaction handlers return an InternalError, when it should return an Invalid Transaction error. This is fixed by returning the error received and relying on the defaults to handle the error correctly.

Return AuthorizationException from Context

---

validator/tests/test_journal/block_tree_manager.py

This reformulation makes the test against basestring unnecessary (and avoids backslash line termination).
Signed-off-by: cclauss <cclauss@bluewin.ch>

basestring was removed from Python 3

---

bin/run_tests
integration/sawtooth_integration/docker/test_poet_liveness.yaml
integration/sawtooth_integration/tests/poet_liveness_data/poet-settings.sh
integration/sawtooth_integration/tests/poet_liveness_data/validator-0.toml
integration/sawtooth_integration/tests/poet_liveness_data/validator-1.toml
integration/sawtooth_integration/tests/poet_liveness_data/validator-2.toml
integration/sawtooth_integration/tests/poet_liveness_data/validator-3.toml
integration/sawtooth_integration/tests/poet_liveness_data/validator-4.toml
integration/sawtooth_integration/tests/test_poet_liveness.py

The existing PoET Smoke Test is not a sufficient test for gating PRs. This test
simulates the long running network test environment using docker containers and
verifies the validators reach a certain block in consensus within the test
timelimit while ensuring blocks have batches in them.
The PoET settings and validator configuration are identical to the LR1 network
test.
To run the test locally, do:
`./bin/run_docker_test test_poet_liveness`

Create PoET Liveness Test

---

docs/source/cli/sawtooth.rst

Also correct the literalinclude line for "sawtooth identity role create"
(it was pulling in the usage output for "sawtooth identity policy create").

Add "sawtooth identity role" to CLI Reference doc

---

families/identity/protos/identities.proto
families/private_utxo/protos/payload.proto
families/seth/rpc/src/client.rs
families/seth/src/protos/seth.proto
families/settings/protos/settings.proto
families/smallbank/protos/smallbank.proto
families/supplychain/protos/application.proto
families/supplychain/protos/payload.proto
protos/authorization.proto
protos/client_batch.proto
protos/client_batch_submit.proto
protos/client_block.proto
protos/client_event.proto
protos/client_receipt.proto
protos/client_state.proto
protos/client_transaction.proto
protos/events.proto
protos/identity.proto
protos/network.proto
protos/processor.proto
protos/state_context.proto
protos/state_delta.proto
protos/transaction_receipt.proto
sdk/javascript/processor/index.js

This will avoid the issues where the default, the first option, is automatically set in a protobuf enum and causes a false positive or negative.
Also, fixes the javascript SDK to set TpProcessResponse status to OK correctly. 
It was working before because of the false positive mentioned above.

Adds an UNSET option to all protobuf enums

---

validator/sawtooth_validator/execution/scheduler_parallel.py
validator/sawtooth_validator/execution/scheduler_serial.py

Cancel is called when, during block publishing, the validator receives
a new chain head and stops the construction of that candidate block
because the predecessor is a different block, with a different state
root hash. No new merkle root will be constructed out of contexts
in the context manager, but they need to be cleaned up. This commit
adds a call to squash with persist=False, and cleanup=True in .cancel.

Fix memory leak in schedulers when .cancel is called

---

integration/sawtooth_integration/tests/test_events_and_receipts.py
validator/sawtooth_validator/server/events/broadcaster.py
validator/sawtooth_validator/server/events/handlers.py
validator/tests/test_events/tests.py

The StateDeltaProcessor would send events to a client since the last block they knew about. This PR adds similar functionality to the EventBroadcaster for events.

Implement catchup for EventBroadcaster

---

bin/run_go_fmt
integration/sawtooth_integration/docker/test_xo_smoke_go.yaml
integration/sawtooth_integration/docker/test_xo_smoke_javascript.yaml
integration/sawtooth_integration/docker/test_xo_smoke_python.yaml
integration/sawtooth_integration/tests/test_xo_smoke.py
sdk/examples/xo_go/src/sawtooth_xo/handler/handler.go
sdk/examples/xo_javascript/xo_handler.js
sdk/examples/xo_python/sawtooth_xo/processor/handler.py
sdk/examples/xo_python/sawtooth_xo/xo_cli.py
sdk/examples/xo_python/sawtooth_xo/xo_client.py
sdk/go/src/sawtooth_sdk/processor/context.go
sdk/javascript/processor/context.js
sdk/javascript/protobuf/index.js

This PR adds state delete to the Go and JS SDKs. It also adds a game delete transaction to xo in order to test state deletes. (This transaction is not in the xo transaction family spec, so it should be considered a nonstandard extension for now.)

State delete in JS and Go

---

families/settings/sawtooth_settings/processor/main.py

settings_tp wasn't printing microseconds so its messages weren't aligned
with validator logging. This is the worst travesty to befall any
codebase ever, but I fixed it. Probably.

Update settings log formatting to match validator

---

validator/sawtooth_validator/execution/scheduler_parallel.py
validator/sawtooth_validator/execution/scheduler_serial.py

Cancel is called when, during block publishing, the validator receives
a new chain head and stops the construction of that candidate block
because the predecessor is a different block, with a different state
root hash. No new merkle root will be constructed out of contexts
in the context manager, but they need to be cleaned up. This commit
adds a call to squash with persist=False, and cleanup=True in .cancel.

Back-port memory leak fix to 0-8

---

docs/source/architecture/events_and_transactions_receipts.rst
families/seth/rpc/src/transactions.rs
families/seth/rpc/tests/test_seth_rpc.py
families/seth/src/sawtooth_seth/client/client.go
families/seth/src/sawtooth_seth/client/response.go
families/seth/src/sawtooth_seth/processor/handler/handler.go
protos/identity.proto
protos/state_context.proto
protos/transaction_receipt.proto
rest_api/openapi.yaml
sdk/go/src/sawtooth_sdk/processor/context.go
sdk/go/tests/state_test.go
sdk/python/sawtooth_sdk/processor/context.py
sdk/python/tests/test_context.py
validator/sawtooth_validator/execution/context_manager.py
validator/sawtooth_validator/execution/execution_context.py
validator/sawtooth_validator/execution/tp_state_handlers.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/server/cli.py
validator/tests/test_context_manager/tests.py
validator/tests/test_receipt_store/tests.py

Also, changes Type in Policy to EntryType.
Removing Data from TransactionReceipt removes extra info and remove the awkward to need to do TransactionReceipt.data[0].data

Remove Data from TransactionReciept and replace with bytes

---

docker/sawtooth-int-identity-tp
docker/sawtooth-int-intkey-tp-cxx
docker/sawtooth-int-intkey-tp-go
docker/sawtooth-int-intkey-tp-python
docker/sawtooth-int-noop-tp-go
docker/sawtooth-int-poet-validator-registry-tp
docker/sawtooth-int-settings-tp
docker/sawtooth-int-smallbank-tp-go
docker/sawtooth-int-xo-tp-go
docker/sawtooth-int-xo-tp-python

The CLIs were updated to use -C ahead of the validator connection
string. Update the dockerfile default commands to include that flag.

Fix docker CMDs to use connection flag

---

sdk/rust/src/signing/secp256k1.rs

Fixes the following warning when building the SDK:
```
Compiling sawtooth_sdk v0.1.0 (file:///Users/adk/Workspace/Blockchain/sawtooth-core/sdk/rust)
warning: variable does not need to be mutable
--> src/signing/secp256k1.rs:137:13
|
137 |         let mut hash: &mut [u8] = & mut [0; 32];
|             ^^^^^^^^
|
= note: #[warn(unused_mut)] on by default
warning: variable does not need to be mutable
--> src/signing/secp256k1.rs:152:13
|
152 |         let mut hash: &mut [u8] = & mut [0; 32];
|             ^^^^^^^^
```

Remove unused mutable declaration

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/networking/interconnect.py

also back ports a duplicate check when adding pending blocks

Backport safe send during authorization to 0-8

---

consensus/poet/families/sawtooth_validator_registry/validator_registry/processor/handler.py
docs/source/_templates/sdk_TP_tutorial.rst
families/battleship/sawtooth_battleship/processor/battleship_transaction.py
families/identity/sawtooth_identity/processor/handler.py
families/seth/src/sawtooth_seth/processor/handler/handler.go
families/settings/sawtooth_settings/processor/handler.py
families/smallbank/smallbank_go/src/sawtooth_smallbank/handler/handler.go
protos/processor.proto
sdk/cxx/include/sawtooth/transaction_handler.h
sdk/cxx/src/transaction_processor.cpp
sdk/examples/xo_go/src/sawtooth_xo/handler/handler.go
sdk/examples/xo_java/XoHandler.java
sdk/examples/xo_javascript/xo_handler.js
sdk/examples/xo_python/sawtooth_xo/processor/handler.py
sdk/go/src/sawtooth_sdk/processor/worker.go
sdk/java/src/main/java/sawtooth/sdk/processor/TransactionProcessor.java
sdk/javascript/processor/index.js
sdk/python/sawtooth_processor_test/message_factory.py
sdk/python/sawtooth_sdk/processor/core.py
validator/sawtooth_validator/execution/executor.py

Previously the header was bytes, requiring TP handlers to go through
the extra step of deserializing it before being able to access it.
Addresses https://jira.hyperledger.org/browse/STL-817

Make TpProcessRequest header unserialized

---

docs/source/transaction_family_specifications/settings_transaction_family.rst

Also: In Execution section, formatted the accept/reject info with bullets for clarity.

Fix defn + add default for vote.approval_threshold

---

perf/smallbank_workload/src/playlist.rs

Fixes issue generating smallbank playlist of transactions where the initial account creation txn does not have its type set, causing this error:
```
$ smallbank_workload playlist create -a 3 -n 1 -o smallbank_playlist.yaml
thread 'main' panicked at 'Unset payload type: create_account {customer_name: "customer_000000" initial_savings_balance: 1000000 initial_checking_balance: 1000000}', src/playlist.rs:358:16
stack backtrace:
0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
1: std::panicking::default_hook::{{closure}}
2: std::panicking::default_hook
3: std::panicking::rust_panic_with_hook
4: std::panicking::begin_panic
5: std::panicking::begin_panic_fmt
6: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
7: smallbank_workload::main
8: __rust_maybe_catch_panic
9: …
```

Set CREATE_ACCOUNT payload type for smallbank workload

---

protos/state_context.proto
sdk/cxx/src/global_state.cpp
sdk/go/src/sawtooth_sdk/processor/context.go
sdk/java/src/main/java/sawtooth/sdk/processor/State.java
sdk/javascript/processor/context.js
sdk/javascript/protobuf/index.js
sdk/python/sawtooth_processor_test/message_factory.py
sdk/python/sawtooth_sdk/processor/context.py
sdk/python/tests/test_context.py
validator/sawtooth_validator/execution/tp_state_handlers.py

The change makes the Entry message consistently named with the `TpState-` prefix that the rest of the messages in `state_context`

Renamed state_context Entry to TpStateEntry

---

consensus/poet/sgx/packaging/poet_enclave_sgx.toml.example
rest_api/packaging/rest_api.toml.example
validator/packaging/path.toml.example
validator/packaging/validator.toml.example

- Change "Sawtooth Lake" to "Sawtooth".
- Add a "title" comment to poet_enclave_sgx.toml.example
to match the others.

Fix top comment in config files

---

bin/build_all

The `$build_dir` variable is not set, and the directory is not created, for the *rust* language version of `bin/build_all` causing the following error.
```
$ ./bin/build_all -l rust installed
[--- Build mode: installed ---]
[--- Building rust ---]
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
```

Create the build_dir directory for Rust

---

validator/sawtooth_validator/journal/chain.py
validator/tests/test_journal/mock_consensus.py
validator/tests/test_journal/tests.py

This reverts commit 7aa1248e88aabac59a7a3cfa7ea6644045008c1f.
An intermittent bug was discovered on LR7 after this commit was merged into
master.

Revert "Skip batch validation if not committing a fork"

---

docs/source/app_developers_guide/ubuntu.rst

Per Dan and Shawn, there's no need to run sawtooth commands as root (that is, at a # prompt) 
in "Using Sawtooth on Ubuntu 16.04" in the Application Developer's Guide.  

Change doc: Don't need root prompt for ubuntu proc

---

consensus/poet/cli/sawtooth_poet_cli/genesis.py

Add optional batch argument so you can create a poet registry enrollment
transaction from the CLI beyond the genesis block.

Add batch option to poet genesis CLI

---

docs/source/architecture/validator_network.rst
docs/source/sysadmin_guide.rst
docs/source/sysadmin_guide/configuring_sawtooth.rst
docs/source/sysadmin_guide/configuring_sawtooth/path_configuration_file.rst
docs/source/sysadmin_guide/configuring_sawtooth/poet_sgx_enclave_configuration_file.rst
docs/source/sysadmin_guide/configuring_sawtooth/rest_api_configuration_file.rst
docs/source/sysadmin_guide/configuring_sawtooth/validator_configuration_file.rst
docs/source/sysadmin_guide/log_configuration.rst
docs/source/sysadmin_guide/permissioning.rst
docs/source/sysadmin_guide/systemd.rst

- Added new "Configuring Sawtooth" section to the sys admin guide.
This section currently documents the validator, REST API,
PoET SGX enclave, and path config files.
- Changed "Log Configuration" to point to the path config info;
removed duplicated path & config info, deleted obsolete Windows
info, and edited wording and formatting.
- Moved text about the old-style /etc/default config files from "Running Sawtooth As A Service" 
(systemd.rst) to the "Configuring Sawtooth" intro (configuring_sawtooth.rst).

Document config files in new "Configuring Sawtooth" section

---

docker/compose/sawtooth-local.yaml
validator/sawtooth_validator/state/client_handlers.py

Reduce the default page size for client list requests to 100.  This will improve the perceived experience of list calls by reducing the amount of objects that have to be deserialized in a given request. 1000 items is still the max page size.

Reduce default page size

---

rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py

Blanket CORS approval represents a security vulnerability and
should be removed previous to 1.0. The REST API is intended to
be lightweight, and features like authentication or CORS should
be handled by a proxy server when needed.

Remove CORS handlers from REST API

---

perf/sawtooth_perf/Cargo.toml
perf/sawtooth_workload/Cargo.toml
perf/smallbank_workload/Cargo.toml

Remove extraneous dependencies from rust performance projects.

Cleanup crates

---

docs/source/architecture/validator_network.rst
protos/authorization.proto
validator/sawtooth_validator/networking/handlers.py
validator/sawtooth_validator/networking/interconnect.py
validator/sawtooth_validator/server/network_handlers.py
validator/tests/test_authorization_handlers/test.py

Before the payload was included in the response from the authorizing
connection and was trusted without any verification. Instead, the
payload should be stored by the validator and only the signature
returned by the authorizing connection.

Store challenge auth payload in cache

---

docs/source/cli.rst
docs/source/cli/identity-tp.rst
docs/source/cli/intkey.rst
docs/source/cli/poet.rst
docs/source/cli/rest_api.rst
docs/source/cli/sawadm.rst
docs/source/cli/sawset.rst
docs/source/cli/sawtooth.rst
docs/source/cli/settings-tp.rst
docs/source/cli/validator.rst
docs/source/cli/xo.rst

- Add sections for settings-tp and identity-tp
- Edit the doc-only text for consistency and clarity
- Add the command name to section title if significantly different
- Remove subsections from "sawadm genesis" (Overview, Output etc.)
to be consistent - the other commands don't have subsections

Add TP cmds to CLI reference; edit doc-only text

---

cli/sawtooth_cli/rest_client.py
docs/source/architecture/rest_api.rst
families/battleship/sawtooth_battleship/battleship_client.py
integration/sawtooth_integration/tests/intkey_client.py
integration/sawtooth_integration/tests/test_events_and_receipts.py
rest_api/openapi.yaml
rest_api/sawtooth_rest_api/rest_api.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_receipt_requests.py
rest_api/tests/unit/test_submit_requests.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_client.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/workload/workload_generator.py
sdk/examples/xo_python/sawtooth_xo/xo_client.py
validator/tests/test_client_request_handlers/test_submit_handlers.py

This change to the API better reflects both RESTful expectations and the nature of the route, which is to return multiple BatchStatus resources.

Rename REST API's /batch_status to /batch_statuses

---

.gitignore
ci/sawtooth-build-docs
docs/Makefile

This PR adds generated HTML pages for the Python, Go, and JS SDKs to the build process. This requires modifying both the Makefile and the docs Docker file. I know little about either of these, so there are almost certainly errors here.
Note that the API docs are just generated and stored in the `build` directory, not integrated into the published docs.
Unrelated to docs, I found that the `.gitignore` file had old entries in it. Those bothered me, so I took them out.

Add generated API docs to build

---

bin/get_version

This adds support for tags like 'v1.0.0rc1' and fixes some PEP8/python2/3 issues.

Get version fixes

---

docs/source/rest_api/error_codes.rst
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_receipt_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_submit_requests.py
rest_api/tests/unit/test_txn_requests.py
validator/sawtooth_validator/database/indexed_database.py
validator/sawtooth_validator/journal/block_store.py
validator/tests/test_client_request_handlers/mocks.py
validator/tests/test_client_request_handlers/test_batch_handlers.py
validator/tests/test_client_request_handlers/test_block_handlers.py
validator/tests/test_client_request_handlers/test_peer_handler.py
validator/tests/test_client_request_handlers/test_state_handlers.py
validator/tests/test_client_request_handlers/test_submit_handlers.py
validator/tests/test_client_request_handlers/test_txn_handlers.py

This PR fixes the bug, where the validator could be caused to raise an error if sent an empty string as a batch id.
It also adds a validation to all input ids, checking to make sure they are 128 character hex strings.

Fix REST API hanging bug, validate ids

---

protos/client_list_control.proto
rest_api/openapi.yaml
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/sawtooth_rest_api/state_delta_subscription_handler.py
rest_api/tests/unit/components.py
rest_api/tests/unit/test_batch_requests.py
rest_api/tests/unit/test_block_requests.py
rest_api/tests/unit/test_state_requests.py
rest_api/tests/unit/test_txn_requests.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/test_client_request_handlers/base_case.py
validator/tests/test_client_request_handlers/test_batch_handlers.py
validator/tests/test_client_request_handlers/test_block_handlers.py
validator/tests/test_client_request_handlers/test_state_handlers.py
validator/tests/test_client_request_handlers/test_txn_handlers.py

Update paging to only have use start which should be an start id and
limit which is the number to be returned. The response will only
contain next.
Sort endpoint is changed to /reverse, compare_lengths have been
removed. When reversing, it is done by the order they are returned
from the blockstore and the key used is "default"

Update the paging and sort controls in the Rest API

---

ci/sawtooth-build-docs
docs/Makefile
docs/source/contents.rst
docs/source/sdks.rst
sdk/python/sawtooth_sdk/processor/__init__.py

This PR adds a file that links to the published nightly docs. This will work for now, but a better way should be figured out.

Add links to API docs

---

bin/generate_cli_output
cli/sawtooth_cli/admin_command/genesis.py
cli/sawtooth_cli/admin_command/keygen.py
cli/sawtooth_cli/batch.py
cli/sawtooth_cli/block.py
cli/sawtooth_cli/identity.py
cli/sawtooth_cli/keygen.py
cli/sawtooth_cli/main.py
cli/sawtooth_cli/parent_parsers.py
cli/sawtooth_cli/sawadm.py
cli/sawtooth_cli/sawset.py
cli/sawtooth_cli/settings.py
cli/sawtooth_cli/state.py
cli/sawtooth_cli/transaction.py
consensus/poet/cli/sawtooth_poet_cli/enclave.py
consensus/poet/cli/sawtooth_poet_cli/main.py
consensus/poet/cli/sawtooth_poet_cli/registration.py
docs/source/cli/xo.rst
families/block_info/sawtooth_block_info/processor/main.py
families/identity/sawtooth_identity/processor/main.py
families/settings/sawtooth_settings/processor/main.py
rest_api/sawtooth_rest_api/rest_api.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_cli.py
sdk/examples/xo_python/sawtooth_xo/xo_cli.py
validator/sawtooth_validator/server/cli.py

Made usage text consistent by starting option descriptions with an imperative verb, "positional arguments" with a noun, and subcommand descriptions with an initial-capped verb in 3rd person singular.
Note: For the xo parent command, deleted the subcommand-only options (moved them into the subcommands).
Also added the missing "xo delete" subcommand to CLI reference doc.

Edit CLI usage for consistency, spelling, grammar, etc.

---

bin/run_tests
integration/sawtooth_integration/docker/test_namespace_permission.yaml
integration/sawtooth_integration/tests/test_namespace_permission.py
validator/sawtooth_validator/execution/executor.py

We propose to modify the validator to enforce namespace permission declared on-chain. The change has its own test added to the `run_tests` script.
Signed-off-by: Benoit Razet <benoit.razet@pokitdok.com>

transaction family namespace permission checked by the validator

---

protos/client_batch.proto
protos/client_batch_submit.proto
protos/client_block.proto
protos/client_receipt.proto
protos/client_transaction.proto
validator/sawtooth_validator/journal/block_store.py
validator/sawtooth_validator/state/client_handlers.py
validator/tests/test_client_request_handlers/test_batch_handlers.py
validator/tests/test_client_request_handlers/test_block_handlers.py
validator/tests/test_client_request_handlers/test_submit_handlers.py
validator/tests/test_client_request_handlers/test_txn_handlers.py

Adding RegEx checks to the block store creates unnecessary performance overhead. These checks have been moved to just validate client input.
A new return status has been added to the client protos to reflect invalid id input.

Refactor validator id checks to just client input

---

ci/sawtooth-publish-js-sdk

normally the newest version is tagged latest
here we tag latest stable version so development
versions are not installed by default

Tag the stable version 'latest'

---

.gitignore
docker/sawtooth-dev-go
docs/Makefile
docs/source/conf.py
docs/source/sdks.rst
signing/sawtooth_signing/core.py

The pydoc API docs were ugly and broken, but it turns out that Sphinx can be used instead.
Unrelated to that, I added a commit to fix a version compatibility hack in `sawtooth-dev-go`.

 Use Sphinx for Python API docs

---

docs/source/_templates/partials/submitting_to_validator.rst
docs/source/_templates/sdk_submit_tutorial.rst

Since the Encoders have been removed from the SDK's, replace the usage
in the documentation with the basic protobuf messages.

Replace encoder with basic protobuf/signer doc

---

cli/sawtooth_cli/identity.py
cli/sawtooth_cli/sawset.py
consensus/poet/cli/sawtooth_poet_cli/registration.py
validator/sawtooth_validator/server/keys.py

Make the same fix in four different files where we are catching a ParseError and then re-raising it.  In the except statement, we need to capture the exception into the variable in __e__ so that we can re-raise it in the lines immediately following.  Without this change, we would raise a NameError instead of the intended exception.
Discovered via [flake8](http://flake8.pycqa.org) testing of https://github.com/hyperledger/sawtooth-core on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./cli/sawtooth_cli/identity.py:567:76: F821 undefined name 'e'
raise CliException('Unable to read key in file: {}'.format(str(e)))
^
./cli/sawtooth_cli/sawset.py:290:76: F821 undefined name 'e'
raise CliException('Unable to read key in file: …
```

except ParseError: --> except ParseError as e:

---

rest_api/sawtooth_rest_api/state_delta_subscription_handler.py

Typo in state_delta_subscription handler that prevents the state-delta
to work.
Signed-off-by: Benoit Razet <benoit.razet@pokitdok.com>

Bugfix in rest-api state-delta

---

docs/source/architecture/journal.rst
validator/sawtooth_validator/journal/block_cache.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/journal/timed_cache.py
validator/sawtooth_validator/server/core.py
validator/tests/test_block_cache/tests.py
validator/tests/test_completer/test.py
validator/tests/test_journal/tests.py

If a block has a count above 0, it will not be purged from the catch.
Also, catch KeyErrors in _validate_permissions and _validate_on_chain_rules and update the completer to check if the journal has the predecessor for the block it is verifying.

Add Reference Counting  to BlockCache

---

validator/sawtooth_validator/journal/block_wrapper.py
validator/sawtooth_validator/journal/chain.py

This fixes a bug where receipts were only created for the latest block
on a fork when a new fork is chosen.

Create receipts for all blocks on a new fork

---

bin/run_tests
validator/sawtooth_validator/config/validator.py
validator/tests/test_config/tests.py

This reverts commit bacfcae1310df319f32e28f3470bd98ebcc9ffe4 and also disables the network permissioning test.
The parallel scheduler change has seemingly introduced some occasional test failures in master. More testing is required.

Revert "Change default scheduler from serial to parallel" and disable network permissioning test

---

validator/sawtooth_validator/concurrent/atomic.py
validator/sawtooth_validator/journal/block_scheduler.py
validator/sawtooth_validator/journal/block_validator.py
validator/sawtooth_validator/journal/block_wrapper.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/journal/chain_commit_state.py
validator/sawtooth_validator/journal/completer.py
validator/sawtooth_validator/server/core.py
validator/tests/test_journal/tests.py

This PR makes some additional architectural changes required to decouple the block validator from the chain controller.
Next steps are:
1. Move `ForkResolutionResult` from block validator to chain controller, along with required methods.
2. Only validate the given block in `process_block_validation`
3. Improve separation between completer, block scheduler, block validator, and chain controller using queues.

(consensus-prototype) Create BlockValidationScheduler and rewrite ChainCommitState

---

ci/sawtooth-build-debs
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.h
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/poet_enclave.i
consensus/poet/sgx/sawtooth_poet_sgx/poet_enclave_sgx/wait_certificate.cpp
consensus/poet/sgx/setup.py

Wait certificates are intended to be verifiable outside of an enclave.
The python portion of PoET took this on to verify the NIST 256p ECDSA
signature created in the enclave using the SGX SDK. It used an ECC library
available for python. Sawtooth security reviewers did not have time
to review that library ahead of Sawtooth's planned 1.0 release and it
was not yet listed in available whitelists. It was deemed more secure
in the near term not to use the python ecdsa library until reviewers
can gain more familiarity with it.
As such this commit reverts wait certificate signature verification to
use the SGX SDK's ECC library call.
This commit does not preclude an observer node verifying wait
certificates using its own ECC lib without SGX.

Remove python3-ecdsa dependency from PoET

---

validator/sawtooth_validator/journal/block_cache.py

Need to Handle the special case for NULL_BLOCK_IDENTIFIER used in the completer block_cache.

Handle special case for NULL_BLOCK_IDENTIFIER in block_cache

---

validator/sawtooth_validator/journal/event_extractors.py

Reproducable by subscribing to sawtooth/state-delta events with a RegEx filter and submitting a state change that doesn't match.

Fix bug where not matching a txn family would crash event reporting

---

CONTRIBUTING.md
docs/source/community/issue_tracking.rst

Change old names in the documentation (two *.rst files)
and a README-type Markdown file.

Fix old URLs & names (Distributed Ledger & Sawtooth Lake)

---

validator/sawtooth_validator/server/events/subscription.py
validator/tests/test_events/tests.py
validator/tests/test_journal/tests.py

Remove EventFilterType, as this shadows the EventFilter.FilterType enum
defined in the protobuf message. As the protobuf message is the source
of truth for the value of those enums, the shadowed type opens up the
possibility of subtle bugs with mismatched enum values.  Replacing this
type with the message enum corrects the problem

Remove EventFilterType

---

consensus/poet/core/tests/test_consensus/test_wait_certificate.py
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_enclave/poet_enclave.cpp
validator/sawtooth_validator/journal/block_wrapper.py

Update NULL_BLOCK_IDENTIFIER to be 128 characters long.

---

cli/sawtooth_cli/admin_command/keygen.py
cli/sawtooth_cli/keygen.py
validator/packaging/ubuntu/postinst

This prevents sawtooth and other users from being
able to read private keys while allowing the group
to read them.
create ~/.sawtooth in a way that it is not group
writable and further restrict the keys there.

Prevent users from writing to /etc/sawtooth

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/journal/block_cache.py
validator/sawtooth_validator/journal/chain.py

Block was being added in descending order (5, 4, 3, ..) but to correctly add reference counts they need to be added in ascending order.

Add block in correct order to block_cache

---

docs/source/app_developers_guide/ubuntu.rst

Corrections and clarifications from this week's test for 1.0rc4. 
- The first commit fixes errors, output, & formatting.  There's also some wording and header-level changes for clarification.
- The second commit reorganizes the transaction processor sections/steps to clarify what tasks the user must do and what is general/background information.  It also includes a new section on stopping Sawtooth components.

Fix Ubuntu install-and-run-Sawtooth procedure

---

consensus/poet/common/c11_support/linux/c11_support.cpp
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.cpp
sdk/c/c11_support.c

- Fixed wrong size zeroing in enclave.cpp file
- Removed extra code in c11_support.cpp/c files

Bug fixes on cxx code

---

docs/source/sysadmin_guide/configure_sgx.rst

- Set user, group, and mode on sgx certificate.
- Run sawadm keygen as root for new /etc/sawtooth permissions.
- Update sawtooth.poet.enclave_module_name.
- Restrict access to validator.toml

Update SGX documentation

---

consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/base64.cpp
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/base64.h
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.cpp
consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/poet.cpp

Remove unneeded includes from poet.cpp and enclave.cpp
Add modification notice to base64 source file required for license
attribution.
See also STL-398

Cleanup poet base64 includes and licensing

---

docs/source/sysadmin_guide/systemd.rst

Correct the --key-dir argument in the command to generate the sawtooth keys.

Fix typo in "sawtooth keygen" command

---

validator/sawtooth_validator/database/indexed_database.py
validator/sawtooth_validator/database/lmdb_nolock_database.py

Since our read workload is essentially random, read-ahead caching is unproductive. It causes extra read IO and replaces pages in the file system cache unnecessarily.

Disable LMDB read ahead caching

---

validator/sawtooth_validator/journal/block_validator.py
validator/sawtooth_validator/journal/chain.py
validator/sawtooth_validator/server/core.py
validator/tests/test_journal/mock_consensus.py
validator/tests/test_journal/tests.py

Because of all the architectural changes, the block validator and chain controller unit tests need some work. I am waiting to make those changes until I implement the block validation pipeline so that I don't have to make the changes twice and because I think it will be easier to write unit tests after all the components are in that pipeline.

Move fork resolution logic from block validator to chain controller

---

validator/sawtooth_validator/execution/scheduler.py
validator/sawtooth_validator/execution/scheduler_parallel.py
validator/sawtooth_validator/execution/scheduler_serial.py
validator/sawtooth_validator/journal/publisher.py
validator/tests/test_journal/mock.py
validator/tests/test_scheduler/tests.py

Add unschedule_incomplete_batches to the Scheduler interface.  This method is called on finalize_block in the BlockPublisher.
This method is implemented on both Serial and Parallel Schedulers.  In both, they preserve the following:
* Any injected batch will always be run
* A minimum schedule of at least one batch, not including injected batches.

Allow Publisher to Unschedule Incomplete Batches

---

validator/packaging/ubuntu/postinst

This change prevents the deb package from clobbering owner, group,
and mode of existing files /etc/sawtooth on package upgrade.
Inital install will remain the same.

Fix deb package postinst on upgrade

---

validator/packaging/ubuntu/postinst

Add a check that "$2" is not set. On an upgrade "$2"
is the previous package version, on a new install it's
undefined.

Fix postinst rules for validator package

---

perf/sawtooth_workload/src/main.rs
perf/smallbank_workload/src/main.rs

As the default key format changed to hex, the rust workload tools should try reading keys generated in hex format, and try WIF format as a fallback.

Workload: Read key as hex, and fallback to wif

---

consensus/poet/core/sawtooth_poet/poet_consensus/poet_fork_resolver.py
consensus/poet/core/tests/test_consensus/test_poet_fork_resolver.py
validator/sawtooth_validator/journal/chain.py

Adds more INFO level log messages around fork resolution to the chain controller and poet fork resolver. Sample output:
```
[2017-12-19 22:26:45.391 INFO     chain] Comparing current chain head 'a89fbefe(47, S:99ef9592, P:0df858fd)' against new block '17d09efa(47, S:99ef9592, P:0df858fd)'
[2017-12-19 22:26:45.392 INFO     chain] Fork comparison at height 47 is between a89fbefe and 17d09efa
[2017-12-19 22:26:45.397 INFO     poet_fork_resolver] Choose current fork a89fbefe over new fork 17d09efa: Current fork wait duration (3.980731) less than new fork wait duration (4.144106)
[2017-12-19 22:26:45.400 INFO     chain] on_block_validated: 17d09efa(47, S:99ef9592, P:0df858fd)
[2017-12-19 22:26:45.402 INFO     chain] Rejected new chain head: 17d09efa(47, S:99ef9592, P:0df858fd)
[2017-12-19 …
```

Improve logging around fork resolution

---

docs/source/rest_api/error_codes.rst
integration/sawtooth_integration/tests/intkey_client.py
protos/client_batch_submit.proto
rest_api/openapi.yaml
rest_api/sawtooth_rest_api/error_handlers.py
rest_api/sawtooth_rest_api/exceptions.py
rest_api/sawtooth_rest_api/route_handlers.py
rest_api/tests/unit/test_submit_requests.py
sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_workload.py
validator/sawtooth_validator/journal/back_pressure_handlers.py
validator/sawtooth_validator/journal/publisher.py
validator/sawtooth_validator/server/component_handlers.py
validator/sawtooth_validator/server/core.py
validator/sawtooth_validator/server/network_handlers.py

Introduces adaptive back pressure on the pending batch queue.  
The amount of batches allowed in the pending queue at any point in time is predicted using a rolling average of batches committed per block.  This is initialized to 30 (the equivalent to 1 transaction per second, with a 30 second wait time), and updated on each block commit.
New batches are rejected before any processing can take place if the pending batch queue exceeds 2 * the average, giving it a geometric increase in batches if all are committed.
Supersedes #1221

Introduce Adaptive Back Pressure to Pending Batches

---

validator/sawtooth_validator/server/cli.py

The default arg type is `str` causing the validator to crash if the min or max peer `--minimum-peer-connectivity` and `--maximum-peer-connectivity` arguments are set.

Set type of validator args for cli command

---

validator/sawtooth_validator/execution/tp_state_handlers.py
validator/sawtooth_validator/gossip/signature_verifier.py
validator/sawtooth_validator/gossip/structure_verifier.py
validator/sawtooth_validator/networking/interconnect.py

Following a suggestion of @jsmitchell in https://github.com/hyperledger/sawtooth-core/pull/1270, this PR gets rid of the following classes of frequently-logged messages:
* interconnect
```
validator-0_1                   | [2017-12-21 16:27:54.942 DEBUG    interconnect] message round trip: TP_PROCESS_RESPONSE 0.018114805221557617
validator-1_1                   | [2017-12-21 16:27:55.035 DEBUG    interconnect] ServerThread sending TP_STATE_GET_RESPONSE to b'a3b0e16d4aaf48b0'
validator-1_1                   | [2017-12-21 16:27:55.038 DEBUG    interconnect] ServerThread receiving TP_STATE_SET_REQUEST
```
* state handlers
```
validator-1_1                   | [2017-12-21 16:29:38.756 DEBUG    tp_state_handlers] GET: [('1cf126fc250d76798773a58316500893684ea4e2bce9ff07638b611bfecb145aa30bcd', …
```

Get rid of excessive logging

---

cli/sawtooth_cli/block.py
cli/sawtooth_cli/rest_client.py
docs/source/cli/sawtooth.rst

This makes the number of blocks returned from block list
configurable. Before, if a block list is run all, blocks would
be listed which pulls a lot of blocks from the database
which causes a Ram increase.

Add limit to block list

---

docs/source/rest_api/error_codes.rst
rest_api/openapi.yaml

Edited the RST doc and autogenerated content for the REST API documentation.
Note: This PR is a cherry-picked version of an earlier PR to fix typos in the REST API documentation.  This PR contains only the commit that changes the RST doc (docs/source/rest_api/error_codes.rst) and auto-generated content (rest_api/openapi.yaml).
I'll copy the relevant comments from #1222 , then close it.

Edit REST API doc: Fix typos, punctuation, and wording issues

---

docs/source/app_developers_guide.rst
docs/source/app_developers_guide/aws.rst
docs/source/app_developers_guide/example_transaction_processors.rst
docs/source/app_developers_guide/ubuntu.rst

This PR does two things to the list of transaction processor commands (aka executables) in the Application Developer's Guide:
Adds the missing TP commands:
- identity-tp
- block-info-tp
- smallbank-tp
Moves the list of transaction processor commands into a separate section so that the info appears only once (and is easier to find in the Contents). The list was in both the Ubuntu and AWS procedures, but the info isn't necessary for the steps in those procedures.

Move TP list to own section; add missing TPs

---

docs/source/sysadmin_guide/installation.rst

The echo redirect doesn't doesn't work because >> isn't done as root. Replacing with the same add-apt-repository commands as in the sysadmin guide's Ubuntu tutorial.

Replace "sudo echo" command with "sudo add-apt-repository"

---

cli/sawtooth_cli/network_command/compare.py
cli/tests/test_network.py

Previously the sawnet compare-chains command would blow up if there was
a communication error. This commit adds error handling around this
problem and displays information about all nodes that didn't have a
communication error.

Handle communication errors gracefully

---

consensus/poet/sgx/sawtooth_poet_sgx/libpoet_bridge/enclave.cpp

Properly destroy the PoET enclave in the case of SGX_ERROR_ENCLAVE_LOST

---

docker/sawtooth-int-validator

Required to add the block-info transaction injector that is configured in `sawtooth-seth` images and compose files

Add block-info package installation to validator image

---

sdk/go/src/sawtooth_sdk/signing/secp256k1.go

Adds a new `NewSecp256k1PrivateKey` function to the go SDK library that creates a `Secp256k1PrivateKey` instance from private key bytes.

Add NewSecp256k1PrivateKey function to SDK go library

---

validator/sawtooth_validator/gossip/gossip.py
validator/sawtooth_validator/networking/interconnect.py

Add a warning for the exception case when a peered node fails to send
its initial block request to a new peer.  Previously, this message would
be lost, and the only logging seen would be messages dropping a
temporary connection, but not the reasoning for doing so.
This message includes the connection id and the failure reason.

Add warning message for failed peering

---

docs/source/app_developers_guide.rst
docs/source/app_developers_guide/sdk_table.rst

New section with a table showing feature completeness, API stability, and maturity level for key features (client signing, transaction processors, and state delta).
Includes a link to the SDKs in the sawtooth-core repo.

Add SDK table to app dev guide to summarize SDK maturity

---

docker/compose/sawtooth-debug.yaml
docker/sawtooth-debug-python

This PR adds two files:
1. A Dockerfile that can be used to build an image with all Sawtooth dependencies, and dependencies for debugging using GDB.
2. A docker-compose file that builds the `debug-sawtooth-python` image, runs a script to change the Python interpreter to `python3-dbg` in the validator, rest api, and sawtooth scripts, and creates containers based on `debug-sawtooth-python` based on local files that run a Validator, settings tp, intkey tp, REST API, and a sawtooth shell.
The purpose of this is to allow developers to use GDB to inspect Sawtooth components.
To test:
1. `$ docker-compose -f docker/compose/sawtooth-debug.yaml up`. No building is required prior to running this command as the docker-compose file automatically builds the required image if it does not exist.
2. `$ …

Add docker files for Python debugging

---

LICENSE

Updates Sawtooth license to use full Apache 2.0 license text
Adds licenses for 3rd party open source components in repository
Sign-off-by: Tom Barnes <thomas.j.barnes@intel.com>

Updates to full Apache 2.0 text, adds 3rd party licenses

---

validator/sawtooth_validator/state/settings_view.py

Use of lru_cache on SettingsView.get_setting created a global setting
cache, which cuased the networks to fork for a significant amount of
time, early in their runs.  Changing this to a per-instance cache, which
was the original intention, fixes the issue.

Make Settings View LRU Cache per Instance

---

cli/sawtooth_cli/identity.py
cli/sawtooth_cli/sawset.py
cli/tests/test_admin_keygen.py
cli/tests/test_config.py
consensus/poet/cli/sawtooth_poet_cli/registration.py
consensus/poet/families/tests/test_tp_validator_registry.py
docker/sawtooth-dev-go
families/battleship/sawtooth_battleship/battleship_client.py
integration/sawtooth_integration/docker/test_config_smoke.yaml
integration/sawtooth_integration/docker/test_permission.yaml
integration/sawtooth_integration/tests/test_config_smoke.py
perf/sawtooth_workload/src/main.rs
perf/smallbank_workload/src/main.rs
sdk/examples/intkey_python/sawtooth_intkey/client_cli/intkey_client.py
sdk/examples/xo_python/sawtooth_xo/xo_client.py
sdk/go/src/sawtooth_sdk/signing/secp256k1.go
sdk/go/tests/secp256k1_test.go
sdk/rust/Cargo.toml
sdk/rust/src/signing/secp256k1.rs
signing/sawtooth_signing/secp256k1.py
signing/setup.py
signing/tests/test_secp256k1_signer.py
validator/sawtooth_validator/server/keys.py

Remove WIF as an option in CLI's and libraries.
Remove supporting libraries incl. pybitcointools and base58
WIF was originally used in Sawtooth because of some ease of using
bitcoin signing libraries. It's since been deprecated in Sawtooth.
Finally, there were concerns raised about some of the requisite libraries
including end of life of pybitcointools.

API Change remove WIF file decoding

---

validator/sawtooth_validator/state/settings_view.py

Use of lru_cache on SettingsView.get_setting created a global setting
cache, which cuased the networks to fork for a significant amount of
time, early in their runs.  Changing this to a per-instance cache, which
was the original intention, fixes the issue.

1.0: Fix settings view LRU Cache per instance
